### PR TITLE
XR -> XC

### PR DESCRIPTION
**Pull request by nutztherookie**

### CODE REVIEW

**Comment by droidmonkey** [comment]
Thanks!

**Comment by nutztherookie** [comment]
you're welcome :)

would you happen to have a nice solution for keepassxc in team? i.e. it's apparently not checking for merge conflicts, nor resolve them. thanks

**Comment by droidmonkey** [comment]
What do you mean?

**Comment by nutztherookie** [comment]
sorry i meant: we would like to use it in a team; i.e. synchronize it (via dropbox, owncloud, whatever) and have it open on multiple devices at once. now, if person A adds something and saves the file it gets synchronized. person B is apparently not informed about that update. if person B now saves, the new entry from person A seems to disappear.

**Comment by droidmonkey** [comment]
This is being implemented in #93 which will be merged to develop in a couple days.

**Comment by nutztherookie** [comment]
omg that is awesome! :) yesterday i started to tinker on some Go(lang) to
see if i wanna start KeePassGO . one less project ;D

**Pull request merged**
