### PR TITLE
KeePass2Reader: fix error message logic

### PR DESCRIPTION
**Pull request by c4rlo**
[Bug found via lgtm.com](https://lgtm.com/projects/g/keepassxreboot/keepassxc/alerts).

[TIP]:  # ( Provide a general summary of your changes in the title above ^^ )

## Type of change
[NOTE]: # ( Please remove all lines which don't apply. )
- ✅ Bug fix (non-breaking change which fixes an issue)

## Description and Context
[NOTE]: # ( Describe your changes in detail, why is this change required? )
[NOTE]: # ( Describe the context of your change. Explain large code modifications. )
[NOTE]: # ( If it fixes an open issue, please add "Fixes #XXX" as necessary )

Fix error message when attempting to open a KeePass 1 database.

While I was at it, I also introduced a dedicated error message for I/O errors when attempting to read the file signature (though this is secondary and doesn't matter much).

## Testing strategy
[NOTE]: # ( Please describe in detail how you tested your changes. )
[TIP]:  # ( We expect new code to be covered by unit tests and documented with doc blocks! )

`make test` continues to pass.

Other than that, I've tested this manually, by attempting to open files `/dev/null`, `CHANGELOG`, and `tests/data/basic.kdb`.

### Before my change

The error message in all three cases is:

> Unable to open the database:
> Error while reading the database: Not a KeePass database.

### After my change

For `/dev/null`:

> Unable to open the database:
> Error while reading the database: Failed to read database file.

For `CHANGELOG`:

> Unable to open the database:
> Error while reading the database: Not a KeePass database.

For `tests/data/basic.kdb`:

> Unable to open the database:
> Error while reading the database: The selected file is an old KeePass 1 database (.kdb).
>
> You can import it by clicking on Database > 'Import KeePass 1 database...'.
This is a one-way migration. You won't be able to open the imported database with the old KeePassX 0.4 version.

## Checklist:
[NOTE]: # ( Please go over all the following points. )
[NOTE]: # ( Again, remove any lines which don't apply. )
[NOTE]: # ( Pull Requests that don't fulfill all [REQUIRED] requisites are likely )
[NOTE]: # ( to be sent back to you for correction or will be rejected.  )
- ✅ I have read the **CONTRIBUTING** document. **[REQUIRED]**
- ✅ My code follows the code style of this project. **[REQUIRED]**
- ✅ All new and existing tests passed. **[REQUIRED]**
- ✅ I have compiled and verified my code with `-DWITH_ASAN=ON`. **[REQUIRED]**

### CODE REVIEW

**Comment by droidmonkey** [comment]
Can you create a database that matches the signature1/signature2 conditions to elicit the import error message?

**Comment by c4rlo** [comment]
Like my comment says above, `tests/data/basic.kdb` is such a database.

**Comment by droidmonkey** [comment]
I need to get my (non-existent) glasses checked! I glossed right over that last part of your PR.

**Comment by phoerious** [comment]
Wait the tests did pass before... Shouldn't they have failed of this is an issue?

**Comment by droidmonkey** [comment]
I think the issue is that the specific error message about being a KeePass1 database that must be imported was not being displayed. The parser correctly failed, just did not display the right error for the human.

**Comment by c4rlo** [comment]
That's correct.

**Comment by phoerious** [comment]
I see. Go on then.

**Pull request merged**
