### PR TITLE
Implement support for Yubikeys and potential other tokens via wireless NFC using smartcard readers (Rebase)

### LINKED ISSUE #4090: HMAC-SHA1 challenge response via NFC
[TIP]:  # ( Provide a general summary of the feature in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Summary
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
This feature would open up HMAC-SHA1 challenge response 2FA to NFC smartcard
devices like Rings, Fobs, Cards etc. and it would free up a precious USB slot. Also it would
ease the transition to the all USB-C future.

## Desired Behavior
[NOTE]: # ( Tell us how the new feature should work, be specific )
Instead of or in addition to just scan for supported HMAC-SHA1 challenge response devices plugged in to a USB slot, scan for NFC readers. If a supported NFC smartcard device is found
the user can choose which slot to use just like it would be plugged in to USB.

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )
I own multiple devices with different USB types and using adapters is tedious. Additionally smartcards which can run the yupikey applet for HMAC-SHA1 challenge response are way cheaper
and possibly more attractive to users.

### PR DESCRIPTION
**Pull request by StarGate01**
This PR is just #6766 but rebased on develop. Unfortunately GitHub does not allow re-opening closed PRs where the target branch has been removed.

Closes #4090

### CODE REVIEW

**Comment by droidmonkey** [comment]
I would just make this required for building with yubikey support. No need for the additional compile time feature. Need to add pcsc to our docker

**Comment by StarGate01** [comment]
I agree, I initially added the compile flag to make migration for maintainers easier. I'll update the PR today or in the next few days.

**Comment by droidmonkey** [comment]
I ordered an nfc reader to test this. Pretty excited actually.

**Comment by StarGate01** [comment]
Cool! Let me know if you encounter any issues, also note that some readers can only do basic NFC and have no proper smartcard (PCSC) interface, and some don't work that well in Linux (see https://ccid.apdu.fr/ccid/section.html).

**Comment by droidmonkey** [comment]
I got one with reviews saying they were using it with yubikey 5, hopefully it works!

https://smile.amazon.com/dp/B01KIKBYAG/ref=cm_sw_r_cp_apa_glt_fabc_3VN0H0BBCDJKM5G5DJWX

**Comment by StarGate01** [comment]
I removed the `WITH_XC_YUBIKEY_PCSC` flag, and also fixed a compilation error when YubiKey support was disabled.

You probably want to update the package dependencies for eg. Snap and other systems to include something like `pcsclite (-dev)/opensc/pcscd` (depending on the distribution) and `libusb-1.0 (-dev)`, and remove the old `ykpers`.

**Comment by droidmonkey** [comment]
I tested this with my new NFC reader and it worked flawlessly, great work!

**Review by droidmonkey — APPROVED** [review]

**Comment by droidmonkey** [comment]
@phoerious would appreciate a second set of eyes on this code. I did a little cleanup but the PCSC code is rather dense. It functionally works.

**Comment by StarGate01** [comment]
Great to hear you got it working. If you have any questions or comments on the PCSC code feel free to ask, unfortunately the WinAPI-type model requires some workarounds.

Also, it appears as if the Windows 10 CI test step sometimes fails?

**Comment by droidmonkey** [comment]
That is just a random failure

**Comment by StarGate01** [comment]
Before you merge this, I would like to change the detection procedure to a more robust and flexible one, that does not rely on a hard-coded ATR whitelist but instead queries the AID. I'll probably implement this in the next 1-2 Weeks.

Do you have a release window planned for 2.7?

**Comment by droidmonkey** [comment]
You got plenty of time, please do make it more flexible

**Comment by StarGate01** [comment]
Alright, I implemented AID scanning instead of the ATR whitelist. Give it a try and let me know if there are any issues.

This should enable unknown or unreleased hardware keys to work with the code, if they implement the HMAC-SHA1 protocol and use one of the AIDs listed.

**Comment by droidmonkey** [comment]
I cleaned up the code a little and fixed use of a Qt 5.15 only function

**Comment by droidmonkey** [comment]
OK final cleanup round, I changed the message when the YubiKey is missing or needs to be touched to "Please present or touch your YubiKey to continue…" this wording works even when the key is a USB key and not currently plugged in. I did not like the word interface, too mechanical.

I also changed the QMultiHash to a QMultiMap so we can use uniqueKeys() function in all Qt versions and get free sorting by serial number.

**Comment by droidmonkey** [comment]
Excellent work on this one, and yes this does make the PKCS#11 integration easier! I plan to add another interface for PKCS#11 and further abstract the differences away. I also plan to eliminate the use of "YubiKey" in favor of "Hardware Key".

**Comment by StarGate01** [comment]
Thank you for fixing the wording and translation entries, since English is not my first language. Also thanks for your support on this PR, working with KeePassXC is fun.

Eveything seems to work like intended on the current version of develop 👍. If you have any questions regarding PC/SC development in the future, feel free to contact me.

Moving to a generic "Hardware Key" interface sounds great, especially since many keys implement PC/SC (and even PKCS#11).

**Comment by droidmonkey** [comment]
I must say using the NFC reader is awesome, except mine makes this horrific beeping noise when establishing connection to the key.

**Comment by StarGate01** [comment]
You could just desolder the buzzer :D but I agree - I even modified my laptop and integrated a reader under the palm rest.

**Comment by droidmonkey** [comment]
Strongly considering it

**Comment by ghost** [comment]
When does this get added to the main release? Is there anything I can do to support/promote this feature?

**Comment by StarGate01** [comment]
This PR has already been accepted and merged into the main codebase, and is on track to release with the next version afaik.

**Comment by droidmonkey** [comment]
When we release 2.7.0

**Comment by StarGate01** [comment]
@p0rt9 If you want to help, you can build the development version and test the feature. Any bugs we catch before release are great.

**Comment by tarioch** [comment]
It's somewhere mentioned that this might also fix the issue with using Yubikey over a Remote Desktop connection.

I tried with the snappshot release from here https://snapshot.keepassxc.org/latest/ with a date of 2021-10-11 06:52 (Windows Portable Version).

And it doesn't seem to work (other yubikey things are passed through, but Keepassxc still doesn't detect any hardware).

**Comment by droidmonkey** [comment]
Are you passing smart cards?

**Comment by tarioch** [comment]
Yes, I think so. It's enabled on the rdp settings and I can also run 

```
certutil -scinfo

```

and it gives

```

Current reader/card status:
Readers: 1
  0: Yubico Yubikey NEO OTP+U2F+CCID 0
--- Reader: Yubico Yubikey NEO OTP+U2F+CCID 0
--- Status: SCARD_STATE_PRESENT | SCARD_STATE_UNPOWERED
--- Status: The card is available for use.
---   Card: Identity Device (NIST SP 800-73 [PIV])
---    ATR:
        ......


=======================================================
Analyzing card in reader: Yubico Yubikey NEO OTP+U2F+CCID 0

--------------===========================--------------
================ Certificate 0 ================
--- Reader: Yubico Yubikey NEO OTP+U2F+CCID 0
---   Card: Identity Device (NIST SP 800-73 [PIV])
Provider = Microsoft Base Smart Card Crypto Provider
Key Container = ..... [Default Container]

```

and then asks for my pin and it gives me the certificate I have on the yubikey.

**Comment by droidmonkey** [comment]
Interesting

**Comment by StarGate01** [comment]
This module does not use the CCID interface that the Yubikey provides via USB, instead it searches for a third-party reader that reads the Yubikey via NFC.

**Pull request merged**
