### PR TITLE
CHANGELOG.md: backfill recent releases

### PR DESCRIPTION
**Pull request by c4rlo**
I happened to notice these were missing.

## Type of change

- ✅ Documentation (non-code change)

### CODE REVIEW

**Comment by droidmonkey** [comment]
Good catch! There are other files that need to be updated as well.

**Comment by c4rlo** [comment]
Which ones?

**Comment by droidmonkey** [comment]
https://www.github.com/keepassxreboot/keepassxc/tree/develop/share%2Flinux%2Forg.keepassxc.KeePassXC.appdata.xml

**Comment by c4rlo** [comment]
Got it, updated. It was already up-to-date in the `2.6.6` tag so I'm just copying it over from there.

**Review by droidmonkey — APPROVED** [review]

**Pull request merged**
