### PR TITLE
Convert preview panel close button from checkbox to momentary

### LINKED ISSUE #2286: Incorrect state of "Close" button in entry details window displayed
Incorrect state of "Close" button displayed after I close entry details window (not sure how to call it correctly, as it also able to show group details) and then open it again.

## Expected Behavior
After entry details window is shown up again, "Close" button state should not be indicated as pressed.

## Current Behavior
After entry details window is shown up again, "Close" button state is indicated as pressed.
screenshot_2018-09-12_10-09-31
screenshot_2018-09-12_10-12-52 copy 1

## Steps to Reproduce (for bugs)
1. Open entry details
2. Close entry details
3. Open entry details again
4. See "Close" button

## Debug Info
KeePassXC - Version 2.3.4
Revision: 6fe821c

Libraries:
- Qt 5.5.1
- libgcrypt 1.8.1

Operating system: Linux Mint 18.3
CPU architecture: x86_64
Kernel: linux 4.10.0-38-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

### PR DESCRIPTION
**Pull request by kneitinger**
## Description

The entryCloseButton QToolButton, had the "checkable" property set.
This caused it to act like a toggle flip flop instead of a momentary
push button.  After removing that property, the signal it was changed
to use was released() instead of toggled(bool).  Trigger upon release
is consistent with the rest of the UI's momentary buttons

## Motivation and context

Fixes #2286

## How has this been tested?

- Opened database, root group was selected by default.  Pressed the button to close the preview panel
- Selected another group. Preview panel appeared and was in correct state (not visually "pressed")
- Repeated process for entries, as well as group-then-entry, and entry-then-group
- Ran existing tests
 

## Screenshots (if appropriate):
result

## Types of changes

- ✅ Bug fix (non-breaking change which fixes an issue)

## Checklist:

- ✅ I have read the **CONTRIBUTING** document. **[REQUIRED]**
- ✅ My code follows the code style of this project. **[REQUIRED]**
- ✅ All new and existing tests passed. **[REQUIRED]**
- ✅ I have compiled and verified my code with `-DWITH_ASAN=ON`. **[REQUIRED]**

### CODE REVIEW

**Comment by kneitinger** [comment]
@droidmonkey While I 100% agree, do we want to work on that in this issue, or create another one to have a better discussion? I could happily go either way :+1:

**Comment by droidmonkey** [comment]
For another PR, but it might be a great follow up

**Comment by phoerious** [comment]
I've said that way back when the panel was introduced. Mark my words.

**Comment by phoerious** [comment]
I think this can be merged. The branch needs to be updated, though.

**Pull request merged**
