### PR TITLE
Add master password inactivity timer

### LINKED ISSUE #6817: Security: Clear entered master password after inactivity
## Summary
I yesterday accidentally entered my master password but for some reason forgot to press enter.  Today, KeePassXC was patiently waiting for someone to press enter and the database was open.

For security, KeePassXC should clear the master password field after 1-2 minutes of inactivity.

### PR DESCRIPTION
**Pull request by tati-frog**
[NOTE]: # ( Describe your changes in detail, why is this change required? )
[NOTE]: # ( Explain large or complex code modifications. )
[NOTE]: # ( If it fixes an open issue, please add "Fixes #XXX" )

I created a new timer that clears the master password field when the user doesn't update it after one minute. Fixes #6817 

## Testing strategy
[NOTE]: # ( Please describe in detail how you tested your changes. )
[TIP]:  # ( We expect new code to be covered by unit tests and documented with doc blocks! )
I verified if it works on a linux and windows machine and also I runned all the tests.

## Type of change
[NOTE]: # ( Please remove all lines which don't apply. )
- ✅ New feature (change that adds functionality)

### CODE REVIEW

**Comment by droidmonkey** [comment]
This is implemented in the lines directly above your change....

**Comment by tati-frog** [comment]
But the lines above clears the input field only when the windows goes out of focus. I think it should also clear the input field when the windows is still visible, or  at least that's what I interpreted from the issue.

**Comment by droidmonkey** [comment]
That was not desired based on testing

**Comment by tati-frog** [comment]
Oh, well, thanks for the review. I will try with another issue.

**Pull request closed without merging**
