### PR TITLE
CLI: Add 'flatten' option to the 'ls' command

### LINKED ISSUE #925: Add an option to flatten the output of `ls`
This option would change the output from, for example
```
dir1/
  dir2/
    entry1
    entry2
```

To
```
dir1/dir2/entry1
dir1/dir2/entry1
```

## Possible Solution
We could add a `-f`, `--flatten` option to the `ls` command for that purpose.

### PR DESCRIPTION
**Pull request by ba32107**
[TIP]:  # ( Provide a general summary of your changes in the title above ^^ )

## Type of change
[NOTE]: # ( Please remove all lines which don't apply. )
- ✅ New feature (non-breaking change which adds functionality)

## Description and Context
[NOTE]: # ( Describe your changes in detail, why is this change required? )
[NOTE]: # ( Describe the context of your change. Explain large code modifications. )
[NOTE]: # ( If it fixes an open issue, please add "Fixes #XXX" as necessary )
Fixes #925. 
This feature adds an option to the CLI command `ls` to flatten the output.
For this I utilized the already existing `Group::hierarchy()` function, which gives me the ancestor groups for a given group. I needed to add an optional parameter to this function called `height`. This parameter determines how far up the ancestor tree the alrogithm should go. If none supplied, it defaults to `-1`, and the behavior is unchanged.

## Testing strategy
[NOTE]: # ( Please describe in detail how you tested your changes. )
[TIP]:  # ( We expect new code to be covered by unit tests and documented with doc blocks! )
- Tested manually with the `--flatten` option both enabled and disabled
- Added tests to cover changes

## Checklist:
[NOTE]: # ( Please go over all the following points. )
[NOTE]: # ( Again, remove any lines which don't apply. )
[NOTE]: # ( Pull Requests that don't fulfill all [REQUIRED] requisites are likely )
[NOTE]: # ( to be sent back to you for correction or will be rejected.  )
- ✅ I have read the **CONTRIBUTING** document. **[REQUIRED]**
- ✅ My code follows the code style of this project. **[REQUIRED]**
- ✅ All new and existing tests passed. **[REQUIRED]**
- ✅ I have compiled and verified my code with `-DWITH_ASAN=ON`. **[REQUIRED]**
- ✅ I have added tests to cover my changes.

### CODE REVIEW

**Comment by ba32107** [comment]
Sure, let me add some new tests for the `hierarchy` function as well. 

Could you point me towards the manpage that needs to be updated? I could not find them nor in the source, neither on GitHub (I'm new to the project).

Thanks

**Comment by louib** [comment]
@ba32107 the manpage's path is `src/cli/keepassxc-cli.1`

**Comment by ba32107** [comment]
@louib thanks, found & updated it.

**Comment by ba32107** [comment]
@louib Got it, CHANGELOG updated. Thanks, I will keep these in mind for the future.

**Pull request merged**
