### PR TITLE
Performed project-wide code formatting using clang-format

### PR DESCRIPTION
**Pull request by droidmonkey**
[TIP]:  # ( Provide a general summary of your changes in the title above ^^ )

## Type of change
[NOTE]: # ( Please remove all lines which don't apply. )
- ✅ Bug fix (non-breaking change which fixes an issue)
- ✅ Documentation (non-code change)

## Description and Context
[NOTE]: # ( Describe your changes in detail, why is this change required? )
[NOTE]: # ( Describe the context of your change. Explain large code modifications. )
[NOTE]: # ( If it fixes an open issue, please add "Fixes #XXX" as necessary )
Performed clang code formatting across the entire code base (src and tests folders). Used the command ```clang-format -i {src,test}/**/*.{cpp,h}```. Disabled code formatting for zxcvbn files.

This is in preparation for code formatting enforcement via CI.

## Checklist:
[NOTE]: # ( Please go over all the following points. )
[NOTE]: # ( Again, remove any lines which don't apply. )
[NOTE]: # ( Pull Requests that don't fulfill all [REQUIRED] requisites are likely )
[NOTE]: # ( to be sent back to you for correction or will be rejected.  )
- ✅ I have read the **CONTRIBUTING** document. **[REQUIRED]**
- ✅ My code follows the code style of this project. **[REQUIRED]**
- ✅ All new and existing tests passed. **[REQUIRED]**
- ✅ I have compiled and verified my code with `-DWITH_ASAN=ON`. **[REQUIRED]**

### CODE REVIEW

**Comment by c4rlo** [comment]
As I just mentioned in https://github.com/keepassxreboot/keepassxc/issues/2623#issuecomment-455893258, there's a `format` [target](https://github.com/keepassxreboot/keepassxc/blob/develop/cmake/CLangFormat.cmake) defined that already applies a variety of directory and file exclusions, that we should probably use instead.

Or if it does the wrong thing, it should be fixed or removed...

**Comment by droidmonkey** [comment]
Sure I'll use that for CI, but for this PR, why not format everything anyway

**Comment by c4rlo** [comment]
Well, `qtiocompressor.cpp` for example seems to be a third-party file that was pulled in from somewhere. So if we ever wanted to update that from upstream, this will make it a bit harder to see what changed.

Then again, it probably doesn't matter much...

**Comment by louib** [comment]
@droidmonkey @c4rlo yeah that was the rationale when I added the exclusion directories. Most are third-party modules that would be harder to update from upstream.

**Pull request merged**
