### PR TITLE
Support opening remote databases

### PR DESCRIPTION
**Pull request by t-h-e**
[NOTE]: # ( Describe your changes in detail, why is this change required? )
[NOTE]: # ( Explain large or complex code modifications. )
[NOTE]: # ( If it fixes an open issue, please add "Fixes #XXX" )
Follow up to https://github.com/keepassxreboot/keepassxc/pull/7222

Adding an option to import a remote database. Import the data to a new database, existing database or a temporary database (see option "Temporary Database" in section "Import Into")

## Screenshots
[TIP]:  # ( Do not include screenshots of your actual database! )

327211408-1d46de32-1ed9-43e8-b47c-4b3f1fc8dcd3

## Testing strategy
[NOTE]: # ( Please describe in detail how you tested your changes. )
[TIP]:  # ( We expect new code to be covered by unit tests and documented with doc blocks! )

Similar to syncing with a remote database, specify a download command and if necessary input to download the remote database.

Also added a unit test.

## Type of change
[NOTE]: # ( Please remove all lines which don't apply. )
- ✅ New feature (change that adds functionality)

### CODE REVIEW

**Comment by t-h-e** [comment]
I'm not sure why this test fails in the CI on Ubuntu
```
11:46:32   FAIL!  : TestGui::testOpenRemoteDatabase() 'QApplication::activeWindow()->findChildren<QTableWidget*>().count() > 0' returned FALSE. ()
11:46:32      Loc: [/opt/buildagent/work/c401303cba1b4098/tests/gui/TestGui.cpp(512)]
11:46:32   FAIL!  : TestGui::testOpenRemoteDatabase() 'action->isEnabled()' returned FALSE. ()
11:46:32      Loc: [/opt/buildagent/work/c401303cba1b4098/tests/gui/TestGui.cpp(2307)]
```

Windows and Mac seem fine. Also tested locally in Windows and Manjaro and there, this test works as well...

**Comment by droidmonkey** [comment]
Could be a modal dialog open on Linux? Like a question or notice dialog.

**Comment by Hidigoudi** [comment]
It would be nice to add the WebDav protocol inside this new feature. Instead of using a NextCloud client sync for example, the database would be accessible only from the server with an authentication. It would add a great feature for companies that want manage employees databases in a central server.

**Comment by droidmonkey** [comment]
@Hidigoudi WebDav can be setup in all major OS's natively as a mounted drive. You can use a third-party WebDav utility with the Remote Sync feature if you like.

**Comment by Maasea** [comment]
@Hidigoudi  You can use the  `curl` command to download and upload 'kdbx' files on Webdav server.
1. You may create a download action:

```
Name: Download
Command: curl -u username:password -o {TEMP_DATABASE} https://you_webdav.com/path/xxxxx.kdbx
```
~~Input: exit~~

2. You also need an upload action:

```
Name: Upload
Command: curl -u username:password -T {TEMP_DATABASE} https://you_webdav.com/path/xxxxx.kdbx
```
~~Input: exit~~
> As far as I know, Windows 10/11 has a built-in curl command.

Don't forget to change the username, password  and the webdav server.

**Comment by t-h-e** [comment]
@Maasea you can leave `Input:` blank as `curl` will exit on its own.

**Comment by tburny** [comment]
In am eagerly waiting for this for months now. Is there anything where we can help?

**Comment by droidmonkey** [comment]
This is great, fixed a regression with importing into an existing database. Couple things that could be done in future improvements to the code base:

1. We should be able to unlock the temporary database file using a proper DatabaseUnlockDialog... but the code right now makes a lot of assumptions that prohibit that. This would enable use of hardware keys.
2. We should write the download sync configuration to the database custom data. Then the user can re-download the database without having to type in the same configuration.

You may be able to implement the second suggestion, but not sure if that would be merged properly in DatabaseTabWidget

**Review by droidmonkey — APPROVED** [review]

**Comment by t-h-e** [comment]
Failing tests seem unrelated to my changes

**Comment by sirtao** [comment]
With the 2025-01-12 Win64 snapshot on Win10 pro, the Import fails to import anything when attempting to use `curl.exe` to download a DB file.
Specifically, it returns `Could not open remote database. Password or key file may be incorrect.` while the same command con terminal works perfectly.

In fact, using `cmd.exe` with input `timeout 2` as command results in the error message instantly instead of waiting the 2 seconds for the exit, which suggests some issue in how commands are passed

### Debug Info

KeePassXC - Version 2.8.0-snapshot
Build Type: Snapshot
Revision: f3b0810

Qt 5.15.11
Debugging mode is disabled.

Operating system: Windows 10 Version 2009
CPU architecture: x86_64
Kernel: winnt 10.0.19045

Enabled extensions:
- Auto-Type
- Browser Integration
- Passkeys
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 3.1.1

**Comment by t-h-e** [comment]
@sirtao Seeing the message `Could not open remote database. Password or key file may be incorrect.` means that the `curl` command exited with status 0 and a file was downloaded. But the message means that the downloaded file could not be opened.
Unfortunately, the specific error message why the file could not be opened is not logged.

You should be able to find the downloaded file within `C:\Users\<user>\AppData\Local\Temp` with a name starting with `RemoteDatabase`. You can check if the downloaded file is actually the file you expect it to be.

**Comment by sirtao** [comment]
> @t-h-e 
> You should be able to find the downloaded file within `C:\Users\<user>\AppData\Local\Temp` with a name starting with `RemoteDatabase`. You can check if the downloaded file is actually the file you expect it to be.

Thank you, but no such file is created using the `Import` function.

It DOES get created *using the same exact command line* when using the Remote Sync function in an already existing database.  

Using the Import function on an already existing\opened DB does nothing, either.

**Comment by droidmonkey** [comment]
Did you use the {TEMP_DATABASE} placeholder? It would help us troubleshoot if you included the commands you used (except the url and any passwords of course).

**Comment by sirtao** [comment]
yes, I did

here the command:  `curl.exe -u USERNAME:PASSWORD -o {TEMP_DATABASE} https://URL.domain/PATH/remote_db.kdbx`

I got it from a few replies earlier: https://github.com/keepassxreboot/keepassxc/pull/10896#issuecomment-2314618940

The same command works when used in Sync and on a regular terminal(replacing `{TEMP_DATABASE}` with an actual path of course)

**Comment by t-h-e** [comment]
Thanks for the info regarding the command.
I was ableto reproduce the issue. Or actually there are multiple.

1. The correct error message is not shown, which threw me off initially when claiming that a file must have been downloaded
2. No timeout is used when opening a remote database in contrast to syncing. Which can work if the command is really fast and you are really lucky. I need to add a timeout as well

I will provide a PR to fix these issues.

Also kind of an issue but related to Qt: In case you have a space anywhere you need to use double quotes. See https://doc.qt.io/qt-6/qprocess.html#splitCommand
In my test, I added `-H 'X-Requested-With: XMLHttpRequest'` which works in a terminal, but not in Qt.

**Comment by t-h-e** [comment]
PR is here: https://github.com/keepassxreboot/keepassxc/pull/11682

**Pull request merged**
