### PR TITLE
Add apply  button to application settings

### LINKED ISSUE #2994: Apply button in settings disabled
## Expected Behavior
Apply button is enabled

## Current Behavior
Nothing happens, Apply button stays inactive.

## Possible Solution
In 2.4.0-beta2 and if I build current develop branch it is always enabled and working.

## Steps to Reproduce
1. Start KeepassXC on macOS
2. Open Settings
3. See Apply Button disabled

## Context
Just changing settings

## Debug Info
KeePassXC - Version 2.4.1
Revision: 7bafe65

Qt 5.12.2
Debugging mode is disabled.

Operating system: macOS Mojave (10.14)
CPU architecture: x86_64
Kernel: darwin 18.5.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (only unsigned sharing)
- YubiKey
- TouchID

Cryptographic libraries:
 libgcrypt 1.8.4

### PR DESCRIPTION
**Pull request by mko-x**
[TIP]:  # ( Provide a general summary of your changes in the title above ^^ )

## Type of change
[NOTE]: # ( Please remove all lines which don't apply. )
- ✅ Bug fix (non-breaking change which fixes an issue)

## Description and Context
```
enableApplyButton(true);
``` 

Fixes #2994

### CODE REVIEW

**Comment by phoerious** [comment]
Can you point us to what issue exactly this is fixing?

**Comment by mko-x** [comment]
Well if I run the 2.4.1 Release or develop Branch the 'Apply' Button never gets enabled or active - so you have to click 'OK' and the 'Apply' Button is useless.

Pointed out in this issue #2994

macos-no-apply

**Comment by phoerious** [comment]
I don't think this fix is complete as is. I haven't tested it on macOS, but on other platforms, the Apply button is always enabled. So the macOS version should either be made consistent (i.e. enable it in the constructor) or enable on all platforms only if settings were changed.

**Comment by droidmonkey** [comment]
The settings widget probably needs to same treatment I have the entry and group edit

**Comment by droidmonkey** [comment]
Actually, just thought about this some more. The problem with having an apply button is that you then need to monitor for _ANY_ changes to the settings to properly enable/disable it. This is tedious and adds significant code overhead for very little gain. I am closing this and the corresponding issue because it should not be implemented at this time.

**Comment by mko-x** [comment]
@droidmonkey 
That's what I saw as well. There would need to be observers or changehandlers for any ui-control.
I see your point and agree with it.

I would suggest to think about removing the apply button, then.

**Comment by droidmonkey** [comment]
Yes absolutely, that is an artifact from another change made. I will make a PR for that.

**Pull request closed without merging**
