### PR TITLE
Support for wordlists in user configuration directory

### PR DESCRIPTION
**Pull request by snipfoo**
Hi!

This commit allows users to put alternative wordlists in a `wordlists` subdirectory below their KeePassXC directory (e.g., under Linux, `~/.config/keepassxc/wordlists`). These wordlists will then appear in the dropdown menu in the *Password Generator* widget.

In order to differentiate between lists shipped with KeePassXC and user-provided lists, the latter appear with an absolute path. Relative paths (for KeePassXC-provided lists) are relative to `resources()->dataPath()`.

## Screenshots
keepassxc-wordlists-in-user-config

## Testing strategy
Tested with zero, one and several files in the `~/.config/keepassxc/wordlists` directory. No problem detected.

## Type of change
- ✅ New feature (change that adds functionality)

Thanks!
SnipFoo

### CODE REVIEW

**Comment by droidmonkey** [comment]
Awesome!! Instead of prefixing with the absolute path can you just prefix the filename with "(CUSTOM)" or similar? You lose focus on the name of the list (seemingly important) with the path in there.

**Comment by snipfoo** [comment]
Hi!

Great, thanks for the feedback!

Using a `(CUSTOM)` prefix instead of the full path is a neat idea, thanks!

I'm however under the impression that we'd still better store the actual path (for user-provided wordlists) in the configuration file, under the `PasswordGenerator/WordList` key. Keeping the actual path there seems more robust to me, especially if the locale changes (and thus we have a translated `(CUSTOM)` tag instead) or if the user drops a file named `(CUSTOM) wordlist.txt` or the like in their `/usr/share/keepassxc/wordlists` directory (although I admit this is highly unlikely). It would also be able to handle the case where the `(CUSTOM)` tag is changed for something else in a later version of KeePassXC.

I've implemented this in a54bb8a by having the wordlist combo box still handle the actual paths internally (in the `Qt::UserRole` data of each item) but display shortened paths (i.e., with the `(CUSTOM)` tag—or translations thereof—for user-provided wordlists).

Here is a screenshot (using a French locale in order to test the translation as well):

keepassxc-wordlists-custom-tag

The configuration corresponding to the above screenshot still contains the following:
```
WordList=/home/[redacted]/.config/keepassxc/wordlists/wordlist_fr_5d.txt
```

Cheers!
SnipFoo

**Comment by droidmonkey** [comment]
Yah that's perfect, thank you!

**Comment by snipfoo** [comment]
Great, thanks!

Since I was still working on this feature, the two extra commits above (25853c0 and 7bfbd31) add buttons for adding or deleting custom wordlists. This allows users to use custom wordlists without having to create the `~/.config/keepassxc/wordlists` directory and to drop wordlist files in there themselves. Added wordlists are copied to the custom wordlist directory, so that they can be reused later on.

Here is a screenshot of the resulting GUI:

keepassxc-wordlists-add-delete-buttons

Behavior:
* The "delete" button asks for confirmation before actually removing the selected wordlist. It is disabled for system-wide wordlists.
* The "add" button opens a file dialog, and will ask for confirmation if there already is a custom wordlist with the same name.
* The wordlist combo box is now always visible and enabled, since the "add" and "delete" buttons appear on the right of the combo box.

Cheers!
SnipFoo

**Comment by droidmonkey** [comment]
Hot!

**Comment by phoerious** [comment]
Can we add an automatic download feature for word lists? We could host them on our website. And I would drop the `(Custom)` prefix. No need for that. I would also prefer nicer display names than the raw filename.

**Comment by droidmonkey** [comment]
I fixed up the code quite a bit. I also reversed the (CUSTOM) tag, instead it shows (SYSTEM) for the built-in wordlist. Adding a download feature can come later, perhaps a button that sends them to the download page?

Whatcha think @phoerious?

**Review by droidmonkey — APPROVED** [review]

**Review by phoerious — APPROVED** [review]
lgtm

**Comment by phoerious** [comment]
Although I would perhaps remove the "SYSTEM" thing entirely. Just disable the delete button when a system list is selected.

**Pull request merged**
