### PR TITLE
Implement feature "custom entry sort order" 

### PR DESCRIPTION
**Pull request by hmb**
## Type of change
- ✅ New feature (non-breaking change which adds functionality)

## Description and Context
This implements the "Enable custom entry sort order within a group" feature request https://github.com/keepassxreboot/keepassxc/issues/2295 with the following parts:

* Extend the password entry header buttons to a tristate logic:
  * sort ascending
  * sort descending
  * unsorted in the native DB custom order
* Add a menu to move entries up and down
* Add keyboard shortcuts to move entries up and down

Fixes https://github.com/keepassxreboot/keepassxc/issues/2295

## Screenshots
Sort Ascending:
grafik

Sort Descending:
grafik

Unsorted:
grafik

## Testing strategy
GUI functionality tested manually and via debugger.
Unit tests for the Entry, Group and EntryModel classes

## Checklist:
- ✅ I have read the **CONTRIBUTING** document. **[REQUIRED]**
- ✅ My code follows the code style of this project. **[REQUIRED]**
- ✅ All new and existing tests passed. **[REQUIRED]**
- ✅ I have compiled and verified my code with `-DWITH_ASAN=ON`. **[REQUIRED]**
- ✅ I have added tests to cover my changes.

### CODE REVIEW

**Comment by hmb** [comment]
I now did "make format" on a buster host. Apparently that generates a little different results to the xenial image in TeamCity.

**Comment by droidmonkey** [comment]
You need cmake-format >= 8.0

**Comment by droidmonkey** [comment]
I rebased, but this PR needs work. I do not want to add anymore toolbar buttons. The context menu entries should only show when the list is natural order. Moving an entry up/down in order should be considered a "non-destructive change" similar to expanding and collapsing a group, this prevents auto-save from triggering.

**Comment by hmb** [comment]
I'll take care of it theese days. Just removed some double changes I did in parallel to commit 
b18838518492b4d3c9de490eac856ca057f21b48 by @sigmaupsilon

**Comment by hmb** [comment]
@droidmonkey Tnx for the approval. Due to the Corona hype I got focused on other things and did not yet push my recent changes that fixed your requests in comment https://github.com/keepassxreboot/keepassxc/pull/4357#issuecomment-596884976.
I removed the toolbar buttons and the menu shows only when in netive sort order. Would it be OK to still push them?
Then I still have a problem fixing the "non-destructive change" behaviour. While it's easy to avoid the auto-save, that kills the possibility to save altogether. I did not yet figure out how to set a "changed" status without triggering autosave and simultaneously let the user still save the changes at will. Maybe you could point me inhto the right direction.

**Comment by droidmonkey** [comment]
No do not push anything, I made all the changes.

**Comment by hmb** [comment]
Ok thanks.

**Pull request merged**
