### PR TITLE
added autoload functionality (should implement #477)

### PR DESCRIPTION
**Pull request by alterratz**
if a folder (within the root folder) is named autoload
    all entries within this folder are opened automatically

    password: the password of the "slave" database
    url: the file name of the database which cab be:
       file:///absolute/path.kdbx
       /absolute/path.kdbx
       path.kbdx (which is relative to the current db)

    Did not test it on windows or osx but since Qt file
    functions have been used I suppose it will work fine.

## Description

iterated over all items in autoload folder in updateTabNameFromDbWidgetSender which is called after a db is opened

also had to change a few lines in DatabaseTabWidget::openDatabase to set passwords for already open databases or ignore databases which have their password set already.

## Motivation and context
implements feature request #477 
I use dependent DBs a lot and manually opening them sucks

## How has this been tested?
created a few (8) databases linked them to the master (4) and other "slave" DBs (4) using different url styles and loaded the master db as well as slave DBs
tried it with some of them opened before loading the master as well.

built it with following settings:
cmake -DWITH_XC_AUTOTYPE=ON -DWITH_XC_HTTP=ON -DWITH_XC_YUBIKEY=ON -DWITH_TESTS=ON -DWITH_ASAN=ON -DCMAKE_BUILD_TYPE=Release ..

## Types of changes
- ✅ New feature (non-breaking change which adds functionality)

## Checklist:
- ✅ I have read the **CONTRIBUTING** document. **[REQUIRED]**
- ✅ My code follows the code style of this project. **[REQUIRED]**
- ✅ All new and existing tests passed. **[REQUIRED]**
- ✅ I have compiled and verified my code with `-DWITH_ASAN=ON`. **[REQUIRED]**

Not yet:
- ✅ My change requires a change to the documentation and I have updated it accordingly.
However if everything else is accepted for merge I'll update the documentation as well.

### CODE REVIEW

**Comment by scic** [comment]
I tested the code by opening a database that uses the AutoExec plugin under Keepass 2. With this PR KeepassXC did correctly open the referenced databases. And I did not notice any issues. It implements https://github.com/keepassxreboot/keepassxc/issues/477 for me.
(I can say nothing about the code)

**Comment by droidmonkey** [comment]
You need to fix this PR. Right now you are pulling in a bunch of changes that have already been merged. You should start over and create a branch on the latest develop. Cherry pick your unique commits on that new branch then update this pr with that branch.

**Comment by alterratz** [comment]
creating a new PR (and closing this one when I'm done)

**Comment by alterratz** [comment]
Moved to PR #1053

**Comment by amynbe** [comment]
The folder must be named "AutoOpen". Is this documented somewhere?

**Comment by droidmonkey** [comment]
The documentation for this feature is lacking and I dont think it works anyway

**Comment by TheZ3ro** [comment]
> If a folder/group (within the root folder/group) is named "AutoOpen", all entries within this folder/group are opened automatically
> 
> The entry should be structured as following:
> **password**: the password of the "slave" database
> **url**: the file name of the database which can be:
> file:///absolute/path.kdbx
> /absolute/path.kdbx
> path.kbdx (which is relative to the current db)

**Comment by droidmonkey** [comment]
So it didn't work for me because the description in the PR *used* to say the folder needed to be named "autoload". I corrected that and it works now.

**Pull request closed without merging**
