### PR TITLE
Add option for monochrome tray icon

### PR DESCRIPTION
**Pull request by phoerious**
[NOTE]: # ( Describe your changes in detail, why is this change required? )
[NOTE]: # ( Explain large or complex code modifications. )
[NOTE]: # ( If it fixes an open issue, please add "Fixes #XXX" )

## Screenshots
[TIP]:  # ( Do not include screenshots of your actual database! )
image image

image

## Type of change
[NOTE]: # ( Please remove all lines which don't apply. )
- ✅ New feature (change that adds functionality)

### CODE REVIEW

**Comment by jensrutschmann** [comment]
Does this also work with the latest KDE breeze theme version (5.70.0)?
They added their own set of monochrome tray icons for keepassxc in that version.

See https://github.com/KDE/breeze-icons/commit/036ba91a2bc334af19de0af14e6f7b01fa5e43bb

**Comment by droidmonkey** [comment]
We no longer use any icons from the system.

**Comment by michaelblyons** [comment]
Would you consider changing the monochrome icons (thank you, btw) to be "mask" icons? I made [a PR](https://github.com/openconnect/openconnect-gui/pull/192) ages ago on another Qt project, OpenConnect GUI, to do this for their tray icons. The maintainer partitioned off MacOS from Windows, but I think the concept could handle both.

**Comment by phoerious** [comment]
We actually don't want our tray icon to be recoloured, since the light and dark versions differ in which areas are opaque.

**Pull request merged**
