### PR TITLE
Adding --no-password option to CLI

### PR DESCRIPTION
**Pull request by louib**
I also added tests for the --key-file option, which was
untested.

Closes https://github.com/keepassxreboot/keepassxc/issues/1873

@phoerious this is one the reasons why I opened https://github.com/keepassxreboot/keepassxc/issues/1873 last week. This way adding features to `unlockDatabase` is normalized across the CLI commands.

## Type of change
[NOTE]: # ( Please remove all lines which don't apply. )
- ✅ Bug fix (non-breaking change which fixes an issue)
- ✅ Refactor (significant modification to existing code)
- ✅ New feature (non-breaking change which adds functionality)
- ✅ Breaking change (fix or feature that would cause existing functionality to change)
- ✅ Documentation (non-code change)

## Description and Context
[NOTE]: # ( Describe your changes in detail, why is this change required? )
[NOTE]: # ( Describe the context of your change. Explain large code modifications. )
[NOTE]: # ( If it fixes an open issue, please add "Fixes #XXX" as necessary )

## Testing strategy
Local testing + unit tests.

## Checklist:
[NOTE]: # ( Please go over all the following points. )
[NOTE]: # ( Again, remove any lines which don't apply. )
[NOTE]: # ( Pull Requests that don't fulfill all [REQUIRED] requisites are likely )
[NOTE]: # ( to be sent back to you for correction or will be rejected.  )
- ✅ I have read the **CONTRIBUTING** document. **[REQUIRED]**
- ✅ My code follows the code style of this project. **[REQUIRED]**
- ✅ All new and existing tests passed. **[REQUIRED]**
- ✅ I have compiled and verified my code with `-DWITH_ASAN=ON`. **[REQUIRED]**
- ✅ My change requires a change to the documentation, and I have updated it accordingly.
- ✅ I have added tests to cover my changes.

### CODE REVIEW

**Comment by droidmonkey** [comment]
Tests are failing for Windows

**Comment by louib** [comment]
@droidmonkey should be good now!

**Comment by arvinep** [comment]
Thanks for this feature.
I have difficulty to find the documentation as I try to figure how to use it.

Trying to use `--no-password` is failing:

```
$ keepassxc-cli clip --no-password -k /home/kepassxc_key /home/keepassxc.kdbx <Entry>
Error while reading the database: Invalid credentials were provided, please try again.
If this reoccurs, then your database file may be corrupt.
```
While skipping `--no-password` and entering the password works perfectly fine. 

```
$ keepassxc-cli clip -k /home/kepassxc_key /home/keepassxc.kdbx <Entry>
Insert password to unlock /home/keepassxc.kdbx: 
Entry's password copied to the clipboard!
```

**Comment by droidmonkey** [comment]
--no-password is meant for a database that does not have a "password" component of its master key. If you have to enter a password, you do not meet the requirements for --no-password.

**Pull request merged**
