### PR TITLE
Remove offset on username field in classic theme

### LINKED ISSUE #5601: Username field has an offset when in classic theme
## Overview
Username field in v2.6.2 has an invisible offset. Doesn't affect the actual information stored in db as far as I can tell.

## Steps to Reproduce
1. Install v2.6.2 on Windows 20H1, default "light" theme.
2. Create a new record.
3. Note the gap in the username field.

## Expected Behavior
All fields are aligned consistently.

## Actual Behavior
image

## Context
```
KeePassXC - Version 2.6.2
Revision: e9b9582

Qt 5.15.1
Debugging mode is disabled.

Operating system: Windows 10 Version 2004
CPU architecture: x86_64
Kernel: winnt 10.0.19041
```

### PR DESCRIPTION
**Pull request by droidmonkey**
[NOTE]: # ( Describe your changes in detail, why is this change required? )
[NOTE]: # ( Explain large or complex code modifications. )
[NOTE]: # ( If it fixes an open issue, please add "Fixes #XXX" )
* Fix #5601 

## Screenshots
[TIP]:  # ( Do not include screenshots of your actual database! )
Classic Theme:
image

## Testing strategy
[NOTE]: # ( Please describe in detail how you tested your changes. )
[TIP]:  # ( We expect new code to be covered by unit tests and documented with doc blocks! )
Tested on Windows

## Type of change
[NOTE]: # ( Please remove all lines which don't apply. )
- ✅ Bug fix (non-breaking change that fixes an issue)

### CODE REVIEW

**Comment by phoerious** [comment]
Scrap all that. I found a much cleaner solution that doesn't need any style sheets in widgets where they don't belong:

```patch
diff --git a/src/gui/styles/base/BaseStyle.cpp b/src/gui/styles/base/BaseStyle.cpp
index 6cde175c..db2897ab 100644
--- a/src/gui/styles/base/BaseStyle.cpp
+++ b/src/gui/styles/base/BaseStyle.cpp
@@ -4777,7 +4777,11 @@ QRect BaseStyle::subElementRect(SubElement sr, const QStyleOption* opt, const QW
     }
     case SE_LineEditContents: {
         QRect r = QCommonStyle::subElementRect(sr, opt, w);
-        int pad = Phantom::dpiScaled(Phantom::LineEdit_ContentsHPad);
+        int pad = Phantom::LineEdit_ContentsHPad;
+        if (w && qobject_cast<const QComboBox*>(w->parentWidget())) {
+            pad += 3;
+        }
+        pad = Phantom::dpiScaled(pad);
         return r.adjusted(pad, 0, -pad, 0);
     }
     default:
```

**Comment by phoerious** [comment]
I pushed it as a new commit, feel free to fix it up with the removal of the style sheets.

**Comment by randrew** [comment]
@phoerious Is there some particular setup I need to reproduce this in a test GUI? I don't see it with a standard line edit.

**Comment by droidmonkey** [comment]
@randrew this is comparing a QLineEdit with a QComboBox (which has a QLineEdit embedded in it). Unfortunately QComboBox doesn't let you style the internal QLineEdit and the left-padding is different between the two.

**Comment by randrew** [comment]
Oh, this is something I never tried in the PhantomStyle funhouse. Thanks for pointing it out. I'll add it to to the funhouse and probably end up adding a similar fix for PhantomStyle itself.

**Comment by droidmonkey** [comment]
I implemented your change @phoerious and also added 2 px stylesheet padding to QLineEdit's. Classic mode looks good now!

**Comment by phoerious** [comment]
I'll have to test if the 2px work well on Linux, too. What I certainly do notice on Windows at least is that the QComboBox has a different height. But that is not something that was touched here.

**Review by phoerious — APPROVED** [review]

**Pull request merged**
