### PR TITLE
Change settings checkbox texts to positive phrasing

### LINKED ISSUE #3601: Positive checkbox texts in application settings dialog
## Summary

In the checkbox texts in the application settings dialogs, I find negative formulations like "Don't do that" difficult to understand, and prefer positive formulations like "Do that". For example, instead of "Don't mark database as modified for non-data changes", I'd prefer "Mark database as modified for non-data changes" (and reverse the meaning of the checkbox).

## Desired Behavior

Current checkbox texts:

* Don't mark database as modified for non-data changes
* Don't require password repeat when it's visible
* Don't hide passwords when editing them
* Don't use placeholder for empty password fields

Suggested new checkbox texts:

* Mark database as modified for non-data changes
* Require password repeat when it's visible
* Hide passwords when editing them
* Use placeholder for empty password fields

Note that this reverses the meaning of the checkbox itself (i. e., checked now is unchecked after the change, and vice-versa).

Technically, it's not a breaking change because existing installations will continue working as before. However, users may find this breaking when they memorized something like "clear the checkbox that says modified for non-breaking changes", because in the future they have to check it to achieve the same behavior.

## Possible Solution

Volunteering to implement it.

## Context

In a different app, I recently spent too much time wondering why something didn't work, when a checkbox was checked but it should have been unchecked. (Checkbox text wasn't completely visible due to low screen resolution, I assumed checking it meant "activate something" when it in fact meant "don't activate it".)

### PR DESCRIPTION
**Pull request by ameyer0**
[TIP]:  # ( Provide a general summary of your changes in the title above ^^ )

## Type of change
[NOTE]: # ( Please remove all lines which don't apply. )
- ✅ New feature (non-breaking change which adds functionality)

## Description and Context
[NOTE]: # ( Describe your changes in detail, why is this change required? )
[NOTE]: # ( Describe the context of your change. Explain large code modifications. )
[NOTE]: # ( If it fixes an open issue, please add "Fixes #XXX" as necessary )
Currently, some checkbox texts in the settings use negative phrasing so it is confusing what the checkbox actually does. This pull request changes the checkboxes to have positive phrasing, and reverses their effects to match.
#### Current text:  
* Don't mark database as modified for non-data changes
* Don't require password repeat when it's visible
* Don't hide passwords when editing them
* Don't use placeholder for empty password fields  
#### New text:  
* Mark database as modified for non-data changes
* Require password repeat when it's visible
* Hide passwords when editing them
* Use placeholder for empty password fields  

Variables related to these settings have been renamed to reflect the new behavior.  

This is a non-breaking change because existing installations' configurations will be upgraded while preserving the behavior the user originally set.

Fixes #3601 

## Screenshots
[TIP]:  # ( Do not include screenshots of your actual database! )
Screenshot_20200311_150017
Screenshot_20200311_150207

## Testing strategy
[NOTE]: # ( Please describe in detail how you tested your changes. )
[TIP]:  # ( We expect new code to be covered by unit tests and documented with doc blocks! )

* Manual testing in KDE for the GUI changes.
* Added a new unit test testUpgrade to cover updating settings from an old config file.

## Checklist:
[NOTE]: # ( Please go over all the following points. )
[NOTE]: # ( Again, remove any lines which don't apply. )
[NOTE]: # ( Pull Requests that don't fulfill all [REQUIRED] requisites are likely )
[NOTE]: # ( to be sent back to you for correction or will be rejected.  )
- ✅ I have read the **CONTRIBUTING** document. **[REQUIRED]**
- ✅ My code follows the code style of this project. **[REQUIRED]**
- ✅ All new and existing tests passed. **[REQUIRED]**
- ✅ I have compiled and verified my code with `-DWITH_ASAN=ON`. **[REQUIRED]**
- ✅ My change requires a change to the documentation, and I have updated it accordingly.
- ✅ I have added tests to cover my changes.

### CODE REVIEW

**Comment by droidmonkey** [comment]
Great work on this!

**Comment by wolframroesler** [comment]
Are you still working on this @ameyer0? If you don't have time, I could try and take care of these merge conflicts.

**Comment by ameyer0** [comment]
@wolframroesler I've been meaning to get back to it, but it'll probably be at least a week until I have time. You're welcome to try and work on the conflicts in the meantime, thanks!

**Comment by wolframroesler** [comment]
@ameyer0 Not sure what's the easiest way for me to contribute to your branch. Do I have to fork your fork of the repo and submit a PR to your branch? Maybe you have to grant me access (https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork)? Note that I'm not a maintainer of the keepassxc repo.

**Comment by droidmonkey** [comment]
@wolframroesler it would be easiest to checkout his branch, make your changes, then push to your own fork. Then make a new PR.

**Comment by wolframroesler** [comment]
Merge conflicts solved, please have a look at #4574.

**Pull request closed without merging**
