### PR TITLE
Fix Issue #1447 where the wrong path was shown for view/edit when opening via search results

### PR DESCRIPTION
**Pull request by nick96**
Fix issue in #1447 where the headline was showing the wrong path when a group was selected in the side bar.

## Description

Added a check in `DatabaseWidget::switchToEntryEdit(Entry* entry, bool create)` that sets the group in the headline to the current group if creating a entry. Otherwise the headline group is the parent group of the entry.

Using the example from the issue, previously the headline would show:
    
    Bad  > Doggy

With this change, we now get:
    
    Good > Doggy

## Motivation and context

Solves issue #1447. 

## How has this been tested?

Manually. I had a look at the gui tests to try and add a test for this but I can't find a way to access the headline attribute to check it contains the correct values. If I've missed it and someone can point me in the right direction so I can add some tests that would be awesome.

## Types of changes

- ✅ Bug fix (non-breaking change which fixes an issue)

## Checklist:

- ✅ I have read the **CONTRIBUTING** document. **[REQUIRED]**
- ✅ My code follows the code style of this project. **[REQUIRED]**
- ✅ All new and existing tests passed. **[REQUIRED]**
- ✅ I have compiled and verified my code with `-DWITH_ASAN=ON`. **[REQUIRED]**
- ~~My change requires a change to the documentation and I have updated it accordingly.~~
-  ~~I have added tests to cover my changes.~~

### CODE REVIEW

**Comment by phoerious** [comment]
If you want to add tests (which would be fanstastic), you can get the label with

```
m_dbWidget->findChild<EditEntryWidget*>("editEntryWidget")->findChild<QLabel*>("headerLabel")->text()
```

**Comment by nick96** [comment]
Okay. I'm working on the tests, taking a little longer than I expected figuring out how to work with the gui programatically but all good

**Comment by TheZ3ro** [comment]
@nick96 if you need some help you can ask here or over IRC 😉

**Comment by nick96** [comment]
@TheZ3ro, thank you, it was just a bit of slow going because I haven't done a lot of work with C++ or Qt.

I've got a test for this issue written and it passes on my computer that passes with the fix and fails without it. However, when I try to push to my fork it fails because the tip of my local it behind the remote. Could this be because I rebased against relase/2.3.0 before writing the test? and am I okay to do a `git push -f` to my fork?

**Comment by phoerious** [comment]
Yes, you can force-push against your branch. But please rebase against release. 2.3.0 first and change the PR target to that branch.

**Pull request merged**
