### PR TITLE
Feature : Clip command using native programs.

### PR DESCRIPTION
**Pull request by louib**
Clip command using native programs.

## Description
Summary of changes:
* Using native programs for the `Clip` command.
* Adding a timeout option for clearing the clipboard
* Renamed PasswordInput -> Utils, since we now use it for other CLI functions.

## Motivation and context
Interacting with the `QClipboard` is not possible for a `QCoreApplication`, and instantiating a `QApplication` does not play nicely with the CLI. The goal is to remove usages of `QApplication` (GUI applications) in the CLI, so that we can instantiate 1 `QCoreApplication` in `keepassxc-cli.cpp`, and that's it. No more branching to know what type of application to instantiate.

The next step is to remove the GUI prompt in favor of a `--key-file` option, supported in all of the commands. 

## How has this been tested?
Unit tests + tested on Mac and Linux.
@droidmonkey could you test this on Windows? I use the `clip` command, which I think is installed by default, but I'm lacking a windows setup to test this.

## Screenshots (if appropriate):
When passing a `timeout` option, the command will countdown until the timeout is finished, and then clear the clipboard.

```
$ ./src/cli/keepassxc-cli clip
Usage: ./src/cli/keepassxc-cli clip [options] database entry [timeout]
Copy an entry's password to the clipboard.

Options:
  -g, --gui-prompt  Use a GUI prompt unlocking the database.

Arguments:
  database          Path of the database.
  entry             Path of the entry to clip.
  timeout           Timeout in seconds before clearing the clipboard.
$ ./src/cli/keepassxc-cli clip ~/test.kdbx entry1 5
Insert password to unlock /home/louib/test.kdbx
> 
Entry's password copied to the clipboard!
Clearing the clipboard in 5 seconds...
```

Then after 5 seconds
```
$ ./src/cli/keepassxc-cli clip ~/test.kdbx entry1 5
Insert password to unlock /home/louib/test.kdbx
> 
Entry's password copied to the clipboard!
Clearing the clipboard in 1 seconds...
Clipboard cleared!
$
```

## Types of changes

- ✅ New feature

## Checklist:

- ✅ I have read the **CONTRIBUTING** document. **[REQUIRED]**
- ✅ My code follows the code style of this project. **[REQUIRED]**
- ✅ All new and existing tests passed. **[REQUIRED]**
- ✅ I have compiled and verified my code with `-DWITH_ASAN=ON`. **[REQUIRED]**
- ✅ My change requires a change to the documentation and I have updated it accordingly.

### CODE REVIEW

**Comment by droidmonkey** [comment]
It most certainly is installed on Windows 10, just checked.

**Comment by louib** [comment]
@droidmonkey I managed to test it on windows, and it unfortunately doesn't work, at least not with MSYS2. If someone is willing to implement this on windows that'd be great. In the meantime I'll just leave it unimplemented, and display a message stating so if used in windows. Sounds good?

**Comment by droidmonkey** [comment]
The clip command works in windows, but not when you use the timeout feature.

**Comment by louib** [comment]
@droidmonkey I managed to make it work on windows, including the timeout feature. Looks like the problem was with the `qPrintable` / `QProcess::write` combination. I switched to `toLatin1()`, and everything looks fine. Can you test again?

**Comment by droidmonkey** [comment]
Yes now it works great!

I have an overarching comment on the CLI though, I kind of think the database path should come as the first parameter. My reason is if I am interacting with the database I constantly have to reposition the cursor on the command line to go all the way back to the beginning.

Also, there should be hidden aliases for commands. ```list``` should resolve to ```ls``` and ```entropy``` should resolve to ```entropy-meter```

**Comment by louib** [comment]
@droidmonkey It'll be harder to dispatch the commands if it's not the first argument, though not impossible. We might also rename `entropy-meter` to `estimate`, so that it's a verb, like the other commands. See https://github.com/keepassxreboot/keepassxc/issues/681 for a general discussion on improving the CLI. I'll merge this one.

**Pull request merged**
