### PR TITLE
Add icon and desktop file

### PR DESCRIPTION
**Pull request by elopio**
## Description
This are files for the integration of the snap with linux desktop environments.

## Motivation and Context
Without this, it won't appear on the dash of ubuntu, and it will get a generic icon.

## How Has This Been Tested?
This is just a copy from the existing keepassx-elopio snap, with the name updated.

## Types of changes
- :negative_squared_cross_mark: Bug fix (non-breaking change which fixes an issue)
- :white_check_mark: New feature (non-breaking change which adds functionality)
- :negative_squared_cross_mark: Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:>
- :white_check_mark: I have read the **CONTRIBUTING** document. [REQUIRED]
- :white_check_mark: My code follows the code style of this project. [REQUIRED]
- :white_check_mark: All new and existing tests passed. [REQUIRED]
- :negative_squared_cross_mark: My change requires a change to the documentation.
- :negative_squared_cross_mark: I have updated the documentation accordingly.
- :negative_squared_cross_mark: I have added tests to cover my changes.

### CODE REVIEW

**Comment by elopio** [comment]
Thanks @TheZ3ro. Let me play with this, I think I can use links.

**Comment by elopio** [comment]
I'm sorry. I tried a whole bunch of options to not duplicate the files, but I failed.
This is the best I can do for now. Of course, we need to fix it in snapcraft. We have a set of items related to desktop files, starting with this bug: https://bugs.launchpad.net/snapcraft/+bug/1588359
I can use this case as an example of what we need to implement, so it will be pretty for you for sure.

**Comment by TheZ3ro** [comment]
Kind of sad that you can't place file other than `setup/gui/`

Maybe TravisCI can copy them in the correct location before launching the snapcraft command?
(Just thinking)

**Comment by elopio** [comment]
Yes, we can modify the tree on travis. The downside is that you can't build the snap with a simple snapcraft call, you need that script.
I personally prefer to duplicate for now, and fix it as soon as snapcraft offers the nice story for desktop files. But if you prefer the alternative, I'm ok doing that too.

**Comment by TheZ3ro** [comment]
I don't know, I was just proposing an alternative but If we can't handle it better it's fine for me

**Pull request merged**
