### PR TITLE
Fix : settings alignment

### PR DESCRIPTION
**Pull request by louib**
Fixing the general settings alignment.

## Description
Trying to fix the alignment of the general settings widget on MacOs. There was also a system tray option which was not hidden for Mac. I regrouped the 2 minimized options, since one of them was alone at the bottom.

## How Has This Been Tested?
Local tests on Mac, I did not test on Windows and Linux yet.

## Screenshots (if appropriate):
Before
screen shot 2017-02-10 at 10 01 10 pm

After
screen shot 2017-02-10 at 10 02 00 pm

The alignment is still not perfect, especially if the window is wide
screen shot 2017-02-10 at 10 02 15 pm
Not sure how to fix that, or what's the wanted appearance. If anyone has an idea on how to fix this, don't hesitate.

The Security tab also has to be updated
screen shot 2017-02-10 at 10 02 27 pm

## Types of changes

- ✅ Bug fix

## Checklist:

- ✅ I have read the **CONTRIBUTING** document. 
- ✅ My code follows the code style of this project. 
- ✅ All new and existing tests passed.

### CODE REVIEW

**Comment by phoerious** [comment]
I was about to redesign the settings anyway for 2.2.0. I especially wanted to get rid of this ugly vertical tab bar. Your changes are a good start, I'd like to build upon that.

I think the Mac fix for the tray icon option should also be backported to 2.1.2.

**Comment by louib** [comment]
@phoerious I'll apply the systray fix to 2.1.2. What were you planning to do for the vertical tab bar?

I had to use spacer to align the labels left. I'm not sure if that's the proper solution.

**Comment by phoerious** [comment]
I'm not quite sure yet. I think I'll use either a classic horizontal tab bar or a vertical one, but then with icons and a proper width.
If I use a horizontal tab bar, I'd also put spacers left and right, so we have one properly sized middle column instead of stuff stretching from left to right.

**Comment by louib** [comment]
@phoerious go right ahead and use this branch!

**Comment by phoerious** [comment]
I think I'm done. Will make a PR very soon. :-)

**Comment by TheZ3ro** [comment]
Screenshot please ahahahah

**Comment by phoerious** [comment]
I'll make a full new PR with all that. But right now, I'm bugfixing on Windows.

**Comment by phoerious** [comment]
Closing in favor of #340. You work's in there.

**Pull request closed without merging**
