### PR TITLE
Fix #3587 Shorten the search delay timer

### LINKED ISSUE #3587: Shorten search delay timer
## Summary
https://github.com/keepassxreboot/keepassxc/commit/4b983251cb464d104aafd95ea56e19b5c404247a#diff-54192eee50d5dba69b89f9f6caa74abcR140 changed the duration of the timer after which a new search filter is applied from 100ms to 300ms. This has been annoying me since I upgraded (which was quite delayed since i am on Debian). I get that this might be preferrable on constrained devices due to the more complex search behaviour now but would it be possible for this to be configurable so we can make it "instant" on more beefy machines?

## Desired Behavior
I don't have to wait for a noticable amount of time for the filtered search results.

## Possible Solution
Add a new config option to configure the search delay time, similar to https://github.com/keepassxreboot/keepassxc/pull/3411 except probably don't need to be able to disable it.

## Context
I think I got used to a workflow of searching for a string that I knew would match and copying right away, now I have to wait. It isn't a big delay but because it is different than what I am used to I notice it (I've been on 2.4.3 (previously on 2.3.4) for two weeks now). I'm surprised no-one has complained already tbh.

### PR DESCRIPTION
**Pull request by Chris-Johnston**
[TIP]:  # ( Provide a general summary of your changes in the title above ^^ )

Fix #3587 . This PR shortens the default search delay timer to 100ms.

## Type of change
[NOTE]: # ( Please remove all lines which don't apply. )
- ✅ New feature (non-breaking change which adds functionality)

## Description and Context
[NOTE]: # ( Describe your changes in detail, why is this change required? )
[NOTE]: # ( Describe the context of your change. Explain large code modifications. )
[NOTE]: # ( If it fixes an open issue, please add "Fixes #XXX" as necessary )

00056ea reduces the search delay timer as discussed in #3587 .

~~As part of the discussion in that PR, it was suggested that this value could be configurable. I think that this could be a good idea for those that wish to be able to specify this option, so I added this as a setting under Config, and added a section in the settings to update this value.~~

## Screenshots
[TIP]:  # ( Do not include screenshots of your actual database! )

No visible changes were made.

## Testing strategy
[NOTE]: # ( Please describe in detail how you tested your changes. )
[TIP]:  # ( We expect new code to be covered by unit tests and documented with doc blocks! )

This change was tested manually, it's a somewhat subtle difference to how quickly the search updates.

## Checklist:
[NOTE]: # ( Please go over all the following points. )
[NOTE]: # ( Again, remove any lines which don't apply. )
[NOTE]: # ( Pull Requests that don't fulfill all [REQUIRED] requisites are likely )
[NOTE]: # ( to be sent back to you for correction or will be rejected.  )
- ✅ I have read the **CONTRIBUTING** document. **[REQUIRED]**
- ✅ My code follows the code style of this project. **[REQUIRED]**
- ✅ All new and existing tests passed. **[REQUIRED]**
- ✅ I have compiled and verified my code with `-DWITH_ASAN=ON`. **[REQUIRED]**
~~- I have added tests to cover my changes.~~

### CODE REVIEW

**Comment by phoerious** [comment]
I am against adding an option for this. There is really no need and it just clutters the program settings.

**Comment by droidmonkey** [comment]
Concur, its an implementation detail not a user configurable item.

**Comment by Chris-Johnston** [comment]
Sure, then I'll revert back to 00056ea at it still would resolve the linked issue

**Comment by Chris-Johnston** [comment]
The changes to ApplicationSettingsWidget have been reverted, this value is set back to 100ms. I'm not seeing any option to re-open this PR, but the branch has been updated.

**Pull request merged**
