### PR TITLE
Add support to get process name on FreeBSD

### PR DESCRIPTION
**Pull request by bapt**
On FreeBSD there is no such thing as /proc/* so right now when a process request a the dialog UI show a cryptic /proc/pid/exe, with the change is shows the proper path of the process.

## Testing strategy
I tested with nheko and nextcloud desktop client, when they start, they both request a password to the fdosecret store, which makes keepassxc popup a dialog saying /proc/<pid>/exe is requesting a password, after the change it is replace with the proper path.

## Type of change
- ✅ Bug fix (non-breaking change that fixes an issue)

### CODE REVIEW

**Comment by HexF** [comment]
Would it possibly be worth pulling this into NixUtils?

**Comment by droidmonkey** [comment]
I was thinking that same thing, but fdo secrets is already a 'nix only service. The only benefit would be repeatability, but we don't need other process names anywhere else atm.

**Comment by bapt** [comment]
Anything I can do so that someone have a look ?

**Review by droidmonkey — APPROVED** [review]

**Comment by droidmonkey** [comment]
You need to run clang-format on the file you changed then recommit

**Comment by bapt** [comment]
Done, sorry I should have done the clang-format before submitting in the first place

**Pull request merged**
