### PR TITLE
Select the search text automatically when focused

### PR DESCRIPTION
**Pull request by knu**
## Description
When the search bar gets the focus, the whole text is automatically selected so you can type a new search text without having to clear what's already there.

## Motivation and Context
While the PR #67 was a great improvement, my "Control+F and type a word" workflow had stopped working since then.
Most popular browsers and editors do this so you can always do a fresh search every time you invoke the "Find" action, so I think KeePassXC should, too.

## How Has This Been Tested?
The new behavior is covered by the new assertions added to the GUI test.

## Types of changes
- :negative_squared_cross_mark: Bug fix (non-breaking change which fixes an issue)
- :white_check_mark: New feature (non-breaking change which adds functionality)
- :negative_squared_cross_mark: Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- :white_check_mark: I have read the **CONTRIBUTING** document. [REQUIRED]
- :white_check_mark: My code follows the code style of this project. [REQUIRED]
- :white_check_mark: All new and existing tests passed. [REQUIRED]
- :negative_squared_cross_mark: My change requires a change to the documentation.
- :negative_squared_cross_mark: I have updated the documentation accordingly.
- :white_check_mark: I have added tests to cover my changes.

### CODE REVIEW

**Comment by knu** [comment]
The GUI test failure may be because the search text edit is not visible due to the window size.
It happened to me on my local environment when I observed the test application had no icons but just captions, taking so much space that the search edit got hidden by the lack of window width.

**Comment by knu** [comment]
I had no idea how to get icons shown, so I just maximized the window as soon as the test app got run, and the test passed.  Anybody got a clue how to fix that?

**Comment by knu** [comment]
As usual, make test passes on my local macOS environment and I need some help... 🤕

**Comment by TheZ3ro** [comment]
The code seems good, IDK if maximizing the window is a good idea but it will definetly solve some problem.
On macOS icons are not loaded unless you first launch a `make install`.

Anyway your last commit fail on linux in getting the focus for the search bar.
I will test this on my environment RN

**Comment by droidmonkey** [comment]
I think there are a couple more enhancements that can be made:

- [ ] When the down arrow is pressed focus should move to the results panel regardless of text selection in the search bar
- [ ] When enter is pressed the top search entry should open in edit mode

**Comment by knu** [comment]
@droidmonkey Hi, thanks for taking a look!  Actually I'd like a search text to be selected also when I move to the text edit using Shift-Tab/Tab, as that's how the address bar and the search text box work in Chrome/Firefox etc.

> When the down arrow is pressed focus should move to the results panel regardless of text selection in the search bar
> When enter is pressed the top search entry should open in edit mode
Good idea.

**Comment by droidmonkey** [comment]
I actually just redid the code based on my comments, I'll open a new PR and close this one.

**Comment by knu** [comment]
Oops, OK, I'll leave this to you.

**Pull request closed without merging**
