### PR TITLE
Skip "StatusIndicator" window in Auto-Type window list (backport)

### PR DESCRIPTION
**Pull request by phoerious**
Backport of #7526

## Type of change
[NOTE]: # ( Please remove all lines which don't apply. )
- ✅ Bug fix (non-breaking change that fixes an issue)

### CODE REVIEW

**Comment by phoerious** [comment]
@droidmonkey The develop PR works, but please wait before merging this. The 2.7.0 branch crashes on macOS.

**Comment by phoerious** [comment]
Crashes because of #7479 (signature mismatch). We have to find another solution for patching the binaries.

EDIT: #7509 fixes the problem.

**Comment by droidmonkey** [comment]
Works fine for me, but I couldn't reproduce the problem on 12.2.1

**Review by droidmonkey — APPROVED** [review]

**Comment by phoerious** [comment]
The crash is probably on reproducible on Apple Silicon, which requires binaries to be signed. But as discussed earlier, it's a problem not with this patch, but with the change in how we patch rpaths.

**Pull request merged**
