### PR TITLE
Add German translation to Appdata

### PR DESCRIPTION
**Pull request by JakobDev**
This PR adds a German translation to the Appdata file, which provides the information for the Software Centers on Linux.

### CODE REVIEW

**Comment by droidmonkey** [comment]
@phoerious  want to include this?

**Comment by phoerious** [comment]
I think I'd rather postpone this and find a way to hook it up with Transifex and our build system. In general, we have the same issue with our .desktop files.

**Comment by JakobDev** [comment]
For PO files you can use [ITS Tool](http://itstool.org/index.html), but I don't know a Tool that can work with QTs owns File format. Maybe I should try to write one.

**Comment by JakobDev** [comment]
@phoerious I have written [2 simple scripts](https://gitlab.com/JakobDev/qt-desktop-translate) that let's you integrate the translation of .desktop files into Qt. I will see if I can do this with AppStream too.

**Comment by phoerious** [comment]
Thanks. I don't think we have to use the Qt format if other formats are more attainable. These will be separate resources on Transifex anyway.

**Comment by droidmonkey** [comment]
@phoerious are we going to close this in favor of a transifex solution or just merge this for now?

**Comment by phoerious** [comment]
Merge it, we can add it to TX anyway.

**Pull request merged**
