### PR TITLE
KeePassX PR Migration: #191 Spelling

### PR DESCRIPTION
**Pull request by phoerious**
This is a rebase of the trivial changes in keepassx/keepassx#191 by @jsoref

## Description
The patch does not fix any bugs or adds any features. It only corrects a lot of spelling mistakes in variable names and code comments.

## How Has This Been Tested?
Code still compiles and runs.

## Types of changes

- :negative_squared_cross_mark: Bug fix (non-breaking change which fixes an issue)
- :negative_squared_cross_mark: New feature (non-breaking change which adds functionality)
- :negative_squared_cross_mark: Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- :white_check_mark: I have read the **CONTRIBUTING** document. [REQUIRED]
- :white_check_mark: My code follows the code style of this project. [REQUIRED]
- :white_check_mark: All new and existing tests passed. [REQUIRED]
- :negative_squared_cross_mark: My change requires a change to the documentation.
- :negative_squared_cross_mark: I have updated the documentation accordingly.
- :negative_squared_cross_mark: I have added tests to cover my changes.

### CODE REVIEW

**Comment by droidmonkey** [comment]
Wow that is a lot of errors!

**Comment by phoerious** [comment]
Yeah, that's why It might be a good idea to merge it. 😆

**Comment by TheZ3ro** [comment]
There are still 4 commit to be added or I'm wrong?

```
spelling: successfully
spelling: transform
spelling: toggle
spelling: whose
```

**Comment by phoerious** [comment]
You're right. Not sure why my rebase onto didn't catch it. Maybe it stopped when I skipped the scrolllock entry (which actually IS writting with 3 l). Let me check.

**Comment by phoerious** [comment]
@TheZ3ro @droidmonkey  are you okay with it when I just cherry pick missing 3 commits?

**Comment by droidmonkey** [comment]
yes

**Comment by phoerious** [comment]
Unfortunately, GitHub doesn't add the commits to this PR, although I reused the same branch. Commits are in here: #161

**Pull request merged**
