### PR TITLE
Improve colorful lock icon for system tray

### LINKED ISSUE #9432: Revert colourful tray icon  on Windows - 2.7.5
## Summary
On Windows 10, with a 125% UI scale, KeePassXC 2.7.5 updated the **colourful** tray icon (for locked and unlocked database). It is now a bit smaller, and a bit blurry, even after a computer restart. The monochrome tray icon did not change, and this one seems OK.   
I reinstalled KeePassXC 2.7.4, and the colourful tray icon has a better dimension. I don't know if you have similar feeling about that...

## Examples
The 2.7.5 colourful tray icon:
image

The 2.7.4 colourful tray icon which, for me, seems better:
image

Regards,

### PR DESCRIPTION
**Pull request by droidmonkey**
* Fix #9432
* Also took this moment to simplify the selection code between locked and unlocked tray icons.

## Screenshots
[TIP]:  # ( Do not include screenshots of your actual database! )
New icon on left, v2.7.5 icon on right

image

## Testing strategy
[NOTE]: # ( Please describe in detail how you tested your changes. )
[TIP]:  # ( We expect new code to be covered by unit tests and documented with doc blocks! )
Tested on Windows

## Type of change
[NOTE]: # ( Please remove all lines which don't apply. )
- ✅ Bug fix (non-breaking change that fixes an issue)

### CODE REVIEW

**Comment by phoerious** [comment]
Hmm. I don't really like the mixed styles too much. Also, the Illustrator source file needs to be updated as well.

**Comment by droidmonkey** [comment]
What do you mean by mixed styles?

**Comment by phoerious** [comment]
The icon itself is properly shaded, the lock symbol is just a plain shape.

**Comment by droidmonkey** [comment]
I applied more of a gradient on the lock:

image

Old one for comparison:
image

**Comment by droidmonkey** [comment]
@phoerious  final version and I updated the Illustrator file

image

**Comment by droidmonkey** [comment]
@phoerious your icon looks even better! I consider this complete.

image

**Pull request merged**
