### PR TITLE
Add autotype settings to group and allow to use "window associations" in entry from parent groups.

### PR DESCRIPTION
**Pull request by frostasm**
This PR is not finished yet!

## Description

Changes: 

- Move "TriState" enum from Group to Tools 
- Add new widget "EditWidgetAutoType" 
- EditGroup and EditEntry use "EditWidgetAutoType" 
- Add algorithm for using "Window Associations" from parent groups (if enabled) 

TODO: 

- add unit tests
- do refactoring

## Motivation and context

Allow to set "Window Associations" for all items in group at one place.

## How has this been tested?

- Manually
- I plan to add some unit tests in future

## Screenshots (if appropriate):

add-autotype-settings-to-group

Group "Auto-Type" settings

image

## Types of changes

- ✅ New feature, with partial breaking change (fix or feature that would cause existing functionality to change)

I keep both new settings format and old settings format (for backward compatibility, database still can be opened in KeePass2)

## Checklist:

- ✅ I have read the **CONTRIBUTING** document. **[REQUIRED]**
- ✅ My code follows the code style of this project. **[REQUIRED]**
- ✅ My change requires a change to the documentation.

### CODE REVIEW

**Comment by TheZ3ro** [comment]
Whats the point of having a group with autotype windows association?

**Comment by frostasm** [comment]
@TheZ3ro the main idea is to have in one place the ability to change window associations for a group of entries.  
For example I have 100 devices with different passwords and I use custom application for connect to devices. Currently I must to add custom window association "//AppName.*{S:CustomField}.*" to each entry.  Create new entries by copying the old entries with existing associations is not a problem, but if in the future I'll have to change associations, it will have to do 100 times.

**Comment by frostasm** [comment]
@TheZ3ro you don't like this idea?

**Comment by TheZ3ro** [comment]
Mmmh IDK, seems good but I don't see much usage.
You can use an entry field and reference it for all the other `//AppName.{REF:etc..etc}.` so you will need to change only that entry.

What do you guys think? @keepassxreboot/core-developers

**Comment by droidmonkey** [comment]
That's an awful lot of code for one checkbox. This is a solution in search of a problem. I appreciate your example but the implementation leads a lot to be desired tbh.

**Comment by frostasm** [comment]
Maybe I'm wrong, but I think that it is convenient to manage auto-type settings at the group level (for all entries that belong to the group). 

In my opinion it is logical that all settings can be inherited from parent group, not just the auto-type sequence

I suggest to standardize (unify) settings for groups and entries

Auto-type settings for group and entry:

- Enabled state: **Enabled/Disabled/Inherit from parent group** (like in group settings) - by default **Inherit from parent group** 
- Autotype sequence - current implementation can use sequence from parent group (leave without changes)
- Windows associations - add option to allow to use parent window associations.

**Comment by TheZ3ro** [comment]
Closing for now since there is no gain with this.

**Pull request closed without merging**
