### PR TITLE
Format notes with HTML

### LINKED ISSUE #1057: Markdown preview for Notes
It'd be great to have support for previewing Markdown in the Notes section for added formatting. One could possibly have a UI similar to GitHub where you have "Write" and "Preview" tabs to toggle between. [cmark](https://github.com/commonmark/cmark) could be used as the Markdown interpreter, and QtWebEngine could be used as the previewer (or use native Windows and macOS web controls wrapped in Qt).

### PR DESCRIPTION
**Pull request by gwisp2**
Makes entry notes HTML-formatted.

## Type of change
- ✅ New feature (non-breaking change which adds functionality)

## Description and Context
Partially fixes #1057. 
To preserve formatting of existing plaintext notes line breaks are automatically replaced with &lt;br/&gt; when displaying.

Markdown support in Qt has following bugs therefore full Markdown support is not possible now.
1. Qt prepends extra empty line when parsing Markdown [(QTBUG-81060)](https://bugreports.qt.io/browse/QTBUG-81060)
2. Qt drops any text after &lt;br&gt; when parsing Markdown (It seems that this bug is not reported yet)

Following GUI widgets are changed:
- Entry editor
- Group editor
- Table of entries
- Entry preview

## Testing strategy
Manually

## Checklist:
- ✅ I have read the **CONTRIBUTING** document. **[REQUIRED]**
- ✅ My code follows the code style of this project. **[REQUIRED]**
- ❓ All new and existing tests passed. **[REQUIRED]** - TestGui::testSearch fails but it also fails without my changes
- ✅ I have compiled and verified my code with `-DWITH_ASAN=ON`. **[REQUIRED]**

### CODE REVIEW

**Comment by droidmonkey** [comment]
We can support markdown the old fashioned way: https://github.com/pbek/qmarkdowntextedit

**Comment by gwisp2** [comment]
> We can support markdown the old fashioned way: https://github.com/pbek/qmarkdowntextedit
qmarkdowntextedit just highlights markdown source, it does not display it as Qt does.
Should we use it for displaying purposes?

**Comment by droidmonkey** [comment]
Hmmmm, yes i was thinking perhaps we could extract the displaying portion out as a widget. There is also a technique to use QWebEngineView and injecting the markdown parsing script into a template index.html

https://doc.qt.io/qt-5/qtwebengine-webenginewidgets-markdowneditor-example.html

**Comment by droidmonkey** [comment]
This is not necessary for inclusion of your PR but while we are at it... Might be nice

**Comment by gwisp2** [comment]
> QWebEngineView
We need to render lots of notes in a table. I guess rendering each item via QWebEngineView and  javascript may be too slow. Another option is using cmark but I am not sure if it supports HTML tags.

> extract the displaying portion out as a widget
Ok, I'll work on it.

**Comment by droidmonkey** [comment]
Closing this as it will be implemented with Qt's built-in support for Markdown.

**Pull request closed without merging**
