### PR TITLE
Add ssh-add CLI command

### PR DESCRIPTION
**Pull request by louib**
This is a WIP to get early feedback from @hifi and @droidmonkey .

## TODOS
- [ ] Add unit tests (probably by mocking the `SSHAgent` functions)
- [ ] Implement the `-d` and `-D` options
- [ ] Update the manpage
- [ ] Add new translation strings

## Testing strategy
Manually tested for now.

## Type of change
[NOTE]: # ( Please remove all lines which don't apply. )
- ✅ New feature (change that adds functionality)
- ✅ Refactor (significant modification to existing code)
- ✅ Documentation (non-code change)

### CODE REVIEW

**Comment by droidmonkey** [comment]
Would prefer an `ssh-agent` command with --lock and --unlock switches. Default is unlock.

**Comment by hifi** [comment]
If I were to add cli functionality myself I would probably call it `ssh-add` to match the OpenSSH cli and copy its functionality somewhat.

**Comment by louib** [comment]
@hifi 
> If I were to add cli functionality myself I would probably call it ssh-add to match the OpenSSH cli and copy its functionality somewhat.

I like that. We would have `keepassxc-cli ssh-add` adding all the keys, `keepassxc-cli ssh-add -d` would remove all the keys, and then you can add/remove specific keys with `keepassxc-cli ssh-add /my/entry`  and `keepassxc-cli ssh-add -d /my/entry`. @droidmonkey what do you think?

**Comment by droidmonkey** [comment]
Love it!

**Comment by hifi** [comment]
It should add all the keys which have add-on-unlock without specifying an entry, same in reverse with -d.  Specifying an entry would be unconditional.

**Comment by louib** [comment]
> It should add all the keys which have add-on-unlock without specifying an entry, same in reverse with -d. Specifying an entry would be unconditional.

Yep, I reused `sshAgent()->databaseUnlocked(database);` for that. I'm not sure about [this](https://github.com/keepassxreboot/keepassxc/pull/6948/files#diff-36ecc20553f057922bbe8534c2f313eda692874250ba676d98ea6781f1654759R75) though.

**Comment by louib** [comment]
`keepassxc-cli ssh-add -l` could be cool also to list which entries in the db hold SSH keys.

**Comment by hifi** [comment]
I don't think it matters as you test for failures already.

Does interactive mode work correctly with this already so it automatically adds and removes keys like with the GUI when unlocking?

**Comment by louib** [comment]
@hifi I would assume it would work with interactive mode but I haven't tested it yet.

**Comment by louib** [comment]
I am no longer storing my ssh keys in keepassxc, so I won't be taking this PR to the finish line. I won't delete the branch in case it can be useful to someone.

**Comment by droidmonkey** [comment]
Oops, I accidentally deleted the branch, dumb github app... it's OK, I don't think this is a very useful feature. Especially considering you cannot remove the key on lock anymore.

**Pull request closed without merging**
