### PR TITLE
Enable shadow warnings on GCC and tweak CMake

### PR DESCRIPTION
**Pull request by AaronDMarasco**
Also added new CMake macros to reduce explicit version/compiler checks for features

Found one unused variable (because the lambda shadowed, original never used)

Fixed handful of shadowed variables

## Testing strategy
Locally tested with GCC 10.1.1 and clang 10.0.0 (Fedora 32). Taking advantage of CI system for other compilers.

Local cmake is 3.17.3 but didn't use any advanced features.

## Type of change
- ✅ Bug fix (non-breaking change that fixes an issue)

### CODE REVIEW

**Comment by phoerious** [comment]
zxcvbn bugs should be fixed upstream, not here.

**Comment by AaronDMarasco** [comment]
> zxcvbn bugs should be fixed upstream, not here.

I guessed that might be the case but didn't see `/ext/` or similar in the path. I'll roll those ones out.

I'm assuming you squash merges; if not, I'll force update.

**Comment by phoerious** [comment]
Please force-push. We'll rebase/squash the PR as needed.

**Comment by phoerious** [comment]
This branch is reverting your previous change.

**Pull request closed without merging**
