### PR TITLE
Toolbar and tool buttons style.

### LINKED ISSUE #2343: Ability to remove toolbar and replace icons with text labels
Visual agnosia is a vision impairment that makes one unable to recognize things. Like icons. Also, a variety of conditions can cause difficulty discerning what tiny icons represent. This is a feature request for either the ability to remove the icons-only toolbar, to have the icons replaced with text labels, or preferably both.

## Expected Behavior
Ideally, one would go into the settings and either check or uncheck "Show toolbar" or check "Icons only", "Icons and text", or "Text only". This would give more freedom in how people prefer to have their buttons, for whatever reason, or remove them entirely, if, for example, the system font size was large enough to make a toolbar impractical.

## Current Behavior
At present, there is no apparent way to edit the toolbar, remove the toolbar, or change how the buttons on the toolbar are displayed. There is nothing in the settings menu, nor can you right click on the toolbar or a button to edit, which is more or less the two main ways of accomplishing this. (I can't find any settings about this anywhere, either.)

## Possible Solution
I wish I knew enough to offer a potential way to fix this. 

## Context
I find the toolbar distracting. It also makes the program look more cluttered. I'd love if it could be removed entirely, since I'm used to using the menus. Though some text buttons would be nice, fewer mouse clicks that way. But if you did that, you'd need to make sure that what's included in the toolbar can be edited, because otherwise it wouldn't fit with the font size I use. 

## Debug Info

KeePassXC - 2.3.4
Revision: 6fe821c

Libraries:
- Qt 5.11.1
- libgcrypt 1.8.3

Operating system: Manjaro Linux
CPU architecture: x86_64
Kernel: linux 4.17.19-1-MANJARO

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

### PR DESCRIPTION
**Pull request by boppybibbles**
## Description
- Add ability to change toolbar state and tool buttons style via application settings widget.
- Save/restore toolbar state on app start/finish.

## Motivation and context
- Resolves #2343.

## How has this been tested?
Manually.

## Screenshots (if appropriate):
image

## Types of changes
- ✅ New feature (non-breaking change which adds functionality)

## Checklist:
- ✅ I have read the **CONTRIBUTING** document. **[REQUIRED]**
- ✅ My code follows the code style of this project. **[REQUIRED]**
- ✅ All new and existing tests passed. **[REQUIRED]**
- ✅ I have compiled and verified my code with `-DWITH_ASAN=ON`. **[REQUIRED]**

### CODE REVIEW

**Comment by phoerious** [comment]
I'll be honest: I'm not a very big fan of such a gigantic vertical toolbar and don't really see the point of it.

**Comment by boppybibbles** [comment]
Toolbar position and buttons style is configurable, default values were not changed. Motivation here is accessibility for those who need it.

**Comment by phoerious** [comment]
What are situations in which this is needed besides personal preference?

**Comment by boppybibbles** [comment]
> What are situations in which this is needed besides personal preference?

As per #2343 particular situation is visual agnosia condition.

**Comment by phoerious** [comment]
You don't need a vertical toolbar for that.

**Comment by droidmonkey** [comment]
@phoerious the vertical orientation is optional, you can drag it around. Although @boppybibbles I couldn't get the toolbar to attach on the sides in Windows.

toolbar

**Comment by boppybibbles** [comment]
> Although @boppybibbles I couldn't get the toolbar to attach on the sides in Windows.
Try to make main window wider. It won't stick if window is not wide enough.

**Pull request merged**
