### PR TITLE
Add OpenPGP / assymetric encryption support

### PR DESCRIPTION
**Pull request by svenseeberg**
* Add a Widget for adding an assymetrically encrypted key component.
* Add support for encrypting a key component with GnuPG and hence
  OpenPGP Smart Cards.

[TIP]:  # ( Provide a general summary of your changes in the title above ^^ )

## Type of change
[NOTE]: # ( Please remove all lines which don't apply. )
- ✅ New feature (non-breaking change which adds functionality)

## Description and Context
[NOTE]: # ( Describe your changes in detail, why is this change required? )
[NOTE]: # ( Describe the context of your change. Explain large code modifications. )
[NOTE]: # ( If it fixes an open issue, please add "Fixes #XXX" as necessary )

## Screenshots
Screenshot from 2019-03-12 18-08-41

## Testing strategy
[NOTE]: # ( Please describe in detail how you tested your changes. )
[TIP]:  # ( We expect new code to be covered by unit tests and documented with doc blocks! )

## Checklist:
[NOTE]: # ( Please go over all the following points. )
[NOTE]: # ( Again, remove any lines which don't apply. )
[NOTE]: # ( Pull Requests that don't fulfill all [REQUIRED] requisites are likely )
[NOTE]: # ( to be sent back to you for correction or will be rejected.  )
- ✅ I have read the **CONTRIBUTING** document. **[REQUIRED]**
- ✅ My code follows the code style of this project. **[REQUIRED]**
- ✅ All new and existing tests passed. **[REQUIRED]**
- ✅ I have compiled and verified my code with `-DWITH_ASAN=ON`. **[REQUIRED]**
- ✅ My change requires a change to the documentation, and I have updated it accordingly.
- ✅ I have added tests to cover my changes.

### CODE REVIEW

**Comment by svenseeberg** [comment]
Sorry, opened the PR against the wrong repo. Should have been my private fork.

**Comment by droidmonkey** [comment]
Oooh and you got me all excited!

**Comment by svenseeberg** [comment]
I'm working on it. (And probably got the worst part for me sorted: working out the Qt UI stuff.)

**Comment by phoerious** [comment]
Just so we get off on the right foot... is GPGME the way to go? I must admit I don't really know how this library works and the documentation is horrendous. What I would expect from the GPG feature is a loose coupling between KeePassXC and the gpg-agent via sockets.

If GPGME is just a small library doing exactly that, that's fine. But to me it looks more like the whole GPG universe and I really don't want to mess with that. It's an enormous amount of complexity added to KeePassXC meaning more dependencies, a ton of legacy code, and possibly even bindings to Gtk+ etc. (may not be true, just read that on Google). If it's possible to constrain all GPG communication to a socket between KeePassXC and a running gpg-agent, that'd be my preferred choice (and also the more flexible way I guess, because KeePassXC needs no knowledge of what keys and devices are used for actually encrypting stuff). My dream implementation would be: generate a (bunch of) master secret(s), send them to a running gpg-agent, get a cipher text back, put them in the public KDBX header, done.

**Comment by svenseeberg** [comment]
AFAICT the gpg-agent documentation is even worse and I could not even tell if it covers the functionality needed. To be honest, I'm not yet really at the point where I'm implementing gpgme or any other library. Currently, its just a placeholder to see if everything works as intended. Also, if everything works as I envision it, replacing it should be relatively easy. But I have your worries in mind and will look into it.

**Pull request closed without merging**
