### PR TITLE
Move local config from ~/.cache to ~/.local/share on Linux

### LINKED ISSUE #4911: Does not open last used database automatically
Hi!
I often have the issue, that when using the global autotype shortcut, nothing happens, because KeepassXC does not open the last used database. I have to open the main window and select the last (and only) database from the recents list. Then it works for a while. Maybe there should be an option to set the default database.

### LINKED ISSUE #5313: Local config data is cleared when ~/.cache mounted on tempfs
## Overview
Since the big update (new gui) keepassXC  very very rarely remembers the last database no matter whether I shutdown the desktop cleanly or with a three or four finger salute (KDE only ?). Before the update it remembered fine. It is enabled in the options. Remember and open on startup

As I only ever use one database my workaround has been , just now, to change it's user .desktop file to explicitly open the database

## Steps to Reproduce

1. Tell keepassXC to remember last database and open on start up.
2. Restart the computer or X by any method
3. Start KeepassXC

## Expected Behavior
Ask me for the password for the last used database instead of having to navigate to it's location almost every time.

## Actual Behavior
Have to navigate to it's location almost every time.

## Context
It occasionally works but I fail to see a pattern. I've tried making sure KeepassXC is closed cleanly but that doesn't make a difference AFAICT. 

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.6.1
Revision: 9a35bba

Qt 5.15.0
Debugging mode is disabled.

Operating system: Gentoo/Linux
CPU architecture: x86_64
Kernel: linux 5.8.3-gentoo-x86_64

Enabled extensions:
- SSH Agent
- Secret Service Integration

Cryptographic libraries:
 libgcrypt 1.8.6

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux/
Desktop Env: KDE
Windowing System: X11

### PR DESCRIPTION
**Pull request by z3ntu**
Some users have ~/.cache mounted on tmpfs which meant that the
'Recent Databases' were lost after every reboot. Move that config to
~/.local/share which is meant for this kind of data.

Fixes #4911
Fixes #5313

## Testing strategy

`~/.local/share/keepassxc/keepassxc.ini` gets created now and not `~/.cache/keepassxc/keepassxc.ini`

## Type of change
- ✅ Bug fix (non-breaking change that fixes an issue)

---

I wasn't sure which branch to target with this PR, it's currently targeting develop, #5313 has the milestone v2.6.2

### CODE REVIEW

**Comment by phoerious** [comment]
> I can't disagree with that, but others have rightly stated there are no other config files being stored in .cache.

The things we store there are technically not config options.

**Comment by z3ntu** [comment]
> You should move a config file currently in cache to the new location.

I've looked into this a bit but I'm not sure how to properly do that. Is it okay if I just move the config file at the start of the `migrate()` function or will this break things? I'm not familiar with the code base so a few pointers would be quite helpful :)

**Comment by droidmonkey** [comment]
Bumping the config version and putting it in migrate is a good idea.

**Comment by phoerious** [comment]
`~/.local/share/keepassxc/keepassxc.ini` is totally the wrong location and makes the whole split redundant. You might as well save the local config to ~/.config/keepassxc/keepassxc.ini then.

**Comment by droidmonkey** [comment]
Well then how about keepassxc_local.ini on Linux.

**Comment by z3ntu** [comment]
@phoerious What's wrong with ~/.local/share ? That's _the_ location for non-config user-specific application data.

**Comment by kotoko** [comment]
Let me reply to @phoerious . I don't want to fight you but only share my perspective.

> Cache is just the wrong place to have on a tmpfs.

IMHO it's wrong assumption that `~/.cache` directory won't be deleted on logout or reboot. The same situation as `/tmp`. I'm not sure what correct directory is but I'm sure that deleting `~/.cache` should not change application settings or history.

> I am actually again merging this. Putting .cache on a tmpfs is like deleting your cookies when you close the browser and then complaining about having to re-login on every website.

Web browsers have own cache also so I would say that deleting .cache is the same as deleting web browsers' cache. That triggers redownload of all images and open tabs but does not delete open tabs or cookies.

**Comment by phoerious** [comment]
.cache is for "non-essential" (i.e. disposable) user data and it is supposed to store a lot of it such as image thumbnails and such. Putting that on a tmpfs is the wrong thing to do for several reasons, even though the Debian project may see that differently. The XDG spec says nothing about it being "volatile", contrary to XDG_RUNTIME_DIR.

**Comment by kotoko** [comment]
It looks like XDG spec says almost nothing about $XDG_CACHE_HOME which is kind of sad. So assuming that it will be purged rarely/frequently is wrong. But it can be purged at some point. Interesting...

I guess my last question would be: is file history in kepassxc really "non-essential"?

**Comment by phoerious** [comment]
I see it very much like cookies. Yes, it is essential for most in most circumstances, but it is disposable and for certain users it is absolutely crucial that it is so.

**Comment by z3ntu** [comment]
Cookies aren't stored in cache - they are still there when you delete the cache. I consider cache as something e.g. when you have a big complicated file where you need to extract certain information which takes long - then you put the result into the cache and you read from cache next time so it's faster. If the cache is deleted it doesn't matter at all because it will just read the original file again and regenerate the cache.
That's what I consider a cache.
And a "last used files" list is not that.

**Comment by phoerious** [comment]
Not true. When you use the disk cleanup feature on Windows, you can select to clean up cookies as well next to any other disposable, temporary, or volatile data.

**Comment by z3ntu** [comment]
I don't think we will get anywhere with this discussion.
You say that the recently used list belongs into ~/.cache and I disagree.
I say the recently used list belongs into ~/.local/share and you disagree.
I don't see either side changing their opinion anytime soon.

But as 6 people (including me) have complained in either #4911 or #5313 that having the list on ~/.cache clears the list when they don't want to I hope you reconsider and allow the list to be put into ~/.local/share (or anywhere away from ~/.cache).

**Comment by droidmonkey** [comment]
I'm in favor of an ENV VAR solution... KPXC_LOCAL_CONFIG=[directory]

**Comment by Kieltux** [comment]
Source: https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html
"There is a single base directory relative to which user-specific configuration files should be written. This directory is defined by the environment variable $XDG_CONFIG_HOME."
An ini file (like keepassxc.ini) is in my opinion a user-specific configuration file, so it should be written to ~/.config.

"There is a single base directory relative to which user-specific non-essential (cached) data should be written. This directory is defined by the environment variable $XDG_CACHE_HOME."
I empty the ~/.cache directory from time to time. It should be safe to empty the ~/.cache directory without changing anything (like empty tmp directories).

**Comment by phoerious** [comment]
Iit is safe. You di not lose any essential settings. And only because the format is ini doesn't make it a config file. Ini is just a generic key-value format.

**Comment by droidmonkey** [comment]
I will only merge this if it uses the env var solution i mentioned above. No need to move the config file in that case.

**Comment by z3ntu** [comment]
Sorry, I'm not willing to implement a solution which uses environment variables to achieve this. In my opinion (and I've talked with a couple of other people about this) the list of recently used files definitely doesn't belong into ~/.cache but into ~/.local/share (I agree that ~/.config was incorrect but ~/.cache is way worse). If you're not willing to accept the PR in its current form please close it.

**Comment by droidmonkey** [comment]
Suit yourself, I'll do it myself

**Pull request closed without merging**
