### PR TITLE
Fix install of libssl and libcrypto on Windows build

### LINKED ISSUE #4523: Issue trying to create package with windows7+msys2
Hi, after trying to follow carefully the instructions at https://github.com/keepassxreboot/keepassxc/wiki/Set-up-Build-Environment-on-Windows and installing all the corresponding packages (as well as wix) I've managed to build keepasxc as well as many other targets +/- ok.

Now, I haven't been able to manage to make a package out of it, please take a look to the log when I try to build `keepasxc-proxy`:

```
$ cmake.exe --build . --target keepassxc-proxy -- -j8 VERBOSE=1
/D/software/vcpkg/downloads/tools/cmake-3.12.4-windows/cmake-3.12.4-win32-x86/bin/cmake.exe -H/C/msys64/home/KneDa/keepassxc -B/C/msys64/home/KneDa/keepassxc/build --check-build-system CMakeFiles/Makefile.cmake 0
/usr/bin/make -f CMakeFiles/Makefile2 keepassxc-proxy
make[1]: Entering directory '/home/KneDa/keepassxc/build'
/D/software/vcpkg/downloads/tools/cmake-3.12.4-windows/cmake-3.12.4-win32-x86/bin/cmake.exe -H/C/msys64/home/KneDa/keepassxc -B/C/msys64/home/KneDa/keepassxc/build --check-build-system CMakeFiles/Makefile.cmake 0
/D/software/vcpkg/downloads/tools/cmake-3.12.4-windows/cmake-3.12.4-win32-x86/bin/cmake.exe -E cmake_progress_start /C/msys64/home/KneDa/keepassxc/build/CMakeFiles 3
/usr/bin/make -f CMakeFiles/Makefile2 src/proxy/CMakeFiles/keepassxc-proxy.dir/all
make[2]: Entering directory '/home/KneDa/keepassxc/build'
/usr/bin/make -f src/proxy/CMakeFiles/proxy_autogen.dir/build.make src/proxy/CMakeFiles/proxy_autogen.dir/depend
make[3]: Entering directory '/home/KneDa/keepassxc/build'
/D/software/vcpkg/downloads/tools/cmake-3.12.4-windows/cmake-3.12.4-win32-x86/bin/cmake.exe -E cmake_depends "MSYS Makefiles" /C/msys64/home/KneDa/keepassxc /C/msys64/home/KneDa/keepassxc/src/proxy /C/msys64/home/KneDa/keepassxc/build /C/msys64/home/KneDa/keepassxc/build/src/proxy /C/msys64/home/KneDa/keepassxc/build/src/proxy/CMakeFiles/proxy_autogen.dir/DependInfo.cmake --color=
make[3]: Leaving directory '/home/KneDa/keepassxc/build'
/usr/bin/make -f src/proxy/CMakeFiles/proxy_autogen.dir/build.make src/proxy/CMakeFiles/proxy_autogen.dir/build
make[3]: Entering directory '/home/KneDa/keepassxc/build'
[ 33%] Automatic MOC and UIC for target proxy
cd /C/msys64/home/KneDa/keepassxc/build/src/proxy && /D/software/vcpkg/downloads/tools/cmake-3.12.4-windows/cmake-3.12.4-win32-x86/bin/cmake.exe -E cmake_autogen C:/msys64/home/KneDa/keepassxc/build/src/proxy/CMakeFiles/proxy_autogen.dir/AutogenInfo.cmake Release
make[3]: Leaving directory '/home/KneDa/keepassxc/build'
[ 33%] Built target proxy_autogen
/usr/bin/make -f src/proxy/CMakeFiles/proxy.dir/build.make src/proxy/CMakeFiles/proxy.dir/depend
make[3]: Entering directory '/home/KneDa/keepassxc/build'
/D/software/vcpkg/downloads/tools/cmake-3.12.4-windows/cmake-3.12.4-win32-x86/bin/cmake.exe -E cmake_depends "MSYS Makefiles" /C/msys64/home/KneDa/keepassxc /C/msys64/home/KneDa/keepassxc/src/proxy /C/msys64/home/KneDa/keepassxc/build /C/msys64/home/KneDa/keepassxc/build/src/proxy /C/msys64/home/KneDa/keepassxc/build/src/proxy/CMakeFiles/proxy.dir/DependInfo.cmake --color=
make[3]: Leaving directory '/home/KneDa/keepassxc/build'
/usr/bin/make -f src/proxy/CMakeFiles/proxy.dir/build.make src/proxy/CMakeFiles/proxy.dir/build
make[3]: Entering directory '/home/KneDa/keepassxc/build'
make[3]: Nothing to be done for 'src/proxy/CMakeFiles/proxy.dir/build'.
make[3]: Leaving directory '/home/KneDa/keepassxc/build'
[ 66%] Built target proxy
/usr/bin/make -f src/proxy/CMakeFiles/keepassxc-proxy_autogen.dir/build.make src/proxy/CMakeFiles/keepassxc-proxy_autogen.dir/depend
make[3]: Entering directory '/home/KneDa/keepassxc/build'
/D/software/vcpkg/downloads/tools/cmake-3.12.4-windows/cmake-3.12.4-win32-x86/bin/cmake.exe -E cmake_depends "MSYS Makefiles" /C/msys64/home/KneDa/keepassxc /C/msys64/home/KneDa/keepassxc/src/proxy /C/msys64/home/KneDa/keepassxc/build /C/msys64/home/KneDa/keepassxc/build/src/proxy /C/msys64/home/KneDa/keepassxc/build/src/proxy/CMakeFiles/keepassxc-proxy_autogen.dir/DependInfo.cmake --color=
make[3]: Leaving directory '/home/KneDa/keepassxc/build'
/usr/bin/make -f src/proxy/CMakeFiles/keepassxc-proxy_autogen.dir/build.make src/proxy/CMakeFiles/keepassxc-proxy_autogen.dir/build
make[3]: Entering directory '/home/KneDa/keepassxc/build'
[ 66%] Automatic MOC and UIC for target keepassxc-proxy
cd /C/msys64/home/KneDa/keepassxc/build/src/proxy && /D/software/vcpkg/downloads/tools/cmake-3.12.4-windows/cmake-3.12.4-win32-x86/bin/cmake.exe -E cmake_autogen C:/msys64/home/KneDa/keepassxc/build/src/proxy/CMakeFiles/keepassxc-proxy_autogen.dir/AutogenInfo.cmake Release
make[3]: Leaving directory '/home/KneDa/keepassxc/build'
[ 66%] Built target keepassxc-proxy_autogen
/usr/bin/make -f src/proxy/CMakeFiles/keepassxc-proxy.dir/build.make src/proxy/CMakeFiles/keepassxc-proxy.dir/depend
make[3]: Entering directory '/home/KneDa/keepassxc/build'
/D/software/vcpkg/downloads/tools/cmake-3.12.4-windows/cmake-3.12.4-win32-x86/bin/cmake.exe -E cmake_depends "MSYS Makefiles" /C/msys64/home/KneDa/keepassxc /C/msys64/home/KneDa/keepassxc/src/proxy /C/msys64/home/KneDa/keepassxc/build /C/msys64/home/KneDa/keepassxc/build/src/proxy /C/msys64/home/KneDa/keepassxc/build/src/proxy/CMakeFiles/keepassxc-proxy.dir/DependInfo.cmake --color=
make[3]: Leaving directory '/home/KneDa/keepassxc/build'
/usr/bin/make -f src/proxy/CMakeFiles/keepassxc-proxy.dir/build.make src/proxy/CMakeFiles/keepassxc-proxy.dir/build
make[3]: Entering directory '/home/KneDa/keepassxc/build'
[100%] Linking CXX executable keepassxc-proxy.exe
cd /C/msys64/home/KneDa/keepassxc/build/src/proxy && /D/software/vcpkg/downloads/tools/cmake-3.12.4-windows/cmake-3.12.4-win32-x86/bin/cmake.exe -E remove -f CMakeFiles/keepassxc-proxy.dir/objects.a
cd /C/msys64/home/KneDa/keepassxc/build/src/proxy && /C/msys64/mingw64/bin/ar.exe cr CMakeFiles/keepassxc-proxy.dir/objects.a @CMakeFiles/keepassxc-proxy.dir/objects1.rsp
cd /C/msys64/home/KneDa/keepassxc/build/src/proxy && /C/msys64/mingw64/bin/g++.exe  -fno-common -Wall -Wextra -Wundef -Wpointer-arith -Wno-long-long -Wformat=2 -Wmissing-format-attribute -fvisibility=hidden -fvisibility-inlines-hidden -fstack-protector-strong -fno-exceptions -fno-rtti -Wnon-virtual-dtor -Wold-style-cast -Woverloaded-virtual -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -Werror=format-security -Wcast-align -std=c++11 -fsized-deallocation -Wno-deprecated-declarations -O3 -DNDEBUG   -Wl,--nxcompat -Wl,--dynamicbase -Wl,--high-entropy-va -Wl,--whole-archive CMakeFiles/keepassxc-proxy.dir/objects.a -Wl,--no-whole-archive  -o keepassxc-proxy.exe -Wl,--out-implib,libkeepassxc-proxy.dll.a -Wl,--major-image-version,0,--minor-image-version,0 @CMakeFiles/keepassxc-proxy.dir/linklibs.rsp
collect2.exe: error: ld returned 5 exit status
make[3]: *** [src/proxy/CMakeFiles/keepassxc-proxy.dir/build.make:108: src/proxy/keepassxc-proxy.exe] Error 1
make[3]: *** Deleting file 'src/proxy/keepassxc-proxy.exe'
make[3]: Leaving directory '/home/KneDa/keepassxc/build'
make[2]: *** [CMakeFiles/Makefile2:605: src/proxy/CMakeFiles/keepassxc-proxy.dir/all] Error 2
make[2]: Leaving directory '/home/KneDa/keepassxc/build'
make[1]: *** [CMakeFiles/Makefile2:617: src/proxy/CMakeFiles/keepassxc-proxy.dir/rule] Error 2
make[1]: Leaving directory '/home/KneDa/keepassxc/build'
make: *** [Makefile:353: keepassxc-proxy] Error 2
```

Therefore when trying to do `make package` it'll stop at that point as well `[ 58%] Linking CXX executable keepassxc-proxy.exe`

Could you please advice?

Ns. I've also experienced some issues (compiler gets stuck) when trying to use ccache so right now I've just disabled, is this one familiar?

### PR DESCRIPTION
**Pull request by droidmonkey**
[TIP]:  # ( Provide a general summary of your changes in the title above ^^ )

## Type of change
[NOTE]: # ( Please remove all lines which don't apply. )
- ✅ Bug fix (non-breaking change which fixes an issue)

## Description and Context
[NOTE]: # ( Describe your changes in detail, why is this change required? )
[NOTE]: # ( Describe the context of your change. Explain large code modifications. )
[NOTE]: # ( If it fixes an open issue, please add "Fixes #XXX" as necessary )
* Replace find_library with find_file. CMake likely changed behavior of find_library to exclude dll files.

* Fixes #4523 

## Testing strategy
[NOTE]: # ( Please describe in detail how you tested your changes. )
[TIP]:  # ( We expect new code to be covered by unit tests and documented with doc blocks! )
Tested on Windows with mingw64 and mingw32.

## Checklist:
[NOTE]: # ( Please go over all the following points. )
[NOTE]: # ( Again, remove any lines which don't apply. )
[NOTE]: # ( Pull Requests that don't fulfill all [REQUIRED] requisites are likely )
[NOTE]: # ( to be sent back to you for correction or will be rejected.  )
- ✅ I have read the **CONTRIBUTING** document. **[REQUIRED]**
- ✅ My code follows the code style of this project. **[REQUIRED]**
- ✅ All new and existing tests passed. **[REQUIRED]**
- ✅ I have compiled and verified my code with `-DWITH_ASAN=ON`. **[REQUIRED]**
- ✅ My change requires a change to the documentation, and I have updated it accordingly.
- ✅ I have added tests to cover my changes.

### CODE REVIEW

**Comment by phoerious** [comment]
Have you tried finding the lib without the extension? It should be able to find .a and .dll files. find_file doesn't make much sense to me.

**Comment by droidmonkey** [comment]
Yes I tried numerous permutations using find_library

**Comment by droidmonkey** [comment]
I think find_file makes sense in this context because we are looking for a specific file to copy into the install directory. Finding a library can (and should) makes assumptions about the type of file you are looking for (shared vs static).

**Comment by phoerious** [comment]
That is somewhat contrary to what the documentation says:

> Each library name given to the NAMES option is first considered as a library file name and then considered with platform-specific prefixes (e.g. lib) and suffixes (e.g. .so). Therefore one may specify library file names such as libfoo.a directly. This can be used to locate static libraries on UNIX-like systems.

https://cmake.org/cmake/help/latest/command/find_library.html

.dll is also definitly defined as a dynamic library suffix on Windows: https://gitlab.kitware.com/cmake/cmake/blob/master/Modules/Platform/Windows.cmake

**Pull request merged**
