### PR TITLE
Use unlock dialog when unlocking a database from browser extension

### PR DESCRIPTION
**Pull request by varjolintu**
[TIP]:  # ( Provide a general summary of your changes in the title above ^^ )

## Type of change
[NOTE]: # ( Please remove all lines which don't apply. )
- ✅ New feature (non-breaking change which adds functionality)

## Description and Context
[NOTE]: # ( Describe your changes in detail, why is this change required? )
[NOTE]: # ( Describe the context of your change. Explain large code modifications. )
[NOTE]: # ( If it fixes an open issue, please add "Fixes #XXX" as necessary )
Instead of rising the KeePassXC window to the front, a separate unlock dialog is used.

## Testing strategy
[NOTE]: # ( Please describe in detail how you tested your changes. )
[TIP]:  # ( We expect new code to be covered by unit tests and documented with doc blocks! )
Manually.

## Checklist:
[NOTE]: # ( Please go over all the following points. )
[NOTE]: # ( Again, remove any lines which don't apply. )
[NOTE]: # ( Pull Requests that don't fulfill all [REQUIRED] requisites are likely )
[NOTE]: # ( to be sent back to you for correction or will be rejected.  )
- ✅ I have read the **CONTRIBUTING** document. **[REQUIRED]**
- ✅ My code follows the code style of this project. **[REQUIRED]**
- ✅ All new and existing tests passed. **[REQUIRED]**
- ✅ I have compiled and verified my code with `-DWITH_ASAN=ON`. **[REQUIRED]**

### CODE REVIEW

**Comment by phoerious** [comment]
This PR would break effective handling of multiple databases the same way Auto-Type does atm, right?

**Comment by varjolintu** [comment]
@phoerious It would, yes. But it's possible to dismiss the dialog and use the main window for opening some other database instead.

**Comment by phoerious** [comment]
I would prefer we move this to 2.6 then and fix UnlockDialog first. It's unfortunate, we didn't manage to do that for 2.5.

**Comment by varjolintu** [comment]
Sure. Let's do that.

**Comment by droidmonkey** [comment]
This should wait until we reconfigure this dialog to allow selecting the database to unlock.

**Comment by droidmonkey** [comment]
Let's include this in 2.6

**Comment by phoerious** [comment]
We did not fix the unlock dialogue not handling multiple databases. That would be another refractor.

**Comment by droidmonkey** [comment]
Right that's a 2.7 job now

**Pull request merged**
