### PR TITLE
Generate the D-Bus adaptor class on the fly

### LINKED ISSUE #5355: DBus interface name does not match XML definition file
## Overview
In https://github.com/keepassxreboot/keepassxc/blob/develop/src/gui/org.keepassxc.KeePassXC.MainWindow.xml, the interface name is declared to be `org.keepassxc.KeePassXC.MainWindow`, while the actual interface name is `org.keepassxc.MainWindow` [1].

[1] https://github.com/keepassxreboot/keepassxc/blob/develop/src/gui/MainWindowAdaptor.h

## Steps to Reproduce
1. Try to open a database with the instruction on the Wiki [2]
```
qdbus org.keepassxc.KeePassXC.MainWindow /keepassxc org.keepassxc.KeePassXC.MainWindow.openDatabase /path/to/database.kdbx passwd /path/to/key
```
[2] https://github.com/keepassxreboot/keepassxc/wiki/Using-DBus-with-KeePassXC

## Expected Behavior
It works.

## Actual Behavior
The working command is different from what the Wiki says

```
qdbus org.keepassxc.KeePassXC.MainWindow /keepassxc org.keepassxc.MainWindow.openDatabase /path/to/database.kdbx passwd /path/to/key
```

In https://github.com/keepassxreboot/keepassxc/commit/98a89e4f2c973683aef8f57eb527d3b7110d6287#diff-29eaf0e2a89ffcb6e44f29774368a853, `org.keepassxc.MainWindow.xml` is renamed to `org.keepassxc.KeePassXC.MainWindow.xml`, and `MainWindowAdaptor.h` is regenerated, but from the comment it appears to be generated with the old interface name.
```
Command line was: qdbusxml2cpp -c MainWindowAdaptor -a MainWindowAdaptor.h:MainWindowAdaptor.cpp org.keepassxc.MainWindow.xml
```
After regenerating MainWindowAdaptor.{h,cpp} and rebuilding, the `openDatabase` command mentioned on Wiki works.

## Context

KeePassXC - Version 2.6.1
Revision: 9a35bba

Qt 5.15.0
Debugging mode is disabled.

Operating system: Arch Linux
CPU architecture: x86_64
Kernel: linux 5.8.5-arch1-1

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
 libgcrypt 1.8.6

Desktop Env: LXQt
Windowing System: X11

### PR DESCRIPTION
**Pull request by yan12125**
That prevents mismatches between the adaptor class and the D-Bus
definition file.

Note that this is a backward-incompatible change. For example, the
command to lock all databases is changed from

> dbus-send --session --print-reply --dest=org.keepassxc.KeePassXC.MainWindow --type=method_call /keepassxc org.keepassxc.MainWindow.lockAllDatabases

to

> dbus-send --session --print-reply --dest=org.keepassxc.KeePassXC.MainWindow --type=method_call /keepassxc org.keepassxc.KeePassXC.MainWindow.lockAllDatabases

Fixes: https://github.com/keepassxreboot/keepassxc/issues/5355

## Screenshots
N/A

## Testing strategy
Manually with dbus-send commands mentioned in the commit message

## Type of change
- ✅ Bug fix (non-breaking change that fixes an issue)
- ✅ Breaking change (causes existing functionality to change)

### CODE REVIEW

**Review by phoerious — APPROVED** [review]
@droidmonkey Do we want to merge this into 2.7 oder defer to 2.8?

**Comment by droidmonkey** [comment]
We can do this now, just need to add to changelog that we are now properly using the org.keepassxc.KeePassXC namespace on our dbus interface. 

Also need to test that, but not to hard to do

**Comment by yan12125** [comment]
Hmm, should I rebase this to 2.7?

**Comment by droidmonkey** [comment]
Yes please.  Tested this and it works perfectly.

**Comment by yan12125** [comment]
Thanks, done!

**Review by droidmonkey — APPROVED** [review]

**Pull request merged**
