### PR TITLE
Moved a hardcoded English menu string to the string resources

### PR DESCRIPTION
**Pull request by vsvyatski**
## Description
Using the Russian localization of KeepassXC I noticed that the menu item "Database > Recent databases > **Clear history**" is not translated to Russian. I couldn't find that string nontranslated on Transiflex, it was just missing. I took a look at the code and found out that the string was just hardcoded (there was no call to `tr(...)`). So I added the call and added the string to keepassx_en.ts and keepassx_ru.ts.

Note, a new string was required to be added to keepassx_en.ts, therefore I couldn't just translate it on Transiflex. I believe I don't have the permission to upload a new base file for translations on Transiflex and I don't see the option to create a new string in the Transiflex web interface. So please make the appropriate arrangements with Transiflex using the TS files updated by me.

## Motivation and context
I'm trying to use the Russian translation of KeepassXC (because I'm Russian) and I don't like the translation flaws and nonfinished translations, therefore I'm contributing this stuff.

## How has this been tested?
This was tested by building and running the program and ensuring that the menu string I've mentioned above looks Russian. Also I've built the thing with `-DWITH_TESTS=ON` and `-DWITH_GUI_TESTS=ON` and run `make test`. 24 of 25 tests have been OK. Number 18 is failing, but it is not related to my change.

## Screenshots (if appropriate):
Here is the screenshot of the current public version 2.1.4 in Russian where that menu item is English
nonlocalized

## Types of changes
- ✅ Bug fix (non-breaking change which fixes an issue)

## Checklist:
- ✅ I have read the **CONTRIBUTING** document. **[REQUIRED]**
- ✅ My code follows the code style of this project. **[REQUIRED]**
- ✅ 24 of 25 tests are passing except for 18. It has something to do with a CSV parser, but I haven't touched that parser, so I don't think it was me who introduced the problem **[REQUIRED]**
Here is the output from your testing utility
```
Running tests...
Test project D:/MyRepositories/keepassxc/build
      Start  1: testgroup
 1/25 Test  #1: testgroup ........................   Passed    0.12 sec
      Start  2: testkeepass2xmlreader
 2/25 Test  #2: testkeepass2xmlreader ............   Passed    0.22 sec
      Start  3: testkeys
 3/25 Test  #3: testkeys .........................   Passed    0.17 sec
      Start  4: testkeepass2reader
 4/25 Test  #4: testkeepass2reader ...............   Passed    0.13 sec
      Start  5: testkeepass2writer
 5/25 Test  #5: testkeepass2writer ...............   Passed    0.17 sec
      Start  6: testgroupmodel
 6/25 Test  #6: testgroupmodel ...................   Passed    0.12 sec
      Start  7: testentrymodel
 7/25 Test  #7: testentrymodel ...................   Passed    0.12 sec
      Start  8: testcryptohash
 8/25 Test  #8: testcryptohash ...................   Passed    0.03 sec
      Start  9: testsymmetriccipher
 9/25 Test  #9: testsymmetriccipher ..............   Passed    0.10 sec
      Start 10: testhashedblockstream
10/25 Test #10: testhashedblockstream ............   Passed    0.10 sec
      Start 11: testkeepass2randomstream
11/25 Test #11: testkeepass2randomstream .........   Passed    0.04 sec
      Start 12: testmodified
12/25 Test #12: testmodified .....................   Passed    0.15 sec
      Start 13: testdeletedobjects
13/25 Test #13: testdeletedobjects ...............   Passed    0.15 sec
      Start 14: testkeepass1reader
14/25 Test #14: testkeepass1reader ...............   Passed    0.23 sec
      Start 15: testwildcardmatcher
15/25 Test #15: testwildcardmatcher ..............   Passed    0.03 sec
      Start 16: testautotype
16/25 Test #16: testautotype .....................   Passed    0.14 sec
      Start 17: testentry
17/25 Test #17: testentry ........................   Passed    0.12 sec
      Start 18: testcsvparser
18/25 Test #18: testcsvparser ....................***Failed    0.18 sec
      Start 19: testrandom
19/25 Test #19: testrandom .......................   Passed    0.03 sec
      Start 20: testentrysearcher
20/25 Test #20: testentrysearcher ................   Passed    0.08 sec
      Start 21: testexporter
21/25 Test #21: testexporter .....................   Passed    0.12 sec
      Start 22: testcsvexporter
22/25 Test #22: testcsvexporter ..................   Passed    0.10 sec
      Start 23: testykchallengeresponsekey
23/25 Test #23: testykchallengeresponsekey .......   Passed    0.08 sec
      Start 24: testgui
24/25 Test #24: testgui ..........................   Passed   14.61 sec
      Start 25: testguipixmaps
25/25 Test #25: testguipixmaps ...................   Passed    0.25 sec

96% tests passed, 1 tests failed out of 25

Total Test time (real) =  17.62 sec

The following tests FAILED:
         18 - testcsvparser (Failed)
Errors while running CTest
make: *** [Makefile:150: test] Error 8
```
- ✅ I haven't compiled and verified my code with `-DWITH_ASAN=ON`, because your build script report that this thing is only supported on Linux. I'm contributing this being on Windows at the moment. **[REQUIRED]**

### CODE REVIEW

**Comment by droidmonkey** [comment]
Please sign up for transifex account (you can link with GitHub) and submit any fixes to translations on there. I approved your contribution, thanks!

**Comment by vsvyatski** [comment]
@droidmonkey, I'm already on Transiflex, I just couldn't find a way to add new strings (only edit existing ones) until now. To be honest, their web interface is not user friendly enough.

**Comment by TheZ3ro** [comment]
The changes made to keepassx_en.ts and keepassx_ru.ts are "useless" here. 
The RU one should be updated on transifex, the EN one should be generated with the translation script.

Most of the time when releasing we forget to run the translation script and upload translations on transifex. We should do that often @droidmonkey @phoerious

**Comment by droidmonkey** [comment]
Its done with the release script and i did it for 2.1.4 release. Agree that changing any of the ts files is worthless.

**Comment by TheZ3ro** [comment]
This is not a Transifex flaw, this is a flaw in our branching model. 2.1.5 translation should be in develop as well

**Comment by vsvyatski** [comment]
Guys, did you actually update the original file on Transifex? The "Clear history" string is still not available there for translation. If I upload a new RU file there with that string added, the string is sort of ignored.

**Comment by TheZ3ro** [comment]
@vsvyatski The string will be available on Transifex only when 2.2.0 release is out, sadly.

**Pull request merged**
