### PR TITLE
SSH Agent: Split private key selection

### LINKED ISSUE #1200: SSH Agent: How to use/store private keys is not obvious
There is a high possibility of someone accidentally removing their only copy of their private key if they don't add it as an attachment but just browse to it instead thinking it's enough. This needs to be addressed.

## Expected Behavior

An early tester thought browsing for a private key also added/saved the key in their KeePassXC database.

## Current Behavior

The intended behaviour is that browsing a key means you are using it externally. The user is supposed to attach the key to the entry.

## Possible Solution

Change the UI to look more like KeeAgent (key selection part):

image

Their version has an explicit selection between them and I chose to make our version more compact which also had a negative side effect for UX.

Doing it like this also fixes the translation issues in the original PR (ping @phoerious).

Thoughts? What kind of UI would feel more natural in KeePassXC that will accomplish the same thing?

## Debug Info
KeePassXC - Version 2.2.2
Revision: ac73e25

Libraries:
- Qt 5.9.2
- libgcrypt 1.8.1

Operating system: Fedora 27 (Twenty Seven)
CPU architecture: x86_64
Kernel: linux 4.13.12-300.fc27.x86_64

Enabled extensions:
- KeePassHTTP
- Auto-Type
- YubiKey
- SSH Agent

### PR DESCRIPTION
**Pull request by hifi**
Fixes #1200. Includes only UI changes.

## Screenshots (if appropriate):
image

## Types of changes

- ✅ Bug fix (non-breaking change which fixes an issue))

## Checklist:

- ✅ I have read the **CONTRIBUTING** document. **[REQUIRED]**
- ✅ My code follows the code style of this project. **[REQUIRED]**
- ✅ All new and existing tests passed. **[REQUIRED]**

### CODE REVIEW

**Comment by hifi** [comment]
Personally I would prefer a single page layout if there's a good way to align it.

**Comment by hifi** [comment]
Made some changed based on discussion outside this PR:
- Fingerprint and comment are now selectable labels
- Fingerprint, comment and public key use monospace font

**Comment by phoerious** [comment]
Did you forget to push the monospace part?

**Comment by phoerious** [comment]
Hmm. It is in the XML file, but it doesn't work on Windows.

**Comment by hifi** [comment]
What would be the correct way to use monospace fonts? It's set as a family so I expected it to pick the default.

**Comment by droidmonkey** [comment]
Please read the QFont description, it is actually a very thorough process: http://doc.qt.io/qt-5/qfont.html

**Comment by hifi** [comment]
Fixed font on Windows with a tiny debatable refactor.

**Comment by droidmonkey** [comment]
Why a class to wrap one static function? We at least want to cache the result to speed up future use. QFont search is expensive. Recommend a lazy init approach.

**Comment by hifi** [comment]
@droidmonkey I couldn't find any reasonable class to stuff it into that would make sense and in the future we might want more standardized fonts.

**Comment by droidmonkey** [comment]
The class is perfectly fine and appropriate, but i don't recommend a static function without caching

**Comment by hifi** [comment]
Wouldn't that go into premature optimization to add caching when it's called only twice per KeePassXC instance at this point?

**Comment by droidmonkey** [comment]
Perhaps :stuck_out_tongue:

**Comment by phoerious** [comment]
Na, ship it.

**Comment by hifi** [comment]
Rebased.

**Comment by phoerious** [comment]
Travis trigger.

**Comment by phoerious** [comment]
Damn you, Travis!

**Pull request merged**
