### PR TITLE
Show what was modified between entry history items

### LINKED ISSUE #2621: Show overall history of changes for entries
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( Do not include screenshots of your actual database! )

## Expected Behavior
[NOTE]: # ( If you're describing a bug, tell us what should happen )
[NOTE]: # ( If you're suggesting a change/improvement, tell us how it should work )

Right now you can go into any individual entry and see the history of password changes.  

I would like to have a combined history.

### PR DESCRIPTION
**Pull request by shemeshg**
[NOTE]: # ( Describe your changes in detail, why is this change required? )
Allow user understand what has changed in the history view
[NOTE]: # ( Explain large or complex code modifications. )
Simple change,

[NOTE]: # ( If it fixes an open issue, please add "Fixes #XXX" )
Fixes #2621

## Screenshots
[TIP]:  # ( Do not include screenshots of your actual database! )
Screen Shot 2021-08-02 at 14 00 02

## Testing strategy
[NOTE]: # ( Please describe in detail how you tested your changes. )
Perform all types of changes, and preview each of them in the History View.
[TIP]:  # ( We expect new code to be covered by unit tests and documented with doc blocks! )

## Type of change
[NOTE]: # ( Please remove all lines which don't apply. )
- ✅ Bug fix (non-breaking change that fixes an issue)
- ✅ New feature (change that adds functionality)
- ✅ Refactor (significant modification to existing code)
Only, 
```
-    m_historyModel->setEntries(m_entry->historyItems());
+    m_historyModel->setEntries(m_entry->historyItems(), m_entry);
```

### CODE REVIEW

**Comment by droidmonkey** [comment]
Why show the notes? You have that as a change test already. I think showing the size of the history entry, number of attachments, and a calculated age (days, months, years depending on value)  would be nice fields to have.

**Comment by shemeshg** [comment]
> Why show the notes? You have that as a change test already. I think showing the size of the history entry, number of attachments, and a calculated age (days, months, years depending on value) would be nice fields to have.

All Corrected

**Comment by michaelk83** [comment]
The Size and Age columns are unclear. The column header should clarify what is being measured (size of what? age of what?), and either the header or rows should show units: Is the age in days? hours? weeks? Is the size in bytes? number of entries? something else?

Also it would be nice to see a diff between two history rows when selected - *how* was the data modified? (Or on a simpler level, at least show the old and new values next to each other.) But that's better left to a separate PR.

**Comment by droidmonkey** [comment]
Yah I tested this and it was not clear to me what a lot of the info meant. This needs a polish.

**Comment by droidmonkey** [comment]
Major overhaul! This is now ready for prime time. @michaelk83 @phoerious @hifi 

image

**Comment by droidmonkey** [comment]
Kind of funny that the gui tests pass 🤣  I didn't touch them and made major changes to the way history works under the hood. Might need to address that some day.

**Comment by michaelk83** [comment]
Looks good. I can see from the code that "Size" is how much the entry takes up in the DB. It's still not entirely clear to me from the UI alone, but I can't think of any other interpretations, so I guess it's good enough.

The date and age don't add up in the first two rows. Different age, but same timestamp. Was the timestamp not updated (a bug)?

Also, rounding down 10 days to 1 week seems like a bit much. Maybe change the cut-off for "X weeks" to 2 and up?

**Comment by droidmonkey** [comment]
Current is meant to indicate (along with the bold) that it is the current version of the entry. To make the differences column make any sense it was necessary to show the current entry as a "history item" so you can see the true lineage. This also means the last line item will always contain no differences since it is the base item. 

Size is consistent with the main entry view.

**Comment by michaelk83** [comment]
I don't have a problem with the "Current", but the 5 min old time is the same as the current one. That doesn't make sense. I'd expect to see that 5 min difference in the timestamp too.

Hmm, are you saying the "Current" version is also 5 min old? How about "5 minute(s) (Current)"?

**Comment by droidmonkey** [comment]
Yes they are both 5 min old. I wanted to keep it short because anything longer tends to get cut off. The age column is just a relative human readable version of the modified time. It isn't meant to be gospel. Gospel is the modified time column.

**Comment by michaelk83** [comment]
Understandable. It's just confusing this way. I would just drop the "Current" label and stick to ages + bold. You can re-add the "Current" as a tooltip.

Btw, with the "Current" label as is, does sorting by the `Age` column still work as expected?

**Comment by droidmonkey** [comment]
Yes sorting still works, sorting is based on the actual seconds from today value. I don't think it is confusing, will wait for other feedback. It distinguishes it from the other, actual, history items along with the bold.

**Comment by michaelk83** [comment]
The confusing part for me was not clearly seeing the age of the current version. But I guess that's because I don't know when that screenshot was taken, so can't tell the age from the timestamp (without some mental juggling based on the older versions).

**Comment by droidmonkey** [comment]
I can support "Current (x days)"

**Comment by droidmonkey** [comment]
Made the tweak mentioned above and also used rounding in the human readable time difference for weeks and months. 1.5 weeks -> 2 weeks. That should give a better feel for the near term timeframes.

image

Keep in mind the (s) at the end will end up being replaced with the singular and plural forms once translated.

**Review by droidmonkey — APPROVED** [review]

**Pull request merged**
