### PR TITLE
Fix missing qtbase translations

### LINKED ISSUE #1093: Standard "OK"/"Cancel"/"Apply" button text without translation
In many window appear the standard button

OK
Apply
Cancel

in English without translation.
Please add it to the language file or use the standard QT resource to translate them.

### PR DESCRIPTION
**Pull request by phoerious**
## Description

This is a work-in-progress PR which resolves #1093.

With this patch, we bundle qtbase translations with KeePassXC builds. For this I refactored the Translator class and added the needed CMake install commands for Windows, macOS and Linux (AppImage only, PPA and other builds should use the system's qt5-translations package).

## Motivation and context

KeePassXC didn't bundle qtbase translations, so standard buttons were left untranslated when qtbase translations didn't exist on the user's system at the same location as on the distributor's system (on Windows, even a different Msys2 install location was apparently enough to break translations).

## How has this been tested?

Windows portable ZIP and installer ship qtbase_*.qm translations files now. I tested that those are loaded correctly by temporarily renaming my /mingw64/usr/share/qt5/translations folder.
macOS DMGs and Linux AppImages ship and successfully load qtbase translations as well.

## Types of changes

- ✅ Bug fix (non-breaking change which fixes an issue)

## Checklist:

- ✅ I have read the **CONTRIBUTING** document. **[REQUIRED]**
- ✅ My code follows the code style of this project. **[REQUIRED]**
- ✅ All new and existing tests passed. **[REQUIRED]**
- ✅ I have compiled and verified my code with `-DWITH_ASAN=ON`. **[REQUIRED]**

### CODE REVIEW

**Comment by phoerious** [comment]
@droidmonkey I added the remaining install commands and further fixes to make this work with macOS and Linux AppImages. Please test if we need to bundle qtbase translations for Snaps as well. If not, please merge.

The only system on which this still isn't working is Arch Linux. Although all needed qtbase_* translations are there, the path is detected correctly and QTranslator says the translations were loaded, the buttons are still untranslated. Other Linux systems (including our Trusty AppImage build system) don't show this behavior.

**Comment by yan12125** [comment]
Thanks for this patch! Here are some new testing results on Arch Linux. After installing the ```qt5-translations``` package,

* "Cancel" is correctly translated into キャンセル if I use Japanese (ja)
* "Cancel" is not translated if I use Chinese (Taiwan) (zh_TW)

For the second case, I can see keepassxc tries to load /usr/share/qt/translations/qtbase_zh_TW.qm, while there's no such file. This is an upstream issue - there's [no qtbase_zh_TW.ts for Qt](https://github.com/qt/qttranslations/tree/5.10/translations).

I build keepassxc with [a custom PKGBUILD](https://github.com/yan12125/aur/blob/master/keepassxc-yan12125-git/PKGBUILD)

**Comment by phoerious** [comment]
I tried it with qtbase_de.qm and that file definitely exists.

**Comment by yan12125** [comment]
Germany work fine for my build:
translations
(this is a corner of the unlock screen)

Maybe something wrong in your build scripts?

**Comment by phoerious** [comment]
No. It works on all other systems, just not on my Arch.

**Pull request merged**
