### PR TITLE
Image File Compression

### PR DESCRIPTION
**Pull request by Peppernrino**
## Description
Ran a series of lossless compression algorithms to make the images smaller. Total reduction of 425,386 bytes.

## Motivation and context
I like compression. I am going around making my favourite programs smaller. :)

## How has this been tested?
They are just image files. Everything should work the same if not better.

## Checklist:
- ✅ I have read the **CONTRIBUTING** document. **[REQUIRED]**
- ✅ My code follows the code style of this project. **[REQUIRED]**

### CODE REVIEW

**Comment by droidmonkey** [comment]
425KB? I don't think you did much of anything. That's 2KB per file modified

**Comment by phoerious** [comment]
Yes, please show us your procedure. We cannot just accept a bunch of modified binaries.

**Comment by phoerious** [comment]
425 isn't much of an improvement...

**Comment by Peppernrino** [comment]
It's something. :D

**Comment by droidmonkey** [comment]
Closing this because we are replacing the icons anyway.

**Pull request closed without merging**
