### PR TITLE
Overhaul action states and add icons to toolbar

### LINKED ISSUE #10981: Going to application settings and back to entry view disables several context menu items
## Overview
I don't want the TOTP not being visible to anybody just looking on my screen. But when I disable the TOTP in the Preview the 
TOTP and Copy Attribute elements in the context menu are grayed out.

## Steps to Reproduce
1. Add TOTP to one entry
2. Open Settings - Security
3. Select "Hide TOTP in the entry preview panel"
4. Save the settings
5. Right click on your Entry which has a TOTP
6. Check status of TOTP and Copy Attribute

## Expected Behavior
Should behave the same way as when the setting was not active. Both context menu entries should work.

## Actual Behavior
Both context manu entries are disabled

## Context

KeePassXC - Version 2.7.8
Revision: f6757d3
Distribution: Snap

Qt 5.15.11
Debugging mode is disabled.

Operating system: Ubuntu Core 22
CPU architecture: x86_64
Kernel: linux 6.8.0-35-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- Passkeys
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 2.19.1

Operating System: Linux - Ubuntu
Desktop Env: Gnome
Windowing System: Wayland

### PR DESCRIPTION
**Pull request by droidmonkey**
* Fixes #10981

[NOTE]: # ( Describe your changes in detail, why is this change required? )
[NOTE]: # ( Explain large or complex code modifications. )
[NOTE]: # ( If it fixes an open issue, please add "Fixes #XXX" )

## Screenshots
[TIP]:  # ( Do not include screenshots of your actual database! )
image

## Testing strategy
[NOTE]: # ( Please describe in detail how you tested your changes. )
[TIP]:  # ( We expect new code to be covered by unit tests and documented with doc blocks! )
Added unit tests and tested extensively manually

## Type of change
[NOTE]: # ( Please remove all lines which don't apply. )
- ✅ Bug fix (non-breaking change that fixes an issue)
- ✅ New feature (change that adds functionality)

### CODE REVIEW

**Comment by varjolintu** [comment]
Something I noticed while debugging:
https://github.com/keepassxreboot/keepassxc/blob/develop/src/gui/EntryPreviewWidget.cpp#L544 This is constantly updated even if the config setting has disabled showing the TOTP in the Preview Panel.

EDIT: Maybe the whole Preview Panel shouldn't get updated if it's not even visible.

**Comment by michaelk83** [comment]
Consider grouping the new Database Settings toolbar icon into the existing Settings icon, with a dropdown. And in that case, you can remove the separator between the Passkeys and Password Generator, since these icons can be considered as just four tools: passkeys, reports, generator, settings.

**Comment by droidmonkey** [comment]
@phoerious this is ready for review

**Review by varjolintu — APPROVED** [review]
At first I was wondering why returning Application Settings or Password Generator activates the previous state (Database Reports / Database Settings / main view), but these are different states in the main view vs. different widgets. So after all it's just logical and works as expected.

**Comment by droidmonkey** [comment]
Yah that is confusing when you only have one database open since everything looks the same, but when you have more than one open the tabs disappear when in the password generator and application settings.

**Pull request merged**
