### PR TITLE
Add display number of characters in passphrases

### LINKED ISSUE #5396: [FR] Display number of characters in generated passphrases
## Summary

~When generating passphrases, it would be nice to have a maximum characters field. This is useful for websites / applications that have an upper limit on how many characters a user's password can be.~

When generating passphrases, it is useful to know how many characters long the passphrase is. Currently this involves using an external tool and regenerating passphrases until an appropriate length is achieved.

It would be nice to have a field that shows how many characters long the passphrase is, similar to the existing entropy field.

## UI Mock-up

Here is a tiny UI mockup. Sorry it looks bad, I used a very simple editor.

~[old mockup](https://user-images.githubusercontent.com/43632885/92334834-6587d880-f046-11ea-9ce3-8a657af26545.png)~

## Notes

See discussion below, this FR was originally for a maximum characters field, but now is for a display of how many characters are in the currently generated passphrase.

~Maximum characters isn't "exactly this many characters". This allows the implementation to be less complex and less costly to run. The purpose is to ensure to generated passphrase will be valid for a given field, and not maximizing the amount of characters used.~

This may overlap with some of the features in issue #4209 . I was worried about overloading that FR with more requests / scope creep, so I filed this separate issue.

### PR DESCRIPTION
**Pull request by Colfenor**
Fixes #5396 

A new information field is added to the passphrase generator view
and depicts the number of characters in the generated passphrase. 

Considering the UI-Implementation I'd be happy to hear improvement suggestions
since I'm still a Qt novice.

In the current implementation a character is only counted if it is a number or letter.

So e.g. whitespace or special characters like '&' are not counted. (see attached screenshot)
If this is not the desired behaviour, I'll change it according to the discussion.

## Type of change
- ✅ New feature (change that adds functionality)

### CODE REVIEW

**Comment by droidmonkey** [comment]
Why not just pull the length of the text edit field?

**Comment by Colfenor** [comment]
alright, so whitespaces, and special characters should be counted aswell ?

**Comment by droidmonkey** [comment]
Yes absolutely that's part of the length

**Comment by Colfenor** [comment]
> Yes absolutely that's part of the length. Or just use `password.length()`

Ok thanks for the clarification ! I had `password.size()` originally in my first commit, however I somehow thought that whitespace or seperator characters are not needed in the passphrase length.

I changed it now, however on first opening of the password generator widget window, there is an UI bug now where the new QLabel appears to be way off its original position.

**Comment by droidmonkey** [comment]
I fixed your layout problem

**Review by droidmonkey — APPROVED** [review]

**Pull request merged**
