### PR TITLE
Add "Lock selected database" action on toolbar

### LINKED ISSUE #6445: Please add feature to selectively lock a single database
## Summary
Please add a feature to allow locking of a **single** database only, when having multiple databases open

## Examples
There is a "Lock databases" entry in "Tools" menu that locks all databases. Please also add a "Lock this database"  entry below "Database" Menu

## Context
I use multiple databases in parallel. In this case. e.g. a "Work" and a "Private" Database. On my Work laptop, I want the Work-Database to be open always as long as I use it. But I just sometime need the Private database. When I need it, I unlock it, grab the needed password - and then want to lock that database again, while keeping the Work database open.

currently I only have two possibilities, that both have downsides:
- Lock databases --> Also my work database gets locked
- Close Private database --> Need to re-open the database from the "recent" menu. Works, but is not as nice.

Thanks for considering!

### PR DESCRIPTION
**Pull request by yamabiiko**
This feature allows locking a single database using an icon in the toolbar.
Also the "Lock databases" icon is changed to make it more clear that its going to lock all databases.
Closes #6445 
The main reason behind this change is allowing to lock a single database when having multiple databases open (without closing it), as described in the issue above.

I wanted to update the translations (change the "Lock databases" string into "Lock all databases" to make the description less confusing and add the "Lock selected databases" string for translations) but I am not quite sure how to do it (the update script seems to fail).

## Testing strategy
This is basically an UI change (existing code was used) so it should be already covered by tests.

## Type of change
- ✅ New feature (change that adds functionality)
- ✅ Refactor (significant modification to existing code)

### CODE REVIEW

**Comment by droidmonkey** [comment]
Nice, good icon too

**Comment by michaelk83** [comment]
I'd place the "lock all" button next to the "lock current" button, or maybe as a dropdown option. So main button would lock the current DB, and dropdown &rarr; Lock All would lock everything.
```
[🔒|▾]
[Lock All]
```

**Comment by droidmonkey** [comment]
Hmmmmm that is not a bad idea. I do like consolidating it into a drop down. But is the default action lock all or lock current?

**Comment by yamabiiko** [comment]
I am not quite sure if it's worth changing the toolbar to add a drop down just for that (why should add entry, delete entry, change entry separate then?), also the "lock all" position is to keep it consistent with the [interface overview](https://keepassxc.org/docs/KeePassXC_UserGuide.html#_interface_overview), but if we decide to change it I'm ok with it

**Comment by michaelk83** [comment]
> why should add entry, delete entry, change entry separate then?

Add/edit/delete are completely different actions, even if related. Lock current and lock all are both lock actions.

> the "lock all" position is to keep it consistent with the [interface overview](https://keepassxc.org/docs/KeePassXC_UserGuide.html#_interface_overview)

Then the question is what makes more sense: group the "current DB actions" (open/save/lock), or group the "lock actions" (lock current/lock all). My non-dropdown idea was to group *all* of them on the left: [Open][Save][Lock Current][Lock All]. I admit the Toolbar section in the User Guide will need to be updated, but it will need to be updated anyway.

If we go with the drop-down, I'd argue for lock current to be the default:
- Most users will only have one DB open. For them, both actions are the same. It's still a single click in the most common case. (Maybe even hide the drop-down when there's only one DB open.)
- Those who work with multiple DBs are the ones who want the "lock current" option. I expect for them, "lock current" would be more common: you unlock one at a time, and you lock one at time (often LIFO style, probably). If "lock current" is the default, that makes the (presumably) common use always a single click. If you make "lock all" the default, then "lock current" can't be done with less than two clicks.
- If locking the current DB also closes the tab (or at least switches to the next unlocked one), that provides a clear visual indication that not everything is locked yet, and then locking everything is just a matter of repeatedly clicking the button a few times.
- The dropdown provides a shorthand to lock everything with at most two clicks, but that's only shorter if you have more than 2 DBs open. That's probably rare even among multi-DB users.
- As a fallback, keyboard shortcuts are the same "length" for both actions.
- Aesthetically, the lock current icon is more generic.

Anyway, the final decision is up to @droidmonkey .

**Comment by droidmonkey** [comment]
We have a drop down choice for the Auto-Type button, which I just noticed you are missing in your toolbar. This might be because you are either running Wayland or didn't build the autotype plugin. A drop down button is rather trivial to setup, you can use the Auto-Type one in code as reference.

**Comment by yamabiiko** [comment]
I have started working on the dropdown change and the issue I've encountered is that if the current database is already locked the button is disabled resulting in the dropdown menu being disabled too. As far as I know, this behaviour can't be changed without an override to the QToolButton class. So the possible solutions are:

- override QToolButton's mouseEventFilter  in a custom class like DatabaseLockToolButton 
- place both icons without a dropdown (one next to each other)
- use as a default action for the icon's dropdown "Lock all" (so the action is not disabled if our current tab is on a locked db)

**Comment by michaelk83** [comment]
The other icons aren't disabled when the DB is locked, so it probably has something to do with how the button is connected. So another option is disconnect it when the DB is locked, and reconnect when unlocked (or when switching tabs). Or just replace it with the lock-all button when the current DB is locked.

But the solution I would prefer is don't show tabs of locked DBs. When the current DB is locked, close its tab. That way, the UI immediately switches to the next unlocked tab, which gives a visual indication that there are still unlocked DBs, and allows to quickly and conveniently close the next DB by the clicking the same button again (without even moving the mouse).

The question is, would this affect how multiple DBs are *un*locked? If you had 2-3 DBs open, and you lock-all, and close KPXC then launch it again, do you get 2-3 tabs of locked DBs? If you had 10 or 15 DBs that you worked with recently (even not open at the same time), would you get 10-15 tabs when you launch KPXC?

**Comment by michaelk83** [comment]
> But the solution I would prefer is don't show tabs of locked DBs. When the current DB is locked, close its tab.
> ...
> The question is, would this affect how multiple DBs are unlocked?

Hmm, yes, this conflicts with #5427. @droidmonkey , thoughts? Maybe close the tabs in the main UI in this PR, but still keep the last few recents in the unlock widget in #5427?

I'd rather not change the default to "lock all", at least, for the reasons I [listed earlier](https://github.com/keepassxreboot/keepassxc/pull/6652#issuecomment-864377596).

Another option: leave the button (and drop-down) disabled if the current tab is locked, but switch to the next unlocked tab when locking.

**Comment by droidmonkey** [comment]
Locking databases does NOT close them. This behavior definitely shouldn't change.

**Comment by michaelk83** [comment]
Ok. Then I vote for this:
> Another option: leave the button (and drop-down) disabled if the current tab is locked, but switch to the next unlocked tab when locking.

Once the tab is switched, the button should be automatically re-enabled, and drop-down will be accessible. Normally you'd only switch back to a locked tab to unlock it. Other than that, you keep working with the unlocked tabs, where the button is enabled.

**Comment by yamabiiko** [comment]
I have changed the code to automatically switch to an open tab when a database is locked (if available). I also have updated the menu, moved the action "Lock Databases" from "Tools" (as it did not seem appropriate) to "Database) and added the lock single database action to the menu.
I also have changed the current shortcut "CTRL+L" and assigned it to single database lock instead of lock all (which I changed to CTRL+SHIFT+L). This can be reverted but it seems more proper that way to me.  






https://user-images.githubusercontent.com/30393429/124309600-7b790380-db5a-11eb-8d15-18b6455853fb.mp4

**Comment by michaelk83** [comment]
Looks nice. Just maybe change "Lock Databases" to "Lock All Databases", to contrast it more with "Lock selected database". When you hover over the main button, does it show "Lock selected database" in a tooltip? Also, the capitalization is inconsistent. Looking at the rest of the menu, this should be "Lock Selected Database".

**Comment by yamabiiko** [comment]
I have changed the strings as suggested

**Comment by michaelk83** [comment]
LGTM. The rest is up to @droidmonkey .

**Comment by chronically-late** [comment]
I've been testing this for over a week now without a problem. The option of locking just a single DB is something I've always missed in KeepassXC, so THANK YOU for the work.

**Review by droidmonkey — APPROVED** [review]

**Comment by droidmonkey** [comment]
This works great, ready for merge.

**Pull request merged**
