### PR TITLE
Fix URL matching with Browser Integration

### LINKED ISSUE #3751: Reject junk URLs for browser integration instead of matching everything
I just got a wrong URL match using the KeepassXC browser extension.

# Current behaviour

URL in question: `https://sso.tu-darmstadt.de/login`
URLs of matched entries: `http://https//aur.archlinux.org https://archlinux.org`, `https://passport.twitch.tv https://www.twitch.tv/` `https://sso.tu-darmstadt.de/login […] https://print.informatik.tu-darmstadt.de/user`

Among the correct entry, there are two false positives. If I allow the correct entry, it is filled in and I can log in. If I click on one of the false positives, it does not fill in and "Error: No logins found" pops up. If I check "Return only best-matching credentials", there still are the false positives, but the correct entry doesn't show up anymore.

# Expected behaviour

There are no false positives, only one suggestion. I think it is reasonable to expect that an url must match at least the first and second domain level `example.com` exactly to be sent over.

## Steps to Reproduce (for bugs)
I cannot reproduce this deterministically yet (you can try creating entries with the urls above), but this is not the first time this happens. When it happens, it is always with the same two false positives.

## Debug info

KeePassXC - 2.5.0
KeePassXC-Browser - 1.5.3
Operating system: Arch Linux
Browser: Chromium 78.0.3904.70

### PR DESCRIPTION
**Pull request by varjolintu**
[TIP]:  # ( Provide a general summary of your changes in the title above ^^ )

## Type of change
[NOTE]: # ( Please remove all lines which don't apply. )
- ✅ Bug fix (non-breaking change which fixes an issue)

## Description and Context
[NOTE]: # ( Describe your changes in detail, why is this change required? )
[NOTE]: # ( Describe the context of your change. Explain large code modifications. )
[NOTE]: # ( If it fixes an open issue, please add "Fixes #XXX" as necessary )
Ignores junk URL's, and fixes port matching. Also renames some functions and variables.

If scheme matching is enabled, entry URL's without a scheme will fallback to `https`.

Fixes #3751.

## Testing strategy
[NOTE]: # ( Please describe in detail how you tested your changes. )
[TIP]:  # ( We expect new code to be covered by unit tests and documented with doc blocks! )
Manually. Previously an entry with URL `https:///example.com` was requested for all sites. Also, tests are included.

## Checklist:
[NOTE]: # ( Please go over all the following points. )
[NOTE]: # ( Again, remove any lines which don't apply. )
[NOTE]: # ( Pull Requests that don't fulfill all [REQUIRED] requisites are likely )
[NOTE]: # ( to be sent back to you for correction or will be rejected.  )
- ✅ I have read the **CONTRIBUTING** document. **[REQUIRED]**
- ✅ My code follows the code style of this project. **[REQUIRED]**
- ✅ All new and existing tests passed. **[REQUIRED]**
- ✅ I have compiled and verified my code with `-DWITH_ASAN=ON`. **[REQUIRED]**
- ✅ I have added tests to cover my changes.

### CODE REVIEW

**Comment by droidmonkey** [comment]
Should we alert the user some how that there is an invalid url entered? Perhaps a simple label that pops up or using the red x icon in the url field similar to when passwords are mismatched. We would have to exclude cmd:// style URLs from that  check though.

**Comment by varjolintu** [comment]
@droidmonkey I agree. Some kind of warning is needed in the GUI also.

**Comment by droidmonkey** [comment]
Something like "the entered URL will not work with the browser extension because {reason}"

**Comment by Talv** [comment]
Will this PR also fix handling of URLs with trailing space (`\x20`)? (And possibly other white-space characters).

Example: entry with an URL like `https://www.kickstarter.com ` will be proposed on *every domain* by browser extension (since v2.5.0).

Further observations:
* Removing space fixes the issue (`https://www.kickstarter.com` behaves fine)
* Appending `/` before the space fixes the issue as well (`https://www.kickstarter.com/ ` behaves fine)

**Comment by varjolintu** [comment]
@Talv It fixes those too. Just tested it.

**Comment by varjolintu** [comment]
This PR has still some issues. Trying to fix them and add the GUI warning. Then we are good to go.

**Comment by varjolintu** [comment]
Problems with the matching are fixed. I'll do the UI stuff next.

**Comment by varjolintu** [comment]
Added the UI warning. This is good to go!

**Comment by droidmonkey** [comment]
This isn't ready for prime time. It's marking perfectly valid URL's as invalid. It also doesn't mark invalid URL's in the new browser settings page.

image

image

image

**Comment by droidmonkey** [comment]
I am going to withhold this until 2.5.2

**Comment by droidmonkey** [comment]
@varjolintu can you separate the fixes for the URL Parsing from the UI error checking code?

**Comment by varjolintu** [comment]
@droidmonkey Sure, I can separate the UI fixes for now.

**Comment by varjolintu** [comment]
@droidmonkey One more thing. Should URL's without a scheme match every time with all scheme's in the page URL? Or just when the scheme matching is disabled?

**Comment by droidmonkey** [comment]
Yah if there is no scheme we assume https

**Comment by varjolintu** [comment]
Pushed and rebased.

**Comment by varjolintu** [comment]
@phoerious We are merging this with 2.5.1, but the UI stuff will be another PR for 2.5.2. That's why I changed the milestone.

**Comment by phoerious** [comment]
ok.

**Comment by a-v-popov** [comment]
It seems that with the "fix" only first level domain is considered.
I.e. if you there are a.foo.com and b.foo.com in the db, and you try to open c.foo.com the two records will match (none of them probably should).

**Comment by varjolintu** [comment]
@a-v-popov Yes, that's what the next PR will fix.

**Pull request merged**
