### PR TITLE
restore WITH_XC_TOUCHID configure option

### PR DESCRIPTION
**Pull request by tenzap**
And set it by default to ON.

Setting it to OFF permits to be able to compile on macOS versions that don't support TouchID and related APIs (Otherwise compilation would crash for missing methods.)

This cmake option was removed with the "windows hello / Quick Unlock" commit

Used methods for touchID on macOS require macOS >= 12.0.1 (and may require 13.0 in future see https://github.com/keepassxreboot/keepassxc/issues/2484)

Replaces #7648 

## Screenshots
[TIP]:  # ( Do not include screenshots of your actual database! )

## Testing strategy
Tested on macos 10.11.6 (compiled through macports).
Will soon be built on macports builders on macos 10.7-12

## Type of change

- ✅ Bug fix (non-breaking change that fixes an issue)

### CODE REVIEW

**Comment by droidmonkey** [comment]
I have no desire for this change. Prefer the code blackouts or a stub interface.

**Comment by tenzap** [comment]
What do you mean by 'code blackouts or a stub interface'

**Comment by droidmonkey** [comment]
You opened this one and if it's not enough do more. https://github.com/keepassxreboot/keepassxc/pull/7648

I do not want to put the feature flag back in. 

You really should just be returning that the feature is unavailable from TouchID and block out the code that is unavailable in earlier versions. In the dependencies, use CMAKE_SYSTEM_VERSION to block out the ones unsupported by prior macos.

**Comment by tenzap** [comment]
> You opened this one and if it's not enough do more. https://github.com/keepassxreboot/keepassxc/pull/7648

Ok, some more is needed indeed. I wasn't sure which one you would prefer.

**Comment by droidmonkey** [comment]
I'll be quite honest I'd rather this be handled in a fork to our project or via pre build patches.  We aren't in the business of constantly messing with our code base to satisfy a very very small population of users on outdated operating systems.

**Comment by tenzap** [comment]
Actually, I'm not sure it will be possible to do the changes with only updating the code in TouchID.mm because it uses the
`-framework LocalAuthentication` which is only available from macOS 10.10. I guess that linking towards it from cmake without having it installed will fail.

If you accept #7648 it is enough to have support down to 10.11 which is probably sufficient (in macports stats, there are users down to 10.11 but not below).

The main issue is that some macs can't install a newer version than 10.11. Not sure if there are still users for version below, but 10.11 is sort of a barrier.

**Pull request closed without merging**
