### PR TITLE
Improve UI of the search edit (resurrecting 5c7c7f54) 

### PR DESCRIPTION
**Pull request by TheZ3ro**
Just a fix to #131, originally by @knu 

## Description

This improves the UI of the search edit.

It was originally submitted as https://github.com/keepassx/keepassx/pull/74 and successfully merged, but the functionality got lost as the search UI was revamped in KeePassXC.

## Motivation and Context

I want the Search UI to work without bothering with the focus.

- The copy action (Control+C) when no text is selected copies the password of the current entry.  This should be reasonable when Control+B copies the username.

- Down at EOL moves the focus to the entry view.  Enter and Tab should do that, but it would be handy for user to be able to get to the third entry by hitting Down three times.

## How Has This Been Tested?

Test case is included in this PR.

## Types of changes

- :negative_squared_cross_mark: Bug fix (non-breaking change which fixes an issue)
- :white_check_mark: New feature (non-breaking change which adds functionality)
- :negative_squared_cross_mark: Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- :white_check_mark: I have read the **CONTRIBUTING** document. [REQUIRED]
- :white_check_mark: My code follows the code style of this project. [REQUIRED]
- :white_check_mark: All new and existing tests passed. [REQUIRED]
- :negative_squared_cross_mark: My change requires a change to the documentation.
- :negative_squared_cross_mark: I have updated the documentation accordingly.
- :white_check_mark: I have added tests to cover my changes.

### CODE REVIEW

**Comment by droidmonkey** [comment]
I cleaned up the code like I mentioned in the previous PR (#131).

Interesting enough the GUI tests fail on Windows 10 in various spots when it tries to detect the "saved state" of the database by comparing the name in the titlebar. It also fails to autoreload the database properly.

**Comment by TheZ3ro** [comment]
Yeah for me too some tests on windows10 fail but it's not due to this PR (they fails also in the develop branch).

We must open a new issue for that

**Comment by TheZ3ro** [comment]
Ping @droidmonkey

**Comment by knu** [comment]
Great, thanks for fixing everything!

**Pull request merged**
