### PR TITLE
Add Windows Hello Integration

### LINKED ISSUE #2462: Feature Request: Windows Hello support
On my Android I use Keepass2Android with support for fingerprint database unlocking.
I would like to request this same functionality on Windows PC's with Hello support.
Windows Hello is a bio metric safety feature used to unlock Windows using for instance a fingerprint or facial recognition.

It would be great to be able to unlock my Keepass with a swipe of my fingerprint sensor, without having to type in a password or anything of the sorts.
Could also be used as an MFA feature, where Windows Hello authentication is required in addition to other authentication methods

### PR DESCRIPTION
**Pull request by HexF**
[NOTE]: # ( Describe your changes in detail, why is this change required? )
[NOTE]: # ( Explain large or complex code modifications. )
[NOTE]: # ( If it fixes an open issue, please add "Fixes #XXX" )

This PR adds integration for Windows Hello.
Most the code is pretty self explanatory, essentially boiling down to mostly a copy/paste of the TouchID code, but instead of calling macOS APIs, calling Windows APIs.
Windows Hello has been a requested feature in the PRs linked below as it provides a faster method to unlock your database

Fixes #2462, #3337 and contributes towards #488

## Screenshots
[TIP]:  # ( Do not include screenshots of your actual database! )
image

## Testing strategy
[NOTE]: # ( Please describe in detail how you tested your changes. )
[TIP]:  # ( We expect new code to be covered by unit tests and documented with doc blocks! )

No unit tests were added, as its basically just a handful of calls to the Windows API which would need to be stubbed (please correct me if I'm wrong)

Manual testing was carried out as follows:
1. Create new database
2. Lock database and enter password, ensuring that Windows Hello is checked.
3. Lock database again, clicking OK with no password.
4. Observe a "Windows Security" popup open, requesting the user authenticate to their computer (either through PIN or Finger Print)
5. Presenting a PIN or finger to a sensor should close the dialog and unlock the database

## Type of change
[NOTE]: # ( Please remove all lines which don't apply. )
- ✅ New feature (change that adds functionality)

### CODE REVIEW

**Comment by HexF** [comment]
Most the code here is copy/paste from the TouchID integration, so I wonder if it would be a better idea to abstract the whole Quick Unlock system so that other systems could be added more easily, e.g. Linux PAM (#6055)

**Comment by droidmonkey** [comment]
I have already implemented this using the WinRT APIs. I also cleaned up the entire process of using quick unlock (touchid or winhello). Unfortunately you are late to the party.

**Comment by HexF** [comment]
> I have already implemented this using the WinRT APIs. I also cleaned up the entire process of using quick unlock (touchid or winhello). Unfortunately you are late to the party.

Am I missing this somewhere in the code, or is it uncommited?

**Comment by droidmonkey** [comment]
I am pushing it this weekend, but the original discussion was in #6029

**Comment by droidmonkey** [comment]
Here is my implementation: https://github.com/keepassxreboot/keepassxc/pull/7384

You are welcome to work on the common proxy interface though! We would love that contribution. We also want to implement a pin-based Quick Unlock option when Windows Hello or Touch ID are unavailable.

**Comment by michaelk83** [comment]
> You are welcome to work on the common proxy interface though! We would love that contribution. We also want to implement a pin-based Quick Unlock option when Windows Hello or Touch ID are unavailable.

@HexF , if you want to work on the common interface, you may want to take a look at the discussion in #3337 , starting from [here](https://github.com/keepassxreboot/keepassxc/issues/3337#issuecomment-854550917). But keep in mind that that was based on the previous implemantation in #6029 , and may need some adjustments for the new code in #7384 . The bottom line is simply to extract the equivalent methods from TouchID and WinHello into a common interface, so that it can be reused for Linux fingerprint support and non-biometric QuickUnlock.

**Comment by droidmonkey** [comment]
I would call it QuickUnlockProvider

**Comment by droidmonkey** [comment]
After running into a nasty "bug" with the winrtcpp library that doesn't put the Windows Hello dialog above the main window.... I may end up putting your implementation into my PR. I'll credit you of course.

**Comment by HexF** [comment]
The main thing you have to do there to fix it is set the window handle correctly, but I think WinRT hides all that from you. 
It should also be noted that I dont encrypt the master password with AES like TouchID and your implementation.

I'll be taking a crack at QuickUnlockProviders and see what I can do

**Comment by smlu** [comment]
Note, setting the key handle doesn't always fix the issue with WindowsHello popping up behind current app.
I've been testing #6029 for a year now and I see random WindowHello dialog showing in front and behind the app.
#6029 uses `effectiveWinId` for window handle, I had tested also with `winId` and had similar results.

**Comment by droidmonkey** [comment]
I made a note on the issue with cppwinrt repo: https://github.com/microsoft/cppwinrt/issues/999#issuecomment-1030900415

**Pull request closed without merging**
