### PR TITLE
Add favicon fetch button next to entry's url edit textbox

### LINKED ISSUE #936: Add favicon download button next to URL field in entry edit
## Expected Behavior
When adding a new entry, have a checkbox underneath the URL to "Download Favicon". KeePassXC would remember whether or not this box was checked for future entries. If this checkbox is checked, the Favicon would automatically be downloaded when the new entry is added.

## Current Behavior
When created a new entry, if you want to download the Favicon you need to first enter the URL. Then click Icon, and then click 'Download Favicon'.

## Context
If someone wants to use favicons for their entries, chances are they will want to do it every time they want to add a new entry. No reason for extra steps to do this.
I see there is a similar feature request to have an item in the Tools menu to download all Favicons, so this feature request is slightly different.

### PR DESCRIPTION
**Pull request by kneitinger**
## Description

When WITH_XC_NETWORKING is defined, create a QToolButton beside
the Edit Entry -> Entry -> URL which when pressed, acts as though the
Edit Entry -> Icon -> Download Favicon button is pressed.  This button
is disabled (grayed-out) when the URL text is empty, and enabled when
the text is present. This PR also removes the `UrlFetchProgessDialog` class
in favor of a "Custom icon successfully download" message (if triggered from
the edit entry tab).

## Motivation and context

Fixes #936

## How has this been tested?

- Compile with `-DWITH_XC_NETWORKING=OFF`
  - Start to create new entry "Favicon Fetch Entry", verify no button present next to url box 
  
  - Enter URL in text box, verify still no button
- Compile with `-DWITH_XC_ALL=ON`
  - Start to create new entry "Favicon Fetch Entry (Networking Enabled)", verify icon button is present, yet disabled 
2018-11-18_19-25-36_no-url
  - Enter text in the URL box and verify the button becomes clickable 
2018-11-18_19-26-30_with-url
  - Click button.  ~Verify progress dialogs appear and no error is present.~ _(removed in this PR)_. Verify "Custom icon successfully downloaded" message appears.
msg
  - Go to Icon tab and verify presence of correct favicon 

  - Return to main entry edit tab and click button again, verify that "Custom icon already exist" info message appears 
already
  - Change URL to nonexistent URL and attempt to fetch icon for it.  Verify "Unable to fetch favicon" error message appears, and last correct favicon still set.

  - Save entry and verify that it has new icon in database widget 

- Run existing tests both with and without networking.

## Types of changes

- ✅ New feature (non-breaking change which adds functionality)

## Checklist:

- ✅ I have read the **CONTRIBUTING** document. **[REQUIRED]**
- ✅ My code follows the code style of this project. **[REQUIRED]**
- ✅ All new and existing tests passed. **[REQUIRED]**
- ✅ I have compiled and verified my code with `-DWITH_ASAN=ON`. **[REQUIRED]**

### CODE REVIEW

**Comment by kneitinger** [comment]
There are a few things I'd like to get input on:
- Should there be an option in the application settings to disable this?  `-DWITH_XC_NETWORKING=OFF` will disable it, but perhaps there are folks using a prebuilt binary that may not want this feature.
- Is the button's icon a good choice?  It is the same one as the Edit Entry -> Icon tab, but might not be the best choice for this small button

**Comment by kneitinger** [comment]
I was playing around with this some more, and I found a bug with the existing favicon fetcher (tested on my branch, current develop, and 2.3.4).

When I:
- Create a new entry with a valid URL
- click "Download favicon" in Icon page
- Save entry and (not necessarily immediately) close keepassxc
- Reopen keepassxc and edit the same entry
- click "Download favicon" in Icon page

it fetches another occurrence of the same favicon instead of displaying the blue "Custom icon already exist" message.
 
This can be repeated any number of times. If someone could take a moment and reproduce this behavior, I'd like to include a fix in this PR.

**Comment by droidmonkey** [comment]
The duplicate icon download is usually because the icons are actually different. I fixed a bug a while back where the comparison between icons was occurring prior to resize, it now does it after resize which produces better results (not perfect though).

I recommend a download image button like this:  image-download-symbol

**Comment by droidmonkey** [comment]
@kneitinger are you going to update the icon to something a little more adequate?

**Comment by droidmonkey** [comment]
I totally agree with eliminating the progress bars, they have been a pain in the butt since they were put in. I also can no longer download any icons... so there is something fishy going on.

**Comment by kneitinger** [comment]
Can't download icons in what situations?  Fallback disabled? I don't seem to have problems with them, but if you can give me a good example URL, I'm happy to check some recent changes for anything that would cause that.

**Comment by droidmonkey** [comment]
Yah the error I am getting is "Cannot create SSL context". This is on the latest develop running right from the build tool. Also cannot download from the snapshot builds available at https://snapshot.keepassxc.org.

**Comment by kneitinger** [comment]
Oh the reason I hadn't run into it yet (despite current dev being merged into my branch) is whether I paste from the URL from the browser or enter the URL by hand I always have 'https://' in the URL.  So this seems to only affect urls without that.

**Comment by droidmonkey** [comment]
This is a Windows-Only issue, I figured it out. You need to install OpenSSL on your system (for now): https://slproweb.com/products/Win32OpenSSL.html

We need to separately figured out how to package the needed libraries.

**Comment by kneitinger** [comment]
Not sure its working completely correctly on linux either.  I don't recall ever seeing this message in the console upon startup:

```
qt.network.ssl: QSslSocket: cannot resolve SSLv3_client_method
qt.network.ssl: QSslSocket: cannot resolve SSLv3_server_method
```

And any urls without a leading 'https://' fail to download.

**Comment by kneitinger** [comment]
@droidmonkey I see activity from you right now.  I want to revise the PR body to reflect the changes accurately, and fix one UI issue I just caught.  I'll post when these are taken care of (~20 mins).

**Comment by droidmonkey** [comment]
No rush, I am just trolling. I am also compiling your branch right now to check it out

**Comment by kneitinger** [comment]
Fixed issue and updated PR body.

In case it is ever needed, here is the raw .svg for the icon (gzipped to make github file uploader happy)

[favicon_download.svg.gz](https://github.com/keepassxreboot/keepassxc/files/2593707/favicon_download.svg.gz)

**Comment by droidmonkey** [comment]
We'll bring this in once the big refactor PR's are merged

**Pull request merged**
