### PR TITLE
allow 12 hour timeout for lockDatabaseIdle

### PR DESCRIPTION
**Pull request by jsachs**
Allow users to increase the timeout for lockDatabaseIdle to 12 hours.
## Description

Increases the maximum lockDatabaseIdleSpinBox value to 43200 seconds.

See https://github.com/keepassxreboot/keepassxc/issues/1331

## Motivation and context

We are considering enforcing lockDatabaseIdle for all of our users. If this is the case, we want our users to be able to select a much longer maximum timeout.

## How has this been tested?

Manually

## Types of changes

- ✅ New feature (non-breaking change which adds functionality)

## Checklist:

- ✅ I have read the **CONTRIBUTING** document. **[REQUIRED]**
- ✅ My code follows the code style of this project. **[REQUIRED]**
- ✅ All new and existing tests passed. **[REQUIRED]**
- ✅ I have compiled and verified my code with `-DWITH_ASAN=ON`. **[REQUIRED]**

### CODE REVIEW

**Comment by phoerious** [comment]
@droidmonkey Should we include this in 2.3.4?

**Comment by droidmonkey** [comment]
Yes that is acceptable

**Comment by foliolin** [comment]
2.3.4 on macOS 10.14.1 still has the restriction of 9999.

image

**Comment by droidmonkey** [comment]
This was added to 2.4.

**Pull request merged**
