### PR TITLE
Make X11Extras conditional on autotype again

### PR DESCRIPTION
**Pull request by Hello71**
After 404fd941e8e5 ("Move global shortcut handling into OSUtils
(#5566)"), X11Extras was made mandatory, even though it is only used for
autotype. Make it conditional on autotype again.

## Testing strategy
Tested that with autotype disabled and X11Extras not installed, KeePassXC successfully compiles, opens database, and opens application settings. Did not test autotype enabled.

## Type of change
- ✅ Bug fix (non-breaking change that fixes an issue)

### CODE REVIEW

**Comment by droidmonkey** [comment]
We are planning to use global shortcuts for things other than Auto-Type.

**Comment by Hello71** [comment]
Is it possible to add a XC_X11 then? The keepassxc -> qtx11extras -> X qtgui dependency chain is quite unfortunate for Wayland users of source-based distros.

**Comment by droidmonkey** [comment]
Sure I can get behind that, as long as you successfully kill off all x11 dependency. Just removing qt5x11 is not enough.

**Comment by Hello71** [comment]
> Sure I can get behind that, as long as you successfully kill off all x11 dependency. Just removing qt5x11 is not enough.

I'm not sure what you mean. I am currently successfully running keepass 2.7.0 plus this PR with qtgui compiled without X support, as defined by Gentoo.

**Comment by droidmonkey** [comment]
Nevermind I was confused. What is even provided by qt5x11extras? The documentation is blank from qt.

**Comment by jirutka** [comment]
I’m with @Hello71, qt11extras is a pretty huge dependency and it’s unnecessary for Wayland users. I’m thinking about using this patch in Alpine package to avoid this dependency chain. However, since it’s part of the application, not just autotype plugin, I have to build KeePassXC twice – with and without autotype – and provide two packages – one for X11 users and the other one for Wayland users. That’s quite suboptimal.

**Comment by Hello71** [comment]
> What is even provided by qt5x11extras? The documentation is blank from qt.

Well, it provides at least the QX11Info which is disabled by this PR. That is necessary to bind global hotkeys using X11 API.

> However, since it’s part of the application, not just autotype plugin, I have to build KeePassXC twice – with and without autotype – and provide two packages – one for X11 users and the other one for Wayland users. That’s quite suboptimal.

I agree, but I think this was true even before 2.7.0. Unfortunately, I don't think there's an easy way to avoid this. I think the "correct" solution is to replace X11 application-internal binding with global DE binding (via desktop file?). That is the only way forward for Wayland. However, Auto-Type will still not work. Probably the right move there is to open a separate project handling simulated keyboard input across X11 and Wayland, and then allow that project to be compiled with X or Wayland support or both.

**Comment by michaelk83** [comment]
> I think the "correct" solution is to replace X11 application-internal binding with global DE binding (via desktop file?). That is the only way forward for Wayland.

There was some talk (and a draft PR) of a global keyboard shortcut portal, but it's not ready yet: https://github.com/keepassxreboot/keepassxc/issues/2281#issuecomment-1065292035 (follow the links from there).

**Pull request closed without merging**
