### PR TITLE
Update src/CMakeLists.txt: Fix CPack Error when building with latest vcpkg

### LINKED ISSUE #10097: CPack Error: Some XML patch fragments did not have matching IDs: 'CM_CP_KeePassXC.exe'
## Overview
This is mostly a reference issue, I already know what is wrong and have linked a pull request to this issue.
After updating the vcpkg repository to the _**latest**_ version and rebuilding KeePassXC, I have received the error message: 
`CPack Error: Some XML patch fragments did not have matching IDs: 'CM_CP_KeePassXC.exe'`

Note: This error does not exist in much older vcpkg versions, such as the prebuilt dependency package provided in the build documentation. This is likely due to changes in the `vcpkg.cmake` file over time by the vcpkg maintainers.

## Environment
Windows 11 Enterprise
Visual Studio 2022 Enterprise
Developer Powershell for VS 2022

## Steps to Reproduce
1.  Download the **_latest_** vcpkg repository and install the dependencies as specified by the KeePassXC Build Documentation
2. Download the `develop` branch of KeePassXC and `cd` into the repository folder. 
3.  Build KeePassXC using the command `cmake -DCMAKE_TOOLCHAIN_FILE=D:\path\to\your\vcpkg.cmake -DCMAKE_BUILD_TYPE=Release -DWITH_XC_ALL=on -DX_VCPKG_APPLOCAL_DEPS_INSTALL=ON -B build -G Ninja`. Replace `D:\path\to\your\vcpkg.cmake` with the location of _your_ vcpkg.cmake
4. `cd` into the `build` directory and type `ninja -j8 package`

## Expected Behavior
The build should work normally, filling the `build` directory with the binaries, along with the portable zip folder, and the MSI installer, which is generated by WiX.

## Actual Behavior
The screenshot below should illustrate the error well.
image

## Context
The error is caused by the fact that running cmake somehow adds the following line to the `CPackConfig.txt` file (which is generated in the `build` directory after running cmake). 

`set(CPACK_COMPONENTS_ALL "Runtime;Unspecified")`

This causes the XML fragments mismatch in the generated WiX files. For example, in the generated WiX file `files.wxs` (which should be located in the `build\_CPack_Packages\win64\WIX` folder after the build), the string `Runtime` is added after `CM_CP` and `CM_FP`

image

You can see that the `CM_CP_Runtime.KeePassXC.exe` in the statement `<Component Id="CM_CP_Runtime.KeePassXC.exe" Guid="*">` mismatches what's in source code file `wix-patch.xml`
which is the `CM_CP_KeePassXC.exe` in the statement `<CPackWiXFragment Id="CM_CP_KeePassXC.exe">`

image

### PR DESCRIPTION
**Pull request by yyualvin**
Added `set(CPACK_COMPONENTS_ALL "")` to prevent cmake from adding the line `set(CPACK_COMPONENTS_ALL "Runtime;Unspecified")` which will cause the error (CPack Error: Some XML patch fragments did not have matching IDs: 'CM_CP_KeePassXC.exe' ) later on. As mentioned by the linked issue, this is an error that happens when building with the latest version of vcpkg.

Specifically we want to prevent the circled elements from being appended to the generated WiX XML files.

image

Fixes #10097 

## Type of change
[NOTE]: # ( Please remove all lines which don't apply. )
- ✅ Bug fix (non-breaking change that fixes an issue)

### CODE REVIEW

**Comment by phoerious** [comment]
Thanks! Could you please test your change also with this branch: https://github.com/keepassxreboot/keepassxc/pull/10088

Don't forget to set `-DCMAKE_TOOLCHAIN_FILE` on your `cmake` command.

**Comment by yyualvin** [comment]
@phoerious While testing this on the branch #10088, I noticed that even when specifying my vcpkg.cmake, it would still have to rebuild all dependencies in the build directory, rather than grabbing the already built ones from my vcpkg directory. Was this an intentional feature?

**Comment by phoerious** [comment]
Ideally, the already-installed binaries should just be copied over if the version dependencies match.

EDIT: See here: https://learn.microsoft.com/en-gb/vcpkg/users/binarycaching

**Comment by yyualvin** [comment]
@phoerious I just tested my change on the branch #10088 and building was successful 😊

**Review by droidmonkey — APPROVED** [review]

**Pull request merged**
