### PR TITLE
Replace "Master Key" with "Database Credentials"

### PR DESCRIPTION
**Pull request by droidmonkey**
**Definitions:**
* Database Key - Cryptographic hash used to perform encrypt/decrypt of the database
* Database Credentials - User facing term to refer to the collection of Password, Key File, and/or Hardware Key used to derive the Database Key

**Changes:**
* Remove the term "master" and "key" from the user's lexicon and clarify  the code base based on the definitions above.
* Clean up wording in the UI to be clearer to the end user.

**No logical code was changed, just the names of functions.**

[NOTE]: # ( Describe your changes in detail, why is this change required? )
[NOTE]: # ( Explain large or complex code modifications. )
[NOTE]: # ( If it fixes an open issue, please add "Fixes #XXX" )

## Screenshots
[TIP]:  # ( Do not include screenshots of your actual database! )
image

image

image

## Type of change
[NOTE]: # ( Please remove all lines which don't apply. )
- ✅ Refactor (significant modification to existing code)
- ✅ Documentation (non-code change)

### CODE REVIEW

**Comment by ThiefMaster** [comment]
🤦‍♂️

**Comment by phoerious** [comment]
4chan making up a white-knight political correctness story. Love it.

**Comment by Grahtni** [comment]
Some people are unable to grasp context or that words can have different meanings.

**Comment by ccoenen** [comment]
commenters be like "I am completely unaffected by this change, yet I wish to express my desire to look dumb"

**Comment by markus-seidl** [comment]
For what is worth, I personally think that "Database key" might be more clear for users.

**Comment by droidmonkey** [comment]
It's actually not. Before this change was ever made or thought of, the unlock database page already had "Enter additional database credentials" on it. Additionally, the use of Database Key can be easily confused with the Key File credential which has actually happened. So this PR aligns the terminology and clearly demarcs the difference between Credentials and Key (see definitions).

The amazing thing is that this is open source software and if database credentials doesn't cut your mustard than you can fork us and go back to master key.

**Comment by phoerious** [comment]
KeePassXCM - Master Key Edition.

**Pull request merged**
