### PR TITLE
Add simple detection of timestamp resolution for CSV files

### LINKED ISSUE #3490: Add: change created date and modified date
Hello Keepassxc,

i use an iMac (2011) and macOS 10.13.6. (+ including current secure update)

I am using current 1Password (7.3.2) version
https://app-updates.agilebits.com/product_history/OPM7

But I don't want to use 1Password anymore, because of their business model.

I used KeePassXC (2.4.3) for the first time. And I think it works very well and the UI/UX are enough for me.

Now comes the problem. I have over 100 notes in 1Password that have a lot of text. The texts also have special characters (but all typed with the english keyboard).
I have in 1Password the "Export" function and the selected (most important to me ) "Title" "Notes" "Modified Date" "Created Date" and "Tags"** and then saved as csv file (over 1.5 MB in size).
** Tags, too, but KeePassXC does not support tags. Here I have as an alternative the folder (group) function

In the csv file everything is added correctly for each column (according to my observations).

Then I used the import csv function of the KeePassXC. But it doesn't work wait over 5 hours and the software doesn't respond.

Even if I make fewer entries so 3 notes in a single csv file, it sometimes and then again does not work.
-------------------------

The title and notes can be copied manually and then added to KeePassXC manually (it takes a long time), but better than nothing. But can't change the **modified date** and **created date** manually.

So here's my proposal. Can you add a function where the user can change the "modified date" and "created date" for the entries? It is very important to me because of the history of the notes.

### LINKED ISSUE #6498: CSV Import doesn't handle millisecond times correcrly
Hi,
  on a 64-bit Linux I see in the listing of entries wrong date in the right-most column tagged "Modified". 
keepassxc_wrong_date

  The expiry date is shown correctly if I double-click the entry and view its details in a dedicated window on "Expires:" line.

### PR DESCRIPTION
**Pull request by evgfilim1**
## Summary

Fixes #6498 

## Screenshots
N/A

## Testing strategy
- Created a record in Firefox password manager
  Firefox password manager
- Exported passwords in Firefox, then imported [logins.csv file](https://github.com/keepassxreboot/keepassxc/files/7649215/test.csv) I got in stable (dark themed) and my snapshot (light themed) and compared the results.
  Properties in stable
  Properties in snapshot

Also:
- Imported my existing *.csv file from Firefox, works fine
- Run tests included with the code, all passed

## Type of change
- ✅ Bug fix (non-breaking change that fixes an issue)

### CODE REVIEW

**Comment by droidmonkey** [comment]
UUID import is not a good idea, there is no reason for it from Firefox and it is a backend detail that the user is not allowed to mess with. Plus you aren't doing any duplication checks which can cause a huge mess. I will not merge a UUID import. 

Secondly, last accessed is meaningless and doesn't need to be imported. I am likely going to hide that field from view because it literally is equal to modified time in the backend code. 

The millisecond precision should be the only change in this code. 

#3490 was already implemented, I'm closing that request.

**Comment by evgfilim1** [comment]
> UUID import is not a good idea, there is no reason for it from Firefox and it is a backend detail that the user is not allowed to mess with. Plus you aren't doing any duplication checks which can cause a huge mess. I will not merge a UUID import.

Okay, I'll remove that, thanks for feedback.

> Secondly, last accessed is meaningless and doesn't need to be imported. I am likely going to hide that field from view because it literally is equal to modified time in the backend code.

But when a database is imported from CSV, it has different access and modification timestamps, so I decided to add it in case someone needs this information. As far as I understood, it's better to remove this field also because it's useless, right? @droidmonkey

image

**Comment by droidmonkey** [comment]
Correct it is useless, probably need to fix the setting of the last accessed field. Just make it equal to modified.

**Comment by evgfilim1** [comment]
@droidmonkey done, could you review my changes now?

**Review by droidmonkey — APPROVED** [review]

**Comment by mmokrejs** [comment]
Thanks for your effort, @evgfilim1 !

**Pull request merged**
