### PR TITLE
Add menu option to allow screenshots

### LINKED ISSUE #7580: Add view menu option to allow screenshots for temporary period of time
## Overview
KeePass 2.7.0 main window is invisible in a remote session with TeamViewer or AnyDesk --> problem with new feature "Prevent screen capture"?

## Steps to Reproduce
1. Connect to your remote pc with TeamViewer or AnyDesk
2. Open KeePassXC on the remote machine
3. The program opens in tray, but the window is not visible. On screen of the remote machine, the window is visible normally, but not in remote software window.

## Expected Behavior
The program should be usable with a remote software like TeamViewer or AnyDesk. Optionally, if this conflicts with the screen capture prevention feature, it should be possible to disable this feature.

## Actual Behavior
The main window keeps invisible.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.0
Revision: d7a9ef4

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 10 and 11

### PR DESCRIPTION
**Pull request by droidmonkey**
* Fix #7580
* Also refactor the code to move everything into MainWindow

## Screenshots
[TIP]:  # ( Do not include screenshots of your actual database! )
image

## Testing strategy
[NOTE]: # ( Please describe in detail how you tested your changes. )
[TIP]:  # ( We expect new code to be covered by unit tests and documented with doc blocks! )
Tested on Windows

## Type of change
[NOTE]: # ( Please remove all lines which don't apply. )
- ✅ New feature (change that adds functionality)

### CODE REVIEW

**Comment by droidmonkey** [comment]
@phoerious would appreciate a review of this one

**Comment by droidmonkey** [comment]
This is a relatively benign change (and rather useful) so will merge it in.

**Comment by LayersOfAbstraction** [comment]
> @phoerious would appreciate a review of this one

Hi, thank you, really appreciate the feature. I prefer to actually start it in the command line as it is safer with the `--allow-screencapture` parameter so I don't forget to disable it after I finish the screen capture. I feel that view menu option you made should be set to disable after closing with a pop-up advising the user so they know it is intentional. 

It could say something like: 

**As a security measure, the Allow Screen Capture option will automatically be disabled after closure.**

**Comment by Scrxtchy** [comment]
> > @phoerious would appreciate a review of this one
> 
> Hi, thank you, really appreciate the feature. I prefer to actually start it in the command line as it is safer with the `--allow-screencapture` parameter so I don't forget to disable it after I finish the screen capture. I feel that view menu option you made should be set to disable after closing with a pop-up advising the user so they know it is intentional.
> 
> It could say something like:
> 
> **As a security measure, the Allow Screen Capture option will automatically be disabled after closure.**

Funny enough, I stumbled across the launch argument from the documentation just now. I added it to my shortcut so I could start it with the configuration as it was causing nvidia shadowplay to not record anything due to the protected content flag. This does feel much safer than just adding in a permanent configuration for this but it's not well known about (and nvidia has no visible error for these things lol, took me a while to realise this was the case)

**Pull request merged**
