### PR TITLE
Refactor continuous integration setup

### PR DESCRIPTION
**Pull request by adolfogc**
## Description
In a nutshell, this PR updates the current continuous integration infraestructure as follows:

- The main Linux builds are continued to be done using Travis CI's Ubuntu 14.04 (trusty) image, a requirement, as explained by @phoerious in this PR's discussion.
- A debug macOS build was enabled on Travis CI and was made "optional" so that it doesn't block PRs.
- Some other Linux builds that use Docker were enabled on Travis CI and were also made "optional".
- Windows support was added using AppVeyor. This support is preliminary, please note that currently it fails test number 21.

### Other details:
- macOS and Windows builds takes into consideration the upcoming switch to `qhttpengine` and `libcurl`.
- "Caching" of Docker images is supported by the use of Docker Hub:
  + The Travis CI settings need to be updated with valid values for the `DOCKER_USER` and `DOCKER_PASSWORD` environment variables.
   + The images will be pushed to Docker Hub after the PR is merged.
   + If the PR doesn't modify a Dockerfile, an image from Docker Hub is used instead of building it, except if the image isn't yet available at Docker Hub.

### To-Dos:
- Add AppVeyor badge: https://www.appveyor.com/docs/status-badges/

## Motivation and context
- Add build coverage for Windows platforms.
- Re-enable macOS builds (without blocking PRs).
- Test other Linux environments using Docker.

## How has this been tested?
On my personal Travis CI and AppVeyor. Please see these updated build logs:
- Travis CI: https://travis-ci.org/adolfogc/keepassxc/builds/305484490
- AppVeyor: https://ci.appveyor.com/project/adolfogc/keepassxc/build/1.0.223/job/mu51slsjjnvlnnoa

❗️ On AppVeyor, it fails test `21 - testcsvparser`. I don't know why.

Also, using my Docker Hub account, these images were pushed by Travis CI:
- https://hub.docker.com/r/adolfogc/keepassxc/tags/

## Screenshots (if appropriate):
N/A

## Types of changes

- ✅ New feature (non-breaking change which adds functionality)

## Checklist:

- ✅ I have read the **CONTRIBUTING** document. **[REQUIRED]**
- ✅ My code follows the code style of this project. **[REQUIRED]**
- ❌  All new and existing tests passed. **[REQUIRED]** (AppVeyor fails a test).
- ✅ I have compiled and verified my code with `-DWITH_ASAN=ON`. **[REQUIRED]**
- ~✅ My change requires a change to the documentation and I have updated it accordingly.~
- ~✅ I have added tests to cover my changes.~

### CODE REVIEW

**Comment by phoerious** [comment]
We cannot migrate away from Ubuntu 14.04. We need it to ensure our builds stay compatible with our AppImage build system.

**Comment by adolfogc** [comment]
@phoerious I've made some changes to accommodate this restriction. What do you think?

**Comment by phoerious** [comment]
I think, building Docker images on the fly and extending the test matrix with multiple Linux systems is a non-starter unless we move to a faster CI system. Travis is already dog-slow and builds take forever. We do have a few donations, so we could spent a little money on this, but it mustn't be too much, so donations can continue to cover the costs in the future.

**Comment by adolfogc** [comment]
I've made some changes to accommodate to these limitations:
- Enable pulling the image if its Dockerfile hasn't been modified
- Push the image when having successfully build the _develop_ branch 
- Reduce the matrix

Please note that Travis is failing due to missing values for the `DOCKER_USER` and `DOCKER_PASSWORD` environment variables. See my build log at: https://travis-ci.org/adolfogc/keepassxc/builds/305189445

**Comment by adolfogc** [comment]
@phoerious 

>We cannot migrate away from Ubuntu 14.04. We need it to ensure our builds stay compatible with our AppImage build system (and our Trusty PPA, as well).

Noted. The main Linux builds are continued to be done using Travis CI's Ubuntu 14.04 (trusty) image.

>I think, building Docker images on the fly and extending the test matrix with multiple Linux systems is a non-starter unless we move to a faster CI system. Travis is already dog-slow and builds take forever. 

I've made some improvements to address this concerns, please refer to the updated PR's description.

**Comment by droidmonkey** [comment]
@adolfogc I corrected the mingw testcsvparser failure in #1319

**Comment by phoerious** [comment]
Short info: we migrated to TeamCity. I think we can still re-use some of the stuff here, but all Travis-related configs can be dropped.

**Comment by adolfogc** [comment]
> I think we can still re-use some of the stuff here, but all Travis-related configs can be dropped.

Maybe we could have AppVeyor for Windows builds, and Travis for macOS builds exclusively? In the case of the latter, we could make them optional, as to not block the PR from being merged.  What do you think?

**Comment by droidmonkey** [comment]
Most of this PR is invalid now that team city is active. We should still implement AppVeyor for Windows builds though. Should we close this one and open a new one for implementing AppVeyor?

**Comment by adolfogc** [comment]
@droidmonkey Agreed.

**Pull request closed without merging**
