### PR TITLE
Fix status bar update when switching to other DB

### LINKED ISSUE #9071: Number of entries not updated when switching between databases
## Overview
When switching between databases, the number of entries shown in the bottom right corner of the application window isn't updated.

## Steps to Reproduce
1. Open two databases with 1 and 2 entries.
2. Switch to the first database. Observe how in the bottom right corner of the application window, it says "1 entry".
3. Switch to the second database. Observe how in the bottom right corner of the application window, it still says "1 entry", even though the active database has 2 entries.

KeePassXC - Version 2.7.4
Revision: 63b2394
Operating System: Windows/Linux/macOS

### PR DESCRIPTION
**Pull request by dmaslenko**
Fixes #9071 bug.

## Testing strategy
The same as described in the bug.

## Type of change
- ✅ Bug fix (non-breaking change that fixes an issue)

### CODE REVIEW

**Comment by dmaslenko** [comment]
I will add GUI test later.

**Review by droidmonkey — APPROVED** [review]

**Comment by droidmonkey** [comment]
The gui tests from this commit are causing problems when I merged it over to the 2.7.x branch. I am going to correct them in a follow up PR.

**Comment by dmaslenko** [comment]
Hm, wondering what kind of GUI test problem?

**Comment by droidmonkey** [comment]
The checked string is localization dependent with quantity replacements.

**Pull request merged**
