### PR TITLE
Set maximum password length to 999 characters when using spinbox text entry

### PR DESCRIPTION
**Pull request by droidmonkey**
[NOTE]: # ( Describe your changes in detail, why is this change required? )
[NOTE]: # ( Explain large or complex code modifications. )
[NOTE]: # ( If it fixes an open issue, please add "Fixes #XXX" )
Reverts changes from #5748 and increases the limit from 128 characters to 999 characters when setting the length using the spinbox text entry.

## Screenshots
[TIP]:  # ( Do not include screenshots of your actual database! )

## Testing strategy
[NOTE]: # ( Please describe in detail how you tested your changes. )
[TIP]:  # ( We expect new code to be covered by unit tests and documented with doc blocks! )

## Type of change
[NOTE]: # ( Please remove all lines which don't apply. )
- ✅ Bug fix (non-breaking change that fixes an issue)

### CODE REVIEW

**Comment by phoerious** [comment]
Why not set it to 99999 or so? Just in case the next "I need 10 billion bit entropy passwords for 256-bit AES" guy comes along.

**Comment by droidmonkey** [comment]
I agree but at least this keeps the slider to a reasonable sensitivity to its width while limiting code changes.

**Comment by phoerious** [comment]
The slider should be restricted to a low manageable number like 64 or 128. A manually entered number larger than that should not affect the slider at all.

**Comment by Snowden-rgb** [comment]
what's with having a limit btw, i created a python program which can get 100000 and above digit passwords

**Comment by droidmonkey** [comment]
Congrats? The limit prevents unnecessary storage of information and keeps things sensible.

**Comment by droidmonkey** [comment]
@phoerious I found a much more elegant solution.

**Comment by phoerious** [comment]
There is absolutely not point in having a 100000-character password.

**Comment by Snowden-rgb** [comment]
> 
> 
> Congrats? The limit prevents unnecessary storage of information and keeps things sensible.

woah, that's cool, 999 digits would be fun, thanks you so very much man

**Review by Snowden-rgb — APPROVED** [review]

**Review by phoerious — APPROVED** [review]

**Comment by c3X69puyujLWudBjwQEjmTUgEXr49cGa74EqHiL** [comment]
thanks @droidmonkey you did it. the bewitched 99 digit limit is gone.

**Comment by phoerious** [comment]
So you can finally create passwords with log2(62^999) bits of entropy to be hashed into a 256 bit hash. 👍

**Pull request merged**
