### PR TITLE
MacOS: Fix crash on exit

### LINKED ISSUE #9423: KeePassXC 2.7.5 on macOS quits unexpectedly on exit
## Overview
Updated from 2.7.4 to 2.7.5 on an Intel Mac running macOS 13.3.1(a). Exiting KeePassXC causes Apples "KeePassXC quit unexpectedly" to pop up every time.

Diagnostics attached.
[2023-0515-keepassxc-diagnostics.txt](https://github.com/keepassxreboot/keepassxc/files/11482436/2023-0515-keepassxc-diagnostics.txt)

### PR DESCRIPTION
**Pull request by droidmonkey**
* Fixes #9423

[NOTE]: # ( Describe your changes in detail, why is this change required? )
[NOTE]: # ( Explain large or complex code modifications. )
[NOTE]: # ( If it fixes an open issue, please add "Fixes #XXX" )

## Testing strategy
[NOTE]: # ( Please describe in detail how you tested your changes. )
[TIP]:  # ( We expect new code to be covered by unit tests and documented with doc blocks! )
~~Needs to be confirmed by someone experiencing this crash~~

## Type of change
[NOTE]: # ( Please remove all lines which don't apply. )
- ✅ Bug fix (non-breaking change that fixes an issue)

### CODE REVIEW

**Comment by baekelite** [comment]
I cloned 2.7.5 and applied this fix.  I no longer observe the crash

**Comment by droidmonkey** [comment]
Awesome thank you

**Comment by red-lonely-neuron** [comment]
Hi. As you requested in the issue #9423, I have tested the fix and the application doesn't crash. Please have a look at my comment over there to see how I tested.

**Comment by droidmonkey** [comment]
Excellent, we'll get 2.7.6 out soon

**Pull request merged**
