### PR TITLE
Fix Botan 3 build

### PR DESCRIPTION
**Pull request by pobrn**
```
Botan commit 819cf8fe6278a19b8266f449228f02fc28a4f784 changed
Botan::Cipher_Dir to be a scoped enumeration, so the users
must be adapted.

This change causes no issues with Botan 2 because normal
enumeration values can also be referred to the same way
scoped enumeration values are accessed.
```

### CODE REVIEW

**Comment by droidmonkey** [comment]
I would like to have cmake automatically enable the botan 3 compile flag if that version is found. Can you incorporate?

**Comment by pobrn** [comment]
I can certainly try but I don't really know CMake, so I am definitely not the best person to do it.

**Comment by droidmonkey** [comment]
Ok, I can add it then no biggie

**Comment by droidmonkey** [comment]
I added a way to auto-detect Botan3 and set everything up correctly if it is found. Fallback is to Botan2 as before. Can you test this on your end to make sure it works correctly? None of our CI has Botan3 installed on it.

**Comment by pobrn** [comment]
Seems to work with Botan 3.

**Comment by pobrn** [comment]
> None of our CI has Botan3 installed on it.

Looks like the MacOS one (now) has Botan 3. The build failure there should be fixed by #9389.

**Comment by pobrn** [comment]
```
Found Botan3: C:/vcpkg/installed/x64-windows/lib/botan.lib (found version "2.19.1")
```

[This is certainly odd.](https://ci.keepassxc.org/buildConfiguration/KeePassXC_Windows10/228461?hideProblemsFromDependencies=false&hideTestsFromDependencies=false&expandBuildProblemsSection=true&expandBuildChangesSection=true&showLog=228460_116_81&logFilter=debug&logView=flowAware)

**Comment by droidmonkey** [comment]
Yah I'm live testing on the macOS CI box. I incorporated your C++20 fix into this PR

**Comment by droidmonkey** [comment]
Looks like I need to fix windows, it is finding botan and thinking it is version 3. We may need to collapse the FindBotan3 and FindBotan2 cmake files into one.

**Review by droidmonkey — APPROVED** [review]

**Pull request merged**
