### PR TITLE
clang-tidy: use braced init list

### PR DESCRIPTION
**Pull request by neheb**
Signed-off-by: Rosen Penev <rosenp@gmail.com>

### CODE REVIEW

**Comment by neheb** [comment]
Can't figure out how to view the Windows failures. My guess is that it doesn't like implicit int conversions.

**Comment by droidmonkey** [comment]
Transient failure don't worry

**Comment by droidmonkey** [comment]
Made a couple manual edits to retain consistency and fix some errors. I also reverted the MainWindow.cpp change since that is silly to split the destructor into a default and a non-default over an #ifdef.

**Review by droidmonkey — APPROVED** [review]

**Comment by neheb** [comment]
Rebased.

**Pull request merged**
