### PR TITLE
Add SECURITY.md to guide security vulnerability reporting

### LINKED ISSUE #11324: Suggestion/Request to Add SECURITY.md to define a Security Policy
Hello! I’d like to propose the addition of a SECURITY.md file to this repository. This would make it easier for users/developers to report security vulnerabilities responsibly improving the project’s security posture and potentially increase the project’s OpenSSF Scorecard rating.
Here’s a guide that could be helpful during implementation: [Adding Security Policy to Your Repository](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository)
I’d be happy to help draft the policy or assist in any other way to get this implemented. Let me know what you think! Thanks again for your continued work on KeePassXC!

### PR DESCRIPTION
**Pull request by AhlamBCoding**
Fixes #11324 

## Screenshots
_No screenshots are required for this documentation change._

## Testing strategy
Since this is a documentation-only change, there is no specific testing needed. However, I have ensured that all links within the SECURITY.md file are functional and correctly point to the intended destinations.

## Type of change
- ✅ Documentation (non-code change)

**I'm happy to incorporate any feedback or adjustments the team might suggest.**

### CODE REVIEW

**Review by droidmonkey — APPROVED** [review]

**Comment by droidmonkey** [comment]
@phoerious whatcha think?

@Ahlam-Banu I added some more language to the document, thank you

**Comment by AhlamBCoding** [comment]
Thank you for review this! appreciate the enhancements and glad I could assist, thanks again!

**Comment by phoerious** [comment]
Perhaps some examples for what are security vulnerabilites and what aren't? I don't want to get a host of "hey, when I inject a DLL into your app, I can read everything" reports.

The sentence about not reserving CVEs without our say-so cannot be overemphasised.

**Comment by droidmonkey** [comment]
Good idea, and yeah still have CVE scars...

**Comment by AhlamBCoding** [comment]
I’ve updated the file to include:
- some examples of what constitutes a security vulnerability and what doesn't.
- highlighted the note about not reserving CVEs without approval.
let me know incase of additional adjustments/modifcations, thanks!

**Comment by phoerious** [comment]
There will be no SQL injection, because we don't do SQL.

**Comment by AhlamBCoding** [comment]
> There will be no SQL injection, because we don't do SQL.

file is now updated accordingly :)

**Comment by droidmonkey** [comment]
There is no need to keep merging develop branch thank you!

**Comment by droidmonkey** [comment]
Made a few cleanup edits, ready for publishing

**Review by droidmonkey — APPROVED** [review]

**Pull request merged**
