### PR TITLE
Add some password-related feature

### PR DESCRIPTION
**Pull request by TheZ3ro**
## Description

 - [X] Add an entropy meter for password generation based on zxcvbn ( #84 )
 - [X] Make the entropy meter standalone (is accessible with the entropy-meter executable)
 - [X] Make zxcvbn a separate library that compile with CMake
 - [X] Update COPYING file with zxcvbn copyright
 - [X] Add entropy test and gui test
 - [X] Color the entropy meter based on the password strength
 - [X] Make password generator a standalone generator like KeePass ( #18 )
 - [X] Don't require password repeat if password is visible ( #27 )
 - [ ] Prevent saving password with Enter when the Generator is open

## Screenshots (if appropriate):
istantanea_2016-11-11_18-49-14

## Types of changes

- :white_check_mark: Bug fix (non-breaking change which fixes an issue)
- :white_check_mark: New feature (non-breaking change which adds functionality)
- :heavy_minus_sign: Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- :white_check_mark: I have read the **CONTRIBUTING** document. [REQUIRED]
- :white_check_mark: My code follows the code style of this project. [REQUIRED]
- :negative_squared_cross_mark: All new and existing tests passed. [REQUIRED]
- :heavy_minus_sign: My change requires a change to the documentation.
- :heavy_minus_sign: I have updated the documentation accordingly.
- :white_check_mark: I have added tests to cover my changes.

**NOTE**
the /src/zxcvbn/dict-src.h file contains an english word dictionary auto-generated from [zxcvbn-c](https://github.com/tsyrogit/zxcvbn-c)

### CODE REVIEW

**Comment by TheZ3ro** [comment]
Little update on the work:
When the password is dictionary-only (es. `hellowhoisthere`) the entropy is **wrongly** set to **0.00**
The entropy-meter executable instead output entropy of `23.852` that is right.

Someone can help debugging this?

**Comment by rockihack** [comment]
The entropy shown in the screenshot is wrong.
Respecting the checkboxes it should be `log2((25+24+8)^2 * 25 * 24 * 8) = ~23.89`

**Comment by TheZ3ro** [comment]
Where does that formula come from?
That entropy is calculated this way:
```python
# n: password length
# c: password cardinality: the size of the symbol space
#    (26 for lowercase letters only, 62 for a mix of lower+upper+numbers)
# entropy = n * lg(c) # base 2 log
import math
math.log(62,2)*5
```

Following [zxcvbn-c](https://github.com/tsyrogit/zxcvbn-c) way, the above formula is used on a single-word password when it doesn't appear in any of the loaded dictionary.
You can test a demo of zxcvbn by downloading that fork, compiling and executing the `/build/utils/entropy-meter` file. The `-a` flag will print advanced information

**Comment by rockihack** [comment]
It's the standard formula from shannon.
`H = - Sum from i=0 to m over (p_i * log2(p_i))`

We assume a uniformly distributed random source and we can simplify the equation to:
`H = -log2(p_i) = log2(1 / p_i)`

For two lowercase characters we get:
`H = -log2(1/(26*26)) = log2(1 / (1 / 26*26)) = log2(26^2) = 2 * log2(26)`

You can see here that zxcvbn derived `n * log2(c)` also from shannon.

The problem here are the checkboxes:
[x] Exclude look-alike characters
[x] Pick characters from every group

The assumption that we got a uniformly distributed random source does not hold true anymore.
We got 3 character groups:
1) a-z (without l) => 25
2) A-Z (without I and O) => 24
3) 0-9 (without 0 and 1) => 8

It is also required to pick atleast one character from each group.
Now we get `p_i = 1 / ((25 + 24 + 8)^2 * 25 * 24 * 8)`
and `H = log2((25 + 24 + 8)^2 * 25 * 24 * 8) = 2 * log2(25 + 24 + 8) + log2(25) + log2(24) + log2(8)`

**Comment by TheZ3ro** [comment]
Oh ok. I wasn't getting the checkbox part.
Just a question, how can the last formula be character indipendent? 
In the screenshot the password is 5 character long, in your example we take a 2 char long password but there are no difference in the formulas.

Anyway, we need to add a check for the checkbox and calculate the `min(check_entropy, zxcvbn_entropy)`

### Update on the PR
#### 0.00 entropy bug
For some passwords the entropy is returned to `-inf`.
If someone wanna help debugging, uncomment `/src/core/PasswordGenerator.cpp` line 34/36 (or use a debugger :smile: )

#### Added EntropyGui Tests
Test now fail for the above bug :tada: 

#### Colored entropySpinBox
The colors at the moment are
```
    entropy < 25 ==>  Red
    entropy >= 25 && entropy < 45 ==> Orange
    entropy >= 45 && entropy < 100 ==> GreenYellow
    entropy > 100 ==> Green
```
istantanea_2016-11-12_16-20-21

**Comment by rockihack** [comment]
You mean this formula `2 * log2(25 + 24 + 8) + log2(25) + log2(24) + log2(8)`?
We got 3 characters limited to a group and 2 from all groups, in each group the probability is uniformly distributed.

1) log2(25 + 24 + 8) // not limited
2) log2(25 + 24 + 8) // not limited
3) log2(25) // limited to a-z without l
4) log2(24) // limited to A-Z without I, O
5) log2(8) // limited to 0-9 without 0, 1

**Comment by TheZ3ro** [comment]
Ok so if I want to generate a password with 6 char, picking from every group and excluding look-alike the entropy would be:
`3 * log2(57) + log2(25) + log2(24) + log2(8)`

3 character from limited group (25,24,8) and 3 character from the total group (57).
Am I right?

Anyway I think we are overcomplicating this. Your thinking is right but only the user will know from what pool the password generator has chosen the character from.
If a malicious person want to guess your password he can only assume which checkbox you pressed but if it's wrong he won't guess the password. He must use the largest group possible to guess it so to his eyes the entropy will be `n * log2(c)`

**Comment by rockihack** [comment]
Yes, you might change the name to "Maximum Entropy"
(maximum entropy is always calculated assuming uniformly distributed probability).

**Comment by TheZ3ro** [comment]
But it's the minimum entropy between BruteForce and Dictionary attack, so the label "Maximum" don't fit very well.
Maybe ''External Entropy" or "Total Entropy" ?

Anyway, can you help me debugging the 0.00 entropy bug?

**Comment by rockihack** [comment]
The term "Maximum Entropy" is well defined.
https://en.wikipedia.org/wiki/Entropy_(information_theory)#Maximum

Consider the case that no suitable wordlist is available,
zxcvbn will calculate the maximum entropy with `H = n * log2(c)`.

**Comment by TheZ3ro** [comment]
Ok I will change the label in the next commit

**Comment by droidmonkey** [comment]
I don't understand what purpose the entropy selection widget has to the right of the entropy progress bar.

Recommend replacing that selection widget with a styled label (using your background colors) that has the text of the cracking method returned by zxcvbn.

Also, entropy calls should always be maximum entropy because you have no idea what a priori knowledge the attacker has.

**Comment by TheZ3ro** [comment]
The widget is read only to:
- display the double value of entropy (the progress bar can only show the integer)
- show a color based on the password "strength"

So we want a styled label that show the double value and the color, or the attack type and the color?

---

Entropy calls are Maximum, but the password `rainbow` has a certain entropy when BruteForcing but  lot less when using a Dictionary attack, so it's the following:

For each attack method take the Maximum entropy, then take the minimum of attack's entropy

---
Also, those are just side-issue, the main issue is that some Dictionary-only words return `-inf` entropy

**Comment by droidmonkey** [comment]
Is there any value to knowing your entropy to the hundredth decimal place? Showing the attack type would be more useful when combined with the integer entropy.

Is the inf entropy a zxcvbn bug?

**Comment by TheZ3ro** [comment]
Idk, maybe it's more accurate using the decimal.
I can convert all of this in a 4 step progress bar for the Strength, and label for the decimal entropy.

With multi-word password the attack time can be multiple (like `ryanhunter2000` is: `ryan` from Dictionary, `hunter` from Dictionary and `2000` from Date) so it should be a list of attack

I don't think it's a zxcvbn bug because the entropy-meter executable behave normally.
In the password generator function the password is a `QString` that need to be converted to `const char*` but also there is no problem with other passwords. For example `he` is good but `hel`, `hell` and `hello` aren't.

**Comment by droidmonkey** [comment]
I fixed the -inf bug and pushed it. The problem was you were using constData() which is an inline function and it would appear that mid-way through the calculations on entropy the string would get corrupted (assumptions).

It would be great if when you are messing with the length spinbox to prevent pressing enter from submitting changes to the entry (ie it should just generate the password).

**Comment by TheZ3ro** [comment]
Yes, I will add that to the feature list in the first comment.

Thanks for the -inf fix :wink:

**Comment by RealOrangeOne** [comment]
There may be a reason for this i'm not aware of, but why not use git submodules for linking to zxcvbn-c. It's far more elegant than copying the code in like this, and makes for a much smaller diff

**Comment by TheZ3ro** [comment]
@RealOrangeOne I was considering this, but I have made a fix to the zxcvbn.cpp file to make it usable under MSYS2 (I'm considering a PR to zxcvbn-c)
Also the dict-src.h is a pre-generated dictionary and by using the git-submodule it will be generated on the user machine. This needs to be added to the Cmake because zxcvbn-c uses make.
So I've used this approach.

We can talk about it and choose the best option

**Comment by RealOrangeOne** [comment]
I'd definately consider opening a PR, provided it doenst affect the functionality of the library.

How expensive is generating dict-src.h? If it doesnt take too long to generate it then running on the users machine should be fine. If it's more than 10 seconds or so.

**Comment by TheZ3ro** [comment]
@RealOrangeOne on my Intel i7, 8GB machine is like 23 seconds witht the `time` command under linux.

Note that this is required only when compiling, and not each time you install keepassxc

@droidmonkey have you seen the new Entropy GUI? Do you like it? 
istantanea_2016-11-15_20-46-33

**Comment by droidmonkey** [comment]
Great start! I put a stylesheet to it and bumped up the entropy values since short passwords are BAD.

keepassxc_pwgen

**Comment by TheZ3ro** [comment]
Nice style. I like it.
Maybe a buff also on the `100` ? Some **18** char long password are `100` bits entropy.

**Comment by droidmonkey** [comment]
It's pretty subjective on what is "good" vs "excellent" entropy. Really we are looking at maximum randomness and difficulty. 100 entropy is extremely difficult if not impossible to crack with current methods.

**Comment by TheZ3ro** [comment]
@droidmonkey TravisCI is broken -> https://travis-ci.org/keepassxreboot/keepassxc/jobs/176377914

**Comment by Manko10** [comment]
I would advise against using widgets with custom background colors and text in front of it. This breaks easily on a different system with a different widget style. Better give the password field a 5px bottom border with a color that shows how good or bad the password is.

An entropy of 85.35 is also a useless piece of information. Entropy has a measurement unit. When calculated using base 2 logarithm, the unit is bits.

**Comment by TheZ3ro** [comment]
> Better give the password field a 5px bottom border with a color that shows how good or bad the password is.

This is still using widget style to me. On xUbuntu/KDE/Windows I have no problem for the current GUI

About the entropy bit, I will fix that ASAP

**Comment by Manko10** [comment]
This is not about modifying widget styles in general. It's more about the text staying legible. It's quite possible that a user has a theme where the text on top of the green, orange or red background becomes unreadable or at least very ugly because their text color isn't black.

**Comment by droidmonkey** [comment]
The text color is controlled by the style. Not by the gtk or otherwise theme.

**Comment by Manko10** [comment]
If you are overriding any palette settings, that's even worse I would say. But regardless of any potential color or theme issues, I would generally prefer a password strength meter in this kind of style: https://blogs.dropbox.com/tech/2012/04/zxcvbn-realistic-password-strength-estimation/ (you guys linked that artcile yourself in #84). It looks a lot more polished and modern, is less obtrusive, doesn't take any unnecessary space and it's what most people are used to nowadays from countless web services.

**Comment by TheZ3ro** [comment]
It's not exactly overriding palette, just changing stylesheet and overriding user style for that specific QLabel and only (does not affect anything else) so it's totally fine

Styling a QProgressBar is a lot harder then styling a QLabel, I've tried to make a colored progressbar before but most of user's style on linux use gradients and on windows can't be changed.
Styling a QLineEdit by adding a 4-step border is also pretty hard.

The possible way is changing the QLineEdit bottom border (1-step) with a color, but i think the current setup is optimal (not so modern but this isn't HTML)

**Comment by Manko10** [comment]
You can style progress bars as well using stylesheets. It's not any
different than styling any other widgets as stylesheets always have
higher priority than native widget styles. This is also true for
QProgressBars.

I don't really like custom styling too much, especially not for text
labels. Even if it doesn't break because you are not using palette
colors, it's always inconsistent with the rest of the UI. I would
consider a thin styled progress bar a lot more subtle.

**Comment by TheZ3ro** [comment]
I've not said you can't, I've said that it's hard to do it nice because you have to use gradients, borders, etc. and this will conflict more against user's style then a simple Label (that seems like a colored button) IMHO

**Comment by Manko10** [comment]
You don't have to use gradients for a simple entropy indicator. It could look exactly like on the linked web page.

**Comment by TheZ3ro** [comment]
With the last commit I've added the StandalonePasswordGenerator.
You can open the PG mode by clicking on the BlackDice icon in the Toolbar or from the **Tools -> Password Generator** item in the top itembar.

Note: The Accept button don't do nothing but I can't disable it from MainWidget.cpp right now

istantanea_2016-11-19_13-13-27

**Comment by TheZ3ro** [comment]
I think this is done.
The `Prevent saving password with Enter when the Generator is open` can be done with a disconnect but since it's called inside the PasswordGeneratorWidget it can't disconnect event connected in the MainWidget (I think).
Adding another slot on the Key_Enter shortcut doesn't prevent the previous event from occouring so IDK

Ping @droidmonkey for the merge

**Comment by droidmonkey** [comment]
I'll review and merge tonight. Excellent work on this @TheZ3ro!

**Comment by Manko10** [comment]
I have one more suggestion I'm working on right now. Maybe wait for that? Otherwise I'd create it as new pull request for that? 
On Nov 21, 2016 2:29 PM, Jonathan White <notifications@github.com> wrote:I'll review and merge tonight. Excellent work on this @TheZ3ro!

**Comment by TheZ3ro** [comment]
@Manko10 explain your suggestion, if it's unrelated I think it's better to open a new PR

**Comment by Manko10** [comment]
It's just a different visualization for the entropy.

**Comment by TheZ3ro** [comment]
Make a screenshot of the changes so we can choose for the better UI

**Comment by Manko10** [comment]
OK, will do once it's finished.

**Comment by rockihack** [comment]
I don't like the interface either, the usability is not that great.

**Target audience:** Users without knowledge about entropy and creating secure passwords

Why does it say "Medium" if the progressbar shows only 25% ?
Why is there a progressbar anyway? It doesn't make much sense for (absolute) bits of entropy. Progressbars should be used to display relative data like 50% out of 100%.

Also for normal users bits of entropy are not important (should be hidden by default, you can add a tooltip for expert users).

Why is the entropy displayed three times with different controls?

The design in [1] is more intuitive. The password strengh (very bad, bad, medium, good, very good) matches the value that is shown by the colored progressbar. Bits of entropy are not shown directly, but I guess you get detailed information if you click on the info icon (=> tooltip).

[1] https://blogs.dropbox.com/tech/2012/04/zxcvbn-realistic-password-strength-estimation/

**Comment by TheZ3ro** [comment]
The actual UI is a trade-off between average user and advanced user.
By me there is a difference between Very Good with 100 bits of entropy and Very Good with 140 bits of entropy.

**Comment by Manko10** [comment]
So, this is the changelog of what I've done now:

* refactor the visual appearance of the password strength indicator
* change password strength colors to use more eye-pleasing KDE Breeze palette
* reword the password strength categories from bad/medium/good/excellent to poor/weak/good/excellent
* fix the PasswordGeneratorWidget height being too small (caused the alphabet selection buttons to be squished)
* fix password visibility not properly being synced with the toggle button at the right (resulted in the need to press it twice to have an effect)
* configure the standalone mode to always show the password by default
* change the "Apply" button text to "Close" in standalone mode and make it actually close the dialog (did nothing before)

Here are some screenshots. If you like it; I would commit it into the feature/passwords feature branch:

password_poor
password_weak
password_good
password_excellent

**Comment by droidmonkey** [comment]
Wow the new generator gui is a marked improvement!

**Comment by TheZ3ro** [comment]
By me this is fine, remember that you have also to fix the guitests if you changed the entropyLabel string.

And adding the Prevent saving password with Enter when the Generator is open feature will complete the PR (see my previous comment on it)

**Note** the PasswordGeneratorWidget was small because on <13' screen with low resolution the AddEntry window exceed the screen height. Check this problem before committing.

Thanks for the contribution

**Comment by Manko10** [comment]
OK, I will fix the GUI tested then and push the changes later today. 

Regarding the widget size: we can't optimize for such tiny screen sizes if that means that the interface looks ugly on all common (bigger)  screen sizes and the missing padding on the buttons was indeed very ugly. Looking at your screenshot, you maybe didn't really notice because your buttons have smaller padding anyway. But with my theme it was somewhat extreme.
If widget height really is serious usability issue (e.g. buttons not visible), then adjustments such as providing a scrollbar or forcefully changing the widget height should be done programmatically only when needed.

On a side node: we should look out a little for coding style consistency. The code contains a lot of if/else blocks in the format

. . if (true) {
. . } 
. . else {
. . } 

But according to the Qt style guide it should be

. . if (true) {
. . }  else {
. . }

**Comment by TheZ3ro** [comment]
On my laptop (1376x768) the in the AddEntry window, when opening the PasswordGenerator the bottom button goes off the screen. An alternative can be make a smaller Notes textarea.

For the ifs, they are ok 
It's not explicitly stated on the [KeePassXC CodingStyleguide](https://github.com/keepassxreboot/keepassxc/blob/develop/.github/CONTRIBUTING.md#coding-styleguide) or the QtStyleguide but [keepassx/keepassx](https://github.com/keepassx/keepassx/search?utf8=%E2%9C%93&q=else+%7B) use this sintax

**Comment by Manko10** [comment]
Let me quote the Qt coding style
```
// Wrong
if (codec) {
}
else {
}
// Correct
if (codec) {
} else {
}
```
https://wiki.qt.io/Qt_Coding_Style ;-)
For your screen size issue: that should be solved conditionally for small screen sizes and not by squishing controls on all resolutions. 
On Nov 22, 2016 10:00 AM, TheZ3ro <notifications@github.com> wrote:On my laptop (1376x768) the in the AddEntry window, when opening the PasswordGenerator the bottom button goes off the screen. An alternative can be make a smaller Notes textarea.
For the ifs, they are ok
It's not explicitly stated on the KeePassXC CodingStyleguide or the QtStyleguide but keepassx/keepassx use this sintax

**Comment by TheZ3ro** [comment]
Yeah, I was meaning that it's not mentioned by our Coding Style officially and it goes against Qt Coding style

> but [keepassx/keepassx](https://github.com/keepassx/keepassx/search?utf8=%E2%9C%93&q=else+%7B) use this sintax

> https://github.com/keepassx/keepassx/search?utf8=%E2%9C%93&q=else+%7B

On my screenshot it's not squished, depends also on DesktopEnvironment and theme

**Comment by Manko10** [comment]
Our coding style says that we use the Qt coding style. ;-)
Anyway, of course it depends on the widget style. As I said, you probably didn't notice it with your theme, but with the standard KDE Breeze theme the different paddings are kind of extreme. 
On Nov 22, 2016 10:25 AM, TheZ3ro <notifications@github.com> wrote:Yeah, I was meaning that it's not mentioned by our Coding Style officially and it goes against Qt Coding style

but keepassx/keepassx use this sintax


https://github.com/keepassx/keepassx/search?utf8=%E2%9C%93&q=else+%7B

On my screenshot it's not squished, depends also on DesktopEnvironment and theme

**Comment by TheZ3ro** [comment]
I agree with you, our stylecode is an "exact" copy of KeePassX's one, the original maintainer did all the ifs "wrong" by not specifying the else stylecode.

I think it's "useless" to argue over this small things, we are a team.

We need to prepare the 2.1.0 release https://groups.google.com/forum/m/#!topic/keepassx-reboot/zUjprJD2LVI

**Comment by droidmonkey** [comment]
Please leave the if/else syntax to another day, I don't like the newline else either.

As for screen height issue, this should be addressed in a different PR if it's an issue across the GUI. Minimal/no padding in user interaction buttons is generally not the solution to that problem.

**Comment by Manko10** [comment]
Alright, I pushed the changes now. Please look over them and report back any issues you have. Please also check specificly if you have any inconsistent password field heights. I set fixed heights for the password fields and the visibility toggle button, because toggling that button caused the layout to wiggle slightly.

I also updated the testEntryEntropy() unit test. I did not fix the failing testDeleteEntry() test, though. That test is not affected by my changes and was failing before.

**Comment by TheZ3ro** [comment]
I indeed like the new UI.

This are my note:
- If I open KeePassXC form a terminal, the terminal keep printing `QFont::setPixelSize: Pixel size <= 0 (0)`
- The minimum size for password fields and visibility buttons is too big on my theme (see screenshot below)
- The AddEntry window on 1360x768 screen is too big (see screenshot below, the bottom button are barely visible, this can be fixed with a scrollbar or resizing the Notes text area)

[Screenshot](https://cloud.githubusercontent.com/assets/686894/20538158/444e9544-b0f0-11e6-9c01-634a020c7532.png)

---

Can you report what test fail in an Issue? Because on TravisCI and on my PC all tests are *Passed*

**Comment by Manko10** [comment]
Well, that's what I feared. Password fields have the wrong height on different themes.
I guess I have to look at what changed in develop and solve the jumpy layout in a different way. :-\

The size issue on your screen should indeed be fixed with a conditional scroll bar. But I would suggest you open another issue for that so we can address it in a separate pull request.

The GUI test that fails is

```
FAIL!  : TestGui::testDeleteEntry() Compared values are not the same
   Actual   (groupView->currentGroup()->name())     : "NewDatabase"
   Expected (m_db->metadata()->recycleBin()->name()): "Recycle Bin"
   Loc: [../tests/gui/TestGui.cpp(344)]
```

It fails for me on this branch and on develop. If you don't have any fails, make sure the GUI tests are actually run. You need to enable the CMake option WITH_GUI_TESTS and then rebuild for the GUI tests to be run at all.

**Comment by TheZ3ro** [comment]
For the jumpy layout it's caused by the Font change when changing the EchoMode of PasswordEdit in `PasswordEdit::updateStylesheet()`.
Adding a `stylesheet.append("font-size: 10pt; ");` on line 63 seems to help a little bit but doesn't fix it.

Can you fix the `QFont::setPixelSize: Pixel size <= 0 (0)` warning that continuously print on terminal?

Obviously I have GUI tests turned on (they are turned on also on TravisCI)
```
$ ./tests/gui/testgui

********* Start testing of TestGui *********
Config: Using QtTest library 5.5.1, Qt 5.5.1 (x86_64-little_endian-lp64 shared (dynamic) release build; by GCC 5.4.0 20160609)
[...]
Totals: 17 passed, 0 failed, 0 skipped, 0 blacklisted
********* Finished testing of TestGui *********
```

**Comment by Manko10** [comment]
Yeah, indeed. The culprit is in PasswordEdit::updateStylesheet(). There the font family is changed between default and monospace depending on which echo mode is on. That of course causes the QLineEdit to change its height. I wonder if we really need monospace fonts. If we want to keep it like that I would at least try to experiment a little with font metrics.
The strange thing is that the height changes don't appear in the PasswordGeneratorWidget, for whatever reason. But there the QLineEdit is a few pixels larger, although everything is set to default.

For now I committed the QLineEdit height fix reversal and a fix for the QFont warning. Please check.

**Comment by Manko10** [comment]
oh, well, I see. The one in the PasswordGeneratorDialog is just a plain QLineEdit, not a PasswordEdit. That does not explain, why it's a few pixels larger, but it explains why it's not changing its height.

**Comment by TheZ3ro** [comment]
Yes, the warning is fixed.

I think the monospace is good for letters like `I` and `l` (instead of Il). 
So why we don't do the opposite, We can apply the monospace font also when the password is dotted (EchoMode=Password). 
I've tried it and works fine (no more jumpy UI)

**Comment by Manko10** [comment]
Yes, it works, but the dots of my default monospace font look a little too fat with too little letter spacing on my system. The sans-serif ones look nicer. However, I couldn't find any other working solution. Setting the QLineEdit max-height according to the font metrics gets rid of the size changes, but I crop the text field border with that approach and setting line-height vis CSS seems to have no effect.

Unfortunately, also letter-spacing doesn't work in Qt CSS, so now I just set it to the default monospace font without further adjustments. I can probably get used to it. It's not as nice as the smaller dots of the default font, but it's better than wiggly layouts.

**Comment by TheZ3ro** [comment]
Yes, also on my font the letter spacing is not so good but I think we can deal with it.

I think we are ready for a review/merge. I've reviewed @Manko10 code and it's good.
Ping @droidmonkey

**Comment by Manko10** [comment]
Actually, I just moved the font setting out of the stylesheet and used a QFont object instead on which I can set proper letter spacing. That way I can even retrieve the default monospace font via QFontDatabase and can get rid of this ugly OS X monospace fix as well (from which I don't even know if it's needed anymore). A nice side effect is also that I now get "Noto Mono" which is my DE's default monospace font instead of something like DejaVu Sans Mono which just happens to be aliased to "monospace".

**Comment by TheZ3ro** [comment]
Tested on my Linux and it works fine.
Maybe a test on MacOS to be sure? (but I think it should work fine)

**Comment by Manko10** [comment]
I would if I had one. But I can't imagine that Qt provides a dedicated system font abstraction when it doesn't work on all platforms. I also can't find any related issues with a quick Google search.

BTW I applied the letter spacing to both echo modes. I thought if we are already using a different font to make individual characters more legible, we might as well space the them out a little.

**Comment by TheZ3ro** [comment]
Tested on macOS Sierra, all gui/tests are passed.

this is a screenshot. Maybe increasing a little the fontsize for labels under the progressbar?
virtualbox_macos sierra_22_11_2016_23_49_35

**Comment by Manko10** [comment]
Wow, does KeePassXC really look that ugly on OS X? :-D
The font size problem is non-trivial. It's set to 8px font size which is 80% of my 10px default font size. HOwever, if your default font size is much larger, the relative size becomes much smaller. Unfortunately, it's not possible to specify relative font sizes via the QWidget font size setting or via stylesheets. Therefore the only solution would be to set it in C++ which is kind of an ugly solution.

**Comment by TheZ3ro** [comment]
I think it's the default QT style :thinking: 

Setting font-size to 9px is too big?

**Comment by Manko10** [comment]
There is no "default Qt style". The font size depends on what you have configured on your system. If there is no explicit override in the *.ui file, widgets use the system's default font size. That is also what the Qt designer shows you. So there is a difference in the designer between a font size of 10 and a font size of 10 in bold numbers. The latter is an explicit override and will always be 10 while the other may also be something else when you change your system's default font size.

In our case that means that the 8pt are always 8pt while the rest around may have a larger font size which makes the entropy and quality label look smaller compared to the rest.

I pushed another commit where I set the label font size dynamically to 80% in the constructor. Please test.

**Comment by TheZ3ro** [comment]
>> Wow, does KeePassXC really look that ugly on OS X? :-D
>
> I think it's the default QT style :thinking:

I was referring to the ugly GUI no MacOS X. I will test ASAP

**Comment by Manko10** [comment]
Ah, yeah. Well, it's ugly. Kinda surprised it is, since Qt is really the only framework that produces GUIs which looks native an almost any platform (not like shitty GTK+ or Mono with WinForms). But I guess we're just using widgets which are uncommon on OS X such as the toolbar at the top.

**Comment by TheZ3ro** [comment]
Tested on macOS and the visibility is improved a lot. Now it's ok and readable.

**Comment by droidmonkey** [comment]
Does Qt allow for scaled fonts like the equivalent 'em' in CSS world?

**Comment by Manko10** [comment]
No, it does not. Unfortunately. Using em units is generally possible,
but not for font sizes.

**Comment by droidmonkey** [comment]
I've reviewed the GUI and most of the code, looks great. Excellent work @TheZ3ro and @Manko10 your contributions are huge in this PR. I am squash-merging this into develop.

**Comment by Manko10** [comment]
Any specific reason for squash merge? I think having the full history on develop can only be beneficial. With squash merges we only lose all the advantage we get from small atomic commits. If at any time we need to bisect a feature, we have a lot more code to look through.

**Comment by droidmonkey** [comment]
This is true, I probably should have squashed some of the intermediate commits only. I'll take that into consideration next time. I am a big fan of a clean history though and this code was well tested with test cases developed and implemented.

**Comment by Manko10** [comment]
And of course people want their contributions being counted on their profile. ;-)

**Pull request merged**
