### PR TITLE
Move CsvParser to format/

### PR DESCRIPTION
**Pull request by louib**
@droidmonkey would like your opinion on this.

I moved the `CsvParser` to `format/`, since this is where all the parsing is done. Should we rename it `CsvImporter` to be consistent with the other importer/exporter classes?

For the `HtmlExporter` class, it has a dependency on `QPixmap`, which means we won't be able to remove the dependency on `Qt::Widget` if it stays in `format/`. The other option would be to not render the icons in the html export.

### CODE REVIEW

**Comment by droidmonkey** [comment]
Need to move the icon handling out of Entry and Group before we can merge this one. I reverted the move of HtmlExporter, once icon handling is moved out you can convert the QByteArray directly to base64 instead of going from Pixmap to QByteArray to Base64.

**Comment by louib** [comment]
> I reverted the move of HtmlExporter, once icon handling is moved out you can convert the QByteArray directly to base64 instead of going from Pixmap to QByteArray to Base64.

I had another look at that and I'm not sure it's going to be that easy. When exporting the images in the `HtmlExporter` we set a specific size `group.iconPixmap(IconSize::Medium)`. I'm not sure we can do that with a `QByteArray` without using `QIcon` or `QImage`. Unless of course we just dump the original image, without specifying a size.

**Comment by louib** [comment]
@droidmonkey here's another problem with keeping that here: that would prevent us from moving the `DatabaseIcons` class to `src/gui`, because we would need access to the raw default icons from `src/format` to print them in the html dump. That would mean converting `DatabaseIcons` to storing `QByteArray` specifically for that use-case.

**Comment by louib** [comment]
@droidmonkey Do you see a problem with making the `HtmlExporter` a GUI only feature, at least for now? This is already the case anyway (not available from the CLI), and I think this is what we'll have to do if we want to avoid splitting the `DatabaseIcons` in 2 (one core class with the raw `ByteArray`s, and one GUI class with the `QPixmapCache`).

**Comment by droidmonkey** [comment]
Yah I am OK with that

**Comment by louib** [comment]
@droidmonkey I that case I think we can merge this one, and I'll migrate the `HtmlExporter` in the next PR, which will remove the rest of the `QIcon` handling from `src/core`.

**Review by droidmonkey — APPROVED** [review]

**Comment by droidmonkey** [comment]
@louib we can finish this work after the Botan PR is merged in.

**Pull request merged**
