### PR TITLE
Clear combo box before adding elements. Fixes #4321.

### LINKED ISSUE #3713: Locked status in tab not correctly visible
I have multiple databases. On first open, the first tab show correct locked status, the second do not.

Both are locked
image

After i close a database (CTRL+F4 or close with icon in tab) and re-open it (not lock/nlock) all show as unlocked in the tabs but they aren't. 
image

If i just lock all opened databases (CTRL+L), than the status in the tab show correct "[Locked]".

I am not sure if this behaviour has changed in 2.5.0. But this issue confused me a bit because i assumed that all my databases are unlocked and my browser extension has some bugs. But in the end, it was just a locked database that i don't saw correctly in KPXC.

	KeePassXC - Version 2.5.0
	Revision: 1ab8a9f

	Qt 5.13.1
	Diagnosemodus ist deaktiviert.

	Betriebssystem: Windows 10 (10.0)
	CPU-Architektur: x86_64
	Kernel: winnt 10.0.17134

	Aktivierte Erweiterungen:
	- Auto-Type
	- Browser-Integration
	- SSH-Agent
	- KeeShare (bestätigtes und unbestätigtes Teilen)
	- YubiKey

	Kryptographische Bibliotheken:
	 libgcrypt 1.8.5

### LINKED ISSUE #4321: Duplicated entries in the Key File dropdown list
## Expected Behavior
There should be only unique or distinct entries in the Key File selection dropdown.

## Current Behavior
Duplicated entries are displayed in the dropdown
snapshot

## Possible Solution
Unknown

## Steps to Reproduce
1. Launch KeePassXC with database pre-selected
2. Click on the Key File dropdown.

## Context
This bug does not affect usability but it's just a bit annoying to see duplicated entries

## Debug Info
KeePassXC - 2.5.3
Operating system: macOS Mojave 10.14.6

### PR DESCRIPTION
**Pull request by HongmouZhang**
## Type of change
[NOTE]: # ( Please remove all lines which don't apply. )
- ✅ Bug fix (non-breaking change which fixes an issue)

## Description and Context
[NOTE]: # ( Describe your changes in detail, why is this change required? )
[NOTE]: # ( Describe the context of your change. Explain large code modifications. )
[NOTE]: # ( If it fixes an open issue, please add "Fixes #XXX" as necessary )
Clear the combo box of key file before adding elements. 
The reason of #4321 comes from several sources. In the application initialization phase, the following code
```c++
if (m_db->isInitialized()) {
        switchToMainView();
    } else {
        switchToOpenDatabase();
    }
```
from DatabaseWidget constructor calls switchToOpenDatabase() to load last key file from configuration file. Straight after the calling, the member function DatabaseWidget::showEvent calls switchToOpenDatabase() again, which causes duplicated entries in Key File dropdown. I saw the above code in constructor is introduced to fix the issue 3713. 

But this is not the only one reason for #4321. If there are more than two unlocked database tabs, once I click the locker to lock all of them, the member function DatabaseWidget::lock() will be called, which fills Key File dropdown entries for all of the database tabs. For the current tab, everything is fine, once I switch to another tab, the member function DatabaseWidget::showEvent will be called, consequently fills the dropdown entries for the newly shown tab again. As a result, the dropdown entries of Key File are duplicated.

For solving the problem, the easiest way is to simply clear the form before fill it.

Fixes #4321.

## Screenshots
[TIP]:  # ( Do not include screenshots of your actual database! )

## Testing strategy
[NOTE]: # ( Please describe in detail how you tested your changes. )
[TIP]:  # ( We expect new code to be covered by unit tests and documented with doc blocks! )
Manually.

## Checklist:
[NOTE]: # ( Please go over all the following points. )
[NOTE]: # ( Again, remove any lines which don't apply. )
[NOTE]: # ( Pull Requests that don't fulfill all [REQUIRED] requisites are likely )
[NOTE]: # ( to be sent back to you for correction or will be rejected.  )
- ✅ I have read the **CONTRIBUTING** document. **[REQUIRED]**
- ✅ My code follows the code style of this project. **[REQUIRED]**
- ✅ All new and existing tests passed. **[REQUIRED]**
- ✅ I have compiled and verified my code with `-DWITH_ASAN=ON`. **[REQUIRED]**

### CODE REVIEW

**Comment by droidmonkey** [comment]
We don't want to do this because every time you switch tabs (and maybe even on window switching) you'll clear the login form which will wipe out any password you entered or what not. The real answer here is to not reload the form on show but also clear it before loading it as well.

**Comment by droidmonkey** [comment]
I am closing this because this will be rolled into a larger refactor of the open widget process.

**Comment by HongmouZhang** [comment]
I understand the point. But actually this is the current behavior of 
KeepassXC. Once you unlock a database, or switch database tab, the 
function DatabaseOpenWidget::hideEvent is called and inside this 
function, the clearForms() is always called. So as a result, for the 
current version, the key combo box cannot keep any path of key files but 
the last one.

So for my code, I think this is the simplest solution for the current 
version without introduce any disadvantage. If you want to keep all the 
past keys, then you have to refactor hideEvent, showEvent, etc. If you 
are planing to do that, I agree that would be a better solution than my PR.

**Comment by droidmonkey** [comment]
Yes the hide/show interactions are crazy convoluted. Clearing forms should be explicit.

**Pull request closed without merging**
