### PR TITLE
Fix CLI man page and change both man pages

### PR DESCRIPTION
**Pull request by sorairolake**
[TIP]:  # ( Provide a general summary of your changes in the title above ^^ )

## Type of change
[NOTE]: # ( Please remove all lines which don't apply. )
- ✅ Documentation (non-code change)

## Description and Context
[NOTE]: # ( Describe your changes in detail, why is this change required? )
[NOTE]: # ( Describe the context of your change. Explain large code modifications. )
[NOTE]: # ( If it fixes an open issue, please add "Fixes #XXX" as necessary )
- Fix lacking commas between short and long option names (e.g. `-l` and `--lower`) in the generate options section of CLI man page, and fix a typo in groff command.
- Changed command and option names in man page to bold. Because it's easier to understand than if it's not bold.

## Checklist:
[NOTE]: # ( Please go over all the following points. )
[NOTE]: # ( Again, remove any lines which don't apply. )
[NOTE]: # ( Pull Requests that don't fulfill all [REQUIRED] requisites are likely )
[NOTE]: # ( to be sent back to you for correction or will be rejected.  )
- ✅ I have read the **CONTRIBUTING** document. **[REQUIRED]**

### CODE REVIEW

**Comment by sorairolake** [comment]
`share/docs/man/keepassxc-cli.1` seems to be updated in #4231, but should I do something to this to match the changes in 6765c979?

**Comment by louib** [comment]
@droidmonkey can we get this one merged? This way we can rebase and use the new man page styling in the currently opened CLI PRs.

**Comment by droidmonkey** [comment]
Sure thing

**Comment by sorairolake** [comment]
Thank you😊

**Pull request merged**
