### PR TITLE
Remove useless bounds on delay and key-repetition

### LINKED ISSUE #216: Delays > 10000 are quietly discarded
The "safety-checks" in https://github.com/keepassxreboot/keepassxc/blob/develop/src/autotype/AutoType.cpp#L384 and https://github.com/keepassxreboot/keepassxc/blob/develop/src/autotype/AutoType.cpp#L388 don't really make sense to me.

## Expected Behavior
If I enter a autotype sequence with '{delay 10001}' I expect it to wait for 10001ms.
If I enter '{left 101}', I expect it to type left 101 times.

Alternatively there should be some sort of warning that these values are invalid.

## Current Behavior
Delays greater than 10000 and repetitions greater than 100 are silently ignored.

## Possible Solution

Remove the checks or show a warning when these values are entered.
Alternatively go the same way as in https://github.com/keepassxreboot/keepassxc/blob/develop/src/autotype/AutoType.cpp#L370 and enforce bounds for the values. Although I think this isn't a good solution either as it quietly disobeys the users instructions.

### PR DESCRIPTION
**Pull request by datamaan**
Fixes  #216

### CODE REVIEW

**Comment by TheZ3ro** [comment]
Why have you deleted the PR template?

I don't think removing those boundaries is generally a good idea. 

There are some problem with this:
- If Delay is > to max_int, toInt() line 377 will fail and num will be set to 0
- If Delay is > db locking time the database will lock and won't perform the autotype
- If users change focus when waiting for the delay, the action won't be performed

Also if we want to inform the user that his delay/repetition is invalid, we can do it only when autotype is triggered. 
This should probably be converted to https://github.com/keepassxreboot/keepassxc/blob/develop/src/autotype/AutoType.cpp#L370

**Comment by droidmonkey** [comment]
The bounds are there to ensure user entered data doesnt degrade the application. Is there a single use case where you need to wait more than 10 seconds or type more than 100 times. Thought cases dont count.

**Comment by phoerious** [comment]
I agree with both of you: having some limits is good for not letting the user accidentally do stupid stuff. However, as they are implemented now they are kind of arbitrary and a proper error message would better than just silently doing something the user did not configure.

**Comment by TheZ3ro** [comment]
The only problem is that the autotype sequence will be evaluated only when it's performed.
We can't display an error when the user save the entry with such a sequence. We can display the error when the user perform autotype with that sequence

**Comment by droidmonkey** [comment]
You could run the sequence through a syntax checker, but that just made the code that much more complicated...

I am closing this PR since it is not a satisfying fix for the underlying issue of silent rejection.

**Pull request closed without merging**
