### PR TITLE
Activating Open Collective

### PR DESCRIPTION
**Pull request by monkeywithacupcake**
Hi, I'm making updates for Open Collective. Either you or a supporter signed this repo up for Open Collective. This pull request adds backers and sponsors from your Open Collective https://opencollective.com/keepassxc ❤️
  
  It adds two badges at the top to show the latest number of backers and sponsors. It also adds placeholders so that the avatar/logo of new backers/sponsors can automatically be shown without having to update your README.md. [[more info](https://github.com/opencollective/opencollective/wiki/Github-banner)]. See how it looks on [this repo](https://github.com/apex/apex#backers).
You can also add a "Donate" button to your website and automatically show your backers and sponsors there with our widgets. Have a look here: https://opencollective.com/widgets

  P.S: As with any pull request, feel free to comment or suggest changes. The only thing "required" are the placeholders on the README because we believe it's important to acknowledge the people in your community that are contributing (financially or with code!).

  Thank you for your great contribution to the open source community. You are awesome! 🙌
  And welcome to the open collective community! 😊

  Come chat with us in the #opensource channel on https://slack.opencollective.com - great place to ask questions and share best practices with other open source sustainers!

### CODE REVIEW

**Comment by Throne3d** [comment]
You seem to have worked off develop for this commit, and yet opened the pull request against master.

This also looks sort of… spammy… as a pull request…

**Comment by monkeywithacupcake** [comment]
Sorry. I don't know how to give you all of the updates and information without automating parts of it. You can use the PR to update wherever it best works for you. We always try to push to master.

**Comment by Throne3d** [comment]
(I'm not actually a proper dev of this project, I've only posted a few changes and follow the IRC channels.)

**Comment by monkeywithacupcake** [comment]
Also, it may make sense to just keep the readme changes.

**Comment by droidmonkey** [comment]
Way too many emojis. I think we should add a _small_ section in our Readme that outlines the donation options. I do not want to add the excessive amount of open collective pr0n though,

**Comment by monkeywithacupcake** [comment]
Very reasonable. Some folks just use the badges at the top of the readme and then a little "If you want to contribute... with a link to their Open Collective page"

**Pull request closed without merging**
