### PR TITLE
Add YubiKey support on CLI.

### PR DESCRIPTION
**Pull request by louib**
Add YubiKey support for the CLI with the `-y`, `--yubikey` option.

Added the `YubiKey::isBlocking` function, partly extracted from `detect`, so that the yubikey detection code could be reused from the GUI and the CLI. Also added more specific error messages by handling more specific yubikey errors.

## Type of change
[NOTE]: # ( Please remove all lines which don't apply. )
- ✅ Refactor
- ✅ New feature

## Description and Context
https://github.com/keepassxreboot/keepassxc/issues/2451

## Testing strategy
Locally + unit tests

## Checklist:
[NOTE]: # ( Please go over all the following points. )
[NOTE]: # ( Again, remove any lines which don't apply. )
[NOTE]: # ( Pull Requests that don't fulfill all [REQUIRED] requisites are likely )
[NOTE]: # ( to be sent back to you for correction or will be rejected.  )
- ✅ I have read the **CONTRIBUTING** document. **[REQUIRED]**
- ✅ My code follows the code style of this project. **[REQUIRED]**
- ✅ All new and existing tests passed. **[REQUIRED]**
- ✅ I have compiled and verified my code with `-DWITH_ASAN=ON`. **[REQUIRED]**
- ✅ My change requires a change to the documentation, and I have updated it accordingly.
- ✅ I have added tests to cover my changes.

### CODE REVIEW

**Comment by droidmonkey** [comment]
This is just a note, but there has got to be a better way of handling these common command line options than updating every single file. Perhaps now (or in the --no-password PR) we should introduce a shared function that adds all the common parameters given a parser argument.

**Comment by louib** [comment]
@droidmonkey I :100: agree, and this is the next refactoring I have in mind for the CLI. I'm going to add a `DatabaseCommand` class to the `Command` hierarchy to centralize the unlocking code for the commands that deal with a db.

**Comment by droidmonkey** [comment]
Targeting this for 2.5.0 since it is a pretty large change.

**Comment by louib** [comment]
@droidmonkey alright! I rebased the PR on develop!

**Comment by louib** [comment]
@droidmonkey I'm going to split this PR in 2 as I realize it's quite large to review, and the small yubikey core part of the patch can be beneficial by itself.

**Comment by droidmonkey** [comment]
Sounds good to me!

**Pull request closed without merging**
