### PR TITLE
Add support for Visual Studio build

### LINKED ISSUE #4582: Compile Windows version with CFG enabled
## Summary
Please consider compiling Windows version of KeePassXC with [control flow guard](https://docs.microsoft.com/en-us/windows/win32/secbp/control-flow-guard) enabled.

## Desired Behavior
CFG enabled.

## Possible Solution
Use MS Visual Studio for the build process of Windows version end [enable `/guard:cf` flag](https://docs.microsoft.com/en-us/cpp/build/reference/guard-enable-control-flow-guard?view=vs-2019)

## Context
CFG is amongst techniques used by MS to defend against ROP / memory corruption.  
This seems to be relevant in context of the application that acts as the central secrets storage.

### PR DESCRIPTION
**Pull request by smlu**
This PR adds CMake build support for Visual Studio 2017 and newer. ~~This build system doesn't require MSYS2 to be installed or used on Windows to successfully compile. All required dependency can be build using Visual Studio with exception to `libgcrypt` and `libgpg-error` for which a port for VS has to be used. For example, [ShiftMediaProject](https://github.com/ShiftMediaProject) port for [libgcrypt](https://github.com/ShiftMediaProject/libgcrypt) and [libgpg-error](https://github.com/ShiftMediaProject/libgpg-error).~~
All KeePassXC modules successfully compile, run and work using this build system on Windows (e.g.: browser, sshagent, autotype, networking, updatecheck, keeshare). Please note, *sshagent* future was tested in app but was not tested with actually `ssh-agent`. The only not tested module is *yubikey*. I don't posses a YubiKey at the moment so I decided to skip this module and a future modification might be needed in order for this module to compile and/or run on Windows using this build system.
This build system also compiles with additional security compile flags [/DYNAMICBASE](https://docs.microsoft.com/en-us/cpp/build/reference/dynamicbase-use-address-space-layout-randomization?view=msvc-160), [/guard:cf](https://docs.microsoft.com/en-us/cpp/build/reference/guard-enable-control-flow-guard?view=msvc-160), [/GS](https://docs.microsoft.com/en-us/cpp/build/reference/gs-buffer-security-check?view=msvc-160) and linker flags [/NXCOMPAT](https://docs.microsoft.com/en-us/cpp/build/reference/nxcompat-compatible-with-data-execution-prevention?view=msvc-160) & [/guard:cf](https://docs.microsoft.com/en-us/cpp/build/reference/guard-enable-control-flow-guard?view=msvc-160) when in release mode. This fixes issue #4582. 

On the code side, a slight modification of existing CMake project and some of the `.cmake` modules had to be made to account for MSVC compiler and specific things related to building with VS compiler. The source code of KeeePassXC was not refactored much, only added or removed some of windows related macros here and there. 
~~The biggest modification done to the CMake projects that also effects other build systems was made to `Findsodium.cmake` module and how `libsodium` is linked into the project. On Windows a macro `SODIUM_STATIC` has to be defined to properly import symbols from static library but at the moment this macro is not defined by current build system. Because `Findsodium.cmake` module already defines `SODIUM_STATIC` macro for `sodium` package a decision was made to refactor all CMake projects to link against sodium library via `sodium` package, opposite to linking directly to library constant `${sodium_LIBRARY_RELEASE}`. This change successfully then links libsodium library and defines all necessary macros. Please note, due to constants `sodium_LIBRARY_DEBUG` and `sodium_DLL_DEBUG` were not used anywhere in the project, they were removed from `Findsodium.cmake`, and constants `sodium_LIBRARY_RELEASE` & `sodium_DLL_RELEASE` were renamed to `sodium_LIBRARY` and `sodium_DLL`.~~

fix #4582 

## Testing strategy
Tests were run only for Visual Studio compiled builds and not for MinGW or other builds.
All test have passed successfully for debug and release mode. 
Note:  For some tests warnings were encountered.
 

## Type of change
- ✅ Bug fix (non-breaking change that fixes an issue)
- ✅ Refactor (significant modification to existing code)

### CODE REVIEW

**Comment by droidmonkey** [comment]
Awesome!

**Comment by phoerious** [comment]
Fantastic. I hope that also makes it easier to use the newer Windows API features, which are not available in windows.h.

**Comment by smlu** [comment]
My next plan is to explore windows [CNG](https://docs.microsoft.com/en-us/windows/win32/seccng/about-cng) API and see if any of possible storage providers (SW, TPM, Windows Hello) can be used to store master key (as some of KeePass plugins do). An later, try to use CNG API to load master key in and decrypt DB without exposing master key in KeePassXC memory.

Btw, I see 2 checks have failed should I try to fix them?

**Comment by droidmonkey** [comment]
Run `make format`. Ignore the Linux one, random failure.

**Comment by droidmonkey** [comment]
It would be good to add a cmake variable to define the library directory that contains argon2, libsodium, gcrypt, etc.

**Comment by smlu** [comment]
> 
> 
> I am getting very serious about replacing libgcrypt, libsodium (to a lesser extent), and Argon2 with Botan.

Thumbs up for this! Botan is great c++ cryptography library. And having less dependency to worry about is I guess plus from security stand point. My next issue was just about asking why any of the well known c++ cryptography library like Botan or CryptoPP wasn't used in this project :)

**Comment by droidmonkey** [comment]
I toyed with it this morning and am committing to Botan. It's about time and there is broad support in all package managers except Xenical, but a PPA can cover that case.

**Comment by droidmonkey** [comment]
This depends on #6209 merge

**Comment by smlu** [comment]
I'll update this PR once #6209 is merged.

**Comment by droidmonkey** [comment]
Use a rebase

**Comment by droidmonkey** [comment]
I have not forgotten about this. I think we're ready to incorporate.

**Comment by droidmonkey** [comment]
One more blocker on this one, Yubikey libraries are not available in vcpkg. Going to be removing that dependency anyway since they are deprecated by Yubikey and I want to have a better API when access the keys. Plan is to move the relevant code directly into KPXC.

**Comment by droidmonkey** [comment]
#6654 is posted, once merged we can get visual studio merged. This PR will need a setup guide included to get vcpkg and everything else squared away.

**Comment by smlu** [comment]
Once the #6654 is merged, I'll try to squeeze in the setup docs as soon as I'll be able to. Somebody else will also probably have to write the guidance for yubikey part (I still haven't got one).

**Comment by droidmonkey** [comment]
Yubikey will work without any special actions after the other pr is merged. I am currently trying to fix the install command, msvc is no playing nice with cmake bundle tools.

**Comment by smlu** [comment]
Oh, that's great. Unfortunately, I'm a little bit busy at the moment, but please let me know if I can help you with anything.

**Comment by droidmonkey** [comment]
Same here, we'll get there

**Comment by droidmonkey** [comment]
Whewww finally got everything working!

The magic variable to install dependencies is `-DX_VCPKG_APPLOCAL_DEPS_INSTALL=ON`

Need to incorporate msvc into the release tool and then this can be merged.

**Comment by smlu** [comment]
Fantastic! I'll try to find some time this weekend and test final version.

**Comment by droidmonkey** [comment]
Release tool updated, we are good to go now!

`./release-tool build -v 2.7.0 --snapshot --vcpkg "/c/vcpkg/scripts/buildsystems/vcpkg.cmake" --cmake-generator "Visual Studio 16 2019" -m "-m"`

**Review by droidmonkey — APPROVED** [review]
Finished up the last minor issues when building a release package. This is ready to merge.

**Comment by smlu** [comment]
Finally got the chance to fully test the final (already merged) version of this PR.
I had no problem building the release and debug version using dependency libraries from the system but found 1 bug in [FindQuaZip.cmake](https://github.com/keepassxreboot/keepassxc/blob/develop/cmake/FindQuaZip.cmake#L8) when using `vcpkg` package manager. The `vcpkg` installs `quazip` as `quazip5.lib` so the the call to `find_library` in [FindQuaZip.cmake](https://github.com/keepassxreboot/keepassxc/blob/develop/cmake/FindQuaZip.cmake#L8) should look for names `libquazip5` and `quazip5`. Also in `vcpkg` case when running compiled KPXC I had to rename `quazip5.dll` to `quazip1-qt5.dll`.

**Comment by droidmonkey** [comment]
I am removing quazip in a future PR that is why I left it alone.

**Comment by smlu** [comment]
Oh, I wasn't aware of that. 
Ok other than that everything works as expected.

**Pull request merged**
