### PR TITLE
Convert all svgz to svg

### LINKED ISSUE #2112: Use plain SVG version of icon instead of compressed ones
## Expected Behavior
Have SVG version of icons instead of compressed ones.

## Current Behavior
The KeePassXC scalables icons are using an Inkscape specific version of the SVG format and that format is compressed.

The uncompressed SVG file version is so small that there is no point in using the compressed version.

Compressed version of SVG are usually useful when there are multiples path and polygons to draw. The KeePassXC icon is so simple that compression isn't needed.

## Possible Solution
Simply open the existing icon in Inkscape and save them as Plain SVG.

Remove unneeded definitions first via `File` > `Cleanup document...`.

## Steps to Reproduce (for bugs)
N/A

## Context
Not having an SVG version prevent users to use this icon directly and prevents the icon from being displayed directly from a web browser.

This also prevent app stores like Chocolatey to update it.

## Debug Info
N/A

### PR DESCRIPTION
**Pull request by wget**
## Description
Fixes #2112

## Motivation and context
Like explained in the ticket, compressed svgz is hard to maintain and cannot be displayed from a browser. Packagers would like to rely on these svg to update automatically application icons without the need to open Inkscape and convert manually.

## How has this been tested?
Don't know whether this has an impact on compilation. The app is using bitmaps version any way AFAIK. Waiting for CI (or any) to prove I'm wrong.

## Types of changes

- ✅ Bug fix (non-breaking change which fixes an issue)
- ✅ New feature (non-breaking change which adds functionality)
- ✅ Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- ✅ I have read the **CONTRIBUTING** document. **[REQUIRED]**
- ✅ My code follows the code style of this project. **[REQUIRED]**
- ✅ My change requires a change to the documentation and I have updated it accordingly.
- ✅ I have added tests to cover my changes.

### CODE REVIEW

**Comment by droidmonkey** [comment]
This might explain the issues i was having with svg icons in the snap

**Comment by hifi** [comment]
For what it's worth they are just gzip compressed so you could `gunzip` the svgz files. Inkscape is not strictly needed but you did say you did some cleanup as well.

**Comment by wget** [comment]
@hifi Yes, actually I ported the SVG image to the new color/dpi rendering of Inkscape and asked Inkscape to remove unneeded definitions of elements which allowed me to reduce some gunzipped file considerably.

**Comment by wget** [comment]
@droidmonkey What do you mean by that? You were experiencing issues in the snap because of my pull request or the reverse order: you were already experiencing issues because of compressed svg icons?

**Comment by droidmonkey** [comment]
reverse order

**Pull request merged**
