### PR TITLE
Make notes hidden by default

### PR DESCRIPTION
**Pull request by grim210**
## Description
I prefer the notes section to be fixed width (#540).  When searching for an issue on the issue tracker, I found #342, which seems like it would be easy to fix while I was working on my own issue.  Overall, it was a simple fix for both.

## Motivation and context

Commit 636b3a0 fixes the issue that I created: #540.
Commit b9531a7 fixes issue #342.

## How has this been tested?
Tried on existing database (my personal one, a few years old), and on a fresh database that was created for the screenshots below.  Notes persisted through save.  Disabling the notes after writing them does not erase them.

Tested on Ubuntu MATE 16.04.2 amd64, with Qt 5.5.1.  All tests in the 'tests' directory were passed (except the YubiKey ones; I don't have one).  There were no apparent side effects during testing.

## Screenshots (if appropriate):
This is what the entry looks like by default:
keepassxc_disabled_notes

When the notes section has been enabled, it looks like this:
keepassxc_monospace_notes

## Types of changes
- ✅ Bug fix (non-breaking change which fixes an issue)
- ✅ New feature (non-breaking change which adds functionality)

## Checklist:

- ✅ I have read the **CONTRIBUTING** document. **[REQUIRED]**
- ✅ My code follows the code style of this project. **[REQUIRED]**
- ✅ All new and existing tests passed. **[REQUIRED]**
- ✅ I have compiled and verified my code with `-DWITH_ASAN=ON`. **[REQUIRED]**

### CODE REVIEW

**Comment by droidmonkey** [comment]
I'm deferring this to 2.3.0 since it is niche and there may be betters ways to address the visibility issue.

**Comment by grim210** [comment]
I see the "needs work" tag was added. Is there anything I need to fix that would prevent the code from being merged as-is?

**Comment by phoerious** [comment]
Only what @droidmonkey wrote.

**Comment by droidmonkey** [comment]
The issue with the current implementation is that the feature is on by default and is hard to "discover". When the notes are hidden, the text area should be replaced with a simple note that states "Notes are hidden, show them by clicking the checkbox to the left".

I do not agree that the checkbox should be unchecked by default, but rather a configuration option added (default to SHOW NOTES).

**Comment by louib** [comment]
@grim210 I think all that's left here would be to add the default to the config. @droidmonkey is that right?

**Comment by droidmonkey** [comment]
I agree looks good, just need a config option.

**Comment by TheZ3ro** [comment]
@grim210 is this still under development or can I continue it myself?

**Comment by droidmonkey** [comment]
Its all you

**Comment by TheZ3ro** [comment]
Closed in favor of #1124 since I can't add commit to this PR :)

**Pull request closed without merging**
