### PR TITLE
Show "New Entry" in the context menu even if an item is selected

### PR DESCRIPTION
**Pull request by lshman**
[TIP]:  # ( Provide a general summary of your changes in the title above ^^ )

## Type of change
- ✅ New feature (non-breaking change which adds functionality)

## Description and Context
[NOTE]: # ( Describe your changes in detail, why is this change required? )
[NOTE]: # ( Describe the context of your change. Explain large code modifications. )
[NOTE]: # ( If it fixes an open issue, please add "Fixes #XXX" as necessary )
In earlier versions of keepassxc there was a "new entry" in the context menu even if an existing entry is selected. Now there are separate menus for item selected and no item selected (good).
I however still like to use the context menu to create a new item. This is difficult if an item is selected and the window is full of items ! This small chnage puts the new item action back in the context menu.

## Screenshots
[TIP]:  # ( Do not include screenshots of your actual database! )
none

## Testing strategy
[NOTE]: # ( Please describe in detail how you tested your changes. )
[TIP]:  # ( We expect new code to be covered by unit tests and documented with doc blocks! )
none

## Checklist:
[NOTE]: # ( Please go over all the following points. )
[NOTE]: # ( Again, remove any lines which don't apply. )
[NOTE]: # ( Pull Requests that don't fulfill all [REQUIRED] requisites are likely )
[NOTE]: # ( to be sent back to you for correction or will be rejected.  )
- ✅ I have read the **CONTRIBUTING** document. **[REQUIRED]**
- ✅ My code follows the code style of this project. **[REQUIRED]**
- ✅ All new and existing tests passed. **[REQUIRED]**
- ✅ I have compiled and verified my code with `-DWITH_ASAN=ON`. **[REQUIRED]**

### CODE REVIEW

**Comment by droidmonkey** [comment]
I would add it below "Delete Entry..."

**Comment by lshman** [comment]
OK - seems like a good place for it. Moved in forked repo

**Comment by lshman** [comment]
sorry hit the wrong button (close). Reopened it

**Comment by lshman** [comment]
Hmm - check unsuccessful ! Nothing to do with my change.
I have had a look at the unit tests. I too had a problem with testcli. I found out it only works if the xclip program is installed - Test works fine after installation. Is that the problem here ?
I also had problems with the testpassphrasegenerator test. This seems to rely on the Resources class finding the correct path for the installed word list. I think the test should run without using the installation. I think the best way is directly passing the word list from the source directory. I could make this change.

**Comment by droidmonkey** [comment]
Disregard the test failure, its an anomoly.

**Pull request merged**
