### PR TITLE
Replace Q_FOREACH and remove BOM

### PR DESCRIPTION
**Pull request by seatedscribe**
Replace last instances of Q_FOREACH with C++11 ranged for-loops
Remove some UTF-8 BOM added by mistake

## Motivation and Context

With Q_FOREACH being obsolete soon, last instances have been converted.
Also some Byte Order Mark added by default by editor have been removed.

## How Has This Been Tested?
I tried the main functionalities by hand

## Types of changes

- :white_check_mark: Bug fix (non-breaking change which fixes an issue)
- :negative_squared_cross_mark: New feature (non-breaking change which adds functionality)
- :negative_squared_cross_mark: Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- :white_check_mark: I have read the **CONTRIBUTING** document. [REQUIRED]
- :white_check_mark: My code follows the code style of this project. [REQUIRED]
- :white_check_mark: All new and existing tests passed. [REQUIRED]
- :negative_squared_cross_mark: My change requires a change to the documentation.
- :negative_squared_cross_mark: I have updated the documentation accordingly.
- :negative_squared_cross_mark: I have added tests to cover my changes.

### CODE REVIEW

**Comment by TheZ3ro** [comment]
I think this need a review, @debfx said that for should use asConst() for optimization

**Comment by debfx** [comment]
Relevant blog post is https://www.kdab.com/goodbye-q_foreach/

Basically:
1. If you are iterating over a const container you don't need to change anything
2. Check if it's possible to make the container const
3. Use asConst()

**Comment by phoerious** [comment]
Is this still being worked on? There are a couple of instances where a range-based for loop is used on a non-const container.

**Comment by phoerious** [comment]
Closing in favor of #387 which properly handles constness.

**Pull request closed without merging**
