### PR TITLE
Remove explicit fonts from SVG

### LINKED ISSUE #6758: KeePassXC slow to launch on macOS
KeyPassXC is slow to launch on every launch. I'm using KeyPassXC 2.6.6 Revision 386b79a on macOS 10.14.6 Mojave.

If I launch it from Terminal with /Applications/KeePassXC.app/Contents/MacOS/KeePassXC I see the following message:

`qt.qpa.fonts: Populating font family aliases took 877 ms. Replace uses of missing font family "Monospace" with one that exists to avoid this cost.`

### PR DESCRIPTION
**Pull request by shemeshg**
[NOTE]: # ( Describe your changes in detail, why is this change required? )
svgCleanup #6758
[NOTE]: # ( Explain large or complex code modifications. )
Remove rel to font names in tow files
[NOTE]: # ( If it fixes an open issue, please add "Fixes #XXX" )
Fixes #6758

## Testing strategy
[NOTE]: # ( Please describe in detail how you tested your changes. )
[TIP]:  # ( We expect new code to be covered by unit tests and documented with doc blocks! )

## Type of change
[NOTE]: # ( Please remove all lines which don't apply. )
- ✅ Bug fix (non-breaking change that fixes an issue)

### CODE REVIEW

**Comment by droidmonkey** [comment]
I think instead of using a default font for this we should rasterize the desired look. The new default is less bold and not as good for an icon.

**Comment by shemeshg** [comment]
> I think instead of using a default font for this we should rasterize the desired look. The new default is less bold and not as good for an icon.

I'm not vector design specialist, so it is beyond my understanding.
Probably we need someone with Linux InkScape or (Adobe [maybe photoshop???])  experience...

**Comment by droidmonkey** [comment]
I can handle this

**Review by droidmonkey — APPROVED** [review]

**Comment by droidmonkey** [comment]
I converted the font to curves, ready for merge

**Pull request merged**
