### PR TITLE
revised this resp. these two guides

### PR DESCRIPTION
**Pull request by DJCrashdummy**
## Type of change
- ✅ Documentation (non-code change)

## Description and Context
* unified the 2 guides (Quickstart & KeeShare) a bit
* use "international" mozilla-link
* removed wrong and/or superfluous newlines & spaces
* some other minor polish & cleanup

for example _highlighting_ is still **not** unified!

## Checklist:
- ✅ I have read the **CONTRIBUTING** document. **[REQUIRED]**

### CODE REVIEW

**Comment by DJCrashdummy** [comment]
...and the screenshots are still the same old ones, although on the homepage (https://keepassxc.org/quickstart/ & https://keepassxc.org/docs/keepassxc-browser-migration/) there are newer and better ones.

no idea where the guides from the homepage are stored... hopefully this work wasn't completely unnecessary?

**Comment by droidmonkey** [comment]
The website repository is here: https://github.com/keepassxreboot/keepassxreboot.github.io

**Comment by DJCrashdummy** [comment]
:man_facepalming: my bad, could have looked for a little bit more thorough.

before i perhaps continue (although i have never worked with github-pages) and do some work unnecessarily more than once, is there a plan for the documentation to unify them in one place? - for now there are at least 3: the hompage-repo, the main-repo and the main-repos wiki...

**Comment by droidmonkey** [comment]
Yes I will be taking care of that very soon. I am putting some finishing touches on right now actually.

**Pull request merged**
