### PR TITLE
Add option to auto-type just the username/password

### LINKED ISSUE #4444: Additional auto type commands
## Summary
The original KeePass has a setting "Show additional auto-type menu commands" which is quite useful for ad-hoc entry formats. Screenshots below should show.

May i request that be implemented in KeePassXC?

image

image

## Desired Behavior
see screenshot

## Possible Solution
I'm not a dev, sorry

## Context
Configuring per entry auto-type settings isn't always useful. For example, single sign on.
One account, creds can be used in multiple places with different auto-type requirements

### PR DESCRIPTION
**Pull request by aneesahmedpro**
**Add option to Auto-Type just the username/password**

Fixes #4444

Some websites these days do not present both the "username" and the "password"
input box on the same webpage (e.g. Google, Amazon). So no custom sequence is
possible to enter both the said attributes in one go.

So, two new context menu actions have been added:
1. To perform the Auto-Type-ing of just the username
2. To perform the Auto-Type-ing of just the password

These context menu actions are analogous to "Copy username" and "Copy
password", except it avoids sending all characters via clipboard.

It "partially fixes" #3630, which is about the ability to perform Auto-Type-ing
of any arbitrary attribute. This PR gives the ability for just the two most
important attributes: the username and the password, for now.

## Explain changes

The `QString`s `Entry::AutoTypeSequenceUsername` and
`Entry::AutoTypeSequencePassword` have been re-used as the `sequence`s for the
Auto-Type-ing of the username and the password respectively.

Analogous to `AutoType::performAutoType`, additional functions
`AutoType::performAutoTypeUsername` and `AutoType::performAutoTypePassword`
were created, which basically skip searching for the `Entry`'s configured
Auto-Type sequence and instead just supply the desired sequence to
`AutoType::executeAutoTypeActions`.

Context menu actions were added so that user can right-click the entry and
trigger an Auto-Type for just the username/password.

## Screenshot

Screenshot from 2020-06-21 08-54-42

_Observe the Auto-Type actions available in the context menu_

## Testing strategy

Tested it for real on Ubuntu with GNOME X.org, and it worked.

Doesn't need new unit test, as it borrows and modifies a few lines of code
for the main Auto-Type functionality, which has its own unit tests already.

## Type of change
- ✅ New feature (change that adds functionality)
- ✅ Breaking change (causes existing functionality to change)

### CODE REVIEW

**Comment by aneesahmedpro** [comment]
Apologies for not noticing the PR template... I'll update soon...

**Comment by aneesahmedpro** [comment]
When a website doesn't put the "username" and the "password" input box on the same webpage, the only solution is to:

1. Copy and paste the username
2. Click "Next" or "Continue" so the next page loads
3. Copy and paste the password
4. Click "Login" finally

But copying and pasting attributes via the clipboard is not totally safe, which
is why the Auto-Type feature was created in the first place. So, an Auto-Type
option should be available to just enter the username/password.

So, new workflow with this PR:

1. Auto-Type the username
2. Click "Next" or "Continue" so the next page loads
3. Auto-Type the password
4. Click "Login" finally

**Comment by aneesahmedpro** [comment]
The vision for future is, of course, to develop this into something which #4444 talks about.

desired feature screenshot

_Above image is taken from #4444 itself_

This PR can be seen as a temporary partial implementation of that future feature: just `{USERNAME}` and `{PASSWORD}` for now.

**Comment by droidmonkey** [comment]
This will have to be completed per the above image to be merged.

**Comment by aneesahmedpro** [comment]
Okay done. How is this? :
Screenshot from 2020-06-22 16-37-54

BTW, does this maybe fix #4444 ?

----
Also, two off-topic questions:
+ On my machine (Ubuntu 18.04, GNOME, X11) there is one test that always fails: `testcli`'s `testClip()` test. What's missing?
+ GCC says `warning: ‘-Werror=’ argument ‘-Werror=implicit-function-declaration’ is not valid for C++` a lot. Maybe look into it and fix the CMake recipe?

**Comment by droidmonkey** [comment]
For your points above, install xclip and we have fixed the c++ warning in the release branch.

Your implementation is great, and it certainly does fix that issue.

**Comment by aneesahmedpro** [comment]
> ...Your implementation is great...
Thanks! That means a lot to me since this is the first time I've worked on a QT application.

BTW, as anything else required from my end? Maybe squashing my commits? Or mentioning `Fixes #4444` in the commit message?

**Comment by droidmonkey** [comment]
I can take care of that, but you're welcome to squash and add the comment

**Comment by aneesahmedpro** [comment]
Better if you do it. You can merge the commit message to your liking during squash :sweat_smile: .

**Comment by hifi** [comment]
You can already specify multiple auto-type sequences and enforce KeePassXC to always ask the sequence if you use the global auto-type hotkey. I use it like this for multi-stage logins:

1. Open up the login page
2. Global hotkey, use arrow keys to pick `{USERNAME}` sequence
3. Next
4. Global hotkey, use arrow keys to pick `{PASSWORD}` sequence
5. Done

I don't see the need for this PR given that it already works without even using the mouse.

**Comment by droidmonkey** [comment]
This is very useful for things like terminal windows where only a password is requested but the window title is not consistent enough for global Auto-Type. Granted you could configure the default sequence to be just password, but this is more user friendly.

I also find value in this when registering for a website, I will generate a strong password and just want to type that into the fields instead of copy/paste.

**Comment by aneesahmedpro** [comment]
Also, the workflow given by @hifi doesn't work for people who use Window Title string matching. (myself included)

**Comment by fabianski7** [comment]
@aneesahmedpro how will this function behave when the global hotkey is pressed? will the user be able to choose which information (user/pass) will be entered? That would be great.

**Comment by zyv** [comment]
> You can already specify multiple auto-type sequences and enforce KeePassXC to always ask the sequence if you use the global auto-type hotkey.

@hifi, I really wish I could do this with the global autotype hotkey on a Mac, because more and more stupid websites split the login sequence into several steps, but in KeePassXC 2.6.0 I can't find this feature... what am I missing, is it coming in the next release?

Screenshot 2020-07-11 at 18 18 07

**Comment by hifi** [comment]
@zyv Have you specified multiple different auto type sequences for the entry with the same window matching pattern?

**Comment by zyv** [comment]
@hifi ah, it's a per entry, not a global setting... Thank you very much, figured it out now!

**Comment by aneesahmedpro** [comment]
> @aneesahmedpro how will this function behave when the global hotkey is pressed? will the user be able to choose which information (user/pass) will be entered? That would be great.

This function does not affect the behaviour of global hotkey at all. All it does is offer some new sequences in a quickly reachable context menu of an entry.

**Pull request merged**
