### PR TITLE
only display advanced settings checkbox on tabs that have them (partially fixes #6190)

### LINKED ISSUE #6190: Database Security -> Advanced Settings checkbox not clickable
## Version
OS: Windows
Version: 2.6.4

## Expected behaviour:
After opening settings I should be able to change advanced settings by clicking the "advanced settings checkbox" in the lower left corner of the settings dialog.

## Current behaviour:
The checkbox is grayed out (disabled) making it impossible to open the advanced settings.

## Suggestion:
If you only provide advanced settings for encryption, you should consider to move the checkbox away from the statusbar into the "Encryption Settings" panel, because the current UI design creates the impression this checkbox has a global effect on the entire settings dialog.
Screenshot:
image

### PR DESCRIPTION
**Pull request by xvallspl**
Current implementation has it disabled instead of hidden. Fixes #6190

In addition, it moves the checkbox into the only tab that has use for it, the Security->Encryption settings tab.

The scrolling bar is not working (yet)

## Screenshots
advancedSettings

## Testing strategy
Went to each tab and checked every configuration

## Type of change
- ✅ Bug fix (non-breaking change that fixes an issue)

### CODE REVIEW

**Comment by michaelk83** [comment]
From the linked issue:
> If you only provide advanced settings for encryption, you should consider to move the checkbox away from the statusbar into the "Encryption Settings" panel, because the current UI design creates the impression this checkbox has a global effect on the entire settings dialog.

I think moving the checkbox to *inside* the relevant tab(s) would make more sense.

**Comment by xvallspl** [comment]
I am still trying to figure out how difficult it would be to move it inside the tabs. While these changes doesn't solve the awkwardness, they improve on the current solution. Maybe "Fixes" is a strong word.

**Comment by droidmonkey** [comment]
I would like it to be part of the Encryption page as well. 

image

**Comment by xvallspl** [comment]
Moved the checkbox into the encryption tab, similar to Jonathan's suggestion.

I would still prefer to have all the settings in the same view, so I'll take a look at that.

**Comment by xvallspl** [comment]
Now simple and advanced settings share view with the checkbox toggling the visibility of the advanced ones. There's a need for a scroll area now, which would be in the next commit

**Comment by droidmonkey** [comment]
You'll want to disable the slide bar choosing the encryption time in your implementation when the advanced settings are shown.

**Comment by droidmonkey** [comment]
This has a crash on Linux ci that needs to be fixed.

**Comment by droidmonkey** [comment]
I made some emergency changes to stop the crashes. I think this needs a fair amount of work to be ready. There are a lot of extra calls to build the version drop down list and the UI elements are not properly sizing for me.

**Comment by xvallspl** [comment]
Ok! I was taking. Alook into this as well

**Comment by droidmonkey** [comment]
Rebased onto develop and tweaked the layout quite a bit:

image

**Comment by droidmonkey** [comment]
Made some more tweaks, this should be final:

image

image

Also removed the global setting that stored whether advanced was shown or not. That could inadvertently cause you to change encryption settings between multiple databases.

**Review by droidmonkey — APPROVED** [review]

**Pull request merged**
