### PR TITLE
add a button to reveal protected attributes in entry view (addresses Issue #1930)

### PR DESCRIPTION
**Pull request by xvallspl**
addresses Issue #1930

Working prototype. 

TODO:

- [x] reorganize, clean and simplify the code
- [x] implement copy on double click
- [x] Improve UI

## Screenshots

protectedEntries

## Testing strategy
Manual testing

## Type of change
- ✅ New feature (change that adds functionality)

### CODE REVIEW

**Comment by droidmonkey** [comment]
Looking very nice!

**Comment by xvallspl** [comment]
Tried factoring out some functionality into functions, but it ends up  making the code more complex to follow.

**Comment by xvallspl** [comment]
I tried several variations of the UI and I lost a lot of time unsuccessfully.  In the end I restored the UI to the original style and if someone is better at this and can/wants to help, please be my guest :)

**Comment by droidmonkey** [comment]
No worries, move onto other things for now

**Review by droidmonkey — APPROVED** [review]

**Comment by droidmonkey** [comment]
I cleaned up the code and moved a lot of stuff into the UI file:
image

**Pull request merged**
