### PR TITLE
Switch Browser Integration to use native raising of windows in macOS

### PR DESCRIPTION
**Pull request by varjolintu**
When popup dialog is launched from KeePassXC-Browser action, the window is raised using native methods (similar to Auto-Type).

## Description
A new class MacUtils is added. This class is used only with macOS and it enables few Cocoa functions for bringing a dialog to the front and switching back to the previous application window. It is used with both Auto-Type and Browser Integration.

Also, the other popup dialogs are brough to front, and the KeePassXC main window is lowered/minimized if needed.

## Motivation and context
Allows popup dialogs to have a proper focus with macOS.
Fixes https://github.com/keepassxreboot/keepassxc/issues/2256.
Fixes https://github.com/keepassxreboot/keepassxc/issues/1954.

## How has this been tested?
Manually.

## Types of changes
- ✅ New feature (non-breaking change which adds functionality)

## Checklist:
- ✅ I have read the **CONTRIBUTING** document. **[REQUIRED]**
- ✅ My code follows the code style of this project. **[REQUIRED]**
- ✅ All new and existing tests passed. **[REQUIRED]**
- ✅ I have compiled and verified my code with `-DWITH_ASAN=ON`. **[REQUIRED]**

### CODE REVIEW

**Comment by varjolintu** [comment]
Building without browser integration is still broken, so this is WIP.

**Comment by varjolintu** [comment]
Fixed. Needed to add the BrowserUtils class to `src/CMakeLists.txt` with the correct linking to the AppKit framework.

**Comment by droidmonkey** [comment]
This needs to be completely redone now that the database widget refactor has occured

**Comment by varjolintu** [comment]
@droidmonkey I just made some changes to this PR after the database widget refactor was merged. So no need to close this.

**Comment by varjolintu** [comment]
Seems this still needs a lot of work. Maybe there's a need to refactor some other stuff to work from a single class instead of spreading the stuff everywhere. Now there is the MacUtils class by maybe that must be refactored to WindowUtils or something similar, which could be used from every platform.

Mostly the problems are not displaying the new unlock or confirmation dialogs, but hiding them properly.

**Comment by droidmonkey** [comment]
Let's punt this to a minor release.

**Comment by varjolintu** [comment]
This indeed needs a lot more work. Showing the popups without raising the main window needs a separate solution for each OS base. So three different implementations, just like in Auto-Type. I wonder why Qt don't have these methods already baked in.

**Comment by varjolintu** [comment]
I decided to modify this PR to include only the necessary macOS side changes, for now. It's still a step forward. Previously macOS popups didn't even have a proper focus when called.

**Comment by l0f4r0** [comment]
In relation to bug #2547, this PR doesn't fix the issue from my side.

**Comment by varjolintu** [comment]
@l0f4r0 Could you elaborate and provide some details, thanks.

**Comment by l0f4r0** [comment]
> @l0f4r0 Could you elaborate and provide some details, thanks.
Sure. When launching autotyping while database is locked, KeepassXC asks for the db password but is then unable to trigger the correct entry. So actually, you need to unlock the database first and then launch autotyping feature.

**Comment by droidmonkey** [comment]
Yeah that bug wasn't actually fixed yet

**Comment by l0f4r0** [comment]
> Yeah that bug wasn't actually fixed yet

Ok, no problem. I just thought it would be because of previous statuses on #2547 ;)

**Pull request merged**
