### PR TITLE
Use a dedicated tray icon when the database is unlocked.

### PR DESCRIPTION
**Pull request by JanHellwig**
## Description
Icons called _keepassxc-unlocked.*_ were added (copies of the _keepassxc.*_ icons).
FilePath::trayIconUnlocked() was changed to return the new icon.

## Motivation and context
On Ubuntu it is currently not possible to override the application icon and the tray/indicator icon in unlocked state with different icons.

## How has this been tested?
Manual testing

## Screenshots:
_Before_
before-locked before-unlocked

_After_
after-locked after-unlocked

If the icons are not overwritten by the theme it looks exactly as before.

## Types of changes
- ✅ New feature (non-breaking change which adds functionality)

## Checklist:
- ✅ I have read the **CONTRIBUTING** document. **[REQUIRED]**
- ✅ My code follows the code style of this project. **[REQUIRED]**
- ✅ All new and existing tests passed. **[REQUIRED]**
- ✅ I have compiled and verified my code with `-DWITH_ASAN=ON`. **[REQUIRED]**

### CODE REVIEW

**Comment by droidmonkey** [comment]
Im confused by this, why are you adding more icons?

**Comment by phoerious** [comment]
This change is also likely to break our tray icon in the AppImage again. We need an absolute icon path, otherwise we have no tray icon at all due to a Unity bug.

**Comment by TheZ3ro** [comment]
@droidmonkey I was confused too, this adds a new icon for the unlocked state with a different name (keepassxc-unlocked) so you can theme the icon in locked/unlocked state without affecting the main icon (keepassxc).
Right now the main icon is also used for the unlocked state.

@phoerious He is using the `icon()` method from [FilePath.cpp, line 131](https://github.com/keepassxreboot/keepassxc/pull/518/files#diff-b87cbff0c0a78fdea6440d81964348d2R131) should return an absolute path (if m_dataPath is an absolute path)

**Comment by droidmonkey** [comment]
Got it, this makes a lot of sense now.

**Comment by TheZ3ro** [comment]
What are we doing about this? @droidmonkey @phoerious

**Comment by phoerious** [comment]
Well, we still have issues with the tray icon for the snap package. We are using relative paths right now (which is probably the reason why it's not working with the snap package), but unset XDG_DATA_DIRS for the AppImage (which is why it's working there). I suppose that we need to switch to absolute paths to fix it reliably which means that this PR can't be merged. Prove me wrong.

**Comment by TheZ3ro** [comment]
@phoerious are you sure are relative path? Like I said before

> using the `icon()` method from [FilePath.cpp, line 131](https://github.com/keepassxreboot/keepassxc/pull/518/files#diff-b87cbff0c0a78fdea6440d81964348d2R131) should return an absolute path (if m_dataPath is an absolute path)

**Comment by JanHellwig** [comment]
I didn't test it in a snap package, but as @TheZ3ro said it should return an absolute path if m_dataPath is an absolute path. If that is not the case then of course it doesn't return an absolute path but it wouldn't be a regession as that would already be the case without the PR.

**Comment by droidmonkey** [comment]
The snap icon needs a lot of love, I wouldn't worry about it in this PR.

**Comment by TheZ3ro** [comment]
Seems that this PR is broken, I need to cherry-pick and make a new PR

**Pull request closed without merging**
