### PR TITLE
Fix Visual Studio install detection in release-tool.ps1

### PR DESCRIPTION
**Pull request by yyualvin**
`Get-CimInstance MSFT_VSInstance` doesn't work for all Windows and Visual Studio installs as it uses the default namespace `root/cimv2`. 

`Get-CimInstance MSFT_VSInstance -Namespace root/cimv2/vs` should work

## Screenshots
Circled red is the `Get-CimInstance MSFT_VSInstance` command not working
Circled green is the `Get-CimInstance MSFT_VSInstance -Namespace root/cimv2/vs` command working.

image

## Testing strategy
The script ran successfully in powershell after the edits were made.

## Type of change
- ✅ Bug fix (non-breaking change that fixes an issue)

### CODE REVIEW

**Comment by yyualvin** [comment]
Saw that this was fixed in another branch. I will close

**Comment by yyualvin** [comment]
Will reopen for now, might be useful since the fix in the other branch involves manually installing a powershell module

**Comment by droidmonkey** [comment]
This is nuts, they changed it without any documentation (I'm not surprised it's microsoft...)

**Comment by droidmonkey** [comment]
Hmmm, I had referenced this article before, looks like they recently added the namespace flag.

https://learn.microsoft.com/en-us/visualstudio/install/tools-for-managing-visual-studio-instances?view=vs-2022&source=recommendations

Yup it was added mid october: https://github.com/MicrosoftDocs/visualstudio-docs/commit/46e97ebdd24bfc53b9e917af41c1e1cae5b702c5

**Review by droidmonkey — APPROVED** [review]

**Comment by droidmonkey** [comment]
I'll have to sign the release script before merge, no need to merge develop into this

**Pull request merged**
