### PR TITLE
Add documentation for keyboard shortcuts 

### LINKED ISSUE #3175: Document keyboard shortcuts
# The documentation of KeepassXC is poor
I discover some shorcuts like Ctrl + Shift + C which show the passwords.
I can see the shortcuts in the menu software, but there are more hdden.

Where is the sortcuts list, please ?

### PR DESCRIPTION
**Pull request by SohamG**
[TIP]:  # ( Provide a general summary of your changes in the title above ^^ )

## Type of change
[NOTE]: # ( Please remove all lines which don't apply. )
- ✅ Documentation (non-code change)

## Description and Context
[NOTE]: # ( Describe your changes in detail, why is this change required? )
[NOTE]: # ( Describe the context of your change. Explain large code modifications. )
[NOTE]: # ( If it fixes an open issue, please add "Fixes #XXX" as necessary )
 - Fixes #3175 
 - Add docs/KEYBINDS.md
 - Add reference to above file in README.md
 - Fix a small error in INSTALL.md in section "Packaging", link to keepassxreboot/keepassxc-packaging

## Testing strategy
[NOTE]: # ( Please describe in detail how you tested your changes. )
[TIP]:  # ( We expect new code to be covered by unit tests and documented with doc blocks! )
No code changes

## Checklist:
[NOTE]: # ( Please go over all the following points. )
[NOTE]: # ( Again, remove any lines which don't apply. )
[NOTE]: # ( Pull Requests that don't fulfill all [REQUIRED] requisites are likely )
[NOTE]: # ( to be sent back to you for correction or will be rejected.  )
- ✅ I have read the **CONTRIBUTING** document. **[REQUIRED]**
- ✅ My code follows the code style of this project. **[REQUIRED]**
- ✅ All new and existing tests passed. **[REQUIRED]**
- ✅ I have compiled and verified my code with `-DWITH_ASAN=ON`. **[REQUIRED]**
- ✅ My change requires a change to the documentation, and I have updated it accordingly.

### CODE REVIEW

**Comment by PF93mc8y7erq92qTmTjJBysALa** [comment]
Thanks for the overview!
How will we know to update this file should the bindings change?

**Comment by SohamG** [comment]
@PF93mc8y7erq92qTmTjJBysALa The only solution I can think of for that is to make it a [PR requirement](https://github.com/keepassxreboot/keepassxc/blob/develop/.github/PULL_REQUEST_TEMPLATE.md); @droidmonkey should I edit the pull request template file for this?

I could look into automating, but I think thats for another PR.

**Comment by PF93mc8y7erq92qTmTjJBysALa** [comment]
> PR Requirement

Seems a relevant one is already listed:
> ✅ My change requires a change to the documentation, and I have updated it accordingly.
And that might be sufficient.

I think you are right - automating it (even just automating a test for it) could be another merge request.

Thanks again!

**Comment by SohamG** [comment]
My pleasure :D

**Comment by droidmonkey** [comment]
I wouldn't bother automating it.

**Pull request merged**
