### PR TITLE
Describe HTML export/paper backups in the user manual

### PR DESCRIPTION
**Pull request by wolframroesler**
[NOTE]: # ( Describe your changes in detail, why is this change required? )
[NOTE]: # ( Explain large or complex code modifications. )
[NOTE]: # ( If it fixes an open issue, please add "Fixes #XXX" )

Add a section to the "Exporting Databases" chapter of the user guide that briefly explains how to create a paper backup using HTML export. Points to the upcoming blog article for details.

WIP because the exact URL of the blog article is still missing.

## Screenshots
[TIP]:  # ( Do not include screenshots of your actual database! )

n/a

## Testing strategy
[NOTE]: # ( Please describe in detail how you tested your changes. )
[TIP]:  # ( We expect new code to be covered by unit tests and documented with doc blocks! )

n/a

## Type of change
[NOTE]: # ( Please remove all lines which don't apply. )
- ✅ Documentation (non-code change)

### CODE REVIEW

**Comment by wolframroesler** [comment]
For completeness, here's my draft of the blog article I wrote about paper backups: https://cloud.owncube.com/s/3CoJDayRMxCkGyp

Once it's published on the KeePassXC blog, I'll put the link into this PR and un-WIP it.

Please note that the blog article applies to KeePassXC 2.5.0+; there's no need to delay publishing it until 2.7.0 is out.

**Comment by droidmonkey** [comment]
Can you open a PR on the website for the blog post? We can do it as well if you don't know the Jekyll mannerisms.

**Comment by wolframroesler** [comment]
Which is the website for the blog PR? In fact, I'm totally unfamiliar with Jekyll and its mannerisms.

**Comment by droidmonkey** [comment]
https://github.com/keepassxreboot/keepassxreboot.github.io/tree/master/blog/_posts

Replicate the format here

**Comment by wolframroesler** [comment]
Link to blog article added. Un-WIPed. Feel free to approve and merge now.

**Pull request merged**
