### PR TITLE
Add Auto-Type button to password generator

### PR DESCRIPTION
**Pull request by shemeshg**
[NOTE]: # ( Describe your changes in detail, why is this change required? )
Add AutoType to Password generator

Current status:
|Password Gen Field| <Regenerate Password><copy password>
Suggested:
|Password Gen Field| <Regenerate Password><copy password><AutoType>

This will enable the following procedure at website that disable Past on Change password form:
- For old password Cmd+Shift+V
- For new password – Press the< AutoType Icon> at the Password Gen form.
- Press ok at the web page to see if new password was accepted.
- If password accepted press  Apply.

[NOTE]: # ( Explain large or complex code modifications. )

It is a small change, but requires explain..

```
void AutoType::executeAutoTypeActions(const Entry* entry, QWidget* hideWindow, const QString& sequence, WId window)
```
Must accept Entry and it will reject the request if I pass it entry with NullPtr

To use
```
void DatabaseWidget::performAutoType(const QString& sequence)
```
I could not get to that function from password Generator directly, since Password Generator is decoupled with the database, (it can be called with out any database opened). 

The obvious solution was:
I’ll cary the signal from the PasswordGenerator→through PasswordEdit→to EditEntryWidget→to DatabaseWidget

[NOTE]: # ( If it fixes an open issue, please add "Fixes #XXX" )

## Screenshots
[TIP]:  # ( Do not include screenshots of your actual database! )
Screen Shot 2021-07-02 at 13 11 04

## Testing strategy
[NOTE]: # ( Please describe in detail how you tested your changes. )

1. Ensure no AutoType button if not opened from Entry.
2. Ensure AutoType works correctly when password generator opened from Entry., 

[TIP]:  # ( We expect new code to be covered by unit tests and documented with doc blocks! )

## Type of change

[NOTE]: # ( Please remove all lines which don't apply. )

- ✅ New feature (change that adds functionality)

### CODE REVIEW

**Comment by michaelk83** [comment]
See #6323 . You may want to adjust to that. Though I suppose your solution is complementary to it.
See also #6500 for the bigger picture.

**Comment by michaelk83** [comment]
> Suggested:
> |Password Gen Field| <AutoType (Same icon same size as copy password)>

Though I can roughly figure out what you mean, please post a proper screenshot.

**Comment by michaelk83** [comment]
> `void AutoType::executeAutoTypeActions(const Entry* entry, QWidget* hideWindow, const QString& sequence, WId window)`
> Must accept Entry and it will reject the request if I pass it entry with NullPtr

What I would do is add an optional `entry` parameter to `PasswordGeneratorWidget`'s constructor. When launched from a DB entry, it would be set to the entry, and you'd have an entry to pass to `executeAutoTypeActions()`. It would also be useful for #6323. When launched without a DB, this would be left as null, and you'd get the bare password generator.

But I'm not familiar enough with the KPXC code to tell if that's a good idea or not.

**Comment by droidmonkey** [comment]
Upon a quick review, this will need a lot of work to streamline the implementation. Also need a screenshot. You are also using the same clipboard icon for the Auto-Type action which is wrong.

**Comment by droidmonkey** [comment]
> What I would do is add an optional `entry` parameter to `PasswordGeneratorWidget`'s constructor. When launched from a DB entry, it would be set to the entry, and you'd have an entry to pass to `executeAutoTypeActions()`. It would also be useful for #6323. When launched without a DB, this would be left as null, and you'd get the bare password generator.

No do not do this. Please don't provide strong  recommendations without confurring with the developers. I appreciate your input but this would violate the current isolation of the password generator (it doesn't know or care about an entry, and it certainly doesn't make calls into the entry class).

**Comment by michaelk83** [comment]
> Please don't provide strong recommendations without confurring with the developers.

That why I said "What I would do", and not "Do this", and added the last line:

> But I'm not familiar enough with the KPXC code to tell if that's a good idea or not.

**Comment by shemeshg** [comment]
> Upon a quick review, this will need a lot of work to streamline the implementation. Also need a screenshot. You are also using the same clipboard icon for the Auto-Type action which is wrong.

Corrected the Icon, I'll wait  for further instructions/decisions of the senior dev team

I can go for the #6323, If you'd like,
However most users not always updates the expiry date, and without that they will be tunneled to the current Password generator, not #6323, 
With this small change, their old password always available using menu->Entry->Auto-Type->{USERNAME}
and PasswordToBe using Mouse click button at the Password Generator.

It is also possible to add (always), a read only field with current password, and also Copy and Autotype at the side, to hint the user. 
So the Generate Password form will not have to be aware of password expiry date.

Anyway, waiting for further detailed instructions.

**Comment by michaelk83** [comment]
> I can go for the #6323, If you'd like,
> ...
> It is also possible to add (always), a read only field with current password, and also Copy and Autotype at the side, to hint the user.

Those changes are complementary, actually. #6323 adds the following, when launched from an entry:

1. Show the current (old) password above the new one.
2. Replace `Close` button with `Cancel` and `Save` (or `Close` and `Save`).
3. `Close`/`Cancel` discards the new password, `Save` updates the entry.

The assumption there is that the new password is copy-pasted to the website, and the user tries to submit it before deciding which button to click (if it's accepted, `Save`; if it's rejected, `Cancel` or try another one).

Your change adds an auto-type button for the (new) password, which is just a different method of transferring it to the website.

I've just double-checked: points 2 and 3 are already implemented. When launched from the small dice icon in the password field, an `Apply Password` button is added (`Close` remains). Clicking `Apply Password` updates the password, and clicking `Close` leaves the old one (discards the new one).

So from #6323, this leaves only adding the current password field when launched from an entry (point 1). It can have the same copy and auto-type buttons as the new password field. If that can be included in this PR without overcomplicating it, then that's worth considering. Otherwise, that can be left to a separate PR.

> So the Generate Password form will not have to be aware of password expiry date.

It doesn't need to be aware of it anyway. The user launches it manually either from the main toolbar, or from the dice icon in the password field. In the latter case, it will update the field when you click `Apply Password`. That already works. Then the last bit is to update the expiry date when the password field changes. But that can be handled by the entry. The Password Generator doesn't need to care about that. That's being worked on in #6456.

**Comment by michaelk83** [comment]
The other thing I noticed, is that the main toolbar dice always launches the unconnected generator (without `Apply Password`), even when editing an entry. Maybe that should be changed to behave the same as the small dice in the password field, when editing? The main toolbar icon is more visible, and easier to click. Can there be more than one password field in an entry? @droidmonkey

**Comment by droidmonkey** [comment]
The toolbar dice should always open the "standalone" generator. That is why the dice icon is within the password edit field, the result is associated with that field. We could easily support more than one password per entry, but that is reliant on the entry templates feature.

**Comment by droidmonkey** [comment]
I am going to close this PR, it requires too much refactor to make it align with a desirable code flow and doesn't solve the main problem we have which is a dedicated "change password" sequence.

**Comment by michaelk83** [comment]
Just a reminder: the only thing missing for a "change password" workflow as in #6323 is to show the current (old) password when the generator is launched from a password field.

**Pull request closed without merging**
