### PR TITLE
Add a context menu entry to delete entries from health check reports

### PR DESCRIPTION
**Pull request by xvallspl**
Addresses Issue #4986

Ideally we would be able to select multiple entries and delete them at once, but it would require deeper changes in the widget. This is a start.

## Screenshots
deleteEntry

## Type of change
[NOTE]: # ( Please remove all lines which don't apply. )
- ✅ New feature (change that adds functionality)

### CODE REVIEW

**Comment by xvallspl** [comment]
Sorry for the suboptimal framing in the screenshot 🙃

**Comment by xvallspl** [comment]
The workflow in the linked issue suggests that we could have a delete entry button in the edit entry widget when triggered from the report. Should I try to have this as well?

**Comment by droidmonkey** [comment]
Technically we could but the edit entry workflow needs to be greatly improved. I prefer a context menu item only for now.

**Comment by phoerious** [comment]
What I would prefer is not blind deletion from the report, but a context action that says "Show affected entries", which sends you back to the main view but with a filter set to only those entries.

**Comment by droidmonkey** [comment]
I made a ton of changes:
* Allow multi-select in health check and HIBP tables
* Created GuiTools namespace and moved shared deletion code into it, now DatabaseWidget and Reports all share the same deletion sequencing. This will be a great pivot point to share more common functions between GUI elements.
* General code cleanup

image

image

image

**Review by droidmonkey — APPROVED** [review]

**Pull request merged**
