### PR TITLE
Fix parsing stat file for polkit

### PR DESCRIPTION
**Pull request by droidmonkey**
[NOTE]: # ( Describe your changes in detail, why is this change required? )
[NOTE]: # ( Explain large or complex code modifications. )
[NOTE]: # ( If it fixes an open issue, please add "Fixes #XXX" )

## Testing strategy
[NOTE]: # ( Please describe in detail how you tested your changes. )
[TIP]:  # ( We expect new code to be covered by unit tests and documented with doc blocks! )
Tested with various errors in the file and with an actual stat file

## Type of change
[NOTE]: # ( Please remove all lines which don't apply. )
- ✅ Bug fix (non-breaking change that fixes an issue)

### CODE REVIEW

**Review by HexF — APPROVED** [review]

**Comment by rgarcia89** [comment]
Any update when this will be merged?

**Comment by rgarcia89** [comment]
@droidmonkey is the fix included in the latest build?
https://snapshot.keepassxc.org/latest/

If so - I cannot confirm it to be working now. I am getting the same error in the UI as before, with the difference that no logs are being produced

**Comment by droidmonkey** [comment]
It should be, yes

**Comment by droidmonkey** [comment]
@rgarcia89 you might be running into this issue: https://github.com/keepassxreboot/keepassxc/issues/10523

**Pull request merged**
