### PR TITLE
Split GuiTests: extract TOTP gui tests

### PR DESCRIPTION
**Pull request by dmaslenko**
This is a pilot variant to split the monolithic TestGUI class. Started with TOTP tests, the next tests will be refactored one by one later.

The idea was discussed here: #9100.
It is recommended to review by commits to follow my step-by-steps changes.

## Type of change
- ✅ Refactor (significant modification to existing code)

### CODE REVIEW

**Comment by droidmonkey** [comment]
I don't recommend you spend any more time on this. I won't merge a split of the gui tests into multiple tests. 

I would welcome a completely different approach to gui testing, but qt kind of ties our hands. I had looked into catch2 testing framework.

**Comment by dmaslenko** [comment]
Got it, let's close the PR.
About the `catch2`, could you sound couple main requirements (your vision), I will check this framework.

**Comment by dmaslenko** [comment]
I checked the Catch2 tutorial, couple other articles and will try to implement a simple one unit test and one gui test.
@droidmonkey, could you confirm, are you planning to migrate all tests or gui only?

**Comment by droidmonkey** [comment]
I would love to migrate all tests eventually, but that would be a huge lift. I find the qt testing framework to be extremely frustrating when it comes to gui testing. Catch2 doesn't necessarily solve that problem but it does offer far cleaner testing infrastructure.

**Pull request closed without merging**
