### PR TITLE
Add button for auto-type in the toolbar (#1026)

### PR DESCRIPTION
**Pull request by frostasm**
fix for #1026 

## Description

Add button for auto-type in the toolbar

## Motivation and context

fix open issue

## How has this been tested?

Manually

## Screenshots (if appropriate):

image

## Types of changes

- ✅ Bug fix (non-breaking change which fixes an issue)

## Checklist:

- ✅ I have read the **CONTRIBUTING** document. **[REQUIRED]**
- ✅ My code follows the code style of this project. **[REQUIRED]**
- ✅ All new and existing tests passed. **[REQUIRED]**
- ✅ I have compiled and verified my code with `-DWITH_ASAN=ON`. **[REQUIRED]**

### CODE REVIEW

**Comment by frostasm** [comment]
Maybe it also make sense to add the button "Copy Url"?

image

**Comment by affinityv** [comment]
Another great idea, thanks and thanks for the work to get the auto-type button in place; much appreciated!

**Comment by phoerious** [comment]
Would you be so kind to rebase this to develop, so I can merge this cleanly?

**Comment by frostasm** [comment]
@phoerious done ;)

**Comment by phoerious** [comment]
Thanks a bunch!

**Pull request merged**
