### PR TITLE
Add notes for CMake options WITH_XC_TOUCHID, WITH_APP_BUNDLE

### PR DESCRIPTION
**Pull request by tiendq**
## Description
- Add CMake options in building instruction: `WITH_XC_TOUCHID`, `WITH_APP_BUNDLE`.
- Remove some redundant whitespaces.

## Motivation and context
Better documentation.

## Types of changes
- ✅ Bug fix (non-breaking change which fixes an issue)

## Checklist:
- ✅ I have read the **CONTRIBUTING** document. **[REQUIRED]**
- ✅ My code follows the code style of this project. **[REQUIRED]**

### CODE REVIEW

**Comment by droidmonkey** [comment]
I fixed this in the group sharing PR (once it's merged), thank you for the contribution though.

**Comment by tiendq** [comment]
What's "group sharing PR"? :)

**Comment by droidmonkey** [comment]
#2109 

You really can't prevent it, you could ask us on IRC if you want

**Comment by tiendq** [comment]
@droidmonkey My PR added WITH_XC_TOUCHID too. Actually I knew this option after a failed build since my MBP doesn't have a touch bar.

I don't see it in your [last commit](https://github.com/keepassxreboot/keepassxc/pull/2109/commits/66a36b3af11b597da3ae2bb867244443a5b71199) in the mentioned issue #2109 

I just want to confirm, if it has been added in another commit then it's fine :)

**Comment by droidmonkey** [comment]
Look at the install.md file in files changed, you'll see the changes.

**Pull request closed without merging**
