### PR TITLE
Show URL field for all schemes.

### LINKED ISSUE #1424: URL not shown in entry table if scheme is not http/https
A minor glitch. Created an entry in keepassxc for an ftp site:
```
Title: FreeBSD ftp
Username: ftpuser
Password: ******
URL: ftp://ftp.freebsd.org/
```
This item appears with an empty URL on the password listing. Anything but http/https shows a blank URL on the password listing.

## Expected Behavior
Strip spaces from urls when saved, support any protocol scheme

## Current Behavior
Only http/https URLs are shown, url is not stripped

## Steps to Reproduce (for bugs)
1. Start keepassxc, open password database
2. CTRL+N
3. Insert sample data above and save
4. Password listing shows the new item but url field is empty

Operating system: Ubuntu 17.10
Browser: Firefox 59.0b3
Proxy used: YES

## Debug Info
KeePassXC - Version 2.2.4
Revision: 83f1a53

Libraries:
- Qt 5.9.1
- libgcrypt 1.7.8

Operating system: Ubuntu 17.10
CPU architecture: x86_64
Kernel: linux 4.13.0-31-generic

Enabled extensions:
- Auto-Type
- Browser Integration

### PR DESCRIPTION
**Pull request by rominf**
## Description
Show URL field for all schemes.

## Motivation and context
Fix #1424

## How has this been tested?
Manually.

## Types of changes

- ✅ Bug fix (non-breaking change which fixes an issue)

## Checklist:

- ✅ I have read the **CONTRIBUTING** document. **[REQUIRED]**
- ✅ My code follows the code style of this project. **[REQUIRED]**
- ✅ All new and existing tests passed. **[REQUIRED]**

### CODE REVIEW

**Comment by phoerious** [comment]
The tests are failing.

**Comment by rominf** [comment]
@phoerious Sorry. I fixed tests.

**Comment by TheZ3ro** [comment]
This change isn't complete as-is. Removing the check will allow `ftp`, `cmd` and other URLs in DetailsWidget and EntryModel as clickable links.

So, you removed the check from the `Entry::resolveUrl` function but you need to add that same check in the `Entry::displayUrl` function (that is calling `resolveUrl`)

Another thing I noticed is `EntryModel` ([line 182](https://github.com/keepassxreboot/keepassxc/blob/0a876c8af915d6244281d3eea8b375047446e902/src/gui/entry/EntryModel.cpp#L182)) resolving reference for `Entry::displayUrl` but there will be no reference in it (displayUrl already resolve them).
Can you change that line with simply `result = entry->displayUrl();` ?

Thanks for the contribution

**Comment by rominf** [comment]
@TheZ3ro 
> This change isn't complete as-is. Removing the check will allow ftp, cmd and other URLs in DetailsWidget and EntryModel as clickable links.

What's wrong with that? When I click on a ftp:// link, keepassxc opens Dolphin as an FTP client. That's the correct behavior in my opinion.

> but you need to add that same check in the Entry::displayUrl function (that is calling resolveUrl)

Why?

**Comment by TheZ3ro** [comment]
Now I remember why we put those checks in the first place.
The favicon downloader ([EditEntryWidget.cpp#L631](https://github.com/keepassxreboot/keepassxc/blob/b80ddef2743f8eb3d952ea1a6f947352ede80d7f/src/gui/entry/EditEntryWidget.cpp#L631) and [EditWidgetIcons.cpp#L189](https://github.com/keepassxreboot/keepassxc/blob/b80ddef2743f8eb3d952ea1a6f947352ede80d7f/src/gui/EditWidgetIcons.cpp#L189) ) was crashing when a non-http link was inserted.
So we created the `webUrl()` function for http-only urls and the `displayUrl()` function for masking passwords in URLs.

Now with the curl downloader the favicon downloader doesn't seems to crash anymore (I tested only with an `ftp` url) so I think we are safe after removing the http/https check

**Comment by TheZ3ro** [comment]
This can be merged in 2.3.1

**Comment by tycho** [comment]
IMO, this needs a better commit message than just "Fix #1424"...

**Comment by droidmonkey** [comment]
Closed in favor of #1768

**Pull request closed without merging**
