### PR TITLE
Feature : --key-file option for CLI

### PR DESCRIPTION
**Pull request by louib**
* Introduced the `--key-file` option for CLI commands
* Removed support for `--gui-prompt` and related code.
* Moved `QCoreApplication` instantiation to `keepassxc-cli.cpp`
* Removed `CompositeKey::readFromLine`, which was assuming a password entered at the password prompt was possibly a key file path. We do not need that anymore now that there's an option for that.

Overall, removing the use of a `QApplication` in the CLI. We only use a `QCoreApplication` now, which removes the need to branch on the application type, and allows to move some duplicated logic to `keepassxc-cli`.

## How has this been tested?
* Unit tests
* Tested all the commands with / without key files
* Tested the merge command with all `key-file`, `key-file-from` and `-s` combination.

## Screenshots (if appropriate):
New documentation for the `key-file` option:
```
$ ./src/cli/keepassxc-cli clip
Usage: ./src/cli/keepassxc-cli clip [options] database entry [timeout]
Copy an entry's password to the clipboard.

Options:
  -k, --key-file <path>  Key file of the database.

Arguments:
  database               Path of the database.
  entry                  Path of the entry to clip.
  timeout                Timeout in seconds before clearing the clipboard.
```

## Types of changes

- ✅ New feature
- ✅ Breaking change
- ✅ Refactoring

## Checklist:

- ✅ I have read the **CONTRIBUTING** document. **[REQUIRED]**
- ✅ My code follows the code style of this project. **[REQUIRED]**
- ✅ All new and existing tests passed. **[REQUIRED]**
- ✅ I have compiled and verified my code with `-DWITH_ASAN=ON`. **[REQUIRED]**
- ✅ My change requires a change to the documentation and I have updated it accordingly.

### CODE REVIEW

**Comment by droidmonkey** [comment]
Any specific reason why you want to remove the gui prompt option?

**Comment by louib** [comment]
@droidmonkey the main reason is that using the gui prompt requires instantiating a `QApplication` instead of a `QCoreApplication`, which has a lot of side effects for a terminal app (weird focus changing in Mac, thread errors messages in Windows, etc). The previous solution was to instantiate a `QApplication only when needed, but this would defer the creation of the app to the latest moment, and add a lot of duplicated logic.

**Comment by droidmonkey** [comment]
Concur with your explanation, thanks!

**Comment by louib** [comment]
@TheZ3ro This PR addresses https://github.com/keepassxreboot/keepassxc/issues/681

**Comment by TheZ3ro** [comment]
@louib updating #681

**Pull request merged**
