### PR TITLE
Enable high-DPI scaling to support 4k screens

### LINKED ISSUE #548: HiDPI icons
I have an 2880x1620 display on a 15.6 inch laptop and some of the icons are really small and hard to identify. Screen scaling is at 2.0. If I set the screen scaling back to 1, all icons are equally small as they should be. So the first two icons scale, but the other dont.

## Current Behavior

bildschirmfoto vom 2017-05-06 17-18-14

## Your Environment

* KeePassXC version/commit used: 2.1.4/cb283bb95ae559d044415f426f841c27bff383f0
* Qt version (e.g. Qt 5.3): 5.6.1
* Compiler (e.g. Clang++3.6.0): dont know i installed it with snap
* Operating System and version:  Ubuntu 16.04

### PR DESCRIPTION
**Pull request by phoerious**
## Description

This enables coordinate system scaling for high-DPI displays, which enforces correct proportions even on small 4k displays. The icons are scaled up without interpolation, which makes them crisp, but a bit pixelated. A new scalable icon set will solve this problem, but is not scope of this patch.

Resolves #548, #1381, #1710, #1888

As a small extra cookie, I snuck in enforcement of our icon set for the message box close icon (which has displayed a weird box on my KDE system ever since #2317 was merged).

## Motivation and context

Icons were tiny, widgets had inhomogeneous proportions and windows were way too small as a result.

## How has this been tested?

Tested on a 13.3" 4k Dell InfinityEdge display under Windows 10, works perfectly.

I also tested it in an Ubuntu 18.10 VM. It works in principle, but Gnome does not set all required properties. For Qt to pick up the correct scaling, DPI may need to be set manually using `xrandr` or KeePassXC needs to be started with

    QT_SCREEN_SCALE_FACTORS=2 keepassxc

If the fonts are still slightly off, they can be corrected by also setting `QT_FONT_DPI=225`. I don't think I can fix this any better. It is definitely working, though, Qt just may not pick up all settings automatically.

## Screenshots (if appropriate):
Before:
before

After:
after

## Types of changes

- ✅ Bug fix (non-breaking change which fixes an issue)

## Checklist:

- ✅ I have read the **CONTRIBUTING** document. **[REQUIRED]**
- ✅ My code follows the code style of this project. **[REQUIRED]**
- ✅ All new and existing tests passed. **[REQUIRED]**
- ✅ I have compiled and verified my code with `-DWITH_ASAN=ON`. **[REQUIRED]**

### CODE REVIEW

**Comment by jo-so** [comment]
Works for me. Looks fine. Thank you!

**Comment by emptyrusso** [comment]
Icons still super-small on windows: 3000×2000 (267 PPI) respectively.

**Comment by droidmonkey** [comment]
This was merged into develop, are you using the 2.4.0 snapshot to test? https://snapshot.keepassxc.org

**Comment by affinityv** [comment]
Nice on HiDPI screen, but makes second screen that is FHD un-usable.  Needs to be adjustable, best if automatic, when moving the displayed windows b/w monitors of different types.

**Comment by affinityv** [comment]
Version 2.3.4 still works perfectly well, both screens are fully usable for me, 2.4.0 doesn't have any option, that I can see to turn off this new "feature".

**Comment by stucki** [comment]
I'm affected by this problem too. It looks like this is now discussed in  #2808, so I suggest to continue over there.

**Pull request merged**
