### PR TITLE
Allow entries to be excluded from Health Check and HIBP

### LINKED ISSUE #4168: Health Check - Exclude entries from check
## Summary
I have some entries, where the password is a PIN (only 4 digits) but here only 4 digits are allowed.
I also have entries where I have unsafe passwords that I can not change (password of the website of my karate teacher, password of the emails of the karate dojo, where I manage the emails, email account of my brother, where I backup his password in KeePassXC).
So a checkbox "Exclude from health check" when editing an entry would really be helpful!
But maybe I should create a new issue here for this feature?

### PR DESCRIPTION
**Pull request by wolframroesler**
[TIP]:  # ( Provide a general summary of your changes in the title above ^^ )

## Type of change
[NOTE]: # ( Please remove all lines which don't apply. )
- ✅ New feature (non-breaking change which adds functionality)

## Description and Context
[NOTE]: # ( Describe your changes in detail, why is this change required? )
[NOTE]: # ( Describe the context of your change. Explain large code modifications. )
[NOTE]: # ( If it fixes an open issue, please add "Fixes #XXX" as necessary )

Adds a checkbox to the "Advanced" page of the entry editor to mark the entry for exclusion from reports (Health Check, HIBP). To be used e. g. for entries with a known-bad password that's out of the user's control (e. g. ATM PIN). The flag is stored in the entry's custom data.

Adds a context menu to the Health Check and HIBP reports with which the user can toggle the "exclude from reports" flags. In addition, these reports have received a checkbox to show excluded entries anyway, making it easy to undo the setting.

Closes #4168.

## Screenshots
[TIP]:  # ( Do not include screenshots of your actual database! )

Screenshot from 2020-04-03 14 58 58

Screenshot from 2020-04-03 21 56 20

## Testing strategy
[NOTE]: # ( Please describe in detail how you tested your changes. )
[TIP]:  # ( We expect new code to be covered by unit tests and documented with doc blocks! )

Tested manually. Also added checks to `TestGui::testEditEntry`.

## Checklist:
[NOTE]: # ( Please go over all the following points. )
[NOTE]: # ( Again, remove any lines which don't apply. )
[NOTE]: # ( Pull Requests that don't fulfill all [REQUIRED] requisites are likely )
[NOTE]: # ( to be sent back to you for correction or will be rejected.  )
- ✅ I have read the **CONTRIBUTING** document. **[REQUIRED]**
- ✅ My code follows the code style of this project. **[REQUIRED]**
- ✅ All new and existing tests passed. **[REQUIRED]**
- ✅ I have compiled and verified my code with `-DWITH_ASAN=ON`. **[REQUIRED]**
- ✅ I have added tests to cover my changes.

### CODE REVIEW

**Comment by wolframroesler** [comment]
Is there anything left for me to do here?

**Comment by droidmonkey** [comment]
I made the following changes:
 - Instead of showing excluded entries in gray color, I appended (Excluded) to the title and added a tooltip description. The gray color does not play well with our theming.
 - I removed the "(e.g. ...)" from the exclude setting, its pretty self explainatory

**Comment by wolframroesler** [comment]
Do you known when this will be approved/merged, @droidmonkey? I'm planning to implement offline HIBP checking (#1083) which I'd like to base on these changes to avoid conflicts.

**Comment by droidmonkey** [comment]
We can merge this today, let me finish up my review of the database icons

**Pull request merged**
