### PR TITLE
I18n fixes in Service.cpp

### PR DESCRIPTION
**Pull request by meskobalazs**
i18n fixes in Service.cpp, solving #874

### CODE REVIEW

**Comment by phoerious** [comment]
Could you rebase against release/2.2.1 please?

As a side note: we also need an English translation to handle plurals correctly. That will also allow us to change strings more freely in the future without messing up existing translations.

**Comment by meskobalazs** [comment]
Sure, I will get to it, as soon as I can.

**Comment by droidmonkey** [comment]
Yah so because you did the work on your own develop branch we can't easily rebase it...

**Comment by TheZ3ro** [comment]
Are we ready to merge this?

**Comment by droidmonkey** [comment]
I am deferring this to 2.3.0 since it breaks the translations

**Comment by phoerious** [comment]
We need an English translation to handle such cases.

**Pull request merged**
