### PR TITLE
SSH Agent: Add support for OpenSSH 8.2 FIDO/U2F keys

### LINKED ISSUE #4334: SSH Agent: Support OpenSSH 8.2 security key (FIDO/U2F) backed SSH keys
OpenSSH 8.2 added support for U2F backed ECDSA and ED25519 keys.

https://www.openssh.com/txt/release-8.2

## Summary
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
Need to implement required changes to OpenSSHKey class to support reading/writing these new keys. They are documented within OpenSSH source and are trivial to support: https://github.com/openssh/openssh-portable/blob/master/PROTOCOL.u2f

Though unfortunately there's a fatal assumption in OpenSSHKey class that all key parts are "strings" in OpenSSH slang but the new keys contain uint8 flags which can't be represented in the current internal format.

## Possible Solution
[NOTE]: # ( Not required, but suggest ideas on how to implement the addition or change )
I'm working on it. With a small hack I can add security key backed SSH keys to ssh-agent from KeePassXC so it's not a big technical requirement on our end.

OpenSSHKey internal storage format needs to be changed to either include the type of each part of a key or store them as a complete blob. Problem is KeeShare depends on the internal format of OpenSSHKey so a blob might not fit here. Possibly RSA keys could have their own class instead of depending on OpenSSHKey which is neutral to the internal structure of a key.

WIP branch (depends on agent func tests), does not pass tests because we need a bigger refactor: https://github.com/hifi/keepassxc/tree/feature/sshagent-sk-keys

## Context
It's better to support them early on so people who upgrade to newer OpenSSH can start using KeePassXC with the keys immediately. Therre's not really any overhead on KeePassXC side.

### PR DESCRIPTION
**Pull request by hifi**
Finally closes #4334 :sweat_smile: 

Shout-out to @yubico for sending me keys with up-to-date firmware to properly test this!

## Testing strategy
Manual tests with Yubikeys on Linux. Automated tests for the in-wire format.

This needs to be tested by people with Yubikeys other than me before merging.

## Type of change
[NOTE]: # ( Please remove all lines which don't apply. )
- ✅ New feature (change that adds functionality)

### CODE REVIEW

**Comment by networkException** [comment]
I tried testing this branch a database but unlocking failed due to a HMAC mismatch (the database has a hardware key as an additional credential)

**Comment by hifi** [comment]
That may be an older pre-release bug and this just needs a rebase. Does the current develop/snapshot work for you?

**Comment by networkException** [comment]
Yep develop works fine. I tried to do a quick rebase but ~~it had conflicts, if it helps I will try to look into resolving them~~ I think I rebased it onto the wrong branch

**Comment by networkException** [comment]
Rebasing onto develop resolved the unlocking issue and using ed25519-sk works flawlessly! The key is only present in the agent when unlocked as expected and I need to confirm with touching the yubikey. Great work :+1:

**Comment by droidmonkey** [comment]
@hifi is this ready for review? Probably needs a rebase on develop.

**Comment by hifi** [comment]
@droidmonkey should be ready for review now. Not sure what that test failure was but I rebased and the code looks pretty much identical.

**Comment by leonlag** [comment]
Adding and removing ed25519-sk keys on fedora 34 using a solokey v1 works for me. Thanks for your great work!

**Review by droidmonkey — APPROVED** [review]
Beautiful code @hifi!

**Pull request merged**
