### PR TITLE
Implement TODO in Group::locate

### PR DESCRIPTION
**Pull request by Molytho**
* Introduce EntrySearcher::Field::Path
* Use EntrySearcher in Group::locate

## Testing strategy
Existing Group::locate tests still pass

## Type of change
- ✅ Refactor (significant modification to existing code)

### CODE REVIEW

**Comment by droidmonkey** [comment]
There is no need to introduce the path field in the entry searcher, the group field is exactly that.

**Comment by Molytho** [comment]
I don't think that it's the same. The group field doesn't match against entry's title.
I agree that it's not strictly necessary to introduce the path field. We could just search twice (first time title, second time group) but this looks ugly to me.
Otherwise, I could refactor EntrySearcher to allow matching for multiple fields in one run (as far as I have seen this is not possible at the moment. You could check if multiple SearchTerms apply but not if either one does).

Which one should I implement: Searching twice or refactoring EntrySearcher?

**Comment by droidmonkey** [comment]
You can keep the path term, we just won't document it since it's a backend feature.  I need to understand where this locate function is even used.

**Comment by Molytho** [comment]
It is used twice:
1. In the locate cli command which could be removed and replaced with a proper search command
2. In the clip cli command which I think it should be replaced anyway because locate also matches for group hierarchy which is kind of nonesense for a command which expects exactly one match with its search term

I want to improve cli anyway so we could just drop the locate method and I replace the locate command with a proper search command and adjust clip command code

**Comment by droidmonkey** [comment]
Let's eliminate group::locate and refactor where it's used. I agree with your assessment.

**Comment by Molytho** [comment]
I opened a need PR for removing it

**Pull request closed without merging**
