### PR TITLE
Document where the binary is created

### PR DESCRIPTION
**Pull request by tredondo**
## Type of change
- ✅ Documentation (non-code change)

### CODE REVIEW

**Comment by droidmonkey** [comment]
Why is this necessary? The instructions are telling you how to install it properly. This is also already stated in the section above.

**Comment by tredondo** [comment]
It's useful for the user to run it as a development/test version before installing it.

**Comment by droidmonkey** [comment]
> These steps place the compiled KeePassXC binary inside the ./build/src/ directory.

**Comment by tredondo** [comment]
BTW, the binary just built from the master branch is 93,399,512 bytes, while the 2.6.6 one is only 6.3MB. Did I miss a flag to compress it?

I used `cmake -DWITH_XC_ALL=OFF ..`.

**Comment by droidmonkey** [comment]
The default build type is debug.  -DCMAKE_BUILD_TYPE=Release

**Comment by tredondo** [comment]
Thanks, mMakes sense. https://github.com/keepassxreboot/keepassxc/wiki/Building-KeePassXC says the default build type is "Snapshot". Would help to mention debug symbols are included.

**Comment by droidmonkey** [comment]
That isn't a build type that is an internal designator.

**Comment by tredondo** [comment]
I've run `cmake ... -DKEEPASSXC_BUILD_TYPE=Release` but I still get a 93,399,512-byte binary.

First, I've found that running `cmake` after I had built with `-DWITH_XC_ALL=ON`, resulted in all features ON, even though many were clearly off:

```
$ cmake -DWITH_XC_YUBIKEY=ON -DWITH_XC_BROWSER=ON -DWITH_XC_NETWORKING=OFF -DWITH_XC_SSHAGENT=ON -DWITH_XC_KEESHARE=OFF -DWITH_XC_KEESHARE_SECURE=OFF -DWITH_XC_UPDATECHECK=OFF -DWITH_TESTS=OFF -DWITH_GUI_TESTS=OFF -DKEEPASSXC_BUILD_TYPE=Release ..
-- Found Git HEAD Revision: 9c108b9

-- Setting up build for KeePassXC v2.6.6

-- Including translations...

-- Using asciidoctor: /usr/bin/asciidoctor
-- Enabled features:
 * Auto-Type, Automatic password typing
 * Networking, Compile KeePassXC with network access code (e.g. for downloading website icons)
 * KeePassXC-Browser, Browser integration with KeePassXC-Browser
 * SSHAgent, SSH agent integration compatible with KeeAgent
 * KeeShare, Sharing integration with KeeShare (requires quazip5 for secure containers)
 * YubiKey, YubiKey HMAC-SHA1 challenge-response
 * FdoSecrets, Implement freedesktop.org Secret Storage Spec server side API.

-- Disabled features:
 * UpdateCheck, Automatic update checking

-- Configuring done
-- Generating done
-- Build files have been written to: /home/tredondo/keepassxc/build
```

Predictably, `make` created a 118,152,776-byte binary. So I ran `rm -rf *` in the `build` directory, then the same `cmake` line above did show the features disabled correctly. However, the executable was still ~93MB.

```
$ rm -rf *
$ cmake -DWITH_XC_YUBIKEY=ON -DWITH_XC_BROWSER=ON -DWITH_XC_NETWORKING=OFF -DWITH_XC_SSHAGENT=ON -DWITH_XC_KEESHARE=OFF -DWITH_XC_KEESHARE_SECURE=OFF -DWITH_XC_UPDATECHECK=OFF -DWITH_TESTS=OFF -DWITH_GUI_TESTS=OFF -DKEEPASSXC_BUILD_TYPE=Release ..
-- The C compiler identification is GNU 9.3.0
-- The CXX compiler identification is GNU 9.3.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Git HEAD Revision: 9c108b9

-- Setting up build for KeePassXC v2.6.6

-- Performing Test CC_HAS_Werror_format_security
-- Performing Test CC_HAS_Werror_format_security - Success
-- Performing Test CXX_HAS_Werror_format_security
-- Performing Test CXX_HAS_Werror_format_security - Success
-- Performing Test CC_HAS_Werror_implicit_function_declaration
-- Performing Test CC_HAS_Werror_implicit_function_declaration - Success
-- Performing Test CC_HAS_Wcast_align
-- Performing Test CC_HAS_Wcast_align - Success
-- Performing Test CXX_HAS_Wcast_align
-- Performing Test CXX_HAS_Wcast_align - Success
-- Performing Test CC_HAS_Qunused_arguments
-- Performing Test CC_HAS_Qunused_arguments - Failed
-- Performing Test CXX_HAS_Qunused_arguments
-- Performing Test CXX_HAS_Qunused_arguments - Failed
-- Performing Test CXX_HAS_fsized_deallocation
-- Performing Test CXX_HAS_fsized_deallocation - Success
-- Found LibGPGError: /usr/lib/x86_64-linux-gnu/libgpg-error.so  
-- Found Gcrypt: /usr/lib/x86_64-linux-gnu/libgcrypt.so (Required is at least version "1.7.0") 
-- Found Argon2: /usr/lib/x86_64-linux-gnu/libargon2.so  
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.11") 
-- Found QREncode: /usr/lib/x86_64-linux-gnu/libqrencode.so  
-- Found sodium: /usr/lib/x86_64-linux-gnu/libsodium.so (Required is at least version "1.0.12") 
-- Found YubiKey: /usr/lib/x86_64-linux-gnu/libyubikey.so;/usr/lib/x86_64-linux-gnu/libykpers-1.so  
-- Performing Test HAVE_PR_SET_DUMPABLE
-- Performing Test HAVE_PR_SET_DUMPABLE - Success
-- Performing Test HAVE_MALLOC_H
-- Performing Test HAVE_MALLOC_H - Success
-- Performing Test HAVE_MALLOC_USABLE_SIZE
-- Performing Test HAVE_MALLOC_USABLE_SIZE - Failed
-- Performing Test HAVE_RLIMIT_CORE
-- Performing Test HAVE_RLIMIT_CORE - Success
-- Found X11: /usr/include   
-- Looking for XOpenDisplay in /usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-gnu/libXext.so
-- Looking for XOpenDisplay in /usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-gnu/libXext.so - found
-- Looking for gethostbyname
-- Looking for gethostbyname - found
-- Looking for connect
-- Looking for connect - found
-- Looking for remove
-- Looking for remove - found
-- Looking for shmat
-- Looking for shmat - found
-- Found Readline: /usr/include  
-- Including translations...

-- Using asciidoctor: /usr/bin/asciidoctor
-- Enabled features:
 * Auto-Type, Automatic password typing
 * KeePassXC-Browser, Browser integration with KeePassXC-Browser
 * SSHAgent, SSH agent integration compatible with KeeAgent
 * YubiKey, YubiKey HMAC-SHA1 challenge-response

-- Disabled features:
 * Networking, Compile KeePassXC with network access code (e.g. for downloading website icons)
 * KeeShare, Sharing integration with KeeShare (requires quazip5 for secure containers)
 * UpdateCheck, Automatic update checking
 * FdoSecrets, Implement freedesktop.org Secret Storage Spec server side API.

-- Configuring done
-- Generating done
-- Build files have been written to: /home/tredondo/keepassxc/build
$ make
[  0%] Generating keepassx_ar.qm
...
[100%] Built target docs
$ ls -al src/keepassxc
-rwxrwxr-x 1 tredondo tredondo 93399512 Dec  1 18:20 src/keepassxc
$ sha256sum src/keepassxc
6a049726721a054cbf97985c7a4ecb1754824c2a318ad3ec6c7896b98c305c16  src/keepassxc
```

**Comment by tredondo** [comment]
Looks like the [build options](https://github.com/keepassxreboot/keepassxc/wiki/Building-KeePassXC#build-options) list an outdated `-DKEEPASSXC_BUILD_TYPE`? Using that option still generated a large build, but using `-DCMAKE_BUILD_TYPE` as you said, generated a <6MB one. Thanks.

**Comment by droidmonkey** [comment]
It's not outdated, it serves a completely different purpose.

**Pull request closed without merging**
