### PR TITLE
insert newDatabase icon in ToolBar

### LINKED ISSUE #203: Add a new database button to the left of open
## Expected Behavior
In addition to an open button, there should be a new button

## Current Behavior
For some reason the open button made me think it was a new button, and the unlabeled dialog confused me tremendously.

## Steps to Reproduce (for bugs)
1. Open KeePassXC.app
2. Look at toolbar

## Your Environment
* KeePassXC 2.1
* macOS

### PR DESCRIPTION
**Pull request by TheZ3ro**
## Description

insert newDatabase icon in ToolBar, fix #203 

## Screenshots (if appropriate):
(this screenshot shows the 16x16 icon, I've added a new commit with the correct 22x22 icon)
istantanea_2017-02-11_12-14-52

## Types of changes

- ✅ Bug fix (non-breaking change which fixes an issue)

## Checklist:

- ✅ I have read the **CONTRIBUTING** document. **[REQUIRED]**
- ✅ My code follows the code style of this project. **[REQUIRED]**
- ✅ All new and existing tests passed. **[REQUIRED]**

### CODE REVIEW

**Comment by TheZ3ro** [comment]
I think we should assign a new KeySequence to the newEntry event and use CTRL+N for the new database.

Yeah, I've used an old branch I was working on for other ui-related issues and forgot to change.

**Comment by phoerious** [comment]
Fine by me. Ctrl+N for new DB and Ctrl+Shift+N for new entry?

**Comment by TheZ3ro** [comment]
Yeah, Done

**Comment by TheZ3ro** [comment]
Fixed a typo with a force push

**Comment by jsoref** [comment]
I'm not sure about the wholesale reassignment of cmd-n.

If you don't have a database open, then cmd-n can't possibly do *anything* useful as new-entry, and thus mapping it to new-database is a good idea.

But, if you have a database open, the most common action is new-entry, and thus I'd argue in favor of it doing that instead of new-database. (With cmd-shift-n as a reasonable alternate for this case.)

**Comment by phoerious** [comment]
I would argue that Ctrl+N is almost always used for creating a new document and a document in our case is a database, not a single entry.
Besides, Ctrl+Shift+N is not so complicated that it would become a burden to use.

**Comment by droidmonkey** [comment]
It could be contextual. If you are not inside an active database CTRL+N could be new database. If you ARE inside an active database CTRL+N could be new entry.

**Comment by phoerious** [comment]
I was thinking about that solution as well, but I suppose that would be rather confusing. That would maybe be a practicable solution if only one of those shortcuts worked at the same time. But you can always create a new database, even if you already have one.

**Comment by jsoref** [comment]
While you can create a database if you have one, you are unlikely to want to, and thus it really shouldn't be the default action.

One could make the half-argument that an entry `is a document` which is why ^N is the right marking for it, but in the case where you don't have a document-container, we're defaulting to creating the container first.

A slightly different model would be that ^N always creates a new entry, and if you don't have a database what it does is creates the new database and inserts a new entry into it so that you're always creating a new entry :-) -- that might be easier to reason through...

**Comment by phoerious** [comment]
I would leave it as is, but we can discuss switching the shortcuts.
Having context-dependent shortcuts, however, is too confusing.

**Comment by jsoref** [comment]
That's fine.

I'd strongly encourage you to make ^N the new entry key*. Users may have 2-3 databases, but they'll have hundreds of entries. They're much more likely to be creating entries than databases, and if they've  been using KeyPass or others in the past (including KeyChain.app), that's the action that they expect.

For reference, macOS has 3 levels of commands:
1. cmd-N -- normal actions
1. cmd-shift-N -- related actions
1. cmd-option-N -- exotic but related actions

For KeyChain.app, new item is in the first category, and new database is in the last. -- A keychain is the KeyChain.app equivalent of a KeePass database.

http://web.archive.org/web/20170212220541im_/https://circleci.com/docs/assets/img/docs/ios-getting-started-keychain-file-menu.png
image

* by `^`, I mean "whatever is the first level thing" -- on macOS that's command and .everywhere else that's control.

**Comment by TheZ3ro** [comment]
If we want to make a behavior based shortcut (that is pretty confusing for users already), I think we should go for "^N default shortcut for create a new entry, if no database opened, open a database and create entry."

Otherwise (if we don't want a behavior based) we should decide and stick with that.

**Comment by jsoref** [comment]
My general preference is just ^N = new-entry, but short of that, the other behavior that @TheZ3ro doesn't mind would be my second choice.

**Comment by phoerious** [comment]
Having used develop for a while now, I think it is actually a good idea to switch the hotkeys. Use Ctrl+N for new entry and Ctrl+Shift+N for new database.

**Comment by TheZ3ro** [comment]
I will revert this PR this afternoon

**Comment by phoerious** [comment]
Just make a new PR that switches the shortcuts.

**Comment by TheZ3ro** [comment]
Yep (reverting always mean doing a new PR)

**Comment by MasinAD** [comment]
From a usability point of view, the omission of the "New Document" icon in the toolbar was one of the greater improvements. As creation of new databases is something users rather seldomly do it's not necessary to expose it prominently.

Thus said, I am curious what has been your rationale for adding it again?

**Comment by TheZ3ro** [comment]
@MasinAD for new users it's fundamental to have a new database icon right in front of their eyes. Also, if you open a document with LibreOffice or Geany, the first button is a new document button

**Comment by MasinAD** [comment]
I do understand that new users should have an easy and obvious way to
create a new database but you already have the "empty" view with a big
button to create a new database – which is a really great way to introduce
new users to KeePassXC.

But the icon will only be used once or twice for almost any user and just
takes screen estate after that. The comparison with LibreOffice or Geany
doesn't convince me because working with documents and creating many of
those is a core workflow of those programs but creating databases or
keyrings is not for a password manager. That said, I noticed the discussion
about hotkeys. It might seem sensible to use ctrl+n for a new database as a
database is currently seen as the analogy to a document in other
applications. I would rather see creation of a database analogous to
configuring an e-mail account in an e-mail client. You'd do it at least
once but very rarely more often than just a handful of times.

**Comment by droidmonkey** [comment]
Thanks for your feedback but i don't foresee this PR being reverted without major community backlash.

**Comment by MasinAD** [comment]
Is there some kind of forum where to discuss such decisions? I understand the Github issue tracker might not be the best fit for it.

As to my motivation: I administrate about 100 client PCs of which about half are Ubuntu clients. Most of my users are computer literate but no enthusiasts. I need to provide them tools with as little friction in day-to-day use as possible. KeePassX works nice, but is lacking in a few areas (you might have noticed ;-) ). KeePassXC has tons of improvements, but I get the feeling the design decisions are not always … well reasoned, in lack of better words.

At my workplace, we have some UX experts. If you want I could ask them to take a look at the current state of the KeePassXC UI.

**Comment by phoerious** [comment]
No, there is no forum. We prefer to keep discussions in one place.
We are open to well-founded UX concerns, but they have to be beyond "I like that better" or "I think people would prefer…" or "In our firm, users don't understand…"

**Comment by MasinAD** [comment]
Well, what had been your reasoning to re-introduce that button, then? Might
be a good start. :-)

2017-07-16 19:33 GMT+02:00 Janek Bevendorff <notifications@github.com>:

**Comment by phoerious** [comment]
Consistency with other applications.

**Comment by droidmonkey** [comment]
If you really don't like it just comment it out and compile the application for your firm.

**Pull request merged**
