### PR TITLE
feature/passwdExpDaysDiff

### LINKED ISSUE #4896: Password expiration presets should be in DAYS
## Overview
presets

The time interval **presets available on the dropdown menu** (to the right of the _Expires_ datetime field) are currently as follows: {1, 2, 3} **weeks**, {1, 3, 6} **months**, or {1, 2, 3} **years**.  Furthermore, they don't seem to be configurable.  

This is not really useful, because mandatory password change times are usually given in **numbers of days**, and while a week always has seven days, a month can have from 28-31 and a year 365-366.  Thus, these units are too imprecise.

Here's a quick survey:

> The password reset timer in Windows Server products is still **42 days**.

([source](https://www.extremetech.com/computing/292534-microsoft-says-forced-password-resets-dont-improve-security))

### Okta
Single sign on (SSO) provider Okta uses **120 days** as the default ([source](https://support.okta.com/help/s/article/How-to-find-a-user-s-password-expiration-date))
> You can configure this setting for **1–999 days**.  ([source](https://help.okta.com/en/prod/Content/Topics/Security/Security_Policies.htm))

(Okta also has a **minimum required duration**, before which the password cannot be changed.  This is given in hours or days.  This is to prevent a user from changing their password back to an old one.)

### RedHat
RedHat's [LDAP admin documentation](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/6/html/identity_management_guide/user-pwdpolicy#tab.pwpolicy-attrs) says they do something similar to Okta, providing parameters
> --maxlife  [...]  The default value is 90 days.
> --minlife  [...]  The default value is one hour.

## Feature Requests
- Please let us specify the expiration in **number of days from now**.
- Please let us **modify the presets**, ideally on a site by site basis, since everybody has a different default.  (I find myself writing this info in the notes field, along with the password requirements.)
- Perhaps the date picker could have a field or mouseover that tells us how many days we are in the future?
- Please let us have a notification when one is about to expire (this, of course, requires a threshold value, a "time to expiration").  Notification is not needed for every entry, but probably only one or two critical ones.  (Inevitably, the same organizations requiring periodic changes are going to make it tedious to recover from missing one!)  Currently, I put an alarm in my calendar for this.

## Other Implementations
- Here is what [Keepass has done](https://sourceforge.net/p/keepass/feature-requests/1483/).
- LastPass, sounds like they [haven't done anything yet](https://forums.lastpass.com/viewtopic.php?f=7&t=369505&p=1225335&hilit=expiration#p1225335).
- PwSafe calls it [recurring password expiration](https://www.microsoft.com/en-us/p/password-safe-store-edition/9p36mk26tt4x?cid=msft_web_chart&activetab=pivot:overviewtab).

### PR DESCRIPTION
**Pull request by shemeshg**
[NOTE]: # ( Describe your changes in detail, why is this change required? )
Added Days to expiration date of PasswordEntry and GroupEntry
[NOTE]: # ( Explain large or complex code modifications. )
[NOTE]: # ( If it fixes an open issue, please add "Fixes #XXX" )
Fixes #4896

## Screenshots
[TIP]:  # ( Do not include screenshots of your actual database! )
Screen Shot 2021-10-08 at 19 30 53
Screen Shot 2021-10-08 at 19 30 40

## Testing strategy
[NOTE]: # ( Please describe in detail how you tested your changes. )
1. On the Entry
1.1 Change "expireDateInDays" see it affect "expireDatePicker" correctly.
1.2 Change "expireDatePicker"  see it affect "expireDateInDays" correctly.
1.3 "expireDateInDays" min value is 0 (no negative)
1.4 Use preset button effect "expireDatePicker" and "expireDateInDays" correctly.
2. Repeat step 1.1, 1.2 1.3 for Group Entry

[TIP]:  # ( We expect new code to be covered by unit tests and documented with doc blocks! )
N/A

## Type of change
[NOTE]: # ( Please remove all lines which don't apply. )
- ✅ Bug fix (non-breaking change that fixes an issue)
- ✅ New feature (change that adds functionality)

### CODE REVIEW

**Comment by shemeshg** [comment]
It is a bit simplified, 
having it in weeks and months would require more effort of coordinating the changes of three controls 
- Dropdown.
- Spinner 
- and Date
and maybe even storing the value of the additional dropbox, and verbose UI

Tell me if it is sufficient or Over simplified

**Comment by droidmonkey** [comment]
I'm confused, I'd this a static value or meant to be a user editable field? If static, this should just appear on the entry preview panel.

**Comment by shemeshg** [comment]
> I'm confused, I'd this a static value or meant to be a user editable field? If static, this should just appear on the entry preview panel.

It is "user editable field", 
- the days field is bound to the DateTime Drop down
- and vice versa 

You can set expiration date with the Days QSpinner or the QDateTimeEdit

See "Testing strategy" above

**Comment by shemeshg** [comment]
Hi

I've just seen: #6456 

Though it is different because it is for Password Change only, yet:
Maybe current PR could be integrated into  #6456
And these reactive  QSpinner of "Days" integrated to the new rubric is designed in #6456 
(and the EditGroup dialog [that is not part of the #6456 as I saw] )

Or even better maybe consider this PR to be rewritten as part of #6456 by @xvallspl
Since 
1. these are really small changes of few lines. 
2. merging of these  UI files would yield a conflict with no sense to resolve (except manually adding the QSpinner).

Tags: #2010 #6456

**Comment by droidmonkey** [comment]
Closing this in favor of the above solution.

**Pull request closed without merging**
