### PR TITLE
New base32 implementation

### PR DESCRIPTION
**Pull request by adolfogc**
This PR provides a new base32 encode/decode implementation, following RFC 4648.

## Description
- ~~Creates a new directory, `src/tools`, for this type of utilities.~~
- Implements missing `Base32::encode`.
- Re-implements `Base32::decode`.
- Changes code base to use the new `Base32::decode` interface, as it now returns an optional value.
- Adds new separate tests for these functions.
- Removes `src/totp/base32.h` and `src/totp/base32.cpp`
- Updates licensing information.

## Motivation and context
The motivation for this PR is given in #964.

## How has this been tested?
- ~Tested on Linux with ASAN enabled, by running `build/tests/testbase32`.~
- Tested on Linux using:
```bash
mkdir build && cd build
cmake -DWITH_ASAN=ON -DCMAKE_BUILD_TYPE=Debug ..
make -j4

# run tests in ./tests
```

## Types of changes
- ✅ New feature (non-breaking change which adds functionality)
- ✅ Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- ✅ I have read the **CONTRIBUTING** document. **[REQUIRED]**
- ✅ My code follows the code style of this project. **[REQUIRED]**
- ✅ All new and existing tests passed. **[REQUIRED]**
- ✅ I have compiled and verified my code with `-DWITH_ASAN=ON`. **[REQUIRED]**
- ✅ I have added tests to cover my changes.

### CODE REVIEW

**Comment by TheZ3ro** [comment]
@droidmonkey what about using `src/crypto` folder for Base32 encoding?

Anyway @adolfogc can you apply the following patch to `/COPYING` file and also delete `/LICENSE.APACHE-2.0` file? (so we finally clean up that Google's base32 forever)

```
--- a/COPYING
+++ b/COPYING
@@ -214,10 +214,6 @@
 Copyright: none
 License: public-domain
 
-Files: src/crypto/salsa20/*
-Copyright: none
-License: public-domain
-
 Files: src/streams/qtiocompressor.*
        src/streams/QtIOCompressor
        tests/modeltest.*
@@ -242,8 +238,3 @@
            2014 Dominik Haumann <dhaumann@kde.org>
 License: LGPL-2.1
 
-Files: src/totp/base32.cpp
-       src/totp/base32.h
-Copyright: 2010 Google Inc.
-License: Apache 2.0
-
```

**Comment by TheZ3ro** [comment]
Another thing, @adolfogc your tests fail on [TravisCI](https://travis-ci.org/keepassxreboot/keepassxc/builds/279062517) with `-DCMAKE_BUILD_TYPE=Debug`

`QFATAL : TestBase32::testDecode() ASSERT: "6 == nPads" in file /home/travis/build/keepassxreboot/keepassxc/src/tools/base32.cpp, line 74`

**Comment by droidmonkey** [comment]
Concur with placing in crypto folder or core folder

**Comment by adolfogc** [comment]
Where should `tools/optional.h` be placed?

**Comment by adolfogc** [comment]
@TheZ3ro Thanks, I reorganized the switch statement and removed that Q_ASSERT. Also, I updated the licensing information. I decided to move all three files to `src/core`.

**Comment by droidmonkey** [comment]
Beautiful implementation

**Comment by adolfogc** [comment]
@droidmonkey Thanks

**Comment by TheZ3ro** [comment]
Last thing before merging, can you rebase on top of latest develop? Thank :+1:

**Comment by adolfogc** [comment]
@TheZ3ro Just rebased to the latest develop.

**Pull request merged**
