### PR TITLE
Optimize includes and forward declarations

### PR DESCRIPTION
**Pull request by SyPeter**
We saw potential in optimizing the includes and applied our tool to it. This results in over 300 less lines of code and faster compilation. This is achieved by:
* Removing unnecessary includes in all files
* Using forward declarations instead of includes if possible
* Split Entry.h into two files (new file is EntryInc.h)

## Testing strategy
* We executed all unit tests and they passed.
* KeePassXC starts like usual.

## Type of change
- ✅ Refactor (significant modification to existing code)

### CODE REVIEW

**Comment by droidmonkey** [comment]
Why do you revert the commit and reapply? It makes it impossible to see the difference between tries. I have no idea what you are changing to try to make it work.

**Comment by SyPeter** [comment]
> Why do you revert the commit and reapply? It makes it impossible to see the difference between tries. I have no idea what you are changing to try to make it work. You should squash the revert and new commit to show the diff from the previous one.

I have to modify the tool that it works for all platforms, so the commits are different in some changes. Unfortunately, I cannot test it for all platforms in all configurations offline. I will try to do iterative changes so that the diffs are easier to see.

**Comment by droidmonkey** [comment]
No worries, I did the squashing so we can compare the attempts

**Comment by droidmonkey** [comment]
Can you allow us to push to your branch? Otherwise you'll need to make these edits:

* Add gui/Icons.h to MainWindow.cpp
* Add gui/osutils/osUtils.h to Icons.cpp

**Comment by phoerious** [comment]
I am very sceptical of these changes. You modified 432 files and since header files do change rather often and unpredictably, you are more likely to break than to fix something. In fact, the CI already fails in several places. Only because a header include is not needed on your system, doesn't mean it's not needed on another platform.

**Comment by SyPeter** [comment]
CI pipeline finally goes through :-) Are any other changes wanted like removing certain forward declarations for their corresponding include files?

**Comment by droidmonkey** [comment]
The optimizer made some questionable changes like dropping paired header in the corresponding cpp file. I corrected those by hand and removed some other undesirable optimizations.

Note: group.h has hard requirements due to friend relationships with specific functions in database & entry.

This PR still needs more review, I am about 50% done.

**Review by droidmonkey — APPROVED** [review]
I went through all these changes and made manual edits where necessary. Also introduced another commit that removes unnecessary headers now that this cleanup is done.

**Pull request merged**
