### PR TITLE
don't change command.name on every execute()

### PR DESCRIPTION
**Pull request by sjamesr**
[TIP]:  # ( Provide a general summary of your changes in the title above ^^ )

## Type of change
[NOTE]: # ( Please remove all lines which don't apply. )
- ✅ Bug fix (non-breaking change which fixes an issue)

## Description and Context
Fixes mutation of command.name every time the command is executed, bug manifests in upcoming interactive mode.

## Checklist:
- ✅ I have read the **CONTRIBUTING** document. **[REQUIRED]**
- ✅ My code follows the code style of this project. **[REQUIRED]**
- ✅ All new and existing tests passed. **[REQUIRED]**
- ✅ I have compiled and verified my code with `-DWITH_ASAN=ON`. **[REQUIRED]**

### CODE REVIEW

**Comment by droidmonkey** [comment]
Why not just include this in the other PR?

**Comment by sjamesr** [comment]
I can do that too, just thought the other PR might take longer to get in.

**Comment by droidmonkey** [comment]
Nah go ahead and combine it, I will push the interactive PR through quickly

**Comment by sjamesr** [comment]
Moved to other PR.

**Pull request closed without merging**
