### PR TITLE
Fix minimize at startup

### PR DESCRIPTION
**Pull request by intika**
## Type of change
- ✅ Bug fix (non-breaking change which fixes an issue)
- ✅ New feature (non-breaking change which adds functionality)
- ✅ Breaking change (fix or feature that would cause existing functionality to change)

## Description and Context
This permit to start the application minimized to system tray
If the system tray is disabled the application will start minimized to the taskbar

## Feature 
Start minimized/hidden to tray 

## Current Behavior
 Keepassxc is started minimized to taskbar

## New Behavior
Keepassxc will start to system tray 
If system tray is disabled Keepassxc start minimized 

## Testing strategy
`mainWindow.hideWindow();` already check if system tray setting is enabled before hiding the window otherwise the window is minimized.

## Checklist:
- ✅ I have read the **CONTRIBUTING** document. **[REQUIRED]**
- ✅ My code follows the code style of this project. **[REQUIRED]**
- ✅ All new and existing tests passed. **[REQUIRED]**
- ✅ I have compiled and verified my code with `-DWITH_ASAN=ON`. **[REQUIRED]**

### CODE REVIEW

**Comment by droidmonkey** [comment]
This causes a crash on Windows. Also do not do a pull request from a private repository.

**Comment by intika** [comment]
I will check and fix windows issue later on when i'll be back to my windows machine (soon)... the repo is not private i just delete it after the PR

**Comment by droidmonkey** [comment]
Don't do that either :-)

**Comment by intika** [comment]
No prob i'll keep an active public fork with my up-coming changes

**Pull request closed without merging**
