### PR TITLE
Fix major visual glitches

### PR DESCRIPTION
**Pull request by phoerious**
## Description
This PR fixes major visual glitches, most of them occurring on OS X (but partly also on other platforms). It therefore fixes almost all issues described in #295. The error message bug, however, has not been fixed, because inline messages have not been merged into the current release branch.

## Motivation and Context

The KeePassXC interface contains many minor layout inaccuracies and some major visual bugs. Most of these issues appear on OS X, because Qt apparently cannot emulate native Mac widgets too well.

## How Has This Been Tested?

All changes have been tested on Mac OS X 10.12 Sierra. Some of the fixes require adding arbitrary paddings to widgets and layouts. **It would therefore be good if someone could test this on other OS X versions before this patch gets merged.**

The changes were also verified on Arch Linux with KDE Plasma 5.9 (Breeze) and Windows 10 to ensure they didn't break anything or that an issue was fixed on those platforms as well if it wasn't a Mac-only problem.

The GUI tests were run on Arch Linux (KDE) and still pass.

### Unlock dialog
I aligned the keyfile combobox and "Browser" button left and right.

Before:
unlock_before

After:
unlock_after

### Change master key dialog
I assigned the password fields a proper width. The checkboxes are still tiny, because they are not really checkboxes. They really are just group boxes with the "checkable" property set. Mac is the only platform that makes a visual problem of that and there is quite a bit of code wired to this, which is why I left it as is for now.

Before:
changepw_before

After:
changepw_after

### Entry edit widget
The form layout of the edit entry widget was a real mess, resulting in the "Expires" checkbox being completely out of place (most noticeable on OS X, but also on other platforms). I reordered everything in a proper grid layout and adjusted label and field widths. On OS X, the "Expires" checkbox is still a little displaced towards the bottom, but it's a lot better now. It's perfect on Plasma 5.

Before:
expires_before
After:
expires_after

In addition to these changes, I also adjusted the margins around the dynamic password generator widget inside the edit entry widget.

Before:
passwordgen_before

After:
passwordgen_after

Furthermore, the "+" and "-" buttons for adding or removing window title rules in the auto-type settings of an entry had a very weird problem on OS X. Although they were identical QPushButtons, one of them looked completely different from the other. I morphed the QPushButtons into QToolButtons, adjusted their width and height and moved the spacer to the left.

Before:
autotype_before
After:
autotype_after

### Database settings
The most dramatic changes were performed on the database settings widget. The form elements had basically no layout at all and the "Use recycle bin" checkbox had no proper text. It only a label to the left instead (which is the wrong side). I reorganized all form elements in a centered grid layout with a max width of 800. I also changed the "Benchmark" QPushButton to a QToolButton, because the QPushButton caused major layout shifts on OS X.

Before:
dbsettings_before

After:
dbsettings_after

### HTTP settings
I changed the default tab of the KeePassHTTP settings to "General" instead of "Advanced". This is the only thing I changed in the settings. A general settings rework is a task for 2.2.0.

### About dialog
I removed the `www.` from the URL and made the "Using:" and "Extensions:" labels selectable. 

## Types of changes

- ✅ Bug fix (non-breaking change which fixes an issue)

## Checklist:

- ✅ I have read the **CONTRIBUTING** document. **[REQUIRED]**
- ✅ My code follows the code style of this project. **[REQUIRED]**
- ✅ All new and existing tests passed. **[REQUIRED]**

### CODE REVIEW

**Comment by phoerious** [comment]
@sfeary @jsoref @ligyxy Could you maybe test these changes? I hope everything looks the same on other Macs.

**Comment by phoerious** [comment]
I added another commit which pixel-perfects the different entry edit widgets on Linux and Windows.

Before:
edit_before

After:
edit_after

**Comment by jsoref** [comment]
What you have done is a vast improvement over what was.

A few minor thoughts:
In 5 the Expires text doesn't appear vertically centered wrt the edit box. I believe it should be.
Also the drop down and edit box don't appear to have the same top/bottom/center.

For the Unlock dialog, it feels like the browse+ok buttons aren't quite right aligned w/ the show password button.

**Comment by phoerious** [comment]
Can you compare with the screen shots? The "Expires" checkbox should look the same as in the "after" screen shot. It isn't perfectly centered, but that's as good as I can make it. Qt on OS X really is a mess and some things just don't look right and there is not much I can do about it. PushButtons are the worst. They introduce arbitrary spacings which can completely destroy a layout.

**Pull request merged**
