### PR TITLE
minor improvements to the documentation

### PR DESCRIPTION
**Pull request by Mo-Gul**
## Type of change
- ✅ Documentation (non-code change)

Feel free to cherry-pick if you don't like some of the changes.

Is it intended that you don't use the `btn:` or `menu:` features of AsciiDoctor?
<https://docs.asciidoctor.org/asciidoc/latest/macros/ui-macros/>

### CODE REVIEW

**Comment by droidmonkey** [comment]
We don't use btn or menu because they are still marked as experimental. I also played around with them and found no real benefit.

**Comment by Mo-Gul** [comment]
You are right, one has to set the `experimental` flag, but as it is written at the beginning of the quoted page:

> Although this attribute is named experimental, the UI macros are considered a stable feature of the AsciiDoc language. The requirement to specify the attribute is merely an optimization for the processor.

I just wanted to make sure you _know_ about them. Then you can make a qualified decision to use or not to use them. But _if_ you would use them, it is more likely to use/have the same style for the same thing. Here some random examples I remembered while reading the "Getting Started Guide".

## Menu

https://github.com/keepassxreboot/keepassxc/blob/3e3e87d3c59c7dbf5d424254f8c466592ced15c9/docs/topics/UserInterface.adoc#L36

https://github.com/keepassxreboot/keepassxc/blob/3e3e87d3c59c7dbf5d424254f8c466592ced15c9/docs/topics/PasswordGenerator.adoc#L15

## Button

https://github.com/keepassxreboot/keepassxc/blob/3e3e87d3c59c7dbf5d424254f8c466592ced15c9/docs/topics/DownloadInstall.adoc#L27

https://github.com/keepassxreboot/keepassxc/blob/3e3e87d3c59c7dbf5d424254f8c466592ced15c9/docs/topics/DownloadInstall.adoc#L41

https://github.com/keepassxreboot/keepassxc/blob/3e3e87d3c59c7dbf5d424254f8c466592ced15c9/docs/topics/AutoType.adoc#L33

**Comment by sorairolake** [comment]
I suggest not changing the hyphen in man pages because Asciidoctor returns an error.

**Review by droidmonkey — APPROVED** [review]
I reverted the em-dash conversion on the man pages and squashed the rest

**Pull request merged**
