### PR TITLE
:bug: Fix result propagation in SymmetricCipherGcrypt::process

### PR DESCRIPTION
**Pull request by petermax2**
## Description

The boolean parameter `ok` has always been set to `true`, regardless of possible errors.

## Motivation and context

I found this bug while skimming through the source code.

## How has this been tested?

not tested. testing would require to pass a faulty crypto block to `SymmetricCipherGcrypt::process`.

## Types of changes

- ✅ Bug fix (non-breaking change which fixes an issue)

## Checklist:

- ✅ I have read the **CONTRIBUTING** document. **[REQUIRED]**
- ✅ My code follows the code style of this project. **[REQUIRED]**
- ✅ All new and existing tests passed. **[REQUIRED]**
- ✅ I have compiled and verified my code with `-DWITH_ASAN=ON`. **[REQUIRED]**

### CODE REVIEW

**Comment by phoerious** [comment]
Could you change the target to release/2.2.2 please? Thanks!

**Comment by petermax2** [comment]
Does this work for you or should I re-open the PR and commit to release/2.2.2?

**Comment by phoerious** [comment]
You could have just rebased your branch. ;-)

**Comment by petermax2** [comment]
Oops I did not think about that. Thank you for pointing it out! :-)

**Pull request closed without merging**
