### PR TITLE
Set SingleMainWindow in .desktop file

### PR DESCRIPTION
**Pull request by z3ntu**
Add SingleMainWindow (introduced in v1.5 of Desktop Entry Specification)
and the older key X-GNOME-SingleWindow that's more widely supported at
the moment.

This allows desktop environments to determine that the application can
only have one window open and hide options like "Open New Window".

## Screenshots

Before:

image

After:

image

## Testing strategy
[NOTE]: # ( Please describe in detail how you tested your changes. )
[TIP]:  # ( We expect new code to be covered by unit tests and documented with doc blocks! )

Install modified manually into `/usr/share/applications/org.keepassxc.KeePassXC.desktop` and observe behavior change on Plasma 5.24.1

### CODE REVIEW

**Review by droidmonkey — APPROVED** [review]

**Comment by droidmonkey** [comment]
Got some build issues:
> [ INFO ] Creating AppImage...
[09:18:59 ](https://ci.keepassxc.org/buildConfiguration/KeePassXC_UbuntuLinux/206949?showRootCauses=true&expandBuildChangesSection=true&expandBuildProblemsSection=true&showLog=206947_2257_2257&logFilter=debug)  appimagetool, continuous build (commit a2d9cfc), build <local dev build> built on 2021-11-10 17:45:54 UTC
[09:18:59 ](https://ci.keepassxc.org/buildConfiguration/KeePassXC_UbuntuLinux/206949?showRootCauses=true&expandBuildChangesSection=true&expandBuildProblemsSection=true&showLog=206947_2258_2258&logFilter=debug)  /opt/buildagent/work/c401303cba1b4098/build/KeePassXC.AppDir/org.keepassxc.KeePassXC.desktop: error: value "1.5" for key "Version" in group "Desktop Entry" is not a known version
[09:18:59 ](https://ci.keepassxc.org/buildConfiguration/KeePassXC_UbuntuLinux/206949?showRootCauses=true&expandBuildChangesSection=true&expandBuildProblemsSection=true&showLog=206947_2259_2259&logFilter=debug)  /opt/buildagent/work/c401303cba1b4098/build/KeePassXC.AppDir/org.keepassxc.KeePassXC.desktop: hint: value item "Security" in key "Categories" in group "Desktop Entry" can be extended with another category among the following categories: Settings, or System
[09:18:59 ](https://ci.keepassxc.org/buildConfiguration/KeePassXC_UbuntuLinux/206949?showRootCauses=true&expandBuildChangesSection=true&expandBuildProblemsSection=true&showLog=206947_2260_2260&logFilter=debug)  /opt/buildagent/work/c401303cba1b4098/build/KeePassXC.AppDir/org.keepassxc.KeePassXC.desktop: error: file contains key "SingleMainWindow" in group "Desktop Entry", but keys extending the format should start with "X-"

**Comment by z3ntu** [comment]
Looks like this is from `desktop-file-validate` which has only quite recently gained support for the new properties, see https://gitlab.freedesktop.org/xdg/desktop-file-utils/-/commits/master/ - pending upstream release.

**Comment by droidmonkey** [comment]
We'll have to sit on this one, may be too new to include and not break a lot of distros

**Comment by z3ntu** [comment]
As far as I understand, only desktop-file-validate complains about this, unknown keys get ignored by desktop environments anyways and should be safe to ship to older distros.

**Comment by vimpostor** [comment]
FYI KDE also respects `X-GNOME-SingleWindow=true`, so if you care about the CI linter, you can also just add the `X-GNOME-SingleWindow=true` change now, and maybe add the `Version` and `SingleMainWindow` update in a few months.

**Pull request merged**
