### PR TITLE
Fix macOS 10.15.4 codesigning crash

### LINKED ISSUE #4398: KeePassXC 2.5.3 crashes on launch on macOS 10.15.4
## Expected Behavior
KeePassXC application opens as normal

## Current Behavior
Application crashes immediately upon launch. A system dialog is opened (see attached image).
Screenshot 2020-03-03 at 21 55 40

## Steps to Reproduce
1. Upgrade to, or freshly install macOS 10.15.4 beta 3 on a Mac computer
2. Install KeePassXC by downloading from the keepassxc.org website.
3. Attempt to open the application.

## Context
Note that KeePassX runs without problems on this same beta OS.

## Debug Info
Cannot post output from app as it will not open
KeePassXC - 2.5.3
Revision: current release version

Operating system: macOS 10.15.4 beta 3
CPU architecture: x64
Kernel: Darwin

Enabled extensions:
- None (fresh installation)

### LINKED ISSUE #4515: Catalina 10.15.4 breaks Touch ID unlocking
## Expected Behavior

After enabling touch id unlocking and unlocking the database initially with the passphare, entering an empty password should allow touch id unlocking.

## Current Behavior

The touch id unlock dialog does not show. The database cannot be unlocked by touch id.

## Possible Solution
None known.

## Steps to Reproduce
* Start KeepassXC
* Unlock the database by passphrase
* Lock the database
* Leave the passphrase empty and hit return the passphrase field

## Debug Info
KeePassXC - Version 2.5.3-2
Revision: f8c962b

Qt 5.14.1
Diagnosemodus ist deaktiviert.

Betriebssystem: macOS 10.15.4
CPU-Architektur: x86_64
Kernel: darwin 19.4.0

Aktivierte Erweiterungen:
- Auto-Type
- Browser-Integration
- SSH-Agent
- KeeShare (bestätigtes und unbestätigtes Teilen)
- YubiKey
- TouchID

Kryptographische Bibliotheken:
 libgcrypt 1.8.5

### PR DESCRIPTION
**Pull request by phoerious**
The recent macOS security patch renders our codesigning "fix" of setting the sandbox entitlement to false twice unusable. This patch adds a full provisioning profile and adjusts the signing procedure to not include entitlements for Qt frameworks.

The patch also changes the app and bundle ID, so granted accessibility privileges have to be granted again after installing the update.

Fixes #4398
Fixes #4515

@droidmonkey Since this is an actual fix and not just a workaround or rebuild, I suggest we release it as 2.5.4 despite there not being any changes on other platforms. I believe the extent to which things were changed (including the bundle ID change, which was long overdue anyway) merits a version number upgrade.

[TIP]:  # ( Provide a general summary of your changes in the title above ^^ )

## Type of change
[NOTE]: # ( Please remove all lines which don't apply. )
- ✅ Bug fix (non-breaking change which fixes an issue)

## Checklist:
[NOTE]: # ( Please go over all the following points. )
[NOTE]: # ( Again, remove any lines which don't apply. )
[NOTE]: # ( Pull Requests that don't fulfill all [REQUIRED] requisites are likely )
[NOTE]: # ( to be sent back to you for correction or will be rejected.  )
- ✅ I have read the **CONTRIBUTING** document. **[REQUIRED]**
- ✅ My code follows the code style of this project. **[REQUIRED]**
- ✅ All new and existing tests passed. **[REQUIRED]**
- ✅ I have compiled and verified my code with `-DWITH_ASAN=ON`. **[REQUIRED]**

### CODE REVIEW

**Comment by droidmonkey** [comment]
Concur with the version bump

**Comment by phoerious** [comment]
Yeah, and then there are entitlements and entitlements. Some can be set just like that, others need to be whitelisted by a provisioning profile.

**Comment by droidmonkey** [comment]
I'm glad this is all thoroughly documented and doesn't require special Apple engineer intervention to figure out! 😏

**Comment by phoerious** [comment]
Oh indeed, 'twas a walk in the park.

**Pull request merged**
