### PR TITLE
Snap: improve cursor theme

### PR DESCRIPTION
**Pull request by joshirio**
[TIP]:  # ( Provide a general summary of your changes in the title above ^^ )
One issue with Qt snaps is the default cursor theme, which is a fallback theme and quite ugly. I propose the following changes to the snapcraft.yaml file to use the system cursor theme when available. Please see the following thread on the snapcraft forum for more background info and limitations of this: https://forum.snapcraft.io/t/qt-apps-and-gtk-themes-an-investigation-with-partial-success/10513

## Type of change
[NOTE]: # ( Please remove all lines which don't apply. )
- ✅ Bug fix (non-breaking change which fixes an issue)

## Description and Context
[NOTE]: # ( Describe your changes in detail, why is this change required? )
[NOTE]: # ( Describe the context of your change. Explain large code modifications. )
[NOTE]: # ( If it fixes an open issue, please add "Fixes #XXX" as necessary )

To use the system cursor theme, the snap needs to connect to the appropriate plug (icon theme plug). In addition, a new stage package is required (qt5 style plugins).
Please see screenshots below for the result.

## Screenshots
Before:
ugly

After:
fix

## Testing strategy
[NOTE]: # ( Please describe in detail how you tested your changes. )
[TIP]:  # ( We expect new code to be covered by unit tests and documented with doc blocks! )
Tested on a few different distros. Please see the forum thread above for details.
It works for example with Ubuntu and elementaryOS. Distros that don't support this will keep using the fallback cursor theme, so for them nothing changes, it has only advantages.

## Checklist:
[NOTE]: # ( Please go over all the following points. )
[NOTE]: # ( Again, remove any lines which don't apply. )
[NOTE]: # ( Pull Requests that don't fulfill all [REQUIRED] requisites are likely )
[NOTE]: # ( to be sent back to you for correction or will be rejected.  )
- ✅ I have read the **CONTRIBUTING** document. **[REQUIRED]**

### CODE REVIEW

**Comment by droidmonkey** [comment]
Given the theming drawbacks on unsupported distros, I do not see the benefit just to correct a mouse cursor. I am going to say NO to this change.

**Comment by joshirio** [comment]
With this change there's no drawback, because the default fusion style is still used. Only forcing the QGTKStyle plugin creates issues when the GTK2 settings are not exposed by the theme and or DE.

So this has only the benefit of using a correct mouse theme when available, if not, nothing changes. Since most users are on Ubuntu, I think this would be a great benefit.

**Comment by droidmonkey** [comment]
Gotcha

**Comment by droidmonkey** [comment]
This will be available on the edge channel in about 20 minutes

**Pull request merged**
