### PR TITLE
Feature/apple watch support

### LINKED ISSUE #5337: Open database using Apple Watch "double tap" confirmation feature on MacOS
Hi,

it would be great to be able to unlock the database using the Apple Watch (double tap) on MacOS. Also TouchID / FaceID like Strongbox allows it on MacOS would be great (but I don't have devices supporting this yet).
https://strongboxsafe.com/feature-comparisons-ios-mac-free-pro/

Any plans to integrate this?

Thanks for the really great application, I like the very well working browser integration which was my main reason to use KyPass before (which hasn't been updated in a year or so).

Best regards!

### PR DESCRIPTION
**Pull request by tqml**
[NOTE]: # ( Describe your changes in detail, why is this change required? )
[NOTE]: # ( Explain large or complex code modifications. )
[NOTE]: # ( If it fixes an open issue, please add "Fixes #XXX" )

I changed the LAPolicy flags so authentication is possible with TouchID or Apple Watch (closes #5337 ). This feature requires at least Catalina (10.15) so I added an availability check which only enables it on Catalina and newer.

## Testing strategy
[NOTE]: # ( Please describe in detail how you tested your changes. )
[TIP]:  # ( We expect new code to be covered by unit tests and documented with doc blocks! )

This PR should only be a draft to see if the simple approach works. Unfortunately I'm not able to test it. I suspect the problem is because of missing code signing (the original TouchID only implementation doesn't work for me either) 

Any hints are much appreciated!

## Type of change
[NOTE]: # ( Please remove all lines which don't apply. )
- ✅ New feature (change that adds functionality)

### CODE REVIEW

**Comment by droidmonkey** [comment]
Awesome, now to setup that iWatch I bought to test this...

And yes, you need to sign the app to get sec controls to work on Catalina ÷

**Comment by mbrinkme** [comment]
Nice to see that you have an approach to use the apple watch to unlock keepassxc. 👍

**Review by dataman713 — APPROVED** [review]

**Comment by droidmonkey** [comment]
I tried using this but I couldn't get the watch unlock feature to work on the Mac at all, even in the lock screen. Anyone have pointers on this? I disabled touchid and it still won't prompt for watch unlock.

**Comment by vaheder** [comment]
> I tried using this but I couldn't get the watch unlock feature to work on the Mac at all, even in the lock screen. Anyone have pointers on this? I disabled touchid and it still won't prompt for watch unlock.

You've enabled "Use your Apple Watch to unlock apps and your Mac" in Security and Privacy Settings? I've also encountered problems with USB 3.0 devices connected to my Mac and the Apple Watch unlock feature; it has to do with radio interference caused by the high speed signaling, if you can believe it. Try it with nothing connected to your laptop (I assume since you mentioned TouchID). Looking forward to this feature!

**Comment by droidmonkey** [comment]
Yah I enabled that setting, maybe I needed to reboot?

**Comment by vaheder** [comment]
Only other thing I can think of is to make sure you're properly logged into the same iCloud account on both iPhone and Mac, but I would imagine you wouldn't be able to enable the setting if that wasn't true already.

**Comment by vaheder** [comment]
Just built this to test it but didn't work for me. I can't sign the app properly, so it may be a side effect of that. I enabled TouchID for the database (I'm assuming the watch unlock follows the same code path) but it didn't seem to work, and the "TouchID for Quick Unlock" is always unchecked, even after correctly unlocking the database.

**Comment by droidmonkey** [comment]
You need to sign the app to make touchid work

**Comment by Tobisaninfo** [comment]
That is a nice approach for all mac users without TouchID. Like to see this in the future.

**Review by droidmonkey — APPROVED** [review]

**Pull request merged**
