### PR TITLE
Fix testgui for Windows

### PR DESCRIPTION
**Pull request by dannysu**
## Description
Adds `TemporaryFile` class to use `QFile` for writing to temporary test file on Windows instead of relying on `QTemporaryFile`. This fixes issue with running `testgui` on Windows due to `QTemporaryFile::close()` doesn't actually close the file when called.

## Motivation and Context
Running `make test` on Windows will result failures in `testgui` (E.g. using MSYS2 MinGW 64-bit on Windows 10).

This is because `QTemporaryFile::close()` doesn't actually close the file behind the scene. See [Qt documentation](http://doc.qt.io/qt-5/qtemporaryfile.html). Due to this behavior, running `testgui` on Windows results in the following failures:
1) **testAutoreloadDatabase** fails because Windows doesn't emit the file changed event needed for auto-reload to work (because file isn't actually closed)
2) **testSave** fails from Access Denied error because `QTemporaryFile` is keeping test file open and conflicts with KeePassXC's attempt to save

Fixing these two issues by creating a `TemporaryFile` class to act as a proxy. On non-Windows platforms, all the functions go straight to the `QTemporaryFile` counterparts. On Windows, the functions will use `QFile` underneath the hood to make sure that once `TemporaryFile::close()` is called, the file is really closed.

## How Has This Been Tested?
Ran `testgui` and ensure everything passes on Windows.
Ran `make test` and see everything passing on Windows.

Should be a low risk change once the automated tests run on non-Windows platform.

## Types of changes
- :white_check_mark: Bug fix (non-breaking change which fixes an issue)
- :negative_squared_cross_mark: New feature (non-breaking change which adds functionality)
- :negative_squared_cross_mark: Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- :white_check_mark: I have read the **CONTRIBUTING** document. [REQUIRED]
- :white_check_mark: My code follows the code style of this project. [REQUIRED]
- :white_check_mark: All new and existing tests passed. [REQUIRED]
- :negative_squared_cross_mark: My change requires a change to the documentation.
- :negative_squared_cross_mark: I have updated the documentation accordingly.
- :negative_squared_cross_mark: I have added tests to cover my changes.

### CODE REVIEW

**Comment by dannysu** [comment]
I've been working on this today, but just realized issue #137 was opened.

**Comment by TheZ3ro** [comment]
@dannysu it's fine, I don't think @droidmonkey will get angry, in #137 there is still the MacOS part to fix :smile: :+1: 

Good job, I will test and review this later

**Comment by droidmonkey** [comment]
YAY! Although that is so ridiculous on Qt's part to have wildly different temp file behavior between platforms.

**Comment by droidmonkey** [comment]
Merged into develop, thanks!

**Comment by droidmonkey** [comment]
Thanks. This pull request has been integrated manually.

**Pull request closed without merging**
