### PR TITLE
Update keepassx_nl_NL.ts

### PR DESCRIPTION
**Pull request by Stephan-P**
## Description
- a large number of faulty space characters removed, words concatenated
- rewording, rephrasing
- typo's corrected
- some new translations
- replaced "..." with single character "…" (also for <source>)

TO DO
Later on I'd like to take up general grammar styling, i.e.:
- "Open database" -> "Database openen"
- or "Sla op als..." -> "Opslaan als..."

## Motivation and context

Incorrect Dutch language
Improved legibility
Missing translations

N/A

## How has this been tested?
NOT TESTED
I hope I didn't introduce XML-parse errors by omitting  opening/closing brackets </>

## Screenshots (if appropriate):
N/A

## Checklist:

- ✅ I have read the **CONTRIBUTING** document. **[REQUIRED]**

### CODE REVIEW

**Comment by phoerious** [comment]
Sorry to close this, but please submit the translations over at Transifex: https://www.transifex.com/keepassxc/keepassxc/
Changes in the source repository are lost next time we pull from there.

**Comment by Stephan-P** [comment]
So, does this mean that all the changes I have made are now down the drain?
Does Transifex offer a way to import the .ts file I've been working on today or do I have to start all over again, making improvements one at a time?

**Comment by phoerious** [comment]
I pushed the XML file (after correction of a small XML syntax error). Next time please translate on Transifex directly. It's a lot of work for us to push translations manually and it's easy to accidentally overwrite a lot of other people's changes.
Please have a look if everything's been pushed correctly.

**Comment by Stephan-P** [comment]
Thanks.
Meanwhile I’ve joined Transifix and will continue from there.

Cheers,
Stephan


________________________________
Van: Janek Bevendorff <notifications@github.com>
Verzonden: Thursday, March 1, 2018 10:15:19 PM
Aan: keepassxreboot/keepassxc
CC: Stephan Paternotte; Author
Onderwerp: Re: [keepassxreboot/keepassxc] Update keepassx_nl_NL.ts (#1586)


I pushed the XML file (after correction of a small XML syntax error). Next time please translate on Transifex directly. It's a lot of work for us to push translations manually and it's easy to accidentally overwrite a lot of other people's changes.
Please have a look if everything's been pushed correctly.

**Comment by Stephan-P** [comment]
Janek,

Having returned from a short skiing holiday, I’m ready to take up some translation work today.
Should I make further improvements to the Dutch translation in the Transifex “develop-keepassx_ents” branch or “keepassx_en.ts”?

Cheers,
Stephan

________________________________
Van: Stephan Paternotte namens Stephan Paternotte <stephan@paternottes.net>
Verzonden: Thursday, March 1, 2018 10:55:58 PM
Aan: keepassxreboot/keepassxc
Onderwerp: RE: [keepassxreboot/keepassxc] Update keepassx_nl_NL.ts (#1586)

Thanks.
Meanwhile I’ve joined Transifix and will continue from there.

Cheers,
Stephan


________________________________
Van: Janek Bevendorff <notifications@github.com>
Verzonden: Thursday, March 1, 2018 10:15:19 PM
Aan: keepassxreboot/keepassxc
CC: Stephan Paternotte; Author
Onderwerp: Re: [keepassxreboot/keepassxc] Update keepassx_nl_NL.ts (#1586)


I pushed the XML file (after correction of a small XML syntax error). Next time please translate on Transifex directly. It's a lot of work for us to push translations manually and it's easy to accidentally overwrite a lot of other people's changes.
Please have a look if everything's been pushed correctly.

**Comment by phoerious** [comment]
Both. We will use develop for 2.4 and continue to pull from the main resource for 2.3.x.

**Comment by Stephan-P** [comment]
Hello Janek,

“Both” sounds to me like double effort.
I’ve now worked over all Dutch translations in keepass_en.ts, further improving lots of strings and adding to consistency.

I’ve downloaded the file and used QTLinguist to produce a .qm, which I tested in my currect installtion of KeePassXC. This lead to a number of additional inconcistencies and corrections, which I’ve processed.

At this point I am very happy with the results.
Please feel free to inform the other Dutch translators to review my work before accepting it for the next release and/or copy this work to the parallel development branch.

Kind regards,
Stephan



________________________________
Van: Janek Bevendorff <notifications@github.com>
Verzonden: Sunday, March 4, 2018 11:18:29 AM
Aan: keepassxreboot/keepassxc
CC: Stephan Paternotte; Author
Onderwerp: Re: [keepassxreboot/keepassxc] Update keepassx_nl_NL.ts (#1586)


Both. We will use develop for 2.4 and continue to pull from the main resource for 2.3.x.

**Comment by phoerious** [comment]
At the moment, they are both mostly identical, because the 2.3 release is very fresh. But they will diverge with time. Before the 2.3 release, the develop resource had hundreds of strings which did not exist in the stable version and vice versa.

**Comment by Stephan-P** [comment]
Is there a mechanism in place that keeps the two branches in sync or do I (we?) need to enforce the sync e.g. by uploading the one .ts file over the other?

________________________________
Van: Janek Bevendorff <notifications@github.com>
Verzonden: Sunday, March 4, 2018 7:24:41 PM
Aan: keepassxreboot/keepassxc
CC: Stephan Paternotte; Author
Onderwerp: Re: [keepassxreboot/keepassxc] Update keepassx_nl_NL.ts (#1586)


At the moment, they are both mostly identical, because the 2.3 release is very fresh. But they will diverge with time. Before the 2.3 release, the develop resource had hundreds of strings which did not exist in the stable version and vice versa.

**Comment by phoerious** [comment]
Transifex should take care of that. If not, just go through entries and click the copy icon on the "Suggestions" tab to copy over the exiting translation.

**Pull request closed without merging**
