### PR TITLE
Passphrase "MIXED case" Type

### PR DESCRIPTION
**Pull request by salevajo**
[NOTE]: # ( Describe your changes in detail, why is this change required? )
[NOTE]: # ( Explain large or complex code modifications. )
[NOTE]: # ( If it fixes an open issue, please add "Fixes #XXX" )
## Description
Create passphrase using one UPPERCASE word in combination with lowercase words. Separator characters will be selected randomly out of the String provided by the user.

## Screenshots
[TIP]:  # ( Do not include screenshots of your actual database! )
Screenshot from 2024-09-13 23-16-27

## Testing strategy
[NOTE]: # ( Please describe in detail how you tested your changes. )
[TIP]:  # ( We expect new code to be covered by unit tests and documented with doc blocks! )
A pattern based test is included in the TestPassphraseGenerator class.

## Type of change
[NOTE]: # ( Please remove all lines which don't apply. )
- ✅ New feature (change that adds functionality)

### CODE REVIEW

**Comment by droidmonkey** [comment]
Do not add the actual translations to a PR, just the English build from running the qt linguist tool. 

However, this PR is unlikely to be merged as it defeats the purpose of a passphrase. The whole point is to be able to remember the passphrase. If that isn't your point, use a random password. Adding _more randomness_ to a passphrase all but guarantees you'll forget it.

**Comment by salevajo** [comment]
The intention is to create a passphrase variant, that can be remembered but can also fulfil additional requirements like numbers and symbols and uppercase letters.

It's for sure not a passphrase by definition, but still useful and usable. Due to the open separator character selection, it can be used quite flexible.

**Comment by droidmonkey** [comment]
I actually didn't know you could add multiple characters to the separator field, lol

**Comment by droidmonkey** [comment]
I'll merge this after thinking it through, no real harm.

**Comment by michaelk83** [comment]
IMHO, this is antithesis to passphrases and should not be merged. If some website allows the use of passphrases, but adds additional requirements like numbers etc, it would be better to satisfy those with fixed modifications, such as capitalizing the 1st letter or adding an easy to remember suffix like "123!".

None of this adds security to the passphrase, it is only to satisfy the misguided requirements of those websites. Although most websites that I know don't even allow enough characters to use a passphrase at all.

I would also disallow the use of multiple (random) separators, and stick to only one per passphrase.

Btw, why is there a duplicate character count, both below the word case, and in the entropy status line? The latter is enough.

**Comment by michaelk83** [comment]
How about this:
- Limit the separator to a single character.
- Add a "Captilized" word case instead of "MIXER", which only capitalizes the 1st letter of the passphrase.
- Add a suffix field, which is appended at the end of the passprase.
- Drop the duplicate Character Count below the Word Case.
- Rearrange them on a single line: `Word Case: [ ...       ]    Separator: [   ]    Suffix: [           ]`

**Comment by salevajo** [comment]
My personal reason for implementing this variant is that I often need easy-to-type, yet complex passwords that are stored in KeePassXC and that I can use on systems that do not have the keystore themselves. Random passwords are much more difficult to type with the same complexity.

Frequently used, they are also usually easy to memorize. But that is not the primary goal of this implementation.

**Comment by droidmonkey** [comment]
How about both "MIXER" (I don't like that name) and "Capitalized" are added. I think MIXER is better named "MIXED case"

**Comment by droidmonkey** [comment]
I removed the code that picked from the list of separators, that isn't a desired behavior for passphrase generation.

I also removed the extra character count display on the passphrase generator tab.

**Review by droidmonkey — APPROVED** [review]

**Pull request merged**
