### PR TITLE
Add support for working with multiple entry attachments at once

### PR DESCRIPTION
**Pull request by frostasm**
## Description

All errors show at once

Supported actions:
- Insert 
- Remove 
- Open 
- Save 

## Motivation and context

To make working with attachments more user friendly

## How has this been tested?

Manually.

## Screenshots (if appropriate):

Window with opening errors:  

image

## Types of changes

- ✅ New feature (non-breaking change which adds functionality)

## Checklist:

- ✅ I have read the **CONTRIBUTING** document. **[REQUIRED]**
- ✅ My code follows the code style of this project. **[REQUIRED]**
- ✅ All new and existing tests passed. **[REQUIRED]**
- ✅ I have compiled and verified my code with `-DWITH_ASAN=ON`. **[REQUIRED]**

### CODE REVIEW

**Comment by frostasm** [comment]
@TheZ3ro if you have free time please review this changes :smile:

**Comment by TheZ3ro** [comment]
@frostasm can you rebase this? Thanks

**Comment by frostasm** [comment]
@TheZ3ro sure ;)

**Comment by frostasm** [comment]
@TheZ3ro done

**Pull request merged**
