### PR TITLE
Implement support for Yubikeys and potential other tokens via wireless NFC using smartcard readers

### LINKED ISSUE #4090: HMAC-SHA1 challenge response via NFC
[TIP]:  # ( Provide a general summary of the feature in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Summary
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
This feature would open up HMAC-SHA1 challenge response 2FA to NFC smartcard
devices like Rings, Fobs, Cards etc. and it would free up a precious USB slot. Also it would
ease the transition to the all USB-C future.

## Desired Behavior
[NOTE]: # ( Tell us how the new feature should work, be specific )
Instead of or in addition to just scan for supported HMAC-SHA1 challenge response devices plugged in to a USB slot, scan for NFC readers. If a supported NFC smartcard device is found
the user can choose which slot to use just like it would be plugged in to USB.

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )
I own multiple devices with different USB types and using adapters is tedious. Additionally smartcards which can run the yupikey applet for HMAC-SHA1 challenge response are way cheaper
and possibly more attractive to users.

### LINKED ISSUE #6439: Yubikey Support via MS RDP
Hello, 
I'm currently working on a project to secure the passwords of our employees. As long user of KeePass and KeePassXC I'm planning to rollout it company wide. For additional security we bought some Yubikeys 5 NFC and I programmed the Slot 2 with HMAC-SHA1 which works fine in normal use case.
But because of Covid-19 most employees are in HomeOffice. Some have notebooks, so no issue there but some use their personal PC and connect via VPN and RDP to their company PC. 
What I did was enabling Smartcard in the Remote Settings:
image

Which seems to work with the newer Yubikey applications like Authenticator, even the button press is working. 
The Yubikey Manager finds the Yubikey and shows a serial, but you can't config everything. 
The old Personalization Tool doesn't find the Yubikey at all. 
So I guess they changed the API in their new applications 
image

Did I miss something in the configuration / settings or is the keepass implementation like the personalization tool? I don't know anything about the yubikey API.

It would be cool if someone could lead me to a workaround or is there any change planned?

### PR DESCRIPTION
**Pull request by StarGate01**
This fixes #4090 and  https://github.com/arekinath/YkOtpApplet/issues/3 , and might fix #6439 . It also potentially provides a base for #255 .

## Rationale
I want to use my Yubikeys with KeePassXC not (only) by plugging them in via USB, but also by wirelessly presenting them to a NFC reader which is connected via USB or built-into my computer - just like I do on my phone.

Eventually, other hardware tokens which do not have a USB interface at all but implement the wireless protocol will be supported automatically as well. Examples include eg. the [Vivokey](https://forum.dangerousthings.com/t/problems-using-vivokey-demo-cards/11903/10?u=stargate01) or any smartcard running [vk-ykhmac](https://github.com/StarGate01/vk-ykhmac).

## Screenshots
Screenshot_2021-07-26_01-49-21

## Explanation of changes
This new interface uses the [PC/SC protocol](https://en.wikipedia.org/wiki/PC/SC) and [API](https://docs.microsoft.com/en-us/windows/win32/api/winscard/), instead of the USB protocol via the [`ykpers`](https://github.com/Yubico/yubikey-personalization) library. Both interfaces can be used in parallel and the same key can be used on both interfaces without reprogramming it.

Many YubiKeys expose their functionality as a smartcard / CCID device, which can be interfaced with using PC/SC. This is especially useful for NFC-only or NFC-capable Yubikeys, when they are used together with a PC/SC compliant NFC reader device.

Essentially, this implementation does the same as the [ykdroid](https://github.com/pp3345/ykDroid) module for [Keepass2Android](https://github.com/PhilippC/keepass2android):
It provides a way to wirelessly (depending on the reader) interface a YubiKey or any key which implements the Yubikey challenge-response HMAC-SHA1 protocol.

Although many (not all) Yubikeys expose their CCID functionality over their own USB connection as well, the HMAC-SHA1 functionality is often locked in this mode, as it requires eg. a touch on the gold button. When accessing the smartcard  functionality wirelessly via NFC (like this code can do using a reader), then the user interaction is to present the key to the reader, just like you would tap the key against your phone when using `ykdroid`. A continuously presented key eventually times out due to security concerns.

This implementation has been tested on Linux using [`pcsc-lite`](https://pcsclite.apdu.fr/), Windows using the native `Winscard.dll` library, and Mac OSX using the native `PCSC-framework` (which is a port of `pcsc-lite` by Apple) library.

### Changes to the build system
Since this feature requires the PCSC API libraries for each OS, the cmake configuration has been changed to automatically find and link the correct one.

A new build flag (`-DWITH_XC_YUBIKEY_PCSC=[ON|OFF]`, requires `-DWITH_XC_YUBIKEY=ON`, default: `OFF`, but included by  `-DWITH_XC_ALL=ON`) can be used to control whether the new interface is compiled in. If this if `OFF`, the functionality remains unchanged, only the existing USB interface is enabled, and no PCSC library is required.

Package maintainers on Linux have to add a dependency on `pcsc-lite` if they want to include this feature.

### Smaller changes
Since the Yubikey can now be a wireless token as well, the verb "plug in" was replaces with a more generic "interface with". This shall indicate that the user has to present their token to the reader, or plug it in via USB.

The hardware key selection menu in the UI now additionally displays how a token is connected (USB or PCSC) and its firmware version.

A sample "third-party" hardware token has been added. This is mainly for future developers to be used as a reference for other smartcards.

## Testing strategy
The new interface has been compiled and tested successfully on Linux x64 5.4.131-1-MANJARO, Windows 10 x64 21H1, and Mac OSX x64 18.2.0 Mojave (using VirtualBox) using the documented build tools.

The hardware keys used for testing were:
 - [Yubikey 5 NFC](https://www.yubico.com/de/product/yubikey-5-nfc/) version 5.4.3
 - Yubikey 5 NFC version 5.2.6
 - [Fidesmo card 2.0](https://shop.fidesmo.com/products/fidesmo-card-2-0) running [vk-ykhmac](https://github.com/StarGate01/vk-ykhmac)

In general, all PC/SC compliant CCID devices which implement the Yubikey HMAC-SHA1 challenge-response protocol should work.

The readers used for testing were:
 - [SCM SCL011](https://support.identiv.com/scl010-scl011/)
 - [SCM SCL3711](https://support.identiv.com/scl3711/)

In general, all PC/SC compliant NFC-capable smartcard readers with CCID / PC/SC driver support for the target OS should work.

The keys were programmed with the same HMAC-SHA1 secret, and verified to be able to generate a valid key to unlock the database in all modes and slot configurations.

## Type of change
- ✅ New feature (change that adds functionality)

## Workflow note
I realize this is a rather large PR, and especially since this is my first one to this project I am happy to receive any feedback concerning conventions, methodology or anything else. If there are questions or concerns regarding the implementation, I am willing to adjust the code if needed.

If there are things that should be changed or any mistakes, please point them out. Although I did my best to verify and test on all systems using all the hardware I have available, some things might have slipped though.

If this is something you do not want to add at all, I would like to discuss why and what would have to be changed or implemented instead.

## Sources and further reading
 - https://github.com/pp3345/ykDroid
 - https://github.com/arekinath/YkOtpApplet
 - https://github.com/arekinath/yktool
 - https://pcsclite.apdu.fr/
 - https://docs.microsoft.com/en-us/windows/win32/api/winscard/
 - https://forum.dangerousthings.com/t/problems-using-vivokey-demo-cards/11903

### CODE REVIEW

**Comment by StarGate01** [comment]
The CI build on Linux probably fails due to the missing `pcsc-lite` package on the build system. 

As for the code format check I have no idea. I ran `make format` as documented and integrated all changes.

**Comment by droidmonkey** [comment]
Please rebase this onto my yubikey pr

**Comment by droidmonkey** [comment]
Also, holy shit you are awesome!

**Comment by StarGate01** [comment]
> Please rebase this onto my yubikey pr

I assume you mean #6654 ?

> Also, holy shit you are awesome!

I am glad you like it, it was quite a challenge to get this running smoothly on all three systems.

**Comment by droidmonkey** [comment]
> I assume you mean #6654 ?

Yes, that will make this easier to merge once we merge that one first.

> it was quite a challenge to get this running smoothly on all three systems.

That is definitely a challenge for a lot of our integrations, very tough project to make this work without a hitch!

**Comment by StarGate01** [comment]
Alright, I rebased the feature branch onto your PR. Everything still works according to my tests.

`develop` has since gained one additional commit, but I chose to not merge or rebase on that too since your PR does not do so as well.

In addition, I added a small fix for Windows, which enables USB hotplugging for reader devices. I also clarified the YubiKey security timeout flow.

**Comment by StarGate01** [comment]
If you do not have a NFC Yubikey or a NFC PC/SC card reader, I added instructions on how to emulate the PC/SC HMAC-SHA1 functionality of a Yubikey completely in software on Linux: https://github.com/StarGate01/vk-ykhmac#readme .

**Comment by droidmonkey** [comment]
Excellent, we'll merge my pr first then rebase yours onto develop

**Comment by StarGate01** [comment]
Should I rebase this PR on the current state of `develop` ?

**Comment by droidmonkey** [comment]
How'd this get closed, stupid github. Yes please rebase. I think this closed cause the branch was deleted, once you rebase and set this up to track develop then I can reopen it.

**Pull request closed without merging**
