### PR TITLE
Improve CMakeLists.txt

### PR DESCRIPTION
**Pull request by adolfogc**
This PR introduces various fixes/improvements to CMakeLists.txt, specifically it:
- enables building on macOS using `-DWITH_ASAN=ON`,
- improves ZLIB version checking,
- enables using other Qt versions than those provided by `brew` (e.g. one provided by the official Qt installer),
- enables building macOS with QtMacExtras (motivation: #1075),
- :fire: removes `utils/fix_mac.sh`.

## Description
See above. In macOS, CMake looks for brew's Qt5 first. If it isn't installed, it looks for one in the current `$PATH`.

This wiki page can be updated like below: https://github.com/keepassxreboot/keepassxc/wiki/Building-KeePassXC

```bash
mkdir build
cd build
cmake -DCMAKE_OSX_ARCHITECTURES=x86_64 -DCMAKE_BUILD_TYPE=Release \
  -DWITH_XC_AUTOTYPE=ON -DWITH_XC_HTTP=ON -DWITH_XC_YUBIKEY=ON  ..
make -j8 package
```
This wiki page can be updated to remove the `fix_mac.sh` hack: https://github.com/keepassxreboot/keepassxc/wiki/Set-up-Build-Environment-on-OS-X

With regards to using ASan in macOS, a note is added in `README.md` to explain how to run it without LSan (currently missing in XCode's toolchain).

## Motivation and context
Currently, building on macOS requires the use of a Qt5 version distributed by `brew` and applying some fixes provided in `utils/fix_mac.sh`. This restricts users who want to build KeePassXC with other Qt5 distributions.

## How has this been tested?
Manually on macOS and Linux.

## Screenshots (if appropriate):

KeePassXC built with the latest Qt5 from brew:
Screenshot 1

KeePassXC built with the Qt 5.10 beta snapshot distributed by Qt:
Screenshot 2

## Types of changes
- ✅ Bug fix (non-breaking change which fixes an issue)
- ✅ New feature (non-breaking change which adds functionality)

## Checklist:
- ✅ I have read the **CONTRIBUTING** document. **[REQUIRED]**
- ✅ My code follows the code style of this project. **[REQUIRED]**
- ✅ All new and existing tests passed. **[REQUIRED]**
- ✅ I have compiled and verified my code with `-DWITH_ASAN=ON`. **[REQUIRED]**
- ✅ My change requires a change to the documentation and I have updated it accordingly.

### CODE REVIEW

**Comment by phoerious** [comment]
Is it normal that "stock" Qt produces an unstyled interface?

**Comment by adolfogc** [comment]
I think it may be an issue of the beta snapshot released for Qt 5.10, I'll try using version Qt 5.9.2 to confirm.

**Comment by adolfogc** [comment]
Update: I've just tested this using "stock" Qt 5.9.2 and it shows an style interface, so it seems to be an issue of the Qt 5.10 beta version.

**Comment by phoerious** [comment]
Looks good. Please rebase, so I can merge. Thanks!

**Pull request merged**
