### PR TITLE
Fix Auto-Type modifiers on Windows

### LINKED ISSUE #7626: Auto-Type: modifier for WIN key not working
Hi,

just tested 2.7.0, the # modifier is not recognized at all, although promised here:

Supported in 2.7.0, use the # modifier. `#d` types WIN+D

_Originally posted by @droidmonkey in https://github.com/keepassxreboot/keepassxc/issues/7537#issuecomment-1068449818_

### LINKED ISSUE #7743: {#} doesn't allow to use hash in Auto-Type sequence
## Overview
Workaround proposed in #7733 doesn't work

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. I edit one entry with JDOE as user name and select 'Auto-Type' 
2. I crete a new association for window '* - Notepad' with the specific sequence '{USERNAME}{#}{USERNAME}'
3. I open Notepad and press my Auto-Type shortcut

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
JDOE#JDOE

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
At step 2, when saving entry, KeepassXC complains that variable doesn't exist
When forcing save with {#}, step failed with same complain

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.0
Revision: d7a9ef4

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 10

### PR DESCRIPTION
**Pull request by droidmonkey**
Also add documentation on modifiers.

* Fix #7626
* Fix #7743 

## Testing strategy
[NOTE]: # ( Please describe in detail how you tested your changes. )
[TIP]:  # ( We expect new code to be covered by unit tests and documented with doc blocks! )
Tested on Windows

## Type of change
[NOTE]: # ( Please remove all lines which don't apply. )
- ✅ Bug fix (non-breaking change that fixes an issue)

### CODE REVIEW

**Review by phoerious — APPROVED** [review]

**Comment by codonell** [comment]
@droidmonkey Why are the existing ASCII sequences used for special charaters? This change in backwards incompatible with all existing auto-type sequences that might have +, ^, % and #, and indeed this breaks a significant number of my auto-type sequences.

**Comment by droidmonkey** [comment]
Take that up with keepass, they chose this syntax not us.

**Comment by codonell** [comment]
> Take that up with keepass, they chose this syntax not us.

As a career implementer of POSIX and ISO C interfaces, I can certainly understand the "Because the standardizing organization said it was this way", thank you for answering my question. I see that "@" is the Windows Key (as modifier) (https://keepass.info/help/base/autotype.html) where is the specification for "#" to be used as Win/Cmd? I'm just trying to write a cleanup pass to export, process, and import my auto-type entries.

**Comment by droidmonkey** [comment]
@ is only defined for keepass 1.x. We chose # for keepassxc to provide that capability since @ is way more common to be used in a sequence as a character and not a modifier.

**Comment by codonell** [comment]
> @ is only defined for keepass 1.x. We chose # for keepassxc to provide that capability since @ is way more common to be used in a sequence as a character and not a modifier.

Certainly, if you used @ it would break emails in auto-type sequences and require escaping, which is why I assume Keepass 2.x deprecated @ usage in auto-type, and switched to recommending VKEY.

Does the choice of # (special meaning for standard ASCII character) for keepassxc cause compatibility problems between keepass and keepassxc when it comes to sharing auto-type sequences?

How can # be used for @? Is # a single-key modifier? Are {VKEY 91 D}e{VKEY 91 U} and #e equivalent now?

So if I have #e in my keepass auto-type and I migrate it to keepassxc it will not be interpreted the same?

Is it possible to remove # from the special characters to avoid this incompatibility with upstream keepass?

**Comment by droidmonkey** [comment]
We don't support the VKEY syntax, and no we aren't going to revert this feature. You should almost never Auto-Type raw characters, placeholders don't apply the modifier logic. 

If you define a sequence using # to hold down the win key in keepassxc, you can easily define a second sequence that uses VKEY in keepass. 

```
#e => WIN+E
{#}e => #e
@e => @e
```

**Pull request merged**
