### PR TITLE
Use Ubuntu 16.10 in Docker to test on Linux

### PR DESCRIPTION
**Pull request by angelsl**
## Checklist:
- [x] I have read the **CONTRIBUTING** document. **[REQUIRED]**
- [x] My code follows the code style of this project. **[REQUIRED]**
- [x] All new and existing tests passed. **[REQUIRED]**
- [x] I have compiled and verified my code with `-DWITH_ASAN=ON`. **[REQUIRED]**

### CODE REVIEW

**Comment by angelsl** [comment]
This is a strange regression.

````
FAIL!  : TestCsvParser::testUnicode() 't.at(0).at(0) == "€1"' returned FALSE. ()
   Loc: [/keepassxc/src/tests/TestCsvParser.cpp(332)]
````

**Comment by angelsl** [comment]
Fixed that issue by setting the locale (the default locale in Docker's Ubuntu images is `POSIX`, which basically breaks the moment you have non-ASCII).

Seems to work now.

**Comment by phoerious** [comment]
the problem with this approach is that we won't notice when things break on Ubuntu 14.04 anymore. That's important to be able to build our AppImage later one.

**Comment by angelsl** [comment]
@phoerious,

You have rejected:

1. backporting Argon2 and Gcrypt to 14.04, citing maintenance costs
2. bundling Argon2 and Gcrypt
3. testing on 16.10, because you need to know when 14.04 breaks and because 16.10 is too new
4. building Argon2 and Gcrypt in Travis because Travis build times are already too long

I don't exactly agree with all these reasons, but since you are project maintainer it is your decision.

I'm out of ideas (and patience). When you and/or your team can find a way to make these new dependencies available, mention me again if you want me to rebase my changes.

Good luck.

**Comment by phoerious** [comment]
I'm not rejecting it, I'm still not yet too happy with the solution.. I know it's difficult and I don't have a definite solution myself. I really appreciate your work on this, but finding an optimal solution on this is difficult. I only want to make sure that whatever solution we choose in the end is the best possible. Maybe there is no good solution.

**Comment by angelsl** [comment]
@phoerious,

OK, fair enough. Thanks for considering my suggestions.

I'll do the necessary rebasing if or when the time comes to merge #399.

**Comment by phoerious** [comment]
@angelsl I'm really thinking hard about a solution. All of them have pros and cons:

- Backporting (pro: easy to use - con: we need to maintain a PPA)
- Bundling (pro: relatively low maintenance cost, same version on all platforms - con: doubles or triples the size of our source code)
- Using 16.10 (pro: just works - con: too new for making it the oldest supported system, building AppImage unsolved*)
- Building in Travis (pro: clean solution, just works - con: Travis builds will probably take twice the time, i.e. 7-10 minutes or so)

\* this is really a problem. Our first AppImage was built on 16.04 (not even 16.10) and we got a lot of reports that it didn't work on users' platforms due to Glibc being too new.

Right now the first and the last option seem to be the best possible, but I'm not too happy with either. :-(

Again, please do not misunderstand my concerns as unnecessary nitpicking. I really want to find a good solution, but we can't make that decision lightly. Whatever we choose has to work seamlessly and be maintained for years.

**Comment by angelsl** [comment]
@phoerious 

The effort needed to maintain a PPA is just about the same as building the dependencies in Travis or bundling them. Action is only needed when there is a new update.

In fact it is [possible to request an official backport](https://wiki.ubuntu.com/UbuntuBackports#Requesting_a_Backport) in which case there is no maintenance needed on your end.

**Comment by angelsl** [comment]
Launchpad builds the packages from source on their build farm. In fact you cannot simply upload `.deb`s to Launchpad, you have to upload sources.

**Comment by phoerious** [comment]
Hmm. Then this actually looks like a solution. I'll have a look into it.

**Comment by droidmonkey** [comment]
Perhaps we need to investigate another CI service instead of Travis. If its not meeting our needs, then we should adapt to a more capable platform.

**Comment by angelsl** [comment]
I've filed backport requests for [Argon2](https://bugs.launchpad.net/trusty-backports/+bug/1674441) and [Gcrypt](https://bugs.launchpad.net/trusty-backports/+bug/1674442).

Argon2 backports cleanly to Trusty. The Gcrypt package uses newer Debian build tools than available in Trusty, though, so that fails. [Here is the PPA of my attempt.](https://launchpad.net/~angelsl/+archive/ubuntu/trusty-crypto-backports/+packages) (You can copy packages to a PPA for this project.)

For reference, the `backportpackage` invocation:

````
backportpackage -u ppa:angelsl/trusty-crypto-backports -s yakkety -d trusty argon2
backportpackage -u ppa:angelsl/trusty-crypto-backports -s yakkety -d trusty libgcrypt20
````

**Comment by phoerious** [comment]
Amazing. Thank you!

**Pull request closed without merging**
