### PR TITLE
Fix memory leak in DatabaseTabWidget::openDatabase function

### PR DESCRIPTION
**Pull request by frostasm**
## Description

Fix memory leak in DatabaseTabWidget::openDatabase function

## How has this been tested?

1. Open first instance of KeePassXC 
2. Open database /tmp/test.kdbx 
3. Open second instance of KeePassXC 
4. Try open database /tmp/test.kdbx 
5. Сhoose "No" in the dialogue that appeared 
6. Close second instance of KeePassXC 

ASAN detect leak:
```
DatabaseTabWidget::openDatabase(QString const&, QString const&, QString const&) /home/frostasm/dev/qt/keepassxc/src/gui/DatabaseTabWidget.cpp:155
```

## Types of changes

- ✅ Bug fix (non-breaking change which fixes an issue)

## Checklist:

- ✅ I have read the **CONTRIBUTING** document. **[REQUIRED]**
- ✅ My code follows the code style of this project. **[REQUIRED]**
- ✅ All new and existing tests passed. **[REQUIRED]**
- ✅ I have compiled and verified my code with `-DWITH_ASAN=ON`. **[REQUIRED]**

### CODE REVIEW

**Comment by TheZ3ro** [comment]
@keepassxreboot/core-developers We need to cherry-pick this also on release/2.2.1

**Comment by droidmonkey** [comment]
You mean 2.2.2?

**Comment by TheZ3ro** [comment]
Yes exactly :smile:

**Comment by droidmonkey** [comment]
Instances like this would be a good transition to QScopedPointer's. Good work finding this issue!

**Pull request merged**
