### PR TITLE
FdoSecrets: skip entries in recycle bin when searching

### LINKED ISSUE #7933: Crash when using the secret service on a secret with a matching entry in the recycle bin
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
KeepassXC crashes when using the "Secret Service Integration" in some conditions.

The crash occurs when I try to access a specific secret from Pycharm (But not all secrets, even with Pycharm).

EDIT: In fact, this is because there is a similar entry in the recycle bin (See: https://github.com/keepassxreboot/keepassxc/issues/7933#issuecomment-1110141210).

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Open KeepassXC
2. Open Pycharm (Configured to use "native keychain")
3. "Git pull" to trigger the access to the Git credentials in the keychain.
4. KeepassXC crashed

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
KeepassXC does not crash.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
KeepassXC crash immediately when accessing the secret.

## Context
[NOTE]: # ( Give us any additional information you may have. )

The issue is with the version 2.7.1, but was not in the 2.6.6 version.
KeepassXC was installed using the OS provided package.
If I reinstall the 2.6.6 version, the crash does not occur.

---
The secret that always generates the crash look like (DOMAIN and PASSWORD are replaced values):
* Entry/Title: `IntelliJ Platform Git HTTP — http://DOMAIN@dev.azure.com`
* Entry/Password: `http://DOMAIN\@dev.azure.com@PASSWORD`
* Advanced/Additional attributes/account: `http://DOMAIN@dev.azure.com`
* Advanced/Additional attributes/service: `IntelliJ Platform Git HTTP — http://DOMAIN@dev.azure.com`
* Advanced/Additional attributes/xdg:schema: `com.intellij.credentialStore.Credential`

This other secret is also used from Pycharm in an equivalent context, but always works as intended (UUID and PASSWORD are replaced values, UUID is a common UUID in standard format):
* Entry/Title: `IntelliJ Platform GitHub — UUID`
* Entry/Password: `UUID@PASSWORD`
* Advanced/Additional attributes/account: `UUID`
* Advanced/Additional attributes/service: `IntelliJ Platform GitHub — UUID`
* Advanced/Additional attributes/xdg:schema: `com.intellij.credentialStore.Credential`

---
I get the following debug info (I only put logs that were generated after I triggered the access to the secret):

gdb
```
Thread 1 "keepassxc" received signal SIGSEGV, Segmentation fault.
FdoSecrets::Item::ensureBackend (this=this@entry=0x0) at /usr/src/debug/keepassxc-2.7.1-2.fc35.x86_64/src/fdosecrets/objects/Item.cpp:341
341             if (!m_backend) {
```

strace
```
write(7, 0x7ffdf5508ce0, 8)             = 8
futex(0x7f6c740180e0, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 0, NULL, FUTEX_BITSET_MATCH_ANY) = 0
futex(0x7f6c74018090, FUTEX_WAKE_PRIVATE, 1) = 0
readlink(0x7ffdf5508d60, 0x7ffdf5508900, 1023) = -1 EINVAL (Invalid argument)
readlink(0x7ffdf5508d60, 0x7ffdf5508900, 1023) = -1 EINVAL (Invalid argument)
readlink(0x7ffdf5508d60, 0x7ffdf5508900, 1023) = 89
readlink(0x7ffdf5508d60, 0x7ffdf5508900, 1023) = -1 EINVAL (Invalid argument)
readlink(0x7ffdf5508d60, 0x7ffdf5508900, 1023) = -1 EINVAL (Invalid argument)
readlink(0x7ffdf5508d60, 0x7ffdf5508900, 1023) = -1 EINVAL (Invalid argument)
readlink(0x7ffdf5508d60, 0x7ffdf5508900, 1023) = -1 EINVAL (Invalid argument)
readlink(0x7ffdf5508d60, 0x7ffdf5508900, 1023) = -1 EINVAL (Invalid argument)
readlink(0x7ffdf5508d60, 0x7ffdf5508900, 1023) = -1 EINVAL (Invalid argument)
readlink(0x7ffdf5508d60, 0x7ffdf5508900, 1023) = -1 EINVAL (Invalid argument)
readlink(0x7ffdf5508d60, 0x7ffdf5508900, 1023) = -1 EINVAL (Invalid argument)
readlink(0x7ffdf5508d60, 0x7ffdf5508900, 1023) = -1 EINVAL (Invalid argument)
readlink(0x7ffdf5508d60, 0x7ffdf5508900, 1023) = -1 EINVAL (Invalid argument)
readlink(0x7ffdf5508d60, 0x7ffdf5508900, 1023) = -1 EINVAL (Invalid argument)
readlink(0x7ffdf5508d60, 0x7ffdf5508900, 1023) = -1 EINVAL (Invalid argument)
readlink(0x7ffdf5508d60, 0x7ffdf5508900, 1023) = -1 EINVAL (Invalid argument)
openat(AT_FDCWD, 0x5622700d8298, O_RDONLY|O_CLOEXEC) = 27
statx(27, 0x7f6c94725570, AT_STATX_SYNC_AS_STAT|AT_EMPTY_PATH, STATX_ALL, 0x7ffdf5509040) = 0
statx(27, 0x7f6c94725570, AT_STATX_SYNC_AS_STAT|AT_EMPTY_PATH, STATX_ALL, 0x7ffdf5509100) = 0
statx(27, 0x7f6c94725570, AT_STATX_SYNC_AS_STAT|AT_EMPTY_PATH, STATX_ALL, 0x7ffdf5509100) = 0
read(27, 0x562270f65b28, 16384)         = 6498
read(27, "", 9886)                      = 0
read(27, "", 16384)                     = 0
openat(AT_FDCWD, 0x562270e71c28, O_RDONLY|O_CLOEXEC) = 28
statx(28, 0x7f6c94725570, AT_STATX_SYNC_AS_STAT|AT_EMPTY_PATH, STATX_ALL, 0x7ffdf5509040) = 0
statx(28, 0x7f6c94725570, AT_STATX_SYNC_AS_STAT|AT_EMPTY_PATH, STATX_ALL, 0x7ffdf5509100) = 0
statx(28, 0x7f6c94725570, AT_STATX_SYNC_AS_STAT|AT_EMPTY_PATH, STATX_ALL, 0x7ffdf5509100) = 0
read(28, 0x562270f65b28, 16384)         = 342
read(28, "", 16042)                     = 0
read(28, "", 16384)                     = 0
close(28)                               = 0
close(27)                               = 0
readlink(0x7ffdf5508d60, 0x7ffdf5508900, 1023) = -1 EINVAL (Invalid argument)
readlink(0x7ffdf5508d60, 0x7ffdf5508900, 1023) = -1 EINVAL (Invalid argument)
readlink(0x7ffdf5508d60, 0x7ffdf5508900, 1023) = 13
readlink(0x7ffdf5508d60, 0x7ffdf5508900, 1023) = -1 EINVAL (Invalid argument)
readlink(0x7ffdf5508d60, 0x7ffdf5508900, 1023) = -1 EINVAL (Invalid argument)
readlink(0x7ffdf5508d60, 0x7ffdf5508900, 1023) = -1 EINVAL (Invalid argument)
openat(AT_FDCWD, 0x5622700d8298, O_RDONLY|O_CLOEXEC) = 27
statx(27, 0x7f6c94725570, AT_STATX_SYNC_AS_STAT|AT_EMPTY_PATH, STATX_ALL, 0x7ffdf5509040) = 0
statx(27, 0x7f6c94725570, AT_STATX_SYNC_AS_STAT|AT_EMPTY_PATH, STATX_ALL, 0x7ffdf5509100) = 0
statx(27, 0x7f6c94725570, AT_STATX_SYNC_AS_STAT|AT_EMPTY_PATH, STATX_ALL, 0x7ffdf5509100) = 0
read(27, 0x562270f65b28, 16384)         = 100
read(27, "", 16284)                     = 0
read(27, "", 16384)                     = 0
openat(AT_FDCWD, 0x562270e71c28, O_RDONLY|O_CLOEXEC) = 28
statx(28, 0x7f6c94725570, AT_STATX_SYNC_AS_STAT|AT_EMPTY_PATH, STATX_ALL, 0x7ffdf5509040) = 0
statx(28, 0x7f6c94725570, AT_STATX_SYNC_AS_STAT|AT_EMPTY_PATH, STATX_ALL, 0x7ffdf5509100) = 0
statx(28, 0x7f6c94725570, AT_STATX_SYNC_AS_STAT|AT_EMPTY_PATH, STATX_ALL, 0x7ffdf5509100) = 0
read(28, 0x562270f65b28, 16384)         = 322
read(28, "", 16062)                     = 0
read(28, "", 16384)                     = 0
close(28)                               = 0
close(27)                               = 0
readlink(0x7ffdf5508d60, 0x7ffdf5508900, 1023) = -1 EINVAL (Invalid argument)
readlink(0x7ffdf5508d60, 0x7ffdf5508900, 1023) = -1 EINVAL (Invalid argument)
readlink(0x7ffdf5508d60, 0x7ffdf5508900, 1023) = 42
readlink(0x7ffdf5508d60, 0x7ffdf5508900, 1023) = -1 EINVAL (Invalid argument)
readlink(0x7ffdf5508d60, 0x7ffdf5508900, 1023) = -1 EINVAL (Invalid argument)
readlink(0x7ffdf5508d60, 0x7ffdf5508900, 1023) = -1 EINVAL (Invalid argument)
openat(AT_FDCWD, 0x562270e71c28, O_RDONLY|O_CLOEXEC) = 27
statx(27, 0x7f6c94725570, AT_STATX_SYNC_AS_STAT|AT_EMPTY_PATH, STATX_ALL, 0x7ffdf5509040) = 0
statx(27, 0x7f6c94725570, AT_STATX_SYNC_AS_STAT|AT_EMPTY_PATH, STATX_ALL, 0x7ffdf5509100) = 0
statx(27, 0x7f6c94725570, AT_STATX_SYNC_AS_STAT|AT_EMPTY_PATH, STATX_ALL, 0x7ffdf5509100) = 0
read(27, 0x562270f65b28, 16384)         = 31
read(27, "", 16353)                     = 0
read(27, "", 16384)                     = 0
openat(AT_FDCWD, 0x562270fab388, O_RDONLY|O_CLOEXEC) = 28
statx(28, 0x7f6c94725570, AT_STATX_SYNC_AS_STAT|AT_EMPTY_PATH, STATX_ALL, 0x7ffdf5509040) = 0
statx(28, 0x7f6c94725570, AT_STATX_SYNC_AS_STAT|AT_EMPTY_PATH, STATX_ALL, 0x7ffdf5509100) = 0
statx(28, 0x7f6c94725570, AT_STATX_SYNC_AS_STAT|AT_EMPTY_PATH, STATX_ALL, 0x7ffdf5509100) = 0
read(28, 0x562270f65b28, 16384)         = 317
read(28, "", 16067)                     = 0
read(28, "", 16384)                     = 0
close(28)                               = 0
close(27)                               = 0
readlink(0x7ffdf5508d60, 0x7ffdf5508900, 1023) = -1 EINVAL (Invalid argument)
readlink(0x7ffdf5508d60, 0x7ffdf5508900, 1023) = -1 EINVAL (Invalid argument)
readlink(0x7ffdf5508d60, 0x7ffdf5508900, 1023) = 23
readlink(0x7ffdf5508d60, 0x7ffdf5508900, 1023) = -1 EINVAL (Invalid argument)
readlink(0x7ffdf5508d60, 0x7ffdf5508900, 1023) = -1 EINVAL (Invalid argument)
readlink(0x7ffdf5508d60, 0x7ffdf5508900, 1023) = -1 EINVAL (Invalid argument)
openat(AT_FDCWD, 0x562270e71c28, O_RDONLY|O_CLOEXEC) = 27
statx(27, 0x7f6c94725570, AT_STATX_SYNC_AS_STAT|AT_EMPTY_PATH, STATX_ALL, 0x7ffdf5509040) = 0
statx(27, 0x7f6c94725570, AT_STATX_SYNC_AS_STAT|AT_EMPTY_PATH, STATX_ALL, 0x7ffdf5509100) = 0
statx(27, 0x7f6c94725570, AT_STATX_SYNC_AS_STAT|AT_EMPTY_PATH, STATX_ALL, 0x7ffdf5509100) = 0
read(27, 0x562270f65b28, 16384)         = 24
read(27, "", 16360)                     = 0
read(27, "", 16384)                     = 0
openat(AT_FDCWD, 0x562270fad5b8, O_RDONLY|O_CLOEXEC) = 28
statx(28, 0x7f6c94725570, AT_STATX_SYNC_AS_STAT|AT_EMPTY_PATH, STATX_ALL, 0x7ffdf5509040) = 0
statx(28, 0x7f6c94725570, AT_STATX_SYNC_AS_STAT|AT_EMPTY_PATH, STATX_ALL, 0x7ffdf5509100) = 0
statx(28, 0x7f6c94725570, AT_STATX_SYNC_AS_STAT|AT_EMPTY_PATH, STATX_ALL, 0x7ffdf5509100) = 0
read(28, 0x562270f65b28, 16384)         = 327
read(28, "", 16057)                     = 0
read(28, "", 16384)                     = 0
close(28)                               = 0
close(27)                               = 0
readlink(0x7ffdf5508d60, 0x7ffdf5508900, 1023) = -1 EINVAL (Invalid argument)
readlink(0x7ffdf5508d60, 0x7ffdf5508900, 1023) = -1 EINVAL (Invalid argument)
readlink(0x7ffdf5508d60, 0x7ffdf5508900, 1023) = 24
readlink(0x7ffdf5508d60, 0x7ffdf5508900, 1023) = -1 EINVAL (Invalid argument)
readlink(0x7ffdf5508d60, 0x7ffdf5508900, 1023) = -1 EINVAL (Invalid argument)
readlink(0x7ffdf5508d60, 0x7ffdf5508900, 1023) = -1 EINVAL (Invalid argument)
openat(AT_FDCWD, 0x562270f62118, O_RDONLY|O_CLOEXEC) = 27
statx(27, 0x7f6c94725570, AT_STATX_SYNC_AS_STAT|AT_EMPTY_PATH, STATX_ALL, 0x7ffdf5509040) = 0
statx(27, 0x7f6c94725570, AT_STATX_SYNC_AS_STAT|AT_EMPTY_PATH, STATX_ALL, 0x7ffdf5509100) = 0
statx(27, 0x7f6c94725570, AT_STATX_SYNC_AS_STAT|AT_EMPTY_PATH, STATX_ALL, 0x7ffdf5509100) = 0
read(27, 0x562270f65b28, 16384)         = 25
read(27, "", 16359)                     = 0
read(27, "", 16384)                     = 0
openat(AT_FDCWD, 0x5622704e5fd8, O_RDONLY|O_CLOEXEC) = 28
statx(28, 0x7f6c94725570, AT_STATX_SYNC_AS_STAT|AT_EMPTY_PATH, STATX_ALL, 0x7ffdf5509040) = 0
statx(28, 0x7f6c94725570, AT_STATX_SYNC_AS_STAT|AT_EMPTY_PATH, STATX_ALL, 0x7ffdf5509100) = 0
statx(28, 0x7f6c94725570, AT_STATX_SYNC_AS_STAT|AT_EMPTY_PATH, STATX_ALL, 0x7ffdf5509100) = 0
read(28, 0x562270f65b28, 16384)         = 330
read(28, "", 16054)                     = 0
read(28, "", 16384)                     = 0
close(28)                               = 0
close(27)                               = 0
readlink(0x7ffdf5508d60, 0x7ffdf5508900, 1023) = -1 EINVAL (Invalid argument)
readlink(0x7ffdf5508d60, 0x7ffdf5508900, 1023) = -1 EINVAL (Invalid argument)
readlink(0x7ffdf5508d60, 0x7ffdf5508900, 1023) = 22
readlink(0x7ffdf5508d60, 0x7ffdf5508900, 1023) = -1 EINVAL (Invalid argument)
readlink(0x7ffdf5508d60, 0x7ffdf5508900, 1023) = -1 EINVAL (Invalid argument)
readlink(0x7ffdf5508d60, 0x7ffdf5508900, 1023) = -1 EINVAL (Invalid argument)
readlink(0x7ffdf5508d60, 0x7ffdf5508900, 1023) = -1 EINVAL (Invalid argument)
openat(AT_FDCWD, 0x562270f62118, O_RDONLY|O_CLOEXEC) = 27
statx(27, 0x7f6c94725570, AT_STATX_SYNC_AS_STAT|AT_EMPTY_PATH, STATX_ALL, 0x7ffdf5509040) = 0
statx(27, 0x7f6c94725570, AT_STATX_SYNC_AS_STAT|AT_EMPTY_PATH, STATX_ALL, 0x7ffdf5509100) = 0
statx(27, 0x7f6c94725570, AT_STATX_SYNC_AS_STAT|AT_EMPTY_PATH, STATX_ALL, 0x7ffdf5509100) = 0
read(27, 0x562270f65b28, 16384)         = 23
read(27, "", 16361)                     = 0
read(27, "", 16384)                     = 0
openat(AT_FDCWD, 0x5622700af948, O_RDONLY|O_CLOEXEC) = 28
statx(28, 0x7f6c94725570, AT_STATX_SYNC_AS_STAT|AT_EMPTY_PATH, STATX_ALL, 0x7ffdf5509040) = 0
statx(28, 0x7f6c94725570, AT_STATX_SYNC_AS_STAT|AT_EMPTY_PATH, STATX_ALL, 0x7ffdf5509100) = 0
statx(28, 0x7f6c94725570, AT_STATX_SYNC_AS_STAT|AT_EMPTY_PATH, STATX_ALL, 0x7ffdf5509100) = 0
read(28, 0x562270f65b28, 16384)         = 313
read(28, "", 16071)                     = 0
read(28, "", 16384)                     = 0
close(28)                               = 0
close(27)                               = 0
readlink(0x7ffdf5508d60, 0x7ffdf5508900, 1023) = -1 EINVAL (Invalid argument)
readlink(0x7ffdf5508d60, 0x7ffdf5508900, 1023) = -1 EINVAL (Invalid argument)
readlink(0x7ffdf5508d60, 0x7ffdf5508900, 1023) = -1 EACCES (Permission denied)
openat(AT_FDCWD, 0x562270f62118, O_RDONLY|O_CLOEXEC) = 27
statx(27, 0x7f6c94725570, AT_STATX_SYNC_AS_STAT|AT_EMPTY_PATH, STATX_ALL, 0x7ffdf5509040) = 0
statx(27, 0x7f6c94725570, AT_STATX_SYNC_AS_STAT|AT_EMPTY_PATH, STATX_ALL, 0x7ffdf5509100) = 0
statx(27, 0x7f6c94725570, AT_STATX_SYNC_AS_STAT|AT_EMPTY_PATH, STATX_ALL, 0x7ffdf5509100) = 0
read(27, 0x562270f65b28, 16384)         = 78
read(27, "", 16306)                     = 0
read(27, "", 16384)                     = 0
openat(AT_FDCWD, 0x5622704e5fd8, O_RDONLY|O_CLOEXEC) = 28
statx(28, 0x7f6c94725570, AT_STATX_SYNC_AS_STAT|AT_EMPTY_PATH, STATX_ALL, 0x7ffdf5509040) = 0
statx(28, 0x7f6c94725570, AT_STATX_SYNC_AS_STAT|AT_EMPTY_PATH, STATX_ALL, 0x7ffdf5509100) = 0
statx(28, 0x7f6c94725570, AT_STATX_SYNC_AS_STAT|AT_EMPTY_PATH, STATX_ALL, 0x7ffdf5509100) = 0
read(28, 0x562270f65b28, 16384)         = 177
read(28, "", 16207)                     = 0
read(28, "", 16384)                     = 0
close(28)                               = 0
close(27)                               = 0
readlink(0x7ffdf5508d60, 0x7ffdf5508900, 1023) = -1 EINVAL (Invalid argument)
readlink(0x7ffdf5508d60, 0x7ffdf5508900, 1023) = -1 EINVAL (Invalid argument)
readlink(0x7ffdf5508d60, 0x7ffdf5508900, 1023) = -1 EACCES (Permission denied)
openat(AT_FDCWD, 0x562270f62118, O_RDONLY|O_CLOEXEC) = 27
statx(27, 0x7f6c94725570, AT_STATX_SYNC_AS_STAT|AT_EMPTY_PATH, STATX_ALL, 0x7ffdf5509040) = 0
statx(27, 0x7f6c94725570, AT_STATX_SYNC_AS_STAT|AT_EMPTY_PATH, STATX_ALL, 0x7ffdf5509100) = 0
statx(27, 0x7f6c94725570, AT_STATX_SYNC_AS_STAT|AT_EMPTY_PATH, STATX_ALL, 0x7ffdf5509100) = 0
read(27, 0x562270f65b28, 16384)         = 34
read(27, "", 16350)                     = 0
read(27, "", 16384)                     = 0
openat(AT_FDCWD, 0x562270fad5b8, O_RDONLY|O_CLOEXEC) = 28
statx(28, 0x7f6c94725570, AT_STATX_SYNC_AS_STAT|AT_EMPTY_PATH, STATX_ALL, 0x7ffdf5509040) = 0
statx(28, 0x7f6c94725570, AT_STATX_SYNC_AS_STAT|AT_EMPTY_PATH, STATX_ALL, 0x7ffdf5509100) = 0
statx(28, 0x7f6c94725570, AT_STATX_SYNC_AS_STAT|AT_EMPTY_PATH, STATX_ALL, 0x7ffdf5509100) = 0
read(28, 0x562270f65b28, 16384)         = 203
read(28, "", 16181)                     = 0
read(28, "", 16384)                     = 0
close(28)                               = 0
close(27)                               = 0
readlink(0x7ffdf5508d60, 0x7ffdf5508900, 1023) = -1 EINVAL (Invalid argument)
readlink(0x7ffdf5508d60, 0x7ffdf5508900, 1023) = -1 EINVAL (Invalid argument)
readlink(0x7ffdf5508d60, 0x7ffdf5508900, 1023) = -1 EACCES (Permission denied)
openat(AT_FDCWD, 0x56227064ae88, O_RDONLY|O_CLOEXEC) = 27
statx(27, 0x7f6c94725570, AT_STATX_SYNC_AS_STAT|AT_EMPTY_PATH, STATX_ALL, 0x7ffdf5509040) = 0
statx(27, 0x7f6c94725570, AT_STATX_SYNC_AS_STAT|AT_EMPTY_PATH, STATX_ALL, 0x7ffdf5509100) = 0
statx(27, 0x7f6c94725570, AT_STATX_SYNC_AS_STAT|AT_EMPTY_PATH, STATX_ALL, 0x7ffdf5509100) = 0
read(27, 0x562270f65b28, 16384)         = 67
read(27, "", 16317)                     = 0
read(27, "", 16384)                     = 0
openat(AT_FDCWD, 0x5622700af948, O_RDONLY|O_CLOEXEC) = 28
statx(28, 0x7f6c94725570, AT_STATX_SYNC_AS_STAT|AT_EMPTY_PATH, STATX_ALL, 0x7ffdf5509040) = 0
statx(28, 0x7f6c94725570, AT_STATX_SYNC_AS_STAT|AT_EMPTY_PATH, STATX_ALL, 0x7ffdf5509100) = 0
statx(28, 0x7f6c94725570, AT_STATX_SYNC_AS_STAT|AT_EMPTY_PATH, STATX_ALL, 0x7ffdf5509100) = 0
read(28, 0x562270f65b28, 16384)         = 189
read(28, "", 16195)                     = 0
read(28, "", 16384)                     = 0
close(28)                               = 0
close(27)                               = 0
access(0x562270f62408, F_OK)            = 0
write(7, 0x7ffdf5508ce0, 8)             = 8
futex(0x562270fc03d0, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 0, NULL, FUTEX_BITSET_MATCH_ANY) = -1 EAGAIN (Resource temporarily unavailable)
futex(0x562270fc0380, FUTEX_WAKE_PRIVATE, 1) = 0
write(5, 0x7ffdf5508c40, 8)             = 8
write(5, 0x7ffdf5508d60, 8)             = 8
write(5, 0x7ffdf5508d30, 8)             = 8
write(5, 0x7ffdf5508d30, 8)             = 8
write(5, 0x7ffdf5508da0, 8)             = 8
write(7, 0x7ffdf55090c0, 8)             = 8
futex(0x7f6c94856fd0, FUTEX_WAKE_PRIVATE, 1) = 1
write(7, 0x7ffdf5508f70, 8)             = 8
write(5, 0x7ffdf5509770, 8)             = 8
poll(0x562270de0e80, 7, 0)              = 1 ([0x562270de0e80])
read(5, 0x7ffdf55098a0, 16)             = 8
poll(0x562270de0e80, 7, 8154)           = 1 ([0x562270de0e80])
read(5, 0x7ffdf55098a0, 16)             = 8
read(20, 0x7f6c80429000, 22)            = 22
read(20, 0x7f6c8043b200, 128)           = 128
write(7, 0x7ffdf5509050, 8)             = 8
poll(0x562270de0e80, 7, 8149)           = 1 ([0x562270de0e80])
read(5, 0x7ffdf55098a0, 16)             = 8
write(7, 0x7ffdf5509050, 8)             = 8
poll(0x562270de0e80, 7, 8147)           = 1 ([0x562270de0e80])
read(5, 0x7ffdf55098a0, 16)             = 8
--- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0x28} ---
+++ killed by SIGSEGV +++
---
```
---
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.1
Revision: 5916a8f

Qt 5.15.2
Debugging mode is disabled.

Operating system: Fedora Linux 35 (Cloud Edition)
CPU architecture: x86_64
Kernel: linux 5.16.20-200.fc35.x86_64

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 2.18.2

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux (Fedora 35)
Desktop Env: KDE
Windowing System: X11

### PR DESCRIPTION
**Pull request by Aetf**
[NOTE]: # ( Describe your changes in detail, why is this change required? )
[NOTE]: # ( Explain large or complex code modifications. )
[NOTE]: # ( If it fixes an open issue, please add "Fixes #XXX" )

When the recycle bin is under the exposed group, searching will return entries in the recycle bin.

fix #7933, replaces #7850

## Testing strategy
[NOTE]: # ( Please describe in detail how you tested your changes. )
[TIP]:  # ( We expect new code to be covered by unit tests and documented with doc blocks! )
Added unit test

## Type of change
[NOTE]: # ( Please remove all lines which don't apply. )
- ✅ Bug fix (non-breaking change that fixes an issue)

### CODE REVIEW

**Comment by bionade24** [comment]
When will a release or a backport of this fix come out?

**Review by droidmonkey — APPROVED** [review]

**Comment by droidmonkey** [comment]
@Aetf In general I don't like leaving naked `Q_ASSERT(pointer)` checks because they will lead to an undiagnosed crash if they are hit in release build. We really should consider graceful exists and error messages (when necessary) for release builds.

**Comment by Aetf** [comment]
> @Aetf In general I don't like leaving naked `Q_ASSERT(pointer)` checks because they will lead to an undiagnosed crash if they are hit in release build. We really should consider graceful exists and error messages (when necessary) for release builds.

Will keep that in mind!

**Comment by bionade24** [comment]
When will there be a new release with this fix or a backport of this bugfix?

**Comment by droidmonkey** [comment]
You can use it right now at https://snapshot.keepassxc.org

**Comment by michaelk83** [comment]
You can also just clear the recycle bin, or define a separate group for FdoSecrets that doesn't include the recycle bin.

**Pull request merged**
