### PR TITLE
Fix regression: Remove length limit on password

### PR DESCRIPTION
**Pull request by bodograumann**
[NOTE]: # ( Describe your changes in detail, why is this change required? )
[NOTE]: # ( Explain large or complex code modifications. )
[NOTE]: # ( If it fixes an open issue, please add "Fixes #XXX" )

A feature of keepassxc, that I used, was to generate long passwords e.g. of 255 characters.
This feature was broken lately.

Not completely sure if this fix will just work like that, but it seemed worth a shot to me.

## Type of change
[NOTE]: # ( Please remove all lines which don't apply. )
- ✅ Bug fix (non-breaking change that fixes an issue)

### CODE REVIEW

**Review by phoerious — APPROVED** [review]
I am fine with merging this, but let me tell you: there is absolutely NOTHING gained from using a password that long.

**Comment by droidmonkey** [comment]
Can we add some form of a limit? I don't think this change is enough to ensure consistent ui

**Comment by phoerious** [comment]
I am fine with users being able to manually enter higher values than what they can dial in with the the slider. I don't care how long these are, but if you want to use excessively long passwords, keep in mind that your password will be hashed into a 128 or 256-bit hash value anyway, so a 10,000-bit entropy password isn't going to do anything for you. It only increases the chances of the web service fucking something up and locking you out.

**Comment by bodograumann** [comment]
I don't want to dismiss the good arguments that you bring, but I intentionally tried to avoid a discussion of whether it is sensible to use such long passwords. So let's just say I enjoy having them ;-)
(And yes, I have had problems due to that; but also when not adhering to a limit of 12 characters or when using some non-alphanumeric characters)

From a UI standpoint I don't find it too confusing if the slider stops at 128 characters. If you feel it might break the UI functionality or not achieve the goal, because the slider still keeps the value below 128, I could test that and possibly come up with a better solution.

**Comment by droidmonkey** [comment]
I'm good with just the text entry being unbound

**Comment by Dykam** [comment]
Just to double check, this was supposed to allow you to enter any length value into the password generator in 2.6.3, right? The thing it did for me is that now, either using the slider or by manual entry, the value doesn't go past 99. The slider still goes to a visual 128, but the effective length caps at 99. Manual entry is even less intuitive as it simply prevents me from adding a 3rd digit.

If this isn't intended behavior, I'll create a bug report.

**Comment by bodograumann** [comment]
Ugh, yeah sorry @Dykam. This is my bad. I should have read the docs more carefully.
Turns out the default maximum for QSpinBox is `99`.
So it seems an unbounded QSpinBox is not possible.

**Comment by droidmonkey** [comment]
This is what I get for not explicitly testing the feature...

**Pull request merged**
