### PR TITLE
Fix removing encrypted ASN.1 keys from ssh-agent

### LINKED ISSUE #6788: Removing from the agent not working for encrypted ASN.1 SSH keys
## Overview

For encrypted ASN.1 SSH keys, the public key is not available before decryption. On the other hand, the GUI does not request the decryption for key removals [1][2]. As a result, removing such keys from the agent does not work.

[1] https://github.com/keepassxreboot/keepassxc/blob/089c8df01d1676abb6d084edf4da7038bc0d9be2/src/gui/entry/EditEntryWidget.cpp#L734
[2] https://github.com/keepassxreboot/keepassxc/blob/089c8df01d1676abb6d084edf4da7038bc0d9be2/src/gui/DatabaseWidget.cpp#L651

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Create an encrypted ASN.1 SSH key with a non-empty passphrase (ex: `ssh-keygen -m PEM -f test_key`)
2. Create an entry and setup this key
3. Hit Ctrl+H to add the key to the agent
4. Hit Ctrl+Shift+H or "Remove from agent" in EditEntryWidget to remove the key from the agent

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
The key is no longer in the agent

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
The key is still in the agent, and there is an error message:
```
process_remove_identity: parse key: invalid format
```

## Context
[NOTE]: # ( Give us any additional information you may have. )
The simplest fix is decrypting the key before removing it from the agent
```Diff
diff --git a/src/gui/DatabaseWidget.cpp b/src/gui/DatabaseWidget.cpp
index 18437545..373ef1d0 100644
--- a/src/gui/DatabaseWidget.cpp
+++ b/src/gui/DatabaseWidget.cpp
@@ -648,7 +648,7 @@ void DatabaseWidget::removeFromAgent()
     }
 
     OpenSSHKey key;
-    if (settings.toOpenSSHKey(currentEntry, key, false)) {
+    if (settings.toOpenSSHKey(currentEntry, key, true)) {
         SSHAgent::instance()->removeIdentity(key);
     } else {
         m_messageWidget->showMessage(key.errorString(), MessageWidget::Error);
diff --git a/src/gui/entry/EditEntryWidget.cpp b/src/gui/entry/EditEntryWidget.cpp
index cd73090a..34143717 100644
--- a/src/gui/entry/EditEntryWidget.cpp
+++ b/src/gui/entry/EditEntryWidget.cpp
@@ -731,7 +731,7 @@ void EditEntryWidget::removeKeyFromAgent()
 {
     OpenSSHKey key;
 
-    if (!getOpenSSHKey(key)) {
+    if (!getOpenSSHKey(key, true)) {
         return;
     }
 
```
I'm not sure if there is a better fix - maybe decrypting the key only when needed?

### Environment

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.0-snapshot
Build Type: Snapshot
Revision: 089c8df

Qt 5.15.2
Debugging mode is disabled.

Operating system: Arch Linux
CPU architecture: x86_64
Kernel: linux 5.10.54-1-lts

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (only unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 2.18.1

[NOTE]: # ( Pick choices based on your environment )
Desktop Env: LXQt
Windowing System: X11
ssh-agent is from openssh 8.6p1

### PR DESCRIPTION
**Pull request by yan12125**
Contents of id_rsa-encrypted-asn1 are from
TestOpenSSHKey::testDecryptRSAAES128CBC().

Maybe testing keys should be extracted and shared among tests?

Closes #6788

## Screenshots
N/A

## Testing strategy

Using steps to reproduce mentioned in #6788

## Type of change
- ✅ Bug fix (non-breaking change that fixes an issue)

### CODE REVIEW

**Comment by yan12125** [comment]
Marking as draft - I'm not sure if skipping `Entry`-related sttufs in the test is a good idea or not.

**Comment by yan12125** [comment]
> I'm not sure if skipping `Entry`-related sttufs in the test is a good idea or not.

There seems no better approach. I'd like to keep it as is until GUI tests (#4468) are introduced.

**Comment by droidmonkey** [comment]
The new test should be combined with the existing keeagent tests.

**Comment by yan12125** [comment]
Hmm, do you mean `tests/TestSSHAgent.cpp`?

**Comment by droidmonkey** [comment]
Yes

**Comment by yan12125** [comment]
Test failures on Windows seem unrelated
```
[03:05:29] [Step 3/4] FAIL!  : TestCli::testYubiKeyOption() 'detected.count() > 0' returned FALSE. ()
[03:05:29] [Step 3/4] C:/BuildAgent/work/c401303cba1b4098/tests/TestCli.cpp(1825) : failure location
```

```
[03:05:57] [Step 3/4] FAIL!  : TestGui::testSave() Compared values are not the same
[03:05:57] [Step 3/4]    Actual   (m_tabWidget->tabName(m_tabWidget->currentIndex())): "testSave*"
[03:05:57] [Step 3/4]    Expected (QString("testSave"))                              : "testSave"
[03:05:57] [Step 3/4] C:/BuildAgent/work/c401303cba1b4098/tests/gui/TestGui.cpp(1271) : failure location
```

https://ci.keepassxc.org/viewLog.html?buildId=196359&buildTypeId=KeePassXC_ReleaseWin64Azure&tab=buildLog

**Comment by droidmonkey** [comment]
Yah don't worry about those. Just noise

**Review by droidmonkey — APPROVED** [review]

**Comment by yan12125** [comment]
Thanks!

**Comment by droidmonkey** [comment]
Thank you too!! Great find and easy fix

**Pull request merged**
