### PR TITLE
Correct multiple snap issues

### LINKED ISSUE #668: Commandline functionality missing (snap)
Installed 2.2.0 snap in ubuntu 16.04. Tried to find commandline documentation without success. Used command:

```
$ keepassxc --help
QXcbConnection: Could not connect to display
Aborted
```

which was very confusing, why is it connecting to something and failing without clear explanation.

In IRC someone said to use ```keepassxc-cli``` but no such command is packaged in the snap?

## Expected Behavior

Please provide CLI documentation. Expected CLI to work.

## Current Behavior

CLI command missing

## Possible Solution

Include CLI command to snap package

## Steps to Reproduce (for bugs)

1. sudo snap install keepassxc
2. keepassxc-cli
3. command not found

## Context

Major annoyance ...

## Your Environment

* KeePassXC version/commit used: (can be found under Help -> About)
* Qt version (e.g. Qt 5.3): 
* Compiler (e.g. Clang++3.6.0): 
* Operating System and version: 

Ubuntu 16.04 server

### LINKED ISSUE #693: YubiKey doesn't works on Snap version
I tried to enable and use YubiKey on Snap version but YubiKey doesn't shows on the list of valid devices. I done a comparison with Debian package (same version 2.2.0) and works fine. So I think the problem could be related to Snap access to USB devices.

### LINKED ISSUE #851: The (linux) desktop icon is hard-coded
I installed an Icon theme (Numix) but the icon does not change.
This is due to the fact that the **Icon** line of the desktop entry snap package is hard-coded.

## Expected Behavior
The desktop icon should change, when the user changes the icon theme.  

## Current Behavior
The desktop icon remains the package provided, despite the theme changes.

## Possible Solution
1. Install the provided icon(s) to a freedesktop standard location.
    * the [Icon Theme Specification](https://specifications.freedesktop.org/icon-theme-spec/icon-theme-spec-latest.html) should be followed
    * as well as the [Icon Naming Specification](https://specifications.freedesktop.org/icon-naming-spec/latest/)
    * The name `keepassxc` seems to be ok, but location should be something like `~/.local/share/icons[/hicolor]` or `/usr/share/icons[/hicolor]`
2. After that, the icon can be referenced by name in the desktop file
    * It can change from `/snap/keepassxc/23/share/icons/hicolor/256x256/apps/keepassxc.png` to simply `keepassxc`

## Steps to Reproduce (for bugs)

1. Install the snap:
```
sudo snap install keepassxc
```
2. Install an icon theme (eg: Numix-Circle):
```
sudo add-apt-repository ppa:numix/ppa
sudo apt update
sudo apt install numix-icon-theme-circle
```
3. Change the icon theme - this can be done with eg the Unity Tweak Tool:
```
sudo apt install unity-tweak-tool
```
4. The desktop entry does not change icon (although the theme provides it!)

## Context
It is a minor tweak, but enables people to use the icon from their favorite icon theme.

## Debug Info

KeePassXC - 2.2.0
Revision: 23

Libraries:
- _None_

Operating system: Ubuntu 16.04
CPU architecture:  x86_64 (64-bit)
Kernel: Linux 4.10.0-30-generic

Enabled extensions:
- _None_

### PR DESCRIPTION
**Pull request by droidmonkey**
## Description

Provide fixes to multiple snap issues reported.
 * Fixes #693 by adding raw-usb plug
 * Fixes #668 by adding 'cli' app to the snap config. Launch using ```keepassxc.cli``` command (snap limitation).
 * Attempt to fix #851 by not hardcoding the icon in keepassxc.desktop

Note: In order to use Yubikey you must manually connect the raw-usb interface using: ```sudo snap connect keepassxc:raw-usb core:raw-usb```
## How has this been tested?

Manually and unit tests.

## Types of changes

- ✅ Bug fix (non-breaking change which fixes an issue)

## Checklist:

- ✅ I have read the **CONTRIBUTING** document. **[REQUIRED]**
- ✅ My code follows the code style of this project. **[REQUIRED]**
- ✅ All new and existing tests passed. **[REQUIRED]**
- ✅ I have compiled and verified my code with `-DWITH_ASAN=ON`. **[REQUIRED]**

### CODE REVIEW

**Comment by TheZ3ro** [comment]
> Note: In order to use Yubikey you must manually connect the raw-usb interface using: sudo snap connect keepassxc:raw-usb core:raw-usb

This needs to go in the documentation and in the FAQ page on the website.

**Comment by droidmonkey** [comment]
Btw it looks like thw new travis image causes asan to blow up.

**Comment by louib** [comment]
@droidmonkey the travis build should be passing if you rebase on `release/2.2.1`

**Comment by josechrist** [comment]
Command line:
It would be nice to have similar options than keepass, that is
keepass <db_URL> -keyfile:<path_to_file> -iousername:<username> -iopassword:<password> -ioscomplete -minimize
However, it would be much better to have -iousername:<path_to_file>
where file contains <username> <passwd> to hide username and passwd from process details

**Pull request merged**
