### PR TITLE
Fix global Auto-Type when database locked

### LINKED ISSUE #1216: MacOS: Auto-Type when database locked causes main window to steal focus
I am using KeepassXC on MacOS. When I press the hotkey to autotype a password in Safari, two instances of KeepassXC are opening to enter the database password. 
schermafbeelding 2017-11-23 om 08 52 10

If I enter the password in one of the instances (in this case: the one on top), the following error is displayed:
schermafbeelding 2017-11-23 om 08 55 30
(translated: could not find an element with window title: About KeepassXC)

## Expected Behavior
Only one instance should open.

## Current Behavior
Two instances open

## Steps to Reproduce (for bugs)
Press hotkey combination to autotype username and password in Safari

## Debug Info
KeePassXC - Version 2.2.2
Revision: 6d46717

Libraries:
- Qt 5.9.1
- libgcrypt 1.8.1

Operating system: macOS High Sierra (10.13)
CPU architecture: x86_64
Kernel: darwin 17.2.0

Enabled extensions:
- KeePassHTTP
- Auto-Type
- YubiKey

### LINKED ISSUE #2547: AutoType with locked database doesn't work
## Expected Behavior
When the database is locked, and the user triggers auto-type the vault should be requested to be unlocked, then auto-type should trigger on the app/tab name when the auto-type was triggered.

## Current Behavior
Currently when the database is locked, and the user triggers auto-type the vault is requested to be unlocked, then auto-type is triggered on the app/tab name when the database is unlocked. (which tends to be a KeePass title or even blank.) 

## Steps to Reproduce
1. Lock all open databases.
2. Trigger auto-type via keyboard combo.
3. Unlock database.

## Debug Info
KeePassXC - Version 2.3.4
Revision: 6fe821c

Libraries:
- Qt 5.9.3
- libgcrypt 1.8.2

Operating system: macOS 10.14
CPU architecture: x86_64
Kernel: darwin 18.2.0

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

### LINKED ISSUE #3003: Auto-Type doesn't work when app is shown as a workspace
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Auto-Type should put the Username and password into the browser window.

## Current Behavior
[NOTE]: # ( Tell us what actually happens )
It puts the password in the keepass searchbar.

## Possible Solution
[NOTE]: # ( Not required, but suggest a fix/reason for the bug )
It was working correctly in 2.3.

## Steps to Reproduce
[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )
1. Open your Firefox browser to a login page.
2. Highlight the corresponding entry in your keepass database.
3. Press Auto-Type button or keyboard short-cut.

## Context
[NOTE]: # ( How has this issue affected you? What unique circumstances do you have? )
I now have to go back and forth from keepass to the webpage copying both the username and the password.

## Debug Info
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.4.1
Revision: REVISION

Libraries:
- LIBS

Operating system: OSX
CPU architecture: ARCH
Kernel: KERNEL

Enabled extensions:
- EXTENSIONS

### LINKED ISSUE #3068: Main window raised on Auto-Type, causes it to fail
## Expected Behavior
In all previous versions, when I typed the global Auto-Type shortcut and there were multiple entries available, just a small dialog would appear with entries for me to select.

## Current Behavior
Now the main KeePassXC window is raised to the front, below the small dialog. When I select the entry, the main window remains raised, and Auto-Type just doesn't happen.

## Debug Info
KeePassXC - Version 2.4.1
Revision: 7bafe65

Qt 5.12.2
Debugging mode is disabled.

Operating system: Ubuntu 19.04 (Xubuntu 19.04)
CPU architecture: x86_64
Kernel: linux 4.15.0-36-generic

Enabled extensions:
- Auto-Type
- Integração com o Navegador
- Agente SSH
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.4

### PR DESCRIPTION
**Pull request by droidmonkey**
[TIP]:  # ( Provide a general summary of your changes in the title above ^^ )

## Type of change
[NOTE]: # ( Please remove all lines which don't apply. )
- ✅ Bug fix (non-breaking change which fixes an issue)

## Description and Context
[NOTE]: # ( Describe your changes in detail, why is this change required? )
[NOTE]: # ( Describe the context of your change. Explain large code modifications. )
[NOTE]: # ( If it fixes an open issue, please add "Fixes #XXX" as necessary )
* Store the currently active window right when the global keyboard shortcut is triggered
* Eliminate unnecessary window raise/lower and delays on macOS
* Remove duplicate addition of macutils symbols from mac Auto-Type plugin
* Fixes #1216 and fixes #3068 and fixes #3003 and fixes #2547

## Testing strategy
[NOTE]: # ( Please describe in detail how you tested your changes. )
[TIP]:  # ( We expect new code to be covered by unit tests and documented with doc blocks! )
Tested on Windows and macOS

## Checklist:
[NOTE]: # ( Please go over all the following points. )
[NOTE]: # ( Again, remove any lines which don't apply. )
[NOTE]: # ( Pull Requests that don't fulfill all [REQUIRED] requisites are likely )
[NOTE]: # ( to be sent back to you for correction or will be rejected.  )
- ✅ I have read the **CONTRIBUTING** document. **[REQUIRED]**
- ✅ My code follows the code style of this project. **[REQUIRED]**
- ✅ All new and existing tests passed. **[REQUIRED]**
- ✅ I have compiled and verified my code with `-DWITH_ASAN=ON`. **[REQUIRED]**
- ✅ My change requires a change to the documentation, and I have updated it accordingly.
- ✅ I have added tests to cover my changes.

### CODE REVIEW

**Comment by veysiertekin** [comment]
Hi @droidmonkey ,

I got a build from the branch, and tested. Problem #1216  seems still exists when database is locked ☹️ 

Screen Shot 2019-05-11 at 18 48 50


Also, if database is not locked, auto-type window does not get any focus. When i click the entry, immediately auto-type window get closed and does not type anything.

Screen Shot 2019-05-11 at 18 46 14

**Comment by droidmonkey** [comment]
I cannot fix the main window appearing.... That is a mac "feature". You have to be careful not to click anything after you unlock and (maybe) select an entry. You might have to increase your auto type delay to make sure things settle before typing begins.

**Comment by veysiertekin** [comment]
> I cannot fix the main window appearing.... That is a mac "feature". 

Ok, that is an understandable reason ☺️

---

After unlocking the database, auto-type window gets open, but when i select any entry via keyword, does not type anything. I have tested with "Auto-type start delay" -> "1000ms" or "3000ms", and "Auto-type typing delay" with "100ms" nothing changed ☹️

Also when database is not locked and pressed global auto-type, like i mentioned above; auto-type window does not get focused there for i can not select any entry.

**Comment by weslly** [comment]
> I cannot fix the main window appearing.... That is a mac "feature". You have to be careful not to click anything after you unlock and (maybe) select an entry. You might have to increase your auto type delay to make sure things settle before typing begins.

Wouldn't it be better to just disable the additional popup on macOS? I already tried to hide the main window before but I don't think it is possible at all to do that with Qt on macOS

**Comment by droidmonkey** [comment]
Disabling the popup would require a big refactor. I'm saving that for 2.5.0

**Comment by droidmonkey** [comment]
@veysiertekin I see what you mean, once the database was unlocked subsequent presses of the global auto-type shortcut causes the sequence selection dialog to not have focus. I have fixed this issue with the latest push, please try it again. I also lowered the activation delays so it feels a little more responsive.

**Comment by veysiertekin** [comment]
Hi @droidmonkey,

I have tested with your latest changes. Seems focusing problem has been fixed, but after selection of an entry, it goes back the application (in this case my browser), and keepassxc does not type anything like i mentioned above 😞 Not even a single character. (By the way i have build with qt/5.12.3, and tested on macOS 10.14.3)

**Comment by droidmonkey** [comment]
You probably have to disable/enable the accessibility access for your custom built application. You do that in macOS settings

**Comment by veysiertekin** [comment]
After addition to accessibility controls, worked as expected!
Thanks @droidmonkey

**Pull request merged**
