### PR TITLE
Adding a `Dockerfile` to run keepassxc in a container

### PR DESCRIPTION
**Pull request by auzias**
## Description
The file `Docker/Dockerfile` can be used to build a Docker image.
To build the image and run a container see the file `Docker/README.md`.

## Motivation and Context
This change is required in order to provide a community manage Docker image.

## How Has This Been Tested?
The container has been tested using the commands shown in `Docker/README.md`.

## Types of changes
- ✅ New feature (non-breaking change which adds functionality)

## Checklist:
- ✅ I have read the **CONTRIBUTING** document. **[REQUIRED]**
- ✅ My code follows the code style of this project. **[REQUIRED]**
- ✅ All new and existing tests passed. **[REQUIRED]**

### CODE REVIEW

**Comment by phoerious** [comment]
I would prefer distributing only stable and signed releases as Docker images, not the current develop branch.

For building KeePassXC in a Docker container we already have a Docker image based on Ubuntu 16.04. However, this still needs some work and we probably need to go back to CentOS 6.8 for best compatibility across the Linux landscape.

**Comment by droidmonkey** [comment]
Is this still required now that we have a docker container as part of the release script?

**Comment by phoerious** [comment]
I think this one is more intended to actually run KeePassXC. I'm not quite sure, though, where to put it in the source tree and how to properly distribute it.

**Comment by auzias** [comment]
It is indeed to *run* KeePassXC, not compile it. As for!
- where to put it: my guess is _it's up to_.
- how to distribute it... I'ld say http://hub.docker.com/

**Comment by phoerious** [comment]
After some more consideration, I still don't know where to put this. I would prefer having this Dockerfile on Dockerhub instead of our repository. I think that would be a better place.

**Comment by droidmonkey** [comment]
Recommend moving this to the packaging repo.

**Comment by droidmonkey** [comment]
Migrated over to keepassxc-packaging/#4

**Pull request closed without merging**
