### PR TITLE
Release preparation script

### PR DESCRIPTION
**Pull request by phoerious**
## Description
Add a helper script for release preparation.
The script automates merging from release branches to the master branch and creating release files.

Here is a list of features:

- merge from release branches to master (all branch names configurable)
- create release tags
- sign merge commits and release tags
- create a source tarball
- build sources either directly on your system or inside a dedicated Docker container (I added a Dockerfile based on Ubuntu 16.04 which can be used for creating a suitable image)
- creates an AppImage
- sign source tarball and AppImage

The script is targeted at the Linux release. Creating the release for Windows and OS X still requires some extra work, but one can easily reuse the source tarball for compiling the release on those platforms.

### CODE REVIEW

**Comment by ArchangeGabriel** [comment]
Some questions here:

– why are those changes in master already while this PR is still open?
– things here are a bit different from those there: https://github.com/keepassxreboot/keepassxc/wiki/Dev:-Prepare-a-release. I think this wiki page could be deleted or at least updated, but there is one difference with it I’d like to understand here.
– why .tar.bz2 source release instead of the provided .tar.gz one? Size? Then why not xz?

Thanks!

**Comment by phoerious** [comment]
This is still open because I'm still fixing a few things.
The release guide is a little outdated and we need to update it. But it's not a big deal since the only three people who bundle releases are @TheZ3ro @droidmonkey and myself. :-)

I chose bz2 because it offers better compression than gz and is still more common than xz. I don't think there are any distributions that don't support xz, but I guess bz2 still has wider compatibility. And besides that size is not that much of an issue because it's only the source code and not a binary release. Besides that, xz only reduces the size by about 100kB.

**Comment by phoerious** [comment]
I added some KeePassXC branding to the Windows installer.

**Comment by TheZ3ro** [comment]
I see little changes  :laughing:

**Comment by phoerious** [comment]
"little" 😆 

I'll add some more things and then I think the release script is finished. Only thing left then is another Docker file for building on CentOS 6.8.

**Comment by phoerious** [comment]
Alright, the script now also updates the language files before merging branches.

**Pull request merged**
