### PR TITLE
Fix id and appdata validation failures (#1131)

### LINKED ISSUE #1131: Invalid Application ID and other AppStream Appdata Issues
## Expected Behavior

Files should validate against the relaxed, or less strict, validation tests and not require downstream patching in order to be usable everywhere.

As part of this issue I will provide a pull request that fixes these issues, as well as some other minor ones.

## Current Behavior

The id is not compliant with the [AppStream specification](https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-id-generic).

Specifically the section that states:
*"The ID must follow a reverse-DNS scheme, consisting of __{tld}.{vendor}.{product}__, for example __org.kde.Gwenview__ or __com.hugski.ColorHug2__."*.

In addition to this the `<icon>` fails to validate with `appstream-util validate-relaxed`. It appears it is not allowed with desktop appdata. Personally I have never seen it used in this context.

While [Section 2.1.3. XML Specification](https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-icon) contradicts this, [Section 2.2. Desktop Applications](https://www.freedesktop.org/software/appstream/docs/sect-Metadata-Application.html) and [4.1. For GUI application upstream maintainers](https://www.freedesktop.org/software/appstream/docs/chap-Quickstart.html#sect-Quickstart-DesktopApps) never mention this tag and the latest validation tools does fail with this tag. It is possible this is an error in the documentation or left overd from older versions of the specification.

There are many more minor validation failures, but those are optional and not required for compliance. Therefore I won't bring it up in this issue.

## Possible Solution

Changing the id to `org.keepassxc.KeePassXC` and renaming the appropriate files based on that. Also removing the incorrect `<icon>` tag.

This will ensure that the most forgiving validation tests do not fail, making the appdata file usable everywhere.

## Steps to Reproduce

Flathub uses `appstream-util` for validation. Passing `appstream-util validate-relax org.keepassxc.appdata.xml`, is a [requirement for Flathub](https://github.com/flathub/flathub/wiki/Review-Guidelines#desktop-integration) (and `flatpak-builder` itself). Currently this fails:

```
org.keepassxc.appdata.xml: FAILED:
• tag-invalid           : <icon> not allowed in desktop appdata
• tag-invalid           : stock icon is not valid [keepassxc]
Validation of files failed
```

Running `appstream-util validate` reveals a lot more issues, but I won't focus on that in this issue. For now I am interested in this passing the minimum requirements since that is a relatively quick and simple fix.

You can also run `appstreamcli validate org.keepassxc.appdata.xml`. Passing this is a [optional requirement for AppImageHub](https://github.com/AppImage/appimage.github.io#checklist-for-submitting-your-own-appimage).

```
W - org.keepassxc.appdata.xml:org.keepassxc:4
    The component ID is not a reverse domain-name. Please update the ID and that of 
    the accompanying .desktop file to follow the latest version of the Desktop-Entry 
    and AppStream specifications and avoid future issues.

Validation failed: warnings: 1, pedantic: 14
```

Relevant to the context bellow is also this output from `flatpak-builder`, used with an updated and [improved manifest](https://github.com/AsavarTzeth/flathub/blob/org.keepassxc.KeePassXC/org.keepassxc.KeePassXC.json).

```
org.keepassxc:                     AppData problem: markup-invalid : <id> does not have correct extension for kind
org.keepassxc:                     AppData problem: tag-invalid : <icon> not allowed in desktop appdata
org.keepassxc:                     AppData problem: tag-invalid : stock icon is not valid [keepassxc]
Error loading AppData file: AppData file /app/share/appdata/org.keepassxc.KeePassXC.appdata.xml was not valid
Error: ERROR: appstream-compose failed: Barnprocess avslutades med kod 1
```

*Note that in this case I make `flatpak-builder` rename the appdata file so that it complies with the spec. The file `org.keepassxc.KeePassXC.appdata.xml` is your current appdata (as of 2.2.2 release).*

## Context

I am working on adding KeePassXC to Flathub. Some of the issues with the appdata and id are blockers for this. Solving this would enable me to finish this work immediately without patching downstream, which will likely be questioned by the Flathub reviewers.

As you might or might not be aware, your [existing flatpak](https://github.com/keepassxreboot/keepassxc-packaging/blob/master/flatpak/org.keepassxc.App.json) manifest uses `org.keepassxc.App` as the id. If you don't like the longer `org.keepassxc.KeePassXC` id that I choose, that is an alternative solution. What matters is that **{product}** is part of the id and that the id is the same everywhere (appdata, desktop entry, dbus id...).

### PR DESCRIPTION
**Pull request by AsavarTzeth**
## Description

According to the AppStream specification **org.keepassxc** is not a valid
id. The product name is missing. This results in failures if one tries
to validate the file and makes it unusable where validation is enforced.

Additionally it seems the specification don't allow the `<icon>` tag with
the component type desktop-application. I am not sure this tag is strictly
necessary anyhow. In any case validation tests require this to be removed.

Fixing both of these issues ensure the AppStream appdata is compliant
and works anywhere passing validations is a requirement.

Also provide some other fixes and improvements to the appdata.

Minor validation failures:

- Fix missing captions for screenshots (`appstreamcli`)
- Fix descriptions cannot start with `<ul>` tag (`appstream-util`)

Other enhancements:

- Add more URL types, but could not add donation type because "&" is not
  allowed in the `<url>` tag and using "%26" causes
  `appstreamcli validate` to fail.
- Add `<developer_name>`, which in cases such as KeePassXC is a team name.

## Motivation and context

Fix #1131, see that for all details.

## How has this been tested?

Using `appstream-util` and `appstreamcli` validation tests. No code is changed as part of this, however I have built the application from source and made sure that it works as part of packaging for flathub.

If anything in this pull request was incorrect the above mentioned tools and `flatpak-builder` would have caught it.

## Types of changes

- ✅ Bug fix (non-breaking change which fixes an issue)

## Checklist:

- ✅ I have read the **CONTRIBUTING** document. **[REQUIRED]**

### CODE REVIEW

**Comment by AsavarTzeth** [comment]
As mentioned in the linked issue, an alternative id could be `org.keepassxc.App`. To me it does not matter but it has to be changed to something. I choose an id based on what is commonly used with other projects.

**Comment by AsavarTzeth** [comment]
That should fix the AppImage recipe. Is there anything else I might have missed?

If you want me to squash all commits before the merge, just tell.

**Comment by AsavarTzeth** [comment]
Since the snap maintainer is yet to respond I took this as an opportunity to refresh my snapcraft knowledge, not that it is that difficult.

I have successfully built a package in the develop branch, with this merged. The snap was installed locally with `sudo snap install --devmode keepassxc_2.2.2_amd64.snap`. The desktop entry shows up and it launches as you would expect. The metainfo also shows up in Gnome Software.

I also verified that `/snap/keepassxc/current` contained these changes, just in case I had made some mistake.

Unless I missed something and as the builds are clean builds, everything should work with this merged.

**Comment by droidmonkey** [comment]
Sorry I didnt realize i had a task here. Never test a snap with --devmode, it basically removes all the sandboxing and could give false positive results. You want to use --dangerous to install a snap offline.

**Comment by AsavarTzeth** [comment]
I just followed the official snapcraft tutorial, which made no mention of this. Still, I did suspect I would do some misstake, like this.

Anyhow now that you are aware, there is no need for me to test it.

**Comment by droidmonkey** [comment]
If it built and installed then its good to go. Snapcraft will yell at you early and often if you make a typo.

**Comment by TheZ3ro** [comment]
@AsavarTzeth can you rebase this PR on latest develop? Thanks

**Comment by AsavarTzeth** [comment]
Rebased and pushed.

**Pull request merged**
