### PR TITLE
Convert from unicode to image based paperclip

### PR DESCRIPTION
**Pull request by droidmonkey**
## Description

Use an image instead of unicode string to display the attachment paperclip. This provides consistency in display and overcomes font deficiencies.

I made the paperclip column fixed width and corrected some sizing issues in the EntryView table.

## Motivation and context

Reports received from beta testers.

## Screenshots (if appropriate):
paperclip

## Types of changes

- ✅ Bug fix (non-breaking change which fixes an issue)

## Checklist:

- ✅ I have read the **CONTRIBUTING** document. **[REQUIRED]**
- ✅ My code follows the code style of this project. **[REQUIRED]**
- ✅ All new and existing tests passed. **[REQUIRED]**
- ✅ I have compiled and verified my code with `-DWITH_ASAN=ON`. **[REQUIRED]**
- ✅ My change requires a change to the documentation and I have updated it accordingly.
- ✅ I have added tests to cover my changes.

### CODE REVIEW

**Comment by phoerious** [comment]
Looks OK to me, but TC is having complaints.

**Comment by droidmonkey** [comment]
I had to move the icon loading into code that contains a GUI. When we run our non-gui tests we explicitly don't load a QApplication which is what QIcon relies on to do loading of images. Strange that there is no assert, it just crashes.

**Comment by phoerious** [comment]
The tests are still crashing.

**Comment by droidmonkey** [comment]
Tests passing, but the docker image is jacked up on teamcity.

**Comment by phoerious** [comment]
You need to force a rebuild. It's still trying to fetch the old libsodium18 package instead of libsodium23.

**Pull request merged**
