### PR TITLE
Bundle icons using the Qt resource system to enable reproducible builds

### LINKED ISSUE #2582: Use reproducible builds
To have a complete chain of trust, a software should:
1. have signed tags, and maybe commits (the writing part) ;
2. use [reproducible builds](https://en.wikipedia.org/wiki/Reproducible_builds) (the compiling part) ;
3. provide digital signatures of the final builds like OpenPGP, Authenticode, etc. (the distribution part).

Steps `1.` and `3.` are completed; great!

But to complete this chain of trust, the project should also comply with step `2.` (the compiling part). If it's already done, there should be some documentation to let users verify it by themselves.

Notable projects already follow the recommendations given on https://reproducible-builds.org/ : Arch Linux, Bitcoin, Debian, FreeBSD, Fedora, OpenWRT, Tails, Tor, etc.

### PR DESCRIPTION
**Pull request by phoerious**
[TIP]:  # ( Provide a general summary of your changes in the title above ^^ )

## Type of change
[NOTE]: # ( Please remove all lines which don't apply. )
- ✅ Bug fix (non-breaking change which fixes an issue)
- ✅ Refactor (significant modification to existing code)

## Description and Context
[NOTE]: # ( Describe your changes in detail, why is this change required? )
[NOTE]: # ( Describe the context of your change. Explain large code modifications. )
[NOTE]: # ( If it fixes an open issue, please add "Fixes #XXX" as necessary )

Bundles icons and other assets using the Qt resource system. Since icons are now compiled into the binary, no more path deduction shenanigans have to be done in order to find them. For the sake of loading PDFs, I left the previous loading logic in place, but greatly simplified it so that no more build paths are hard-coded into the binary allowing for reproducible builds (fixes #2582).

I wanted to bundle translations as well, but couldn't find a quick and easy way to add the *.qm files as resources, which are compiled on-the-fly, and adding the raw *.ts files is useless.

## Checklist:
[NOTE]: # ( Please go over all the following points. )
[NOTE]: # ( Again, remove any lines which don't apply. )
[NOTE]: # ( Pull Requests that don't fulfill all [REQUIRED] requisites are likely )
[NOTE]: # ( to be sent back to you for correction or will be rejected.  )
- ✅ I have read the **CONTRIBUTING** document. **[REQUIRED]**
- ✅ My code follows the code style of this project. **[REQUIRED]**
- ✅ All new and existing tests passed. **[REQUIRED]**
- ✅ I have compiled and verified my code with `-DWITH_ASAN=ON`. **[REQUIRED]**

### CODE REVIEW

**Comment by droidmonkey** [comment]
🥂 FANTASTIC

**Comment by droidmonkey** [comment]
Can we rename `FilePath` to `Resources`?

**Comment by phoerious** [comment]
Sure.

**Comment by phoerious** [comment]
Done.

**Comment by phoerious** [comment]
Umpf. Lots of conflicts. Great.

**Comment by phoerious** [comment]
Rebased, conflicts solved, ready for review.

**Comment by droidmonkey** [comment]
Sorry I'll review this tonight

**Pull request merged**
