### PR TITLE
Browser Integration tests

### PR DESCRIPTION
**Pull request by varjolintu**
[TIP]:  # ( Provide a general summary of your changes in the title above ^^ )

## Type of change
[NOTE]: # ( Please remove all lines which don't apply. )
- ✅ New feature (non-breaking change which adds functionality)

## Description and Context
[NOTE]: # ( Describe your changes in detail, why is this change required? )
[NOTE]: # ( Describe the context of your change. Explain large code modifications. )
[NOTE]: # ( If it fixes an open issue, please add "Fixes #XXX" as necessary )

## Checklist:
[NOTE]: # ( Please go over all the following points. )
[NOTE]: # ( Again, remove any lines which don't apply. )
[NOTE]: # ( Pull Requests that don't fulfill all [REQUIRED] requisites are likely )
[NOTE]: # ( to be sent back to you for correction or will be rejected.  )
- ✅ I have read the **CONTRIBUTING** document. **[REQUIRED]**
- ✅ My code follows the code style of this project. **[REQUIRED]**
- ✅ All new and existing tests passed. **[REQUIRED]**
- ✅ I have compiled and verified my code with `-DWITH_ASAN=ON`. **[REQUIRED]**

### CODE REVIEW

**Comment by droidmonkey** [comment]
Yes!

**Comment by droidmonkey** [comment]
You have a compiler error:

```[08:28:35]	/Users/kpxc/keepassxc/23018/tests/TestBrowser.cpp:78:70: error: too many arguments to function call, expected 2, have 3
[08:28:35]	    auto decrypted = m_browserAction->decryptMessage(message, NONCE, "test-action");
[08:28:35]	                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                 ^~~~~~~~~~~~~
[08:28:35]	/Users/kpxc/keepassxc/23018/src/browser/BrowserAction.h:79:5: note: 'decryptMessage' declared here
[08:28:35]	    QJsonObject decryptMessage(const QString& message, const QString& nonce);
[08:28:35]	    ^```

**Comment by varjolintu** [comment]
> You have a compiler error:

Yes I'm aware of that :) Rebasing this after I see if anything else is needed.

**Comment by varjolintu** [comment]
The JSON comparisons still fail, be patient. Everything compiles fine with the newer versions on my machine.

**Pull request closed without merging**
