### PR TITLE
Add monospaced font option for Notes field

### PR DESCRIPTION
**Pull request by ba32107**
[TIP]:  # ( Provide a general summary of your changes in the title above ^^ )

## Type of change
[NOTE]: # ( Please remove all lines which don't apply. )
- ✅ New feature (non-breaking change which adds functionality)

## Description and Context
[NOTE]: # ( Describe your changes in detail, why is this change required? )
[NOTE]: # ( Describe the context of your change. Explain large code modifications. )
[NOTE]: # ( If it fixes an open issue, please add "Fixes #XXX" as necessary )
Fixes https://github.com/keepassxreboot/keepassxc/issues/540

## Screenshots
[TIP]:  # ( Do not include screenshots of your actual database! )
See https://github.com/keepassxreboot/keepassxc/issues/540#issuecomment-505585978

## Testing strategy
[NOTE]: # ( Please describe in detail how you tested your changes. )
[TIP]:  # ( We expect new code to be covered by unit tests and documented with doc blocks! )
- Manual testing

## Checklist:
[NOTE]: # ( Please go over all the following points. )
[NOTE]: # ( Again, remove any lines which don't apply. )
[NOTE]: # ( Pull Requests that don't fulfill all [REQUIRED] requisites are likely )
[NOTE]: # ( to be sent back to you for correction or will be rejected.  )
- ✅ I have read the **CONTRIBUTING** document. **[REQUIRED]**
- ✅ My code follows the code style of this project. **[REQUIRED]**
- ✅ All new and existing tests passed. **[REQUIRED]**
- ✅ I have compiled and verified my code with `-DWITH_ASAN=ON`. **[REQUIRED]**

### CODE REVIEW

**Comment by droidmonkey** [comment]
I just realized that the group preview has a notes tab... we should combine that with general just like the entry preview.

Also, there is a lot of repeated code, it strikes me that when we move towards the style settings page we should introduce a `Style` class which you could call `getNotesFont` or similar function.

**Comment by ba32107** [comment]
I also realized as part of working on this that groups also have notes. I'll create an issue to track that.

**Comment by ba32107** [comment]
I just also realized that `Font.cpp` is a thing. I think I should change the implementation of this PR to use `Font::fixedFont()` instead of what it does currently.

**Comment by droidmonkey** [comment]
Not a bad idea

**Comment by ba32107** [comment]
Done. I also ran the code formatter and it changed an unrelated file.

**Pull request merged**
