### PR TITLE
Set URL placeholder text to https://example.com

### LINKED ISSUE #3830: Set URL field text suggestion to 'https://example.com'
Hello,
I have been introducing KeePassXC to a non-technical user. She was slightly confused about the field with the name "URL" since she apparently did not know what a URL is.

## Possible Solution
Rename "URL" to "Webpage" and add a note to translators that the translated name should be clear to non-technical users.

## Debug Info
Still present in KeePassXC 2.5.0. We have been using the Polish translation, but the field name is same in English version.

### PR DESCRIPTION
**Pull request by wolframroesler**
[TIP]:  # ( Provide a general summary of your changes in the title above ^^ )

## Type of change
[NOTE]: # ( Please remove all lines which don't apply. )
- ✅ New feature (non-breaking change which adds functionality)

## Description and Context
[NOTE]: # ( Describe your changes in detail, why is this change required? )
[NOTE]: # ( Describe the context of your change. Explain large code modifications. )
[NOTE]: # ( If it fixes an open issue, please add "Fixes #XXX" as necessary )

Adds a placeholder text to the URL input field in the entry editor, for non-technical users who don't know what a URL is.

Fixes #3830

## Screenshots
[TIP]:  # ( Do not include screenshots of your actual database! )

url-placeholder

## Testing strategy
[NOTE]: # ( Please describe in detail how you tested your changes. )
[TIP]:  # ( We expect new code to be covered by unit tests and documented with doc blocks! )

Tested manually.

Note: The "Title:" label in the dialog is cropped (visible in the screenshot); this has nothing to do with this PR and should be fixed independently.

## Checklist:
[NOTE]: # ( Please go over all the following points. )
[NOTE]: # ( Again, remove any lines which don't apply. )
[NOTE]: # ( Pull Requests that don't fulfill all [REQUIRED] requisites are likely )
[NOTE]: # ( to be sent back to you for correction or will be rejected.  )
- ✅ I have read the **CONTRIBUTING** document. **[REQUIRED]**
- ✅ My code follows the code style of this project. **[REQUIRED]**
- ✅ All new and existing tests passed. **[REQUIRED]**
- ✅ I have compiled and verified my code with `-DWITH_ASAN=ON`. **[REQUIRED]**

### CODE REVIEW

**Comment by droidmonkey** [comment]
There was an issue taking about what to replace the term "URL" with to make it more understandable for non technical users.

**Comment by wolframroesler** [comment]
AFAICT this was discussed in #3830 and the compromise was to keep the term "URL" and add an example URL as a placeholder in the input field, or are you referring to another issue?

**Comment by droidmonkey** [comment]
Oh right lol that was it

**Comment by wolframroesler** [comment]
Just a ping to make sure this little PR isn't forgotten ... :)

**Pull request merged**
