### PR TITLE
Update CHANGELOG.md - 2.7.7

### PR DESCRIPTION
**Pull request by yesbhautik**
Updated the CHANGELOG.md for version 2.7.7 which realised before 2 days.

## Type of change
- ✅ Documentation (non-code change)

### CODE REVIEW

**Comment by droidmonkey** [comment]
Need to bring over the share/linux/org.keepassxc.KeePassXC.appdata.xml file as well

**Comment by yesbhautik** [comment]
> Need to bring over the share/linux/org.keepassxc.KeePassXC.appdata.xml file as well

I have updated this file please check #10426.

**Comment by droidmonkey** [comment]
Just add it to this one please

**Comment by yesbhautik** [comment]
> Just add it to this one please

sorry but not getting your point. Just commit the PR which created for CHANGELOG.md.

**Comment by droidmonkey** [comment]
Add the file to this pr...

**Pull request closed without merging**
