### PR TITLE
Feature/qrcode

### PR DESCRIPTION
**Pull request by DavidHamburg**
Added feature to display passwords as QR Code.

## Description

Added menu and context menu item 'Show QR Code' to entries. The action opens a new small dialog which displays the password as QR Code.

## Motivation and Context

QR Codes help to transmit long passwords to mobile phones.

## How Has This Been Tested?

I have tested the branch at my local linux installation manually.

## Screenshots (if appropriate):

QR Code Dialog

## Types of changes
- ✅ New feature (non-breaking change which adds functionality)

## Checklist:
- ✅ I have read the **CONTRIBUTING** document. **[REQUIRED]**
- ✅ My code follows the code style of this project. **[REQUIRED]**
- ✅ All new and existing tests passed. **[REQUIRED]**

## Documentation

I'm not sure how to update the wiki pages. At least the dependencies list should be extended by qrencode.

### CODE REVIEW

**Comment by droidmonkey** [comment]
Please see #96

**Comment by DavidHamburg** [comment]
@droidmonkey ah ok. I missed this feature really badly when I made the switch from keepass to keepassx/c. This comes really handy when you need a password at your phone.

**Comment by droidmonkey** [comment]
I cant disagree with you, but it allows for bad security practices.

**Comment by DavidHamburg** [comment]
@droidmonkey You are right - you have to be careful and use qr readers that don't require any internet connection or save your passwords - e.g. https://www.microsoft.com/en-us/store/p/qr-code-offline/9wzdncrfj4tf. Then its way more secure than sending your password by mail  or messenger over the internet.

**Comment by droidmonkey** [comment]
Now there might be some room for innovation and we could publish a trusted app fot android/iphone that specifically reads qr codes and NOTHING else. This is a nice wishlist app that would pair well with this pr in the future.

**Pull request closed without merging**
