### PR TITLE
Build the snap in travis

### PR DESCRIPTION
**Pull request by elopio**
Build the snap in travis on every pull request.

## Motivation and Context
This will make sure that no PR breaks the snap. And it's the first step for automatically publishing the snap to the ubuntu store.

## How Has This Been Tested?
Travis will test it.

## Types of changes
- :negative_squared_cross_mark: Bug fix (non-breaking change which fixes an issue)
- :white_check_mark: New feature (non-breaking change which adds functionality)
- :negative_squared_cross_mark: Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- :white_check_mark: I have read the **CONTRIBUTING** document. [REQUIRED]
- :white_check_mark: My code follows the code style of this project. [REQUIRED]
- :white_check_mark: All new and existing tests passed. [REQUIRED]
- :negative_squared_cross_mark: My change requires a change to the documentation.
- :negative_squared_cross_mark: I have updated the documentation accordingly.
- :white_check_mark: I have added tests to cover my changes.

### CODE REVIEW

**Comment by elopio** [comment]
Ok, ready. It was missing a popd.

**Comment by elopio** [comment]
Thanks for merging.
Now, to get this into the store somebody from your team needs to register it: https://myapps.developer.ubuntu.com/dev/click-apps/register-name/

After that, we can hook travis to automatically release. Can you take care of it @droidmonkey?
Please let me know if you need a hand.

pura vida.

**Comment by droidmonkey** [comment]
I'm on it!

**Comment by droidmonkey** [comment]
Posted (pending review)! The name is "keepassxc.droidmonkey"

This is a warning I received (which I think is why it doesn't show up in the application search):

```
desktop interfaces (unity7) specified without meta/gui/*.desktop. Please provide a desktop file via setup/gui/*.desktop if using snapcraft or meta/gui/*.desktop otherwise. It should reference one of the 'apps' from your snapcraft/snap.yaml. lint-snap-v2_meta_gui_desktop
```

**Comment by elopio** [comment]
@droidmonkey oh, sorry. I lost that in one of the repo migrations. Please review #91.
That should get rid of the warning, so you can publish without waiting for a manual review.

About the name, I was thinking that instead of using your personal account, you could register it under a team account. So instead of keepassxc.droidmonkey, it would be something like keepassxc.keepassxreboot. But for now, this is fine. I know the store team is hard working to make a great experience for multiple snaps with the same name. Later we can discuss about a rename, if you find it important.

**Comment by TheZ3ro** [comment]
Guys, why we don't open a discussion on [GoogleGroup](https://groups.google.com/forum/#!forum/keepassx-reboot) about this?

Also thanks @elopio for your work :+1:

**Pull request merged**
