### PR TITLE
Adds listener for Gnome specific screensaver activation

### PR DESCRIPTION
**Pull request by mikewoudenberg**
Adds a Screensaver activated listener for Gnome specific events to lock the database on Session deactivate on Ubuntu 17.x

## Description
Simply registers 

## Motivation and context
This is a simple implementation to restore the lock DB on session deactivate behaviour on Ubuntu 17.x as mentioned in #687   

## How has this been tested?
I made the modification to the project, built it on Ubuntu 17.10, ran it, opened a database and locked my session. Upon unlocking my session I found the database locked as expected.

I couldn't find a way to add tests to the project to test this automatically 

## Types of changes
- ✅ Bug fix (non-breaking change which fixes an issue)

## Checklist:
- ✅ I have read the **CONTRIBUTING** document. **[REQUIRED]**
- ✅ My code follows the code style of this project. **[REQUIRED]**
- ✅ All new and existing tests passed. **[REQUIRED]**
- ✅ I have compiled and verified my code with `-DWITH_ASAN=ON`. **[REQUIRED]**
- ✅ My change requires a change to the documentation and I have updated it accordingly.

### CODE REVIEW

**Comment by TheZ3ro** [comment]
@droidmonkey did you tested this?

**Comment by droidmonkey** [comment]
No i just approved the code itself, sorry meant to put a note in

**Comment by TheZ3ro** [comment]
Nevermind, I will test it today :)

**Comment by TheZ3ro** [comment]
Congrats @mikewoudenberg :tada:

**Pull request merged**
