### PR TITLE
add gui feature to copy password with TOTP appended

### PR DESCRIPTION
**Pull request by jimheden**
For use cases where a single field is used to enter both password and TOTP, this would save time.

## Testing strategy
Tested manually on Fedora 36

## Type of change
- ✅ New feature (change that adds functionality)

### CODE REVIEW

**Comment by droidmonkey** [comment]
Can you list more than one website that forces this craziness? I am not a fan of adding this as a feature, it's undiscoverable and used by 0.01%. In the past we recommened you create an Auto-Type window association for this pattern: `{PASSWORD}{TOTP}`

**Comment by jimheden** [comment]
I searched for "concatenate your password" and the first two links were sap and ibm, so perhaps useless for most, but quite useful for people who have to use {PASSWORD}{TOTP}

**Comment by jimheden** [comment]
In my environment it's freeipa, and the clipboard is better than Auto-Type for me as I can share it with VMs.
https://www.freeipa.org/page/V4/OTP#Self-Managed_Tokens

**Comment by mpas97** [comment]
I've also worked in companies where this was treated as an essential security measure to use topt after password only. Even Apple has created a [password manager resources repository](https://github.com/apple/password-manager-resources) recently where there is a main point "Websites Where 2FA Code is Appended to Password".

**Review by droidmonkey — APPROVED** [review]

**Pull request merged**
