### PR TITLE
Several fixes for Auto-Type

### LINKED ISSUE #7491: Auto-type failed to input tilde as a last pasword's character
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
I've noticed that regular and pick chars auto-type failed to input ~ as a last character

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Generate regular or pick chars auto-type password with ~ as a last character
2. Run auto-type of {password} or select ~ as last character in pick chars auto-type
3. Tilde won't appear until you press another key on keyboard

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Tilde should be inputed just as any character

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.0 Beta

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 10

### PR DESCRIPTION
**Pull request by droidmonkey**
* On Windows, offer explicit methods to use the virtual keyboard style of typing. This partially reverts 1150b69 by going back to the standard unicode method by default. However, uses can either add {MODE=VIRTUAL} to their sequence or choose "Use Virtual Keyboard" / CTRL+4 from the selection dialog.

* Took this opportunity to clean up the signature of  AutoType::performAutoType and AutoType::performAutoTypeWithSequence by removing the "hideWindow" attribute.

* Show keyboard shortcuts on the selection dialog context menu

* Fix selection dialog help icon color when in dark theme

* Fix #7491 

Also remove two unused/duplicate icons in separate commit.

## Screenshots
[TIP]:  # ( Do not include screenshots of your actual database! )
autotype_selection_dialog_type_menu

## Testing strategy
[NOTE]: # ( Please describe in detail how you tested your changes. )
[TIP]:  # ( We expect new code to be covered by unit tests and documented with doc blocks! )
Tested on Windows using VirtualBox and normal applications.

## Type of change
[NOTE]: # ( Please remove all lines which don't apply. )
- ✅ Bug fix (non-breaking change that fixes an issue)

### CODE REVIEW

**Review by hifi — APPROVED** [review]
No immediate regressions on Linux, can't test Windows. LGTM otherwise.

**Comment by michaelk83** [comment]
> choose "Use Virtual Keyboard" / CTRL+4 from the selection dialog.

Rather than placing that in the drop-down, maybe use a separate checkbox? So that you could still do `Type {...}` in virtual keyboard mode.

**Comment by droidmonkey** [comment]
Considered it, but it adds clutter to the UI and you should only use the virtual keyboard in specific circumstances. It does break in not-so-edge cases due to Windows being shit at internationalization. Going to leave it as is for now.

**Comment by hifi** [comment]
> ... So that you could still do `Type {...}` in virtual keyboard mode.

This is a bit kludgey but you can use the `{MODE=VIRTUAL}` in an entry sequence (duplicate or main) to get more options in the dialog.

**Comment by droidmonkey** [comment]
Tested on macOS and there are no regressions, works great!

**Pull request merged**
