### PR TITLE
Use entry action icons without any frame

### PR DESCRIPTION
**Pull request by lindhe**
Replace the chat icons with similar icons that does not have any frame at all.

Downloaded from https://materialdesignicons.com/

Signed-off-by: Andreas Lindhé <andreas@lindhe.io>

[TIP]:  # ( Provide a general summary of your changes in the title above ^^ )

## Type of change
- ✅ Bug fix (non-breaking change which fixes an issue)

## Description and Context
I agree with @OLLI-S [comment](https://github.com/keepassxreboot/keepassxc/pull/4066#issuecomment-575945036) in #4066, that current choice of icons for actions on entries is a bit strange. They are in speech bubbles, indicating some sort of "comment" or "chat" functionality. My suggestion is to simply drop the frame altogether, which makes the icons larger and hopefully clearer. 

I'm perfectly happy to scrap this PR if you have better solutions in mind. Just putting this out there, do what you want with it.

### Alternatives

* Another option I think would be fine is to have them in circles. Circles means nothing, but might be a neat visual cue to indicate a logical grouping of these icons.
* Should the `entry-delete` icon (the `X`) perhaps be a minus instead (either [minus](https://materialdesignicons.com/icon/minus) or [minus-circle-outline](https://materialdesignicons.com/icon/minus-circle-outline))? Makes sense as contrast to the `+` symbol.

## Screenshots
New icons with this commit
New icon for Clone entry

## Checklist:
[NOTE]: # ( Please go over all the following points. )
[NOTE]: # ( Again, remove any lines which don't apply. )
[NOTE]: # ( Pull Requests that don't fulfill all [REQUIRED] requisites are likely )
[NOTE]: # ( to be sent back to you for correction or will be rejected.  )
- ✅ I have read the **CONTRIBUTING** document. **[REQUIRED]**
- ✅ My code follows the code style of this project. **[REQUIRED]**
- ✅ All new and existing tests passed. **[REQUIRED]**
- ✅ I have compiled and verified my code with `-DWITH_ASAN=ON`. **[REQUIRED]**

### CODE REVIEW

**Comment by lindhe** [comment]
Forgot to include screenshot of the clone icon. Just a minute.

**Comment by phoerious** [comment]
Although I agree that the speech bubbles are perhaps a little confusing, I do like the visual grouping they create. In the screenshot you provided, there is no clear distinction between the different icons and it is not obvious what each group does or which icon belongs to a group in the first place (despite the additional whitespace between the groups). The proposed icons also have very different stroke widths, which creates quite an inhomogeneous overall appearance.

**Comment by lindhe** [comment]
I agree. Here's a screenshot of what it looks like with circles instead:

Icons with circles

**Comment by droidmonkey** [comment]
I like the circles, it also ties in the clone entry icon nicely.

**Comment by OLLI-S** [comment]
I really like the icons in the first screen shot (in the original posting).

Then I looked at the icons with the circles and my first thought was, that it is not good if only these icons have circles and the other icons not. And that you have separator lines between the blocks of icons, so you have a visual separation.

But then I had a closer look at the icons with the circles and I must say that they fit better in the complete layout (unique thickness of the lines).
They are really great!

But I also have a question:
In KeePassXC I have left to the "Open Database" icon the "New Database" icon.
Is it intended that this icon is missing in the screen shots above?

**Comment by phoerious** [comment]
> And that you have separator lines between the blocks of icons, so you have a visual separation.

The separator lines are very thin and hard to see and some themes swallow them completely.

> In KeePassXC I have left to the "Open Database" icon the "New Database" icon.
Is it intended that this icon is missing in the screen shots above?

Yes, that was removed, since it's an action that almost nobody needs when they already have a database.

**Comment by grenzor** [comment]
IMO the `file-document-box` family mentioned in https://github.com/keepassxreboot/keepassxc/pull/4066#issuecomment-570713501 looked like it would fit "entries" the best. Only thing it seemed to lack was the view/edit icon didn't have a pencil to make it more accurate. Maybe the icon with a pencil could requested at the Material Design repo if people think that `file-document-box` is more fitting for entries?

**Comment by OLLI-S** [comment]
I did not read anything in https://github.com/keepassxreboot/keepassxc/pull/4066#issuecomment-570713501, I just had a look at the following screen shot posted there:

image

I want to give **some general information** about the design of icons.
This is one of the criteria in the reports I write (checking applications under software-ergonomic aspects, usability, accessibility and UC ).

Icons must be easily distinguishable, it must be easy to keep them apart from each other.
So the distinctive feature (what differentiates the icons from each other) must be clearly visible, what means: must be at least 10 dpx (device pixels) in height.
The distinctive feature for "Add" and "Delete" is the "+" and the "-" symbol in the icons and this symbol is too small (smaller than 10 dpx).

**Comment by grenzor** [comment]
That picture is of the entry menu where the size of the distinctive features shouldn't be much of an issue since their function name is right next to the icon (they also don't look that small to me).

Icons/distinctive feature sizes matter much more in the toolbar where they aren't named and I think the plus and minus sizes would be big enough once the icons are scaled to the other toolbar icon sizes.

**Comment by droidmonkey** [comment]
I don't prefer the document icons because they are very busy with the horizontal lines.

**Comment by phoerious** [comment]
Those icons were a suggestion, but I think we discarded them pretty quickly for reasons mentioned.

**Comment by lindhe** [comment]
Like phoerious says, this is just a suggestion. Do what you will with it – I'm not one to hold grudges for discarding a PR.

**Pull request merged**
