### PR TITLE
Improve OPVault handling and replace test opvault

### PR DESCRIPTION
**Pull request by droidmonkey**
* Fix various bugs in opvault parsing to include: TOTP parsing, date handling, naming convention, attachments, and multiple url's.

* Remove category groups that don't have any entries.

* Simplify tests by focusing on the resulting database instead of the parsing mechanics.

* Remove proprietary "freddy" opvault in favor of self-made "keepassxc" opvault.

TODO:
 - [x] Fix macOS selection of opvault "file" (#4069)

[NOTE]: # ( Describe your changes in detail, why is this change required? )
[NOTE]: # ( Explain large or complex code modifications. )
[NOTE]: # ( If it fixes an open issue, please add "Fixes #XXX" )

## Testing strategy
[NOTE]: # ( Please describe in detail how you tested your changes. )
[TIP]:  # ( We expect new code to be covered by unit tests and documented with doc blocks! )
Changed tests to be more relevant to what we are expecting from the import process.

## Type of change
[NOTE]: # ( Please remove all lines which don't apply. )
- ✅ Bug fix (non-breaking change that fixes an issue)

### CODE REVIEW

**Comment by droidmonkey** [comment]
Ready for review

**Comment by droidmonkey** [comment]
Tests fixed and used QStringLiteral, ready to go after CI.

**Comment by jnprbill** [comment]
What is the passphrase for keepassxc.opvault?  I am trying to reproduce a bug and can't repro with freddy.opvault.  Would like to try keepassxc.opvault.

**Comment by droidmonkey** [comment]
I believe it is "secret" or "a"

**Comment by jnprbill** [comment]
Thank you.  "a" works.

**Pull request merged**
