### PR TITLE
Update Italian language

### PR DESCRIPTION
**Pull request by bovirus**
Update Italian language

### CODE REVIEW

**Comment by TheZ3ro** [comment]
We manage translation on [Transifex](https://www.transifex.com/keepassxc/keepassxc/)

**Comment by bovirus** [comment]
I sent you a message to join me to Transiflex Italian translation group.
Thanks.

**Comment by phoerious** [comment]
You should be able to simply join the team yourself.

**Comment by bovirus** [comment]
@TheZ3ro 

I joined to the team and I uploaded two ts files (now are 100% translated and checked)-

Please if you can merge two ts file in transiflex in one single ts file that I can compile as .qm and use it on program language folder to test it in place.

Now with two file is not possible.

**Comment by phoerious** [comment]
You can use the update.sh script in share/translations to update your language files with whatever is on Transifex and then recompile KeePassXC.

**Comment by bovirus** [comment]
I updated the file Italian file on Transliflex.
Who and when automatically update file into github repository?

**Pull request closed without merging**
