### PR TITLE
CLI: Group commands

### PR DESCRIPTION
**Pull request by louib**
This PR adds group manipulation commands (mkdir, mv and rmdir).

## Type of change
[NOTE]: # ( Please remove all lines which don't apply. )
- ✅ New feature (non-breaking change which adds functionality)

## Description and Context
See  https://github.com/keepassxreboot/keepassxc/issues/2703

## Testing strategy
unit tests + local testing.

## Checklist:
[NOTE]: # ( Please go over all the following points. )
[NOTE]: # ( Again, remove any lines which don't apply. )
[NOTE]: # ( Pull Requests that don't fulfill all [REQUIRED] requisites are likely )
[NOTE]: # ( to be sent back to you for correction or will be rejected.  )
- ✅ I have read the **CONTRIBUTING** document. **[REQUIRED]**
- ✅ My code follows the code style of this project. **[REQUIRED]**
- ✅ All new and existing tests passed. **[REQUIRED]**
- ✅ I have compiled and verified my code with `-DWITH_ASAN=ON`. **[REQUIRED]**
- ✅ My change requires a change to the documentation, and I have updated it accordingly.
- ✅ I have added tests to cover my changes.

### CODE REVIEW

**Comment by louib** [comment]
@sjamesr would you be up for a review on this one? would be nice with the new open command to have a kinda complete set of CLI commands.

**Comment by louib** [comment]
What about the `rmdir` behaviour? The Unix command would fail on a non-empty directory, whereas we will send the full group to the recycle bin **if it's enabled**. Does that make sense or is it too dangerous? I thought about adding a `-r` option to `rm` instead...

**Comment by droidmonkey** [comment]
I think the `rmdir` behavior is expected and non-destructive (if recycle bin is enabled). This is the same behavior as the GUI application. Having two distinct commands, one for entries `rm` and one for groups `rmdir`, makes a lot of sense to me.

**Comment by droidmonkey** [comment]
An additional command to add would be mvdir which would move or rename a group. I played around with implementing it and ran across a lot of edge cases. Recommend saving that one for the future.

**Pull request merged**
