### PR TITLE
Support quazip 1.0

### PR DESCRIPTION
**Pull request by antonio-rojas**
Adjust FindQuaZip for quazip 1.0 paths

## Testing strategy
Builds with quazip 1.0

## Type of change
- ✅ Bug fix (non-breaking change that fixes an issue)

### CODE REVIEW

**Comment by droidmonkey** [comment]
Quality 1.0 is incompatible with qt 5

**Comment by droidmonkey** [comment]
Why?

**Comment by Polynomial-C** [comment]
This patch breaks quazip detection each time a new quazip release appears. We just have this issue now here at [Gentoo downstream](https://bugs.gentoo.org/791955).
Any chance quazip detection could be done by using pkgconfig instead?

**Comment by droidmonkey** [comment]
I've removed quazip dependency in my upcoming keeshare refactor. This needs to be merged into 2.6.5 with support for both 0.x and 1.x quazip.

**Pull request closed without merging**
