### PR TITLE
Hide window when performing entry auto-type on macOS

### LINKED ISSUE #2883: Autotype doesn't work on Mac with 2.4.0
## Expected Behavior
Command + V on a Mac focuses on the last open window and enters the autotype sequence

## Current Behavior
It doesn't work. Tried Command + Shift + V but it enters the values in KeePassXC itself.

## Possible Solution
Not sure if this is intentional.

## Steps to Reproduce
1. Select an entry
2. Press Command + V -> nothing happens
3. Press Command + Shift + V the username and password are typed inside the search box for KeePassXC

## Context
The above used to work in 2.3.x

## Debug Info
KeePassXC - Version 2.4.0
Revision: c51752d

Libraries:
- Qt 5.12.2
- libgcrypt 1.8.4

Operating system: macOS Mojave (10.14)
CPU architecture: x86_64
Kernel: darwin 18.2.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (only unsigned sharing)
- YubiKey
- TouchID

### PR DESCRIPTION
**Pull request by droidmonkey**
[TIP]:  # ( Provide a general summary of your changes in the title above ^^ )

## Type of change
[NOTE]: # ( Please remove all lines which don't apply. )
- ✅ Bug fix (non-breaking change which fixes an issue)

## Description and Context
[NOTE]: # ( Describe your changes in detail, why is this change required? )
[NOTE]: # ( Describe the context of your change. Explain large code modifications. )
[NOTE]: # ( If it fixes an open issue, please add "Fixes #XXX" as necessary )
* Instead of choosing the last active window, always hide the current window (ie, KeePassXC)
* Fixes #2883

## Testing strategy
[NOTE]: # ( Please describe in detail how you tested your changes. )
[TIP]:  # ( We expect new code to be covered by unit tests and documented with doc blocks! )
Tested on macOS

## Checklist:
[NOTE]: # ( Please go over all the following points. )
[NOTE]: # ( Again, remove any lines which don't apply. )
[NOTE]: # ( Pull Requests that don't fulfill all [REQUIRED] requisites are likely )
[NOTE]: # ( to be sent back to you for correction or will be rejected.  )
- ✅ I have read the **CONTRIBUTING** document. **[REQUIRED]**
- ✅ My code follows the code style of this project. **[REQUIRED]**
- ✅ All new and existing tests passed. **[REQUIRED]**
- ✅ I have compiled and verified my code with `-DWITH_ASAN=ON`. **[REQUIRED]**
- ✅ My change requires a change to the documentation, and I have updated it accordingly.
- ✅ I have added tests to cover my changes.

### CODE REVIEW

**Comment by droidmonkey** [comment]
Whoops, missed the actual function call.

**Comment by RegnifDLog** [comment]
I think this broke auto-type for Full Screen Mode.  In 2.3.4 I could go from Chrome in Full Screen Mode to KeePassXC (not full screen), select the record, and hit autotype, and it would switch back to Chrome and work as expected.  With 2.4.1 it minimizes KeePassXC and types the username and pass in another active window that isn't in Full Screen Mode.  It seems as though focus won't go back to a Full Screen Mode window.

**Comment by easimon** [comment]
Seems like this change breaks Auto-Typing in the "Tunnelblick: Login Required" dialog.

Instead of selecting Tunnelblick login dialog, it seems to select the last window that is also reachable with CMD-Tab, and happily pastes login data there. 

Unfortunately Tunnelblick is not reachable like this, since it seems to use a different window / dialog type. Even the Tunnelblick configuration window does not have a title bar. Also, Tunnelblick's dialog title is not selectable in the Autotype/Window Associations configuration page in KeepassXC.

It may be arguable if that is an issue in either KeepassXC or Tunnelblick (not providing a main window to change to). But I wonder if that could be solved in KeepassXC again, since it worked before 2.4.1.

**Comment by droidmonkey** [comment]
That is unfortunate. Switching to the last selected window is the behavior on every other platform (fwiw). I would argue that Tunnelblick needs to conform to OS window standards

**Pull request merged**
