### PR TITLE
Fix broken build when using system zxcvbn

### LINKED ISSUE #10779: Broken build when using system zxcvbn
## Steps to Reproduce
Delete the contents of `src/zxcvbn` and build with system zxcvbn. This should not result in a broken build. However, exactly this happens to be the case. 

## Expected Behavior
Build completes without errors.

## Actual Behavior
The build stops when compiling `CliTest.cpp` with an error that the header `zxcvbn/zxcvbn.h` cannot be found.

### PR DESCRIPTION
**Pull request by sebastianlipponer**
Fixes #10779.

This change is a fixup of the zxcvbn include statement added in `CliTest.cpp` in commit https://github.com/keepassxreboot/keepassxc/commit/5513ff5c1fee82538f8ffb871c5be5d0976e787c . A zxcvbn/ directory prefix breaks building with system zxcvbn. Remove this prefix to align this include statement with ones present in other files. Furthermore, add zxcvbn libraries as dependency to CliTest.

Move src/zxcvbn to src/thirdparty/zxcvbn.

### CODE REVIEW

**Comment by droidmonkey** [comment]
Which system does this break on? We build using system zxcvbn on our Linux CI.

**Comment by sebastianlipponer** [comment]
Linux is actually affected. The reason you don't see this in CI is simply because file `src/zxcvb/zxcvbn.h` is still present and is used when compiling `CliTest.cpp`.

**Comment by droidmonkey** [comment]
I see, so the provided header is used even though we are linking to the system library.

**Comment by sebastianlipponer** [comment]
Exactly, I think the CI job should be updated to remove `src/zxcvbn` upfront to ensure that nothing is used from there when building with system zxcvbn.

Also, with the CMake changes I have made it should be possible to just move zxcvbn to `src/thirdparty`.

**Comment by droidmonkey** [comment]
I don't agree with tampering with the src folder for CI. But I do agree with moving to thirdparty. Can you bundle that in this PR?

**Review by droidmonkey — APPROVED** [review]

**Pull request merged**
