### PR TITLE
Add UI for editing tags

### PR DESCRIPTION
**Pull request by crmarsh**
## Description
This change exposes the tags field of entries to be viewed/edited in the advanced tab, and to be viewed in the details view. Also, text search is updated to also match tags. I've never touched Qt before, nor am I particularly good at UI things, so I'm happy to get any feedback on fixing this if it doesn't meet your standards.

## Motivation and context

I wanted to use the tags feature in a script I was writing. I was editing them in windows with KeePass, but found keepassxc much better on Linux, but missing this one thing.

This is related to #508, but does not add all the UI they request.

## How has this been tested?

This change should have very minimal impact, doesn't modify any existing behavior, just exposes one more piece of data (that was already being read/written) to the UI in the advanced tab of the entry editor. I tested this on Linux, saw that I was able to edit tags, and the changes were visible to other editors.

## Types of changes

- ✅ New feature (non-breaking change which adds functionality)

## Checklist:

- ✅ I have read the **CONTRIBUTING** document. **[REQUIRED]**
- ✅ My code follows the code style of this project. **[REQUIRED]**
- ✅ All new and existing tests passed. **[REQUIRED]**
- ✅ I have compiled and verified my code with `-DWITH_ASAN=ON`. **[REQUIRED]**

### CODE REVIEW

**Comment by crmarsh** [comment]
Thanks for taking a look so quickly :-)

Well, it's useful in interacting with other things as I said, but point taken. I'm open to looking at it some more. Do you have any suggestions for a place to add tags to that might be good for a newbie?

**Comment by droidmonkey** [comment]
Tags is a super complicated, advanced feature. I would not even attempt this if you are not familiar with Qt and/or our code base.

**Comment by crmarsh** [comment]
I agree that there is a gold plated version of supporting tags that would require a lot more effort/skill, but perhaps there is some minimal change that would satisfy the usefulness requirement to merge this.

**Comment by crmarsh** [comment]
I've updated this a little to also include tags in the search, perhaps that is what you were looking for?

**Comment by droidmonkey** [comment]
No. To implement tags fully you need to include global suggestions, click-to-filter, colors, click to remove ([example](https://zgab33vy595fw5zq-zippykid.netdna-ssl.com/wp-content/uploads/2017/10/DevStory-753x675.png). Anything less than this and it is not worth merging.

**Comment by crmarsh** [comment]
I'm well aware that this is not fully implementing tags -- I apologize, I thought a start was better than nothing, and would perhaps spur on further development by people more interested in this.

**Comment by phoerious** [comment]
You are welcome to work on it, but we cannot merge it until it has reached some basic maturity and usefulness. I have no problem with work-in-progress PRs, though.

**Comment by droidmonkey** [comment]
@crmarsh thanks for the head start, I just want to make sure you don't go down a rabbit hole that doesn't end up leading to a successful PR. If you take a good look at the examples I provided that may give you a good roadmap for where to take your current implementation.

**Comment by phoerious** [comment]
@crmarsh You still there?

**Comment by crmarsh** [comment]
I'm still alive; I'm just not sure I'm really interested in putting a lot more work into this. @droidmonkey I don't need pictures of what tag interfaces look like, I've used them, I could use a pointer to which widget implements them.

**Comment by droidmonkey** [comment]
There is not a qt tag widget, but I found this small example that might be a good place to start.

**Comment by droidmonkey** [comment]
Closing in favor of a new PR in the future

**Pull request closed without merging**
