### PR TITLE
Compare window title with entry URLs during autotype matching.

### LINKED ISSUE #537: Auto-Type new feature
I think it would be very useful if Auto-Type shortcut could use URL entry to match the browser address bar. There are many sites that Title entry doesn't match with the window title, like network devices.

### PR DESCRIPTION
**Pull request by jensrutschmann**
## Description
Compare window title with entry URLs during autotype matching (in addition to the entry title).

## Motivation and context
Sometimes websites don't set the title to something that can be used for looking up entries in the database, for example: 
Website: https://bugs.kde.org/show_bug.cgi?id=379616 (randomly picked issue)
Window title: "Bug list - Mozilla Firefox"
The entry title for this website would probably be something like "KDE Bugzilla", so there's no way the entry could be found. Instead of manually adding window hints, comparing the URL would make the entry match the window - if the browser adds the url / domain to the window title. This can be achieved with add-ons such as:
- https://addons.mozilla.org/it/firefox/addon/add-url-to-window-title/
- https://chrome.google.com/webstore/detail/url-in-title/ignpacbgnbnkaiooknalneoeladjnfgb

I'm using these add-ons together with the changes from this PR instead of keepasshttp (which is much more complex to set up but has more features of course).

Resolves #537

## How has this been tested?
- Added unit tests
- Manually tried while running on Linux

## Types of changes
- ✅ New feature (non-breaking change which adds functionality)

## Checklist:
- ✅ I have read the **CONTRIBUTING** document. **[REQUIRED]**
- ✅ My code follows the code style of this project. **[REQUIRED]**
- ✅ Compile with `-DWITH_ASAN=ON`. **[REQUIRED]**
    - Travis built successfully with this flag.
- ✅ All new and existing tests passed. **[REQUIRED]**
- ✅ I have added tests to cover my changes.

## TODO
- Currently this is an extension to the title matching, toggled by config option 'AutoTypeEntryTitleMatch'.
    - Should we adapt the i18n for this option?
    - Should this be another option? Probably there's no value in a separate option.
    - Should the existing option be renamed? I don't know how config option migration would need to be done.
- Please carefully review my pointer usage - I haven't done much C programming in the past.

### CODE REVIEW

**Comment by TheZ3ro** [comment]
Just one thing @jensrutschmann 
In the `SettingsWidgetGeneral.ui` file can you change the text to 
`Use entry title and URL to match windows for global Auto-Type`

**Comment by jensrutschmann** [comment]
Hey @TheZ3ro I've updated the UI file.

I could also update the German translation in transifex, but should I wait until this PR has been merged?

**Comment by TheZ3ro** [comment]
@jensrutschmann yes, you must wait until this PR is merge and we update the translation files over on Transifex with the 2.2 release

**Comment by GUiHKX** [comment]
This is what I was looking for (I'm a new KeepassXC user)! However, wouldn't it be better to have this as a separated option?

When I use KeePass on Windows I use [these Auto-Type options](https://i.imgur.com/f43mVVa.png) plus
 [this extension for Chrome](https://chrome.google.com/webstore/detail/ignpacbgnbnkaiooknalneoeladjnfgb?utm_source=chrome-app-launcher-info-dialog)... That way, I can use  Auto-Type on some third-party websites with no conflicts. For example, if I have two entries: 'Steam' and 'Steam Tools' (two different websites), auto-type will have a conflict... So, matching only URLs is the best option.

if I want to use Auto-Type on a regular desktop program, on KeePass I just have to add a tag containing the exact window title of the program, and then Auto-Type will work beautifully with no conflicts.

**Pull request merged**
