### PR TITLE
Final PR for 2.4.0

### LINKED ISSUE #1598: Support KeePassXC-Browser in Snaps
With the new KeePassXC 2.3.0, my snap install automatically updates, and warns me about KeePassHTTP, provides a nice link to the migration guide to change to KeePassXC-Browser.

However, when I follow the first step on these instructions, I get the warning:

> We're sorry, but KeePassXC-Browser is not supported for Snap releases at the moment.

## Expected Behavior

Support KeePassXC-Browser.

## Steps to Reproduce (for bugs)

1. Open Tools -> Settings
2. Click "Browser Integration"
3. See "not supported" message.

## Context

I wasn't aware of this change -- which seems like a great addition -- but searching the issue queue, I'm not finding any issue for it. Is this the right place?

I basically want to subscribe to an issue so I know when this feature is complete!

## Debug Info

KeePassXC - Version 2.3.0
Revision: 4c0ed74
Distribution: Snap

Libraries:
- Qt 5.7.1
- libgcrypt 1.7.6-beta

Operating system: Ubuntu Core 16
CPU architecture: x86_64
Kernel: linux 4.4.0-116-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

### LINKED ISSUE #2609: New database creation does not permit creating Yubikey-only protected database
Related to https://github.com/keepassxreboot/keepassxc/issues/2608

On Windows KeepassXC databases may be created without a password using HMACSHA1 only. On Linux this is not permitted.

image

I think there is reasonable security in the 20byte HMACSHA1 response so I would recommend warning but not preventing a user from doing this in the linux app. This would also be consistent with the Windows app.

### LINKED ISSUE #2647: Change wording on KeePassXC-Browser upgrade dialog in 2.4.0
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )

> Your KeePassXC-Browser settings need to be moved into the database settings.
This is necessary to maintain your current browser connections.
Would you like to migrate your existing settings now?

## Current Behavior
[NOTE]: # ( Tell us what actually happens )

> Legacy browser integration settings have been detected.
Do you want to upgrade the settings to the latest standard?
This is necessary to maintain compatibility with the browser plugin.

## Possible Solution
[NOTE]: # ( Not required, but suggest a fix/reason for the bug )
Update wording of message

### PR DESCRIPTION
**Pull request by droidmonkey**
[TIP]:  # ( Provide a general summary of your changes in the title above ^^ )

## Type of change
[NOTE]: # ( Please remove all lines which don't apply. )
- ✅ Bug fix (non-breaking change which fixes an issue)

## Description and Context
[NOTE]: # ( Describe your changes in detail, why is this change required? )
[NOTE]: # ( Describe the context of your change. Explain large code modifications. )
[NOTE]: # ( If it fixes an open issue, please add "Fixes #XXX" as necessary )
* Fix #2609 - Database can be created without a password; a warning is shown
* Fix #2647 - Wording updated for question about "legacy" browser settings
* Fix #1598 - Utility script to install native messaging configuration when using snaps or flatpak. Re-enabled browser extension support while building a snap.

```make format``` will be run and merged right after this PR and before the tag is made.

## Checklist:
[NOTE]: # ( Please go over all the following points. )
[NOTE]: # ( Again, remove any lines which don't apply. )
[NOTE]: # ( Pull Requests that don't fulfill all [REQUIRED] requisites are likely )
[NOTE]: # ( to be sent back to you for correction or will be rejected.  )
- ✅ I have read the **CONTRIBUTING** document. **[REQUIRED]**
- ✅ My code follows the code style of this project. **[REQUIRED]**
- ✅ All new and existing tests passed. **[REQUIRED]**
- ✅ I have compiled and verified my code with `-DWITH_ASAN=ON`. **[REQUIRED]**
- ✅ My change requires a change to the documentation, and I have updated it accordingly.
- ✅ I have added tests to cover my changes.

### CODE REVIEW

**Comment by varjolintu** [comment]
I cannot get the proxy to communicate with the snap version even after the helper script. I can see from `ss -apx` that the socket is listening but `strace` never reports any connection to the socket KeePassXC is listening.

**Comment by droidmonkey** [comment]
I have a fix for it, going to push in a moment

**Comment by varjolintu** [comment]
And btw, I wonder if that script is even necessary because we changed the native messaging script updating to be enabled by default. Would it solve the problem automatically? However, for me the option is disabled in the settings when using snaps, and it cannot be changed.

**Comment by droidmonkey** [comment]
The executable running in the snap cannot write to any "dot-folder" so we cannot inject the json file from the snap. This is the purpose of the script.

**Pull request merged**
