### PR TITLE
WIP: Change CTRL/CMD + W behavior to close window instead of database

### PR DESCRIPTION
**Pull request by wootsaejao**
[TIP]:  # ( Provide a general summary of your changes in the title above ^^ )

## Type of change
[NOTE]: # ( Please remove all lines which don't apply. )
- ✅ Breaking change (fix or feature that would cause existing functionality to change)

## Description and Context
Fix UX bug #2672 .  

## Screenshots
[TIP]:  # ( Do not include screenshots of your actual database! )

## Testing strategy
Automated GUI test added.

## Checklist:
[NOTE]: # ( Please go over all the following points. )
[NOTE]: # ( Again, remove any lines which don't apply. )
[NOTE]: # ( Pull Requests that don't fulfill all [REQUIRED] requisites are likely )
[NOTE]: # ( to be sent back to you for correction or will be rejected.  )
- ✅ I have read the **CONTRIBUTING** document. **[REQUIRED]**
- ✅ My code follows the code style of this project. **[REQUIRED]**
- [ ]  All new and existing tests passed. **[REQUIRED]**
- [ ]  I have compiled and verified my code with `-DWITH_ASAN=ON`. **[REQUIRED]**
- ✅ My change requires a change to the documentation, and I have updated it accordingly.
- ✅  I have added tests to cover my changes.

### CODE REVIEW

**Comment by droidmonkey** [comment]
This isn't the desired behavior on all operating systems. Ctrl+w closes tabs on Windows and Linux.

**Comment by wootsaejao** [comment]
> This isn't the desired behavior on all operating systems. Ctrl+w closes tabs on Windows and Linux.

I will limit the behavior to MacOS only, then.

**Comment by wootsaejao** [comment]
Oh, actually on MacOS, CMD+W does close tab when open multiple databases. Should we keep closing tabs until the last one is left, then close the window?

**Comment by droidmonkey** [comment]
Yes

**Comment by wootsaejao** [comment]
Noob question..., how can I run GUI test on my local machine?

**Comment by wootsaejao** [comment]
Figured out.

In the root `CMakeList.txt`, I have turned `WITH_GUI_TESTS` option to `ON`. `testgui` is now available under _Cmake Application_ (I'm using Clion).

**Comment by wootsaejao** [comment]
`Database > Close Database` menu item shortcut is still misleading.

**Comment by wootsaejao** [comment]
I'm planning to make a toggle-able setting for this.

I don't have any prior experience with Qt, so the code will be a bit messy. Any feedback would be greatly appreciated. :)

**Comment by droidmonkey** [comment]
I don't recommend working on this issue as your first entry to Qt.

**Comment by wootsaejao** [comment]
Agreed. I'm backing off for now.

**Comment by droidmonkey** [comment]
#2039 would be a good first issue to tackle.

**Pull request closed without merging**
