### PR TITLE
Draft: Libvirt auto-type support / auto-type extensibility

### PR DESCRIPTION
**Pull request by thebigb**
I was missing a way to use credentials on headless VMs/guests (e.g. server guests or other types of guests without a remote viewer such as SPICE/VNC), so I decided to extend the auto-type feature with support for [libvirt's `virDomainSendKey`](https://libvirt.org/html/libvirt-libvirt-domain.html#virDomainSendKey).

While this PR probably as functional as it's going to get, I'm still not really happy with the naming of some stuff like "external plugin". If you can think of a better names, let me know.

#### New plugin interface

Since the current auto-type plugin interface is very specifically built for platform integration and the libvirt feature requires explicit target selection I decided to create a new plugin interface. The libvirt plugin implements this new interface.

#### Target selection

The new plugin interface allows the implementation to (optionally) return a list of available targets. On auto-type the user is presented with a selection dialog to pick the desired target from the list. Upon selection, the plugin implementation gets the selected target provided with the auto-type action. 

#### Limitations

The plugin uses [libvirt's `virDomainSendKey`](https://libvirt.org/html/libvirt-libvirt-domain.html#virDomainSendKey) to send keystrokes, and sadly is constrained to a [limited key map](https://github.com/qemu/keycodemapdb/blob/master/data/keymaps.csv). So no unicode unless someone can figure out a reliable way to do that. I took a gander at [hex code input](https://en.wikipedia.org/wiki/Unicode_input#Hexadecimal_input), but that doesn't seem a great solution. 

#### Dead keys

In my experience the default Windows keyboard layout is US International (with dead keys), so I added some basic dead keys support. Dead keys are supported in the sense that it will properly output stuff like double quotes, backticks, and carets (but no accented letters). Since dead keys can be enabled/disabled in the OS, I added two new settings. One allows to enable/disable dead keys for Windows guests (best effort guest OS detection), the other allows to enable/disable dead keys for other guest operating systems.

## Screenshots

context-menu
target-select
dead-keys-settings

## Testing strategy

Functional:

- Create one or more libvirt domains (easiest to do with `virt-manager`)
- Make sure one of the libvirt domains is running (and shows up in `virsh list`)
- Open context menu "Perform Auto-Type To Plugin" -> "Libvirt"
- Select target libvirt domain
- ???
- Profit

Added two basic unit tests for the new plugin interface. Not sure what/how to automatically test other stuff. 

## To do

- [ ] Figure out why persistence of the two new settings seems broken. Could've sworn it worked at some point... :sweat_smile: 

## Type of change

- ✅ New feature (change that adds functionality)

### CODE REVIEW

**Comment by droidmonkey** [comment]
Thank you for the contribution, but this is a very specific use case that likely has a small audience. I think this would be best left as a fork for those interested, but not merged into the main program.

**Comment by thebigb** [comment]
That is fair enough. I moved the fork to another namespace and set this feature branch as default.

I would appreciate it if someone would review the code though. I don't write a lot of C++, so there might be an anti-pattern here and there.

**Comment by hifi** [comment]
With libvirt I've had no issues auto-typing to a SPICE window (like virt-viewer) when it has no input grab but the window is active. Is this *really* needed at all?

**Comment by thebigb** [comment]
I definitely agree that the use-cases are quite exotic, so I'm fine with maintaining a fork for this.

The main use-case I built this for is GPU passthrough, where you don't have SPICE/VNC available.

But even if SPICE/VNC is available, this extension does prevent accidental auto-typing to the wrong place if you mess up the window focus. 

Also when you have a headless guest, auto-grab won't work and you need to explicitly grab input during the initial auto-type delay. Of course you can increase the initial auto-type delay to work around that, but this extension does take out the guessing game of whether you got the right window and the input grab is active.

**Comment by droidmonkey** [comment]
Closing this in favor of a maintained fork.

**Pull request closed without merging**
