### PR TITLE
Add button to hide pre-release warning for this release.

### PR DESCRIPTION
**Pull request by phoerious**
[NOTE]: # ( Describe your changes in detail, why is this change required? )
[NOTE]: # ( Explain large or complex code modifications. )
[NOTE]: # ( If it fixes an open issue, please add "Fixes #XXX" )
Add button to hide pre-release warning for this release.

## Screenshots
[TIP]:  # ( Do not include screenshots of your actual database! )
image

## Type of change
[NOTE]: # ( Please remove all lines which don't apply. )
- ✅ New feature (change that adds functionality)

### CODE REVIEW

**Comment by droidmonkey** [comment]
There's a lot of code for a simple button.

**Comment by phoerious** [comment]
I just wanted to disconnect the signals afterwards and remove the button in case the pop-up is shown again for something else.

**Comment by droidmonkey** [comment]
Can we wrap the config setting in #ifdef QT_DEBUG so it doesn't pollute release config

**Comment by phoerious** [comment]
Is that really necessary? I find the extra two lines in two files more distracting than just leaving it there. If we are starting to ifdef the config options, we should do the same for all messages, but that gets our of hand rather quickly.

**Pull request merged**
