### PR TITLE
[RFC] Implement Freedesktop.org Secret Storage spec server side API

### PR DESCRIPTION
**Pull request by Aetf**
[TIP]:  # ( Provide a general summary of your changes in the title above ^^ )

This PR adds the feature requested in #1403, adding a new plugin implementing the Freedesktop.org Secret Storage [spec] version 0.2. Basically this exposes a new DBus service that is described in the spec which can be used by libsecret-based applications.

[spec]: https://www.freedesktop.org/wiki/Specifications/secret-storage-spec/

## Type of change
[NOTE]: # ( Please remove all lines which don't apply. )
- ✅ New feature (non-breaking change which adds functionality)

## Description and Context
[NOTE]: # ( Describe your changes in detail, why is this change required? )
[NOTE]: # ( Describe the context of your change. Explain large code modifications. )
[NOTE]: # ( If it fixes an open issue, please add "Fixes #XXX" as necessary )

For motivation, please see #1403 for discussion.

For a description of the plugin, please see the [README](https://github.com/Aetf/keepassxc/blob/fdo-secret-service/src/fdosecrets/README.md) file.

There are also some modifications to existing code:

- Add a helper class to override the message box's parent window
- `EntrySearcher` can now search attribute values including custom ones
- Extract `applyGroupIconTo` to be a member function of `Group`
- `DatabaseTabWidget::newDatabase` returns the created `DatabaseWidget`
- `DatabaseTabWidget` emits `databaseOpened` signal when a new tab is added
- `DatabaseWidget` can delete a list of entries now
- `DatabaseWidget` emits `databaseReplaced` signal when replacing the database
- Add `Aes128` in `SymmetricCipher::algorithmIvSize`
- Add necessary slots in `MainWindow` to show desktop notifications

## Screenshots
[TIP]:  # ( Do not include screenshots of your actual database! )
image
image

image

image

## Testing strategy
[NOTE]: # ( Please describe in detail how you tested your changes. )
[TIP]:  # ( We expect new code to be covered by unit tests and documented with doc blocks! )

- There are unit tests for session negotiation, but have no idea how to test other parts, as they are directly exposed on DBus.
- In develop, I've been successfully using the [python-secretstorage](https://github.com/mitya57/secretstorage) as a DBus client and I find its own test cases cover most of the common usage patterns and can exercise the server quite well.
- In addition, I tried to directly use seahorse and connecting to KeePassXC. It can successfully add/change/remove entries, as well as lock/unlock databases.
- I've been using this as the password backend for Vivaldi for a few weeks.

## Checklist:
[NOTE]: # ( Please go over all the following points. )
[NOTE]: # ( Again, remove any lines which don't apply. )
[NOTE]: # ( Pull Requests that don't fulfill all [REQUIRED] requisites are likely )
[NOTE]: # ( to be sent back to you for correction or will be rejected.  )
- ✅ I have read the **CONTRIBUTING** document. **[REQUIRED]**
- ✅ My code follows the code style of this project. **[REQUIRED]**
- ✅ All new and existing tests passed. **[REQUIRED]**
- ✅ I have compiled and verified my code with `-DWITH_ASAN=ON`. **[REQUIRED]**
- ✅ My change requires a change to the documentation, and I have updated it accordingly.
- ✅ I have added tests to cover my changes.

### CODE REVIEW

**Comment by Aetf** [comment]
Rebased on the latest develop branch and fixed EntrySearcher unit test.

**Comment by droidmonkey** [comment]
Can you please squash a majority of your interstitial commits? It is hard to see the forest from the trees at the current state.

**Comment by Aetf** [comment]
Sure, will do once I get to my computer.

**Comment by Aetf** [comment]
Re-ordered and squashed commits. Changes to other parts of KeepassXC are isolated into individual commits before the one last big commit adding the plugin. It should be a lot easier to read now.

**Comment by droidmonkey** [comment]
Oh very nice, thank you. I will review after 2.4.1 is settled.

**Comment by Aetf** [comment]
Force-pushed to fix some bugs when the database was reloaded due to external file changes. A new signal `databaseReplaced` is added to `DatabaseWidget`.

**Comment by Aetf** [comment]
Rebased on develop

**Comment by droidmonkey** [comment]
You have an issue in our CI, are we missing a dependency?

```
/opt/buildagent/work/c401303cba1b4098/src/fdosecrets/FdoSecretsPlugin.cpp:58:37: error: no member named 'get' in 'QScopedPointer<FdoSecrets::Service, QScopedPointerDeleter<FdoSecrets::Service> >'
[18:54:29]	            connect(m_secretService.get(), &Service::error, this, [this](const QString& msg) {
[18:54:29]	                    ~~~~~~~~~~~~~~~ ^
[18:54:29]	/opt/buildagent/work/c401303cba1b4098/src/fdosecrets/FdoSecretsPlugin.cpp:74:28: error: no member named 'get' in 'QScopedPointer<FdoSecrets::Service, QScopedPointerDeleter<FdoSecrets::Service> >'
[18:54:29]	    return m_secretService.get();
[18:54:29]	           ~~~~~~~~~~~~~~~ ^
```

**Comment by Aetf** [comment]
Ah, I see. `QScopedPointer::get` was introduced in Qt 5.11. I'm on Qt 5.12 so it's working locally... What is our lowest Qt version requirement? I need to find a way to check I'm not using any newer APIs.

**Comment by Aetf** [comment]
Remove any usages of APIs later than Qt 5.3. (I used the docker image at `ci/trusty`, which installs Qt 5.3.2, but isn't the requirement >= 5.2?)

**Comment by Aetf** [comment]
Just figured out that I can view the build log by logging in as a guest on TeamCity... I'll fix other CI test failures in a few days.

**Comment by droidmonkey** [comment]
@Aetf I haven't forgot about this. I will review this week and merge if acceptable. I'll also approve your bounty win.

**Comment by Aetf** [comment]
No problem :smile:

**Comment by droidmonkey** [comment]
@hifi We can use the desktop notification that was added here to notify when SSH credentials are being accessed (as an option). 

This notification path would also be nice for KeeShare.

**Comment by droidmonkey** [comment]
Merged!

P.S. - Go Blue!!

**Comment by Aetf** [comment]
Awesome! Thanks for reviewing it! 🚀

**Comment by phddoom** [comment]
@Aetf Thanks for this PR I just installed keepassxc-git from the AUR to try this out.

I am unable to get keepassxc to prompt to unlock when using `secret-tool`.

```bash
secret-tool lookup ATTRIBUTE VALUE
```

Produces nothing in the calling shell and no window prompting to unlock the database.

Am I doing something wrong, or misunderstanding what has been implemented?

Let me know if there is any information you need to help debug.

Thanks

**Comment by Aetf** [comment]
@phddoom Hi!

For security reasons, by default, your existing database will not be accessible through the secret storage API. You need to manually enable that.


- First of all, check that the integration plugin itself is enabled in KeepassXC settings.
- Then, on the same settings page, you will see a list of currently opened databases, with their exposed groups.
- Clicking on the "pen" button in the "Manage" column will bring you to the database specific settings page where you can select the group you want to expose.

image
image

**Comment by phddoom** [comment]
@Aetf  Thank you for the walkthrough.

I had followed those steps previously before making my post, I have double checked and I have the expected filename and group showing up in the secret service integration options.

Here is what I receive when the database is unlocked:

```
$ secret-tool search --all --unlock Uuid <UUID> 
[/org/freedesktop/secrets/collection/New_20database/<UUID>]
label = <LABEL>
secret = <SECRET>
created = 2017-08-09 23:17:18
modified = 2017-08-09 23:17:18
schema = (null)
attribute.Title = <TITLE>
attribute.URL = 
attribute.UserName = 
attribute.Path = <PATH>
attribute.Uuid = <UUID>
attribute.Notes = 
```

But when the database is locked:

```
$ secret-tool search --all --unlock Uuid <UUID> 
$
```

Let me know if there is any debug or logging I can do to help.

Thanks

**Comment by elvirolo** [comment]
I'm not sure this is the right place for reporting this - do let me know if I should open an issue instead (although it seems that issues are reserved for release and pre-release versions).
I tried using this plugin by using the latest git version which I installed via the AUR but it doesn't seem to let me expose groups. The plugin is enabled, but the "exposed database groups" list is empty.

I use the nextcloud desktop plugin, which interacts with libsecret via qtkeychain. As soon as my database is unlocked, it asks me to log in. It appears in the "authorization" tab, but I can't expose any password entries to it.

FWIW, I use sway 1.0 and (automatic) console login.

Thank you very much indeed for your work; I'd been hoping for this feature to be implemented for a very long time.

**Comment by droidmonkey** [comment]
For reference, this is the perfect place to post issues which may be documentation or training related regarding new features. Creating new issues for recently merged, but not deployed, features spreads the conversation out. With this conversation I can write documentation that meets niche cases not tested by the author. Now if this blows up into something that needs fixing, then we can create an issue to track it.

**Comment by Aetf** [comment]
@phddoom, unfortunately that behavior is intended. `secret-tool search --unlock` works like the following:
- Call `SearchItems` to get a list of locked items, and a list of unlocked items.
- Call `Unlock` on the list of locked items

However, in KeepassXC, when a database is locked, it's "gone" and there is *no* information left in the program to be able to search inside it. So the list of locked items is empty. So nothing will happen and the database remains locked.

@elopio The "exposed database groups" list enumerates exposed database groups for currently opened databases (either locked or not). You can then go from there to the per-database setting page to configure the exposed group. See my previous [comment](https://github.com/keepassxreboot/keepassxc/pull/2726#issuecomment-493243028).

If you have databases open but that list is empty, it's a bug and please create a new issue for that.

@droidmonkey What is the canonical place for this kind of plugin manual or "get started" like documentation? There are indeed some cases that are not so intuitive and I'd like to help document them.

Thanks

**Comment by elvirolo** [comment]
Thank you for your reply. My database is indeed open and unlocked, but the list is empty.

**Comment by Aetf** [comment]
@elvirolo  Okay. So there's indeed something went wrong. A few things to try:

- Close the app settings page and reopen it, see if the list is populated with your database.
- Outside of the app settings page, you can go directly to the database settings page using menu: `Database` -> `Database settings...`. Then you can use the `Secret Service Integration` section to adjust the exposed group for the current database.

**Comment by droidmonkey** [comment]
@Aetf I am going to flesh out our documentation section of the website once I get the final products from our tech writer. The best place for documentation will be (in the future) https://github.com/keepassxreboot/keepassxreboot.github.io

**Comment by Aetf** [comment]
@droidmonkey Cool! Let me know if anything is needed from my part documenting this plugin.

**Comment by elvirolo** [comment]
@Aetf Thank you for your help. Exposing a group from the database settings page did make it work for the Nextcloud client (which uses qtkeychain). However, NetworkManager doesn't seem to be able to store Wifi secret in Keepassxc. Here are the errors which are displayed in the journal when I try to configure a connection for a specific user (which is supposed to store the secret in the user's keyring):
```

no secrets: No agents were available for this request.
state change: need-auth -> failed (reason 'no-secrets', sys-iface-state: 'managed')

```

**Comment by Aetf** [comment]
@elvirolo Could you please post a record of dbus messages while reproducing the error using the following command?

```
dbus-monitor "interface='org.freedesktop.Secret.Service'" "interface='org.freedesktop.Secret.Collection'" "interface='org.freedesktop.Secret.Item'" "interface='org.freedesktop.Secret.Prompt'" > dbus.log
```

Please run the command right after starting KeepassXC, and make sure it's running when you use NetworkManager. Then, stop monitoring by hit `ctrl-c`. The log will be written in file `dbus.log`.

Note that the recording contains secret values passing through the interface, so be sure to **NOT** use your actual database file.

**Comment by elvirolo** [comment]
@Aetf Thank you for your reply. Here is the content of the logfile:

```
signal time=1558741284.373695 sender=org.freedesktop.DBus -> destination=:1.76 serial=2 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=NameAcquired
   string ":1.76"
signal time=1558741284.373797 sender=org.freedesktop.DBus -> destination=:1.76 serial=4 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=NameLost
   string ":1.76"

```

**Comment by Aetf** [comment]
@elvirolo Sorry for the late reply, I was busy last week...

It that all the content of the log file? It means no one ever contacted KeepassXC through the API. Could you double check if the dbus service is running when KeepassXC is open and while using NetworkManager? The command is
```
dbus-send --session --dest=org.freedesktop.DBus --type=method_call --print-reply  /org/freedesktop/DBus org.freedesktop.DBus.ListNames | grep 'org.freedesktop.secrets'
```
If it prints nothing, then the service is not running.

If the dbus service is running, then the issue is with NetworkManager, which doesn't correct use the API.

**Comment by elvirolo** [comment]
It is indeed running (the command outputs "string "org.freedesktop.secrets""). I'll contact the NetworkManager team to try and find out what's wrong. Thanks for your help.

**Comment by kocjs** [comment]
What is the right way to disable gnome-keyring-daemon?
On my Debian Buster system with GNOME this was the only way that worked so far.
`chmod 000 /usr/bin/gnome-keyring-daemon`

**Comment by michaelk83** [comment]
> Could you please post a record of dbus messages while reproducing the error using the following command?
> ```
> dbus-monitor "interface='org.freedesktop.Secret.Service'" "interface='org.freedesktop.Secret.Collection'" "interface='org.freedesktop.Secret.Item'" "interface='org.freedesktop.Secret.Prompt'" > dbus.log
> ```
> ...
> Note that the recording contains secret values passing through the interface, so be sure to **NOT** use your actual database file.

If this is still the current behavior, isn't that a security issue? A malicious script could launch `dbus-monitor` and then access those secret values via the log with a real database (or would that require root access?). Ideally, all communications should be encrypted, so that no secrets would be exposed. If that wasn't included in the original implementation, then that should be fixed separately.

[This comment](https://github.com/keepassxreboot/keepassxc/issues/1403#issuecomment-458704918) by @ntninja seems relevant (last two paragraphs):

> The browser protocol is better insofar as that it forces clients to provision their own HOTP key for encryption and authentication rather than regressing to a basic “if it can connect, it's trusted for everything”. See point 4 of my [proposal/notes](https://github.com/keepassxreboot/keepassxc/issues/1403#issuecomment-457949605) on my ideas on how this can be implemented (within certain limits) based on the sender's identity however.
> 
> I will admit however that provisioning those keys inside the bridge however is not ideal, but it's not like we can upgrade the existing SecretStorage protocol with this property.

If this needs changes to `libsecret` API to implement better, then we should reach out to Stef Walter, who is the maintainer of `libsecret` and co-author of the Secret Service API. But this should be fixed as possible with the current API.

[This `libsecret` issue](https://gitlab.gnome.org/GNOME/libsecret/-/issues/53) also may be relevant.

**Comment by droidmonkey** [comment]
This feature has come quite a long way since this PR. Dbus traffic is encrypted using asymmetric cryptography and we have implemented a prompt window when credentials are requested.

**Comment by michaelk83** [comment]
@droidmonkey , while we're at it, what's the situation on client isolation (point 4 of [ @ntninja 's plan](https://github.com/keepassxreboot/keepassxc/issues/1403#issuecomment-457949605))? One of the things that was bugging me with KWallet was the lack of such isolation: any app could get the password of any other app. I understand this is a general problem with such password stores, and is difficult to solve. But anything we can do to start moving the needle towards a solution, would be welcome IMO. It may be worthwhile to involve Stef Walter on that, at least.

**Comment by droidmonkey** [comment]
There is nothing stopping an app from requesting arbitrary data from the collection. This is part of the spec, and without strict AAA guarantees at the process level I'm not sure you'll ever get there. (e.g. Process A can cryptographically prove they are really Process A and has access to this specific credential set)

We did implement the prompt to allow access which tells you which process is requesting which entry. We also create a new encryption pipe for each client.

**Comment by michaelk83** [comment]
> We did implement the prompt to allow access which tells you which process is requesting which entry. We also create a new encryption pipe for each client.

That's already a start, which is good. But how is the process identity determined here? If it's just a string passed from the client, it's very easy to impersonate. Or more commonly, a client may neglect setting a sensible string - a known issue with KWallet.

If we can determine the process ID as has been suggested, that can be converted to the binary path. Maybe that could be tapmered-with too, if there's no tamper-proof system call for that, but that would already be more reliable than a client-specified string.

Once we have the app identity, KPXC can create a separate collection for each app, and let the user control which apps can access which collections (by default, only the one created for that app). Maybe that's already done?

Using collections for this lets binaries store more than secret. That's especially useful for interpreted scripts. This way, each script can save its own secrets in the interpreter's collection. The scripts for a particular interpreter still won't be isolated from each other, but at least they'll be isolated from other interpreters and binaries.

For further security, KPXC could fingerprint the binary on first access, and use that to control subsequent access. At its simplest, that could just be a SHA hash of the binary. That would mean that new binary versions will need to re-authenticate, but as far as I'm concerned, that's a feature. As long as the user has access control, he could tell KPXC to "let this newer version use that older version's collection". And the whole fingerprinting feature can be optional.

(In the future, there might be an online database of trusted binary fingerprints for each package, maintained by the package publishers. But that's a long way off.)

This isn't a perfect solution, but I think it's better than no isolation at all, a la KWallet.

**Comment by droidmonkey** [comment]
You should read up on all the subsequent FDO Secrets PRs from this one first. A lot of work has been done and almost everything you mention above is done already. Exception being the hashing of the binary.

**Comment by michaelk83** [comment]
> A lot of work has been done and almost everything you mention above is done already. Exception being the hashing of the binary.

Awesome, thanks! I have a bunch of PRs on my reading list already. Going over them.

**Pull request merged**
