### PR TITLE
Add methods isHardwareKeySupported and refreshHardwareKeys to DBus

### PR DESCRIPTION
**Pull request by Zocker1999NET**
[NOTE]: # ( Describe your changes in detail, why is this change required? )
[NOTE]: # ( Explain large or complex code modifications. )
[NOTE]: # ( If it fixes an open issue, please add "Fixes #XXX" )
Refs #8017 (is not a direct fix but allows an "improved workaround" which should be enough for most use cases)

It adds two methods to the DBus interface called isHardwareKeySupported and refreshHardwareKeys. The first one reflects if KeePassXC was built with hardware key support and can be used to verify that calling the second method (or future methods) makes sense. The second one allows one to force KeePassXC to refresh the list of detected hardware keys (similar to clicking on "Refresh" in the UI). This enables 3rd-party services to e.g. inform KeePassXC that a YubiKey was inserted and, like described in https://github.com/keepassxreboot/keepassxc/issues/8017#issuecomment-1119464959, allows 3rd-party applications to unlock a database which is secured with a Yubikey (semi-)automatically (given the key inserted was remembered to be last used for this database).

## Screenshots
[TIP]:  # ( Do not include screenshots of your actual database! )
*feature not really visible in UI*

## Testing strategy
[NOTE]: # ( Please describe in detail how you tested your changes. )
[TIP]:  # ( We expect new code to be covered by unit tests and documented with doc blocks! )
- tested manually by
    - calling isHardwareKeySupported with and without hardware key support and checking return value
    - inserting & removing YubiKey multiple times, calling refresh via DBus and verify in UI that KeePassXC detects inserted key / key was missing again and selected key automatically if recently used
- documentated and commented new functions properly
- **did not add any unit tests** because
    - testing isHardwareKeySupported properly without rebuilding not possible and unit test would depend on same code
    - I really have no good idea how to test refreshHardwareKeys using unit tests, ideas are appreciated

## Type of change
[NOTE]: # ( Please remove all lines which don't apply. )
- ✅ New feature (change that adds functionality)

### CODE REVIEW

**Comment by droidmonkey** [comment]
You don't need the issupported call because you return false if it's not in the refresh call. There is no circumstance where you would call issupported and NOT call refresh right afterwards if it is supported. Might as well collapse them.

**Comment by Zocker1999NET** [comment]
isSupported can help with deducting what the error was. Refresh will also return false if no devices were found. Instead of calling them in the order you suggested, if you call them as described below, isSupported serves the purpose to detuct what the error was:
```python3
if refresh():
  print("Devices were found successfully")
else:
  if isSupported():
    print("User, please insert your Yubikey")
  else:
    print("Oh, you seem to use a KeePassXC version which does not support Yubikeys. You might need to reinstall another KeePassXC variant")
```

**Review by droidmonkey — APPROVED** [review]

**Comment by michaelk83** [comment]
FYI, this is missing an update [in the Wiki](https://github.com/keepassxreboot/keepassxc/wiki/Using-DBus-with-KeePassXC).

**Comment by droidmonkey** [comment]
I added them

**Pull request merged**
