### PR TITLE
Remove offensive words from wordlist

### PR DESCRIPTION
**Pull request by elitejake**
[NOTE]: # ( Describe your changes in detail, why is this change required? )
[NOTE]: # ( Explain large or complex code modifications. )
[NOTE]: # ( If it fixes an open issue, please add "Fixes #XXX" )
I removed 3 words from the wordlist (used by the passphrase generator) which could be considered as offensive.
Because of the nature of these words, if occurred in a passphrase, can offend certain users. 
I used a public dataset to find the offensive words.

## Testing strategy
[NOTE]: # ( Please describe in detail how you tested your changes. )
[TIP]:  # ( We expect new code to be covered by unit tests and documented with doc blocks! )
I did not test my changes because I do not think it's necessary.

## Type of change
[NOTE]: # ( Please remove all lines which don't apply. )
- ✅ Bug fix (non-breaking change that fixes an issue)

### CODE REVIEW

**Comment by phoerious** [comment]
Could you check if there is a more up-to-date wordlist available on the EFF website?

**Comment by droidmonkey** [comment]
Fun fact, the probability of getting any one of those three words on any selection attempt is 0.038%

**Comment by elitejake** [comment]
> Could you check if there is a more up-to-date wordlist available on the EFF website?

[`eff_large.wordlist`](https://github.com/keepassxreboot/keepassxc/blob/develop/share/wordlists/eff_large.wordlist) is the longest wordlist available on [eff.org/dice](https://www.eff.org/dice). I don't think there has been any improvements or updates to the wordlist.

EFF has released slightly longer Fandom-inspired wordlists though:
- [`gameofthrones_8k-2018.txt`](https://www.eff.org/files/2018/08/29/gameofthrones_8k-2018.txt)
- [`harrypotter_8k_3column-txt.txt`](https://www.eff.org/files/2018/08/29/harrypotter_8k_3column-txt.txt)
- [`memory-alpha_8k_2018.txt`](https://www.eff.org/files/2018/08/29/memory-alpha_8k_2018.txt)
- [`starwars_8k_2018.txt`](https://www.eff.org/files/2018/08/29/starwars_8k_2018.txt)

These files are released under Creative Commons Attribution 3.0 United States license.

There are much longer public-domain wordlists in [Moby Words II](https://github.com/elitejake/Moby-Project/tree/main/Moby%20Words%20II).

**Review by phoerious — APPROVED** [review]
Ok, then.

**Pull request merged**
