### PR TITLE
Fixed background color when window is out of focus

### LINKED ISSUE #11424: Main window: background colors do not match when it is out of focus
## Overview
main

When the main window is out of focus, its different elements have different background colors. The background color should be the same. This applies to both dark and light themes. Although in a light theme it is not so noticeable, in any case the background color of the same elements has a different color.

### PR DESCRIPTION
**Pull request by xboxones1**
Fixes https://github.com/keepassxreboot/keepassxc/issues/11424
## Screenshots
before after

## Testing strategy
Manual

## Type of change
[NOTE]: # ( Please remove all lines which don't apply. )
- ✅ Bug fix (non-breaking change that fixes an issue)

### CODE REVIEW

**Comment by droidmonkey** [comment]
before/after screenshots please

**Review by droidmonkey — APPROVED** [review]

**Comment by droidmonkey** [comment]
Whoops, just make a new PR with the correction

**Comment by xboxones1** [comment]
Ok, I'll make a new PR, but I'd like to fix the scrollbar as well. Do you have any idea why this is happening?

**Comment by droidmonkey** [comment]
Not sure about the scrollbar, might be buried deep in the Qt style sheet documentation

**Pull request merged**
