### PR TITLE
Feature : Update entries across groups when merging

### PR DESCRIPTION
**Pull request by louib**
## Summary of changes:
* Find existing entries across the whole database when merging, using their UUID
* Update existing entry location when merging
* Added `shallow` option for cloning a group
* Moved `merge` tests to their own test file.
* Added `qDebug` statements when merging.

## Description

Currently the merge functionality updates the entries by UUIDs, but only if they are in the same group. Moving an entry to another group would prevent that entry from updating, and would create a second entry with the same UUID in the database. This would cause other problems, like the duplicate entry not being written when saving.

This PR searches for entries using UUIDs across all the destination DB when merging.

I initially wanted to create a separate function for the synchronize feature (see https://github.com/keepassxreboot/keepassxc/issues/819). I don't think this is a good idea anymore. I think users will expect the merge functionality to detect identical entries and merge / update them. And if the databases are completely different, no UUIDs will match, so it will basically only be a merge.

One thing that I think is missing would be to detect entries using the title. I also think users will expect this when merging 2 databases that have identical / similar structure, but have been created differently (so the entries have different UUIDs). This is tricky though because there might be multiple entries with the same name, and some of those entries might even match with the UUID, so additional logic would need to  be done for that. That would solve https://github.com/keepassxreboot/keepassxc/issues/818.

As the merge functionality gets more complex, we will add more unit tests for it, so I moved the merge tests to their own test file.

I added debug statements, because when I perform a merge/sync of my database (normally using the CLI), I want to have feedback on what was updated/created/moved.

Finally, I don't handle deleted entries and recycle bins yet, but I guess we should handle that in the future.

## How has this been tested?
* Existing unit tests are passing
* Added new unit tests for entry relocation / updating.

## Types of changes

- ✅ Bug fix
- ✅ New feature

## Checklist:

- ✅ I have read the **CONTRIBUTING** document. **[REQUIRED]**
- ✅ My code follows the code style of this project. **[REQUIRED]**
- ✅ All new and existing tests passed. **[REQUIRED]**
- ✅ I have compiled and verified my code with `-DWITH_ASAN=ON`. **[REQUIRED]**
- ✅ I have added tests to cover my changes.

### CODE REVIEW

**Comment by louib** [comment]
@keepassxreboot/core-developers this one is ready for reviewing.

**Comment by louib** [comment]
@TheZ3ro after a quick look at the KeePass code, I believe the MergeMode is configured at the database level, and not at the group level. I'm not even sure it's stored in the kdbx file. It looks like there's an intermediate form when merging to select the merge mode for the current merge operation. I believe that makes more sense than setting the merge mode at the group level. Would keeping the merge mode but setting it at the database level be acceptable?

I would also add a `synchronize` merge mode which would match entries and groups using the uuids.

**Comment by louib** [comment]
@keepassxreboot/core-developers opinions on this (and on the direction of the merge/synchronization feature)?

**Comment by louib** [comment]
@TheZ3ro I readded the `MergeMode`, I think we can address how to deal with it (Add the UI, move to the database level, etc) in another PR. There was a bug with the `KeepBoth` mode where the duplicated entry would use the same UUID as the old entry, with the same consequences as stated above. I fixed it and added unit test for it.

I think there is still a lot of work to do on the merge feature, but this is a path in the good direction I think. This PR is ready for a review.

**Comment by louib** [comment]
@TheZ3ro I think we should also match groups using UUIDs, but this is going to change the behaviour of the functionality. We could add an option to fallback on entry title / group name matching in the future. What do you think?

**Comment by TheZ3ro** [comment]
@louib it's ok I agree

**Pull request merged**
