### PR TITLE
USB Hotplug Detection and TouchID lid close fix

### LINKED ISSUE #8945: [macOS] Prompt for a master password, despite having quick unlock via Touch ID after opening the lid
## Overview
I have quick unlock enabled. Whenever I try to unlock my database after it has been locked due to closing the lid), there is a prompt for a master password. There is no button for quick unlock. After typing anything in the field (bad / good password), only then prompt to use the Touch ID and the db gets unlocked (given I use the right finger, so this part works fine).

**Note:** This seems to work as expected if I manually lock the db / put the machine to sleep / lock it.

## Steps to Reproduce
1. Unlock a db with quick unlock enabled.
1. Close the lid (make sure in your settings that KeePassXC will lock the db in this case).
1. Open the lid and try to unlock the db.

## Expected Behavior
As the quick unlock is enabled, I can click "Unlock Database" button, use the Touch ID to have the db unlocked.

## Actual Behavior
I get a prompt for a password, then (regardless the password is valid or not), I get a prompt for using Touch ID.
image1
image2
image3

## Context

KeePassXC - Version 2.7.4
Revision: 63b2394

Qt 5.15.6
Debugging mode is disabled.

Operating system: macOS 12.6
CPU architecture: arm64
Kernel: darwin 21.6.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 2.19.2

### PR DESCRIPTION
**Pull request by phoerious**
KeePassXC now automatically detects hotplugged USB devices, so users don't have to manually refresh the YubiKey list anymore.

Also fixes TouchID not being available after lid close (fixes #8945 and #10315)

## Type of change
[NOTE]: # ( Please remove all lines which don't apply. )
- ✅ New feature (change that adds functionality)
- ✅ Bug fix

### CODE REVIEW

**Comment by droidmonkey** [comment]
This is great, we can also implement an option to auto lock the database when the yubikey is unplugged. The downside to that is if you have pending changes to save, you'll have to plug your key back in.

**Comment by phoerious** [comment]
Windows implementation added. This should be ready for review.

**Comment by phoerious** [comment]
I took the chance to also improve the unlock widget.

All clutter except the password field is now hidden away by default. The hardware key selection has been reduced to a single checkbox that is only shown when a key is inserted and the key file selection is just a small link:

image

I show a hardware key selection combobox only if more than one key is inserted (when does that ever happen?):
image

Clicking the key file link opens the key file selection and then adds a new UI element for it:
image

**Review by droidmonkey — APPROVED** [review]

**Comment by liayn** [comment]
> I show a hardware key selection combobox only if more than one key is inserted (when does that ever happen?):

That happens all the time if you have any account that allows to register only 1 OTP key (Paypal... to name a few), but one owns multiple keys (which you should).

**Comment by phoerious** [comment]
You should have multiple keys for backup purposes, but there is no point in having them plugged in at the same time, unless perhaps you have one for work and another personal key. If you are just too paranoid to use the same key for different services, then you also shouldn't have them with you at the same time.

But anyway. You can have two plugged in if you need to.

**Comment by synthgab** [comment]
> when does that ever happen?

When you have a Yubikey with two slots (e.g. a Neo) ...

By the way, I struggled a little bit with this new feature and it seems that the key is not detected correctly right upon insertion: my 2015 Yubikey Neo still works like a charm, but its getting old and now needs some time to wake up, so I'm not sure this is worth filing a bug report.

The trick is to check the serial number: a 'refresh' is needed when it's only 2 or 3 digits instead of the 7 digits I expect, not a big deal, just paying attention when unlocking the database...

**Comment by phoerious** [comment]
Which YubiKey do you have?

**Comment by synthgab** [comment]
Hello, I have a [Yubikey NEO](https://support.yubico.com/hc/en-us/articles/360013714579-YubiKey-NEO), I bought it in something like 2015. Firmware version is 3.4.9, if that may help, but as I said, I'm used to have to wait a few seconds for it to initialize when plugged-in (TOTP over NFC on Android also takes a few seconds to load the codes).

I have kept slot 1 for Yubico OTP (with a custom keypair used for VPN connection), and slot 2 with challenge-response for KeepassXC, on top of the TOTP feature for several other accounts.

[Edit] Syntax fixing.

**Comment by droidmonkey** [comment]
The NEO keys were garbage, they have to be handled specially because they don't comply with yubikeys spec.

**Comment by phoerious** [comment]
I have a spare NEO as well and tested it with the change. For me, it worked totally fine. What OS are you on?

**Comment by synthgab** [comment]
Hello,

Thank you for following up on my comment, I'm on Windows and I reproduce this delay on both Windows 11 (23H2) and Windows 10 (21H2).

However, I agree with Neo 'randomness': each manufacturing year behaves differently, and this is why I don't believe it's worth spending time on this. I managed to adapt to my NEO specialties , my friends who are using some did the same, and when the replacement time will come, I'll perform a more thorough review...

Thanks !

**Comment by cdo256** [comment]
This is a great feature for convenience, however it's not automatically detecting new keys. On Linux (Guix), on the unlock screen, I'm only seeing new hardware keys I insert after I exit to the main page and go back to the unlock screen. On the terminal I'm getting:

`Hardware key USB error: Access denied (insufficient permissions)`

I performed an strace, but I couldn't determine which access it was. Nothing related to udev, dev, sys, pam, or usb stood out as being the culpret. As expected running keepassxc as root, resolves the issue. I've attached both straces for running under `sudo -E` and straight as a user.

The operating system is Guix Linux at a8353e9d6b34fd8d42d2e8f14ce844849fe9c293.

Let me know if you need any more information.

[sudo-strace.trace](https://0x0.st/Xo2U.trace), [user-strace.trace](https://0x0.st/Xo20.trace).

**Comment by droidmonkey** [comment]
You need the yubikey udev rules installed. Never heard of guix though. 

https://github.com/Yubico/yubikey-personalization/blob/master/70-yubikey.rules

**Pull request merged**
